### ISSUE TITLE
Showcases

### ISSUE THREAD

**Issue by janwirth** [BrainJS/brain.js#1]
We could add a section with showcases to the readme to provide usage examples and inspirations.
Due to the response of the community I think there might plenty of better-written projects than mine.

I wrote a classifier module that is able to perform multilabel classification on new oservations. It has to be trained with the target-classes alone.
https://github.com/FranzSkuffka/flextractor/tree/master/lib/classifier

What are your thoughts? What did you build already?

**Comment by robertleeplummerjr** [comment]
I love it!  I'll go ahead and push the missing branches over so we can extend there.

**Comment by robertleeplummerjr** [comment]
Done: http://harthur-org.github.io/brain/
Going to add a link in the project Description.

**Comment by janwirth** [comment]
Nice, I am not sure yet when I will have the time to build a showcase, but I'll put it in my todos!

**Comment by robertleeplummerjr** [comment]
I would like to showcase [smartsweepers](http://robertleeplummerjr.github.io/smartSweepers.js/), but using only brain.js.  Also, I have dreams of one day solving the [elevator saga](http://play.elevatorsaga.com/) with it.

**Comment by robertleeplummerjr** [comment]
can you give us a gh-pages branch so we can display something with a single click?

**Comment by janwirth** [comment]
@robertleeplummerjr do you mean me? I do not have write access to this repo.

**Comment by robertleeplummerjr** [comment]
I mean on https://github.com/FranzSkuffka/flextractor/tree/master/lib/classifier

**Comment by janwirth** [comment]
fairly busy atm, will put it on my list!

**Comment by robertleeplummerjr** [comment]
Link fixed: https://brain.js.org/

**Comment by robertleeplummerjr** [comment]
Since the page works, although simple, lets close this and continue with showcases as they come up.
