### ISSUE TITLE
Demo site url /brain -> /brain.js

### ISSUE THREAD

**Issue by ecwyne** [BrainJS/brain.js#10]
http://harthur-org.github.io/brain.js/

**Comment by craigsheen** [comment]
https://harthur.github.io/brain/ Would also work (as further down in the documentation.)

**Comment by robertleeplummerjr** [comment]
Thanks for finding!
https://github.com/harthur-org/brain.js/commit/a52d12e3b5cd9e4ccce118a63e526cab40735ea4#diff-04c6e90faac2675aa89e2176d2eec7d8
https://github.com/harthur-org/brain.js/commit/55371e1be1b8fabd9d351f1bb1d7dfa3d9f0e77d#diff-04c6e90faac2675aa89e2176d2eec7d8
https://github.com/harthur-org/brain.js/commit/18e52bd6b315a21d9437dfac906e0056173dd888#diff-04c6e90faac2675aa89e2176d2eec7d8
