### ISSUE TITLE
Error loading json file from a trained neural network

### ISSUE THREAD

**Issue by Amglsox** [BrainJS/brain.js#103]
Hi, I'm having trouble loading JSON from an already trained network. When using the network from the generated JSON, it does not have the outputs that are required to use the Run method. Can you tell me? Below is the screen and the code.

![errorede](https://user-images.githubusercontent.com/34178609/34138785-7c594866-e458-11e7-8b65-3a0f0a41039a.PNG)

```
var net2 = new brain.NeuralNetwork({learningRate: 0.6});
var actual_JSON;
function init() {
 loadJSON(function(response) {
  // Parse JSON string into object
	actual_JSON = JSON.parse(response);
	console.log(actual_JSON);
	net2.fromJSON(actual_JSON);
 });
}

function loadJSON(callback) {   

    var xobj = new XMLHttpRequest();
        xobj.overrideMimeType("application/json");
    xobj.open('GET', 'jsonFinal.json', true);
    xobj.onreadystatechange = function () {
          if (xobj.readyState == 4 && xobj.status == "200") {
            callback(xobj.responseText);
          }
    };
    xobj.send(null); }
```

**Comment by robertleeplummerjr** [comment]
Would you by chance be able to reproduce this on a jsfiddle or the like?

**Comment by robertleeplummerjr** [comment]
bump

**Comment by Amglsox** [comment]
Sorry I got it sorted out. Thank you!!!!

**Comment by robertleeplummerjr** [comment]
Always a pleasure when someone does housekeeping.  Ty!
