### ISSUE TITLE
es6 it!

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#11]
I'd like to update the syntax to that of es6, thoughts?

**Comment by MrIsaacs** [comment]
Seems legit. Maybe having an own branch for es6 is a good thing? So tagging different branches is made easier an makes the codebase compatible for older interpreter and users can choose a compatible version as they need.

**Comment by robertleeplummerjr** [comment]
If we were to do it, I'd first create a new branch, then I'd like to ensure we use something like babel to compile it for compatibility.  I'd also like to make part of the build process create a browser specific file, so that rather than doing it manually, it is built in.  All of which wouldn't be too complicated.

**Comment by robertleeplummerjr** [comment]
Once all that clears, then we could merge it into master, and continue on our merry way.

**Comment by robertleeplummerjr** [comment]
It is here, huzzah!

**Comment by IonicaBizau** [comment]
There's a tool caled [`lebab`](https://github.com/mohebifar/lebab) by @mohebifar which would be probably useful to convert it automagically and then edit the things that still have to be edited manually (if any). :grin:

**Comment by robertleeplummerjr** [comment]
very cool!

**Comment by robertleeplummerjr** [comment]
What would be our strategy for es5/legacy compatibility?

**Comment by Macil** [comment]
Why not transpile it to es5 with babel as a prepublish step? That seems to be the normal route for modules written in es6+.

**Comment by robertleeplummerjr** [comment]
I like it!

**Comment by robertleeplummerjr** [comment]
@IonicaBizau I mostly manually translated it already.

**Comment by robertleeplummerjr** [comment]
Ready and waiting here: https://github.com/harthur-org/brain.js/pull/28

**Comment by robertleeplummerjr** [comment]
As soon as this is merged, auto builds are next, then a pr for the recurrent neural network stuff.  Just fyi.

**Comment by robertleeplummerjr** [comment]
Merged!

**Comment by IonicaBizau** [comment]
For publishing I use `babel-it` which babelifies the files in place when `npm publish`ing.

**Comment by robertleeplummerjr** [comment]
Would you be up for taking a look at master, and seeing if you can apply your knowledge there?

**Comment by IonicaBizau** [comment]
@robertleeplummerjr Well, pretty much `npm i -g babel-it` and instead of doing `npm publish` you do `babel-it`. 😁

**Comment by robertleeplummerjr** [comment]
rnn, lstm, and gru working 100%, with some simple unit tests and travic-ci build: https://github.com/harthur-org/brain.js/pull/29
