### ISSUE TITLE
Quality Obj in toJson()

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#111]
I think it would be beneficial to have a second item in the `toJson` object for recording quality of the network.  This will help when sharing networks with others.  to give them some kind of idea how many resources have been put into actually training that network.  It will also give some basic metrics in figuring out what types of networks take a really long time to train.

Perhaps something like this:
```
{
   layers: [ ... ],
   quality: {
      iterations: 70, // Times Trained
      accuracy: 0.0012323, // Percentage
      trainingSetLength: 15000,
      standardDeviation: 0.02 // no clue what actual numbers of this would look like yet
   }
}
```
  The idea for this is that I could create a network that is trained to determine handwriting, then I could give it to Lenny and he could continue training it from his data set that is different from mine, to improve it.  Then Carl could use it to solve his problem with Mo's terrible handwriting.

**Comment by mubaidr** [comment]
https://github.com/BrainJS/brain.js/pull/150
