### ISSUE TITLE
Confidence Level

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#112]
It would be nice to set an expected confidence level for the output, then output that is outside that confidence can be treated differently.

This would be extremely helpful in allowing the user to be alerted when something is unclear to the network and then allow the user determine what additional training should be taken.

One of the important things in AI that it seems to me is often forgotten is to let the user continue to provide feedback, allowing the network to continue to train after the set training has taken place.

It would make sense to let the user configure the way these low confidence items are handled. A few options would be:

### Stream It
I think the best would be to have a stream, similar to an error stream but instead of error it would be a `low confidence stream`.  Any time you give an input that returns an output that falls bellow your set confidence level an object is emitted to the low confidence stream and the developer can choose what to do with it. 

This would be useful for users who are interactively working with the network.

### Ignore It
I could see in production cases where you have a network that isn't at a place that you can do anything about it when output that is low confidence shows up, so don't waste any more resources on it.

### Save It
Allow the user to bundle it up and save it then they can address it at a different time.

## Thoughts
I thought of this as I created my network for determining handwritten numbers (0-9)  The output was an array of 10 numbers.  I took the largest number and that was what the network's result was.  But I got thinking, why not utilize the degree of that number?

I didn't do the math but just assumed the number was the probability that that element was the given output.  This lead me to originally think that the confidence level would be just the probability of that given output element.

I then started thinking and I don't know if that would be a catch all solution.  I think it might be useful to have some standard deviation stored as we train the data, then we could better determine the magnitude of the confidence.

As I continue to think I also wonder if we would find localized biases (I don't know if I am using the best words here).  The thing that makes me think this is that if you train on a small but detailed data set, you could be train for specific input, but as that input increases in variance, the training is less and less correct.  So I think there should also be a component of iterations.  In other words a network that has trained on a 1,000 sized sampling would probably have less confidence then a network that has trained on a 1,000,000 sized sampling.

To handle this last scenario, I think there should be a factor that increases confidence logarithmically based on the size of the training set.

## So Maybe

Maybe the confidence level could be a semi-arbitrary number (i.e. 1-10) that is produced by finding how far the away from the standard deviation the given output is, and counter balancing that with a weight of how many iterations (which would not be weighed linearly but instead logarithmically)

  ## However

It would probably be easiest to just use the probabilities of that show up in the output, so maybe we should do that first, then worry about the fancy shmancy scale.

**Comment by robertleeplummerjr** [comment]
I wrote this when I first became acquainted with the project: https://github.com/BrainJS/brain.js/blob/master/src/likely.js

It really needs an examples page, which I could just use the unit test for.  Maybe I'll do that this morning.

In short, it gives a single result that the network is most sure about, here is the unit test: https://github.com/BrainJS/brain.js/blob/master/test/base/likely.js#L5

**Comment by mubaidr** [comment]
There is plug-in (kind of) available for this named likely. https://github.com/BrainJS/brain.js/blob/master/src/likely.js
