### ISSUE TITLE
BUG: NeuralNetworkGPU undefined `size`

### ISSUE THREAD

**Issue by nsantini** [BrainJS/brain.js#116]
Many functions in NeuralNetworkGPU use a for loop like `for(let k = 0; k < size; k++)`, but the variable `size` is not defined resulting in a runtime error

**Comment by nsantini** [comment]
Some functions access the variable like `this.constants.size` which probably does whats intended

**Comment by nsantini** [comment]
Here is a screenshot of the issue

![screen shot 2018-01-10 at 1 21 29 pm](https://user-images.githubusercontent.com/438741/34749963-41378082-f609-11e7-8999-4ce50e7ac2e2.png)

**Comment by robertleeplummerjr** [comment]
ty ty for finding this, I'll get this resolved asap.

**Comment by nsantini** [comment]
Thank you so much, BrainJS rocks!

**Comment by robertleeplummerjr** [comment]
I fixed this issue, and will release a new version of brain tonight, but a bug persists where the neural network eventually has exploding gradients, and I'm investigating.
