### ISSUE TITLE
LSTM input formats

### ISSUE THREAD

**Issue by umranium** [BrainJS/brain.js#119]
Hi,

I've looked through the samples and the documentation but can't seem to figure this out. And since I'm not very experienced in javascript, I can't comprehend the code that well.

In the [childrens' books sample](https://github.com/BrainJS/brain.js/blob/master/examples/childrens-book.js), the LSTM is trained using a list of strings. How does the code convert the list of strings to numeric vectors? Am I correct that the data formatter used in the LSTM breaks down the list of strings, to a large list of characters, then converts each character into a numeric vector?

If that's the case, I have a long time-series like the following:
`[[0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0]]`. I'd like to train the LSTM to predict the next `[x, y, z]` value in the time-series. How would I train one to do so?

**Comment by mubaidr** [comment]
This feature is available, please check this for an example: https://github.com/BrainJS/brain.js/issues/109#issuecomment-381353855
