### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#123]
Now that we have a specific released version we might want to consider our branching flow.

I don't know the best but pattern but I have always liked something like this:

### master
The branch that is the current latest release
### dev
Stuff getting ready to be put into the next official version.

### The Flow
New features and bug fixes would be merged into dev, then periodically dev would be merged into master and an actual version is created and pushed out to npm.  It is simple and effective imo.

If you already have this set up, or there is already a standard we are following just let me know.

**Comment by robertleeplummerjr** [comment]
I'd _love_ to have this setup.  I'll take care of it right now.

**Comment by robertleeplummerjr** [comment]
I'm going to use `develop` rather than `dev`.  It seems that is more the convention I've seen of late, but let me know if that is a problem.

**Comment by robertleeplummerjr** [comment]
Before doing, I read a bit of: http://nvie.com/posts/a-successful-git-branching-model/
I added `develop` and changed the default branch where pull requests are made.  Ty for taking the time to look at this seemingly small thing, I'm sure it will help for future organization.

![easy as 123](https://s-media-cache-ak0.pinimg.com/originals/a0/8a/68/a08a687cd1784f929500ef1bf68f5f49.jpg)
