### ISSUE TITLE
About brain.recurrent.lstm() Training Data

### ISSUE THREAD

**Issue by dc198689** [BrainJS/brain.js#126]
Hi, I am new touch brain.js.
I am try to using your example ( children book )
I have few questions want to ask.

1. What’s the meaning of train error unit
    e.g : 0.356345533563
    If i get train error unit about 1.242335324, 
    Is that means always matching wrong ?

2. Is the training data set support other language ?
    e.g only chinese, chinese and english words in 1 sentence

**Comment by robertleeplummerjr** [comment]
In the context of recurrent neural networks `RNN`, `LSTM` and `GRU`:
1. error is base 2 log probability
2. it'll work with any language.  Internally the network translates these to a matrix, so the values are only represented
