### ISSUE TITLE
we need a clean way to visually represent layers

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#128]
Example: http://visjs.org/examples/network/layout/hierarchicalLayout.html

Would help with understanding structure.

**Comment by perkyguy** [comment]
Should this be a job for brain-ct?

**Comment by faroukcharkas** [comment]
I already am working on this :D

**Comment by robertleeplummerjr** [comment]
nice
Ultimately this will be for: 
this branch: https://github.com/BrainJS/brain.js/tree/nn-gpu-layers
see readme here: https://github.com/BrainJS/brain.js/tree/nn-gpu-layers/src/layer

**Comment by mubaidr** [comment]
@faroukcharkas any update?

**Comment by mubaidr** [comment]
Closing this one, track this here: https://github.com/BrainJS/brain.js/issues/26

**Comment by faroukcharkas** [comment]
@mubaidr I've already finished the first version although it just wasn't right. I am closing in on the second version. I can share some screenshots of the second version. This is a chain of [screenshots](https://imgur.com/a/AP4tDi1?). Keep in mind that there are only two people working on this venture. You can expect the beta version to be out between August 29-September 15. Contact me at _farouk.charkas@gmail.com_ if you want to work on this and/or keep in touch about the project.

**Comment by mubaidr** [comment]
Great news! 


Is it open source?

**Comment by faroukcharkas** [comment]
Initially, we were not planning on making it open-source. We believe the project hasn't risen to the level of maturity to really benefit from open-source. A lot of what we are doing is quickly running trials on user interface techniques to bring neural networks to the general public. Open source is great, but it is generally slow. If you'd like to work on it, we can discuss that later, but for now, it won't be open source for like a year or so. Shortly after we come out beta, we'll introduce an open source functionality. Thanks for that suggestion, Muhammad.
