### ISSUE TITLE
fromJSON does not work correctly

### ISSUE THREAD

**Issue by nimec77** [BrainJS/brain.js#129]
const brain = require('brain.js');
const net = new brain.NeuralNetwork();
net.train([{ input: [0, 0], output: [0] },
    { input: [0, 1], output: [1] },
    { input: [1, 0], output: [1] },
    { input: [1, 1], output: [0] },
]);
console.log(net.run([1, 0]));
const json = JSON.stringify(net.toJSON());
const net2 = new brain.NeuralNetwork();
net2.fromJSON(JSON.parse(json));
console.log(net2.run([1, 0]));
console.log(json);
console.log(JSON.stringify(net2.toJSON());

Output:
[ 0.9331472516059875 ]
[ 0.4262164235115051 ]

{"sizes":[2,3,1],"layers":[{"0":{},"1":{}},{"0":{"bias":5.219508124805883,"weights":{"0":-3.594487237455296,"1":-3.5995564144376537}},"1":{"bias":2.0856377515985987,"weights":{"0":-5.735954921370731,"1":-5.8343520918041145}},"2":{"bias":-0.6705773932893153,"weights":{"0":-0.959203897155529,"1":-1.0322345440841676}}},{"0":{"bias":-3.2519169651133897,"weights":{"0":7.143018785739898,"1":-7.763584975007569,"2":0.7122170310638396}}}],"outputLookup":false,"inputLookup":false,"activation":"sigmoid"}

{"sizes":[2,3,1],"layers":[{"0":{},"1":{}},{"0":{"bias":-0.19466669410397675,"weights":{"0":-0.17359103265184084,"1":-0.02786247227162758}},"1":{"bias":-0.08352935478566491,"weights":{"0":-0.061752889680215445,"1":0.03982842307436235}},"2":{"bias":-0.13502597334246796,"weights":{"0":0.14226186821238596,"1":0.04276978407112059}}},{"0":{"bias":-0.1714507729333036,"weights":{"0":-0.12001827908808389,"1":-0.05747073690797366,"2":-0.0998779787025125}}}],"outputLookup":false,"inputLookup":false,"activation":"sigmoid"}

In version 1.0.0 everything works correctly

**Comment by robertleeplummerjr** [comment]
What version are you on?

**Comment by nimec77** [comment]
I tried on versions 1.0.2, 1.0.1 and 1.0.0 Correctly worked only on version 1.0.0

**Comment by robertleeplummerjr** [comment]
Perfect!

**Comment by robertleeplummerjr** [comment]
reproduced.  fixing.

**Comment by robertleeplummerjr** [comment]
fixed here: https://github.com/BrainJS/brain.js/pull/131

**Comment by robertleeplummerjr** [comment]
Fixed and deployed in https://github.com/BrainJS/brain.js/releases/tag/1.0.3
Mind reproducing?

**Comment by nimec77** [comment]
Now everything works correctly. Thank you!

**Comment by robertleeplummerjr** [comment]
![](https://media.giphy.com/media/mbTaFQPK6iqEo/giphy_s.gif)
