### ISSUE TITLE
Error given when forgotten to train

### ISSUE THREAD

**Issue by faroukcharkas** [BrainJS/brain.js#135]
## *What* is wrong?
When you forget to train the network an error message pops up saying something along the lines of `this.runInput is not a function`.

## *Where* does it happen?
This error appears when you run the neural network in the browser.

## *How* do we replicate the issue?
In order to replicate the issue, forget to train the network. Go from creation to running right away.

## *How* important is this (1-5)?
I would rate this a `1`. It'd just be great if it told you, "Hey, you forgot to train me!"

## Expected behavior (i.e. solution)
For it to instead of telling you, `this.runInp...` but instead say `Network was not trained on data` or something like that.

## Other Comments
I came across this when I forgot to train the network. Because of my forgetfulness, it costed me a day or so. This could've helped a little.

**Comment by perkyguy** [comment]
This was fixed in PR #136 , if it's not, just re-open this and I can take a look at what happened.

**Comment by robertleeplummerjr** [comment]
ty guys!
