### ISSUE TITLE
[Help needed] Guess next trend on chart

### ISSUE THREAD

**Issue by elmondogri** [BrainJS/brain.js#138]
Hello, I am not sure this is the best place to post my problem but I can't find another.

I am using Brain.js since a few days and am completly new to Machine Learning so I might be missing something obvious.

I have a huge (20k+) set of prices in json, something like:
`[{time:555555555000, price: 5.5456}, {time:555555556000, price: 5.5454}, {time:555555557000, price: 5.5457}, ...]`

Now what I want is, based on the last X prices, let brain.js guess if the price will go up or down for the next point.

I am doing something like this:

```
const brain = require('brain.js');
var net = new brain.NeuralNetwork();
var json = require('./tmp/test'); // no need to add the .json extension
    var data = [];
     var x = 100;

    for (var i = 0; i < json.length - 1; i++) {
	if (i < x) {
		continue;
	}

	var newData = {
		input: [],
		output: [1, 0, 0]
	};
	for (var i2 = (i - x); i2 < i; i2++) {
		if (json[i2+1].price > json[i2].price) {
			newData.input.push(1);
		} else if (json[i2+1].price == json[i2].price) {
			newData.input.push(0.5);
		} else {
			newData.input.push(0);
		}
	}
	
	if (json[i + 1].price > json[i].price) {
		newData.output = [0,0,1];
	}
	else if (json[i + 1].price == json[i].price) {
		newData.output = [0,1,0];
	}

	data.push(newData);
}
```

So as you can see, input contains the last 100 prices (I have tested with 10 and 50 and get the same error), already sorted by timestamp, and the output will be either [1,0,0] if 101th price is lower, [0,1,0] if it's equal, [0,0,1] if it's higher.

Then it trains using: 

```
net.train(data, {
				log: true,
				iterations: 20 // (have tried with 10, 100, 1000, 5000, error rate is always > 0.09
			});
```

Then I try to run, so I take 100 value somewhere inside json (still sorted by timestamp, so we are using the same as training data), and push them inside input array, but when I run 

```
var output = net.run(input);
console.log(output);	
```

output is always like the next price is higher, for exemple: `[ 2.233065781373218e-15, 0.2800779938697815, 0.9999711513519287 ]` and this even if next price is equal or lower.

What am I missing? I know it can't be 100% accurate, but something must be wrong as I always have the same result, aka new price is higher.

Thank you for your time.

**Comment by freddyC** [comment]
@elmondogri Hope you are enjoying brain.js, thanks for using it.  I am a bit new to the project myself, but one thing I have heard is that sometimes when we try to doctor the data (like you are doing with your `1, 0.5, 0` inputs) it can hinder the learning of the network.  I don't know if that is what is going on for sure.  What would happen if you tried something like this?  (I don't think I have changed too much of the logic)

```javascript
var json = require('./tmp/test');
var data = [];
var x = 100;

for (var i = x; i < json.length -1; ++i) {
  var input = [];
  for (var j = i - x; j < i; ++j) {
    input.push(json[j + 1] - json[j]);
  }
  var output = json[i + 1] - json[i];   // I don't know if this output would be any better then what you had, just something else you could try

  // You might want to log this out to verify the values are reasonable
  data.push({
    input: input,
    output: output
  })
}
```
Also you want to keep the iterations relatively high (the default is 20k).  It may take some time for your network to run depending on your test data size and your setup.

I did a neural net for figuring out hand written letters and it took about 1.5 hours to run with a data set of 5k images (mnist images 28x28 so each input was an array of 784) and the default NeuralNetwork (with hidden layers of [80,50, 25]).  The error rate decreased slowly at first but eventually got down to around 0.0026 or so.

I hope this helps.  Let me know what you find out.

**Comment by fede-ciliberti** [comment]
Price must be in the 0 to 1 range. You can map it like a percent of change

**Comment by ellocofray** [comment]
Hello, I am trying to run brain.js within a web worker in the same way as
the example in https://brain.js.org/ but for some reason the variable brain
is not being exported. Surely it is because the version has changed. I
appreciate if you can tell me how to proceed. Thank you very much.
-- 

Federico Ciliberti

Santa Fe 606 Firmat, Santa Fe (2630)

+5493465592485

**Comment by elmondogri** [comment]
Thank you for both you replys, unfortunalty I am having no luck with your solution @freddyC , as the output is always [NaN, NaN, NaN], this is I guess (thanks to @ellocofray)because sometimes trades[i].price - trades[i-1].price is lower than 0, anyway I got the idea that doctoring the data is not a good idea so I tried something else, and still have the exact same problem, being that the output is always the same, whatever the input is, here is my entire code maybe it s easier to understand:

```
var fs = require('fs');
const brain = require('brain.js');

var MongoClient = require('mongodb').MongoClient;
var db = MongoClient.connect('mongodb://127.0.0.1:27017/', function(err, dbs) {
	
	db = dbs.db('bibot');
	var count = 50;
	var network = new brain.NeuralNetwork();
	
	getTrades('trades1517339832018', ['VIBEBTC'], 5000, function(trades) {
		console.log('Total trades', trades.length);
		var trainingData = createTrainingData(trades, count, 2500);
		network.train(trainingData, {
			log: true,
			iterations: 500 // console.log() progress periodically
		});
		
		saveNetwork(network, 'VIBEBTC');
		
		var testData = createTestData(trades, count, 3500, 50);
		
		var performance = {right: 0, wrong: 0};
		
		for (i = 0; i < testData.length; i++) {
			var input = testData[i].input;
			
			var expected_output = testData[i].output;
			var expected_index = expected_output.indexOf(Math.max(...expected_output));
			
			var output = network.run(input);
			var index = output.indexOf(Math.max(...output));
			
			console.log(expected_output, output);
			console.log(index == expected_index);
			if (index == expected_index) {performance.right++;} else {performance.wrong++;};
		}
		
		console.log(performance);
	});
}); 











//-------------------------- functions -------------------------------------- //

function getTrades(collection, symbols, limit, callback) {
	db.collection(collection).ensureIndex({"symbol": 1});
	db.collection(collection).ensureIndex({"timestamp": 1});  
	db.collection(collection).find({'symbol': { $in: symbols}}).limit(limit).sort({'timestamp': 1}).toArray(function(err, trades) {
		console.log(trades.length);
		callback(trades);
	});
}

function createTrainingData(trades, count, max) {
	var trainingData = [];
	for (var i = 0; i < trades.length; i++) {
	
		if (i <= count ) {
			continue;
		}
		
		if (trainingData.length >= max ) {
			break;
		}
		
		var input = {greater:0, equal:0, lower:0};
		for (i2 = i - count; i2 < i; i2++) {
			if (trades[i2].price > trades[i2-1].price){
				input.greater++;
			} 
			else if (trades[i2].price == trades[i2-1].price){
				input.equal++;
			}
			else {
				input.lower++;
			}
		}
		

		var output = [];
		
		if (trades[i].price > trades[i-1].price){
			output = [0,0,1];
		} 
		else if (trades[i].price == trades[i-1].price){
			output = [0,1,0];
		}
		else {
			output = [1,0,0];
		}
		
		trainingData.push({
			input: input,
			output: output
		});
		
	}
	console.log('Training data created with: ' + trainingData.length + ' trades');
	return trainingData;
}

function createTestData(trades, count, startFrom, max) {
	var testData = [];
	for (var i = startFrom; i < trades.length; i++) {
		
		if (i <= count ) {
			continue;
		}
		
		if (testData.length >= max ) {
			break;
		}
		
		var input = {greater:0, equal:0, lower:0};
		for (i2 = i - count; i2 < i; i2++) {
			if (trades[i2].price > trades[i2-1].price){
				input.greater++;
			} 
			else if (trades[i2].price == trades[i2-1].price){
				input.equal++;
			}
			else {
				input.lower++;
			}
		}
		

		var output = [];
		
		if (trades[i].price > trades[i-1].price){
			output = [0,0,1];
		} 
		else if (trades[i].price == trades[i-1].price){
			output = [0,1,0];
		}
		else {
			output = [1,0,0];
		}
		
		testData.push({
			input: input,
			output: output
		});
	}
	console.log('Test data created with: ' + testData.length + ' trades');
	
		console.log(testData)
	return testData;
}

function saveNetwork(network, symbol) {
	fs.writeFile('./networks/' + symbol + '_' + new Date().getTime() + '.json', JSON.stringify(network.toJSON()), (err) => {  
		// throws an error, you could also catch it here
		if (err) throw err;

		// success case, the file was saved
		console.log('Network saved!');
	}); 
}
```

and here is a sample output:

![image](https://user-images.githubusercontent.com/20752444/35753427-695ccaec-0868-11e8-86a3-bd9a88c3991b.png)


If you have any clue that would be great!

**Comment by perkyguy** [comment]
@elmondogri do you have any sample data that you could share?

**Comment by robertleeplummerjr** [comment]
Can you setup a simple https://jsfiddle.net for collaboration?

**Comment by bitcoinvsalts** [comment]
@elmondogri It seems we are trying to build the same thing (using binance too). Please contact me at herve76@gmail.com

**Comment by robertleeplummerjr** [comment]
A new feature has been added that will handle this.  More details here: https://github.com/BrainJS/brain.js/issues/109#issuecomment-381353855

**Comment by mubaidr** [comment]
New feature is available. If you still need help, feel free to re-open this issue.
