### ISSUE TITLE
`FeedForward` class in `nn-gpu-layers` branch learns inconsistently

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#140]
![A GIF or MEME to give some spice of the internet](https://media0.giphy.com/media/J5XkFdokUvVHG/giphy.gif)

## *What* is wrong?
It's learning should be more consistent.  At times it learns very well, others it is completely confused.

## *Where* does it happen?

in the following code:

```js
import { FeedForward, layer } from './src/index';
const { input, feedForward, output } = layer;
const net = new FeedForward({
  inputLayer: () => input(),
  hiddenLayers: [input => feedForward({ width: 3 }, input)],
  outputLayer: (input) => output({ width: 1 }, input)
});

net.train([
  { input: [0, 0], output: [0] },
  { input: [0, 1], output: [1] },
  { input: [1, 0], output: [1] },
  { input: [1, 1], output: [0] }
]);

console.log(net.run([0,0])); // should be close to [[0]]
console.log(net.run([0,1])); // should be close to [[1]]
console.log(net.run([1,0])); // should be close to [[1]]
console.log(net.run([1,1])); // should be close to [[0]]
```

## *How* do we replicate the issue?
The code sample above should be sufficient for reproducing the issue.

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
```js
console.log(net.run([0,0])); // should be close to [[0]]
console.log(net.run([0,1])); // should be close to [[1]]
console.log(net.run([1,0])); // should be close to [[1]]
console.log(net.run([1,1])); // should be close to [[0]]
```

## Other Comments

**Comment by perkyguy** [comment]
`inputLayer: () => input(),` should be `inputLayer: () => input({ width: 2 }),`

**Comment by robertleeplummerjr** [comment]
doh!  How could I have missed it!

**Comment by perkyguy** [comment]
It's ok, not everyone can be as observant as I!
