### ISSUE TITLE
Async Runner

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#143]
![A GIF or MEME to give some spice of the internet](https://media1.tenor.com/images/9c3bf8e8de1b15b9073ff8ae83820e77/tenor.gif?itemid=5501510)

## *What* is wrong?

We have added thaw.js but we don't run the network async.

## *Where* does it happen?

NeuralNetwork

## *How* do we replicate the issue?

Train the network the run the network, there is an async way to train it but no async way to run it.

## *How* important is this (1-5)?

2

## Expected behavior (i.e. solution)

The user should be able to run it async in a similar way to training async.

## Other Comments
the 5th

**Comment by robertleeplummerjr** [comment]
@freddyC is this completed for the `NeuralNetwork` class as of now?

**Comment by freddyC** [comment]
The training is Async but actually running is not.  I am not certain how important this is as a priority but it seems like thematically if we have a train async we would also want to be able to run async.  I think it might be a good approach to have steam for running the network, then wrap the stream in a promise to allow async running.

**Comment by robertleeplummerjr** [comment]
fairly sure this is completed?

**Comment by mubaidr** [comment]
Any update on this?

**Comment by mubaidr** [comment]
I am closing this issue, please re-open if required.
