### ISSUE TITLE
Results Stream

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#144]
![A GIF or MEME to give some spice of the internet](https://media.tenor.com/images/d320022232cbe60fb7f342be86806cfa/tenor.gif)

## *What* is wrong?

We have a trainingStream but we don't have a running stream.

## *Where* does it happen?

NeuralNetwork

## *How* important is this (1-5)?

2

## Expected behavior (i.e. solution)

When the user has a trained network we should have a way to open up a stream that we can pass data to and it will stream the resulting data.

## Other Comments
No Sir.

**Comment by bitcoinvsalts** [comment]
+1

**Comment by robertleeplummerjr** [comment]
Now working, please reopen if you find any issues.  The api did change a little. New example [here](https://github.com/BrainJS/brain.js/blob/master/examples/stream-example.js).
