### ISSUE TITLE
Running brain.js inside a web worker

### ISSUE THREAD

**Issue by fede-ciliberti** [BrainJS/brain.js#146]
## *What* is wrong?
Hello, I am trying to run brain.js within a web worker in the same way as
the example in https://brain.js.org/ but for some reason the variable brain
is not being exported. Surely it is because the version has changed. I
appreciate if you can tell me how to proceed. Thank you very much.

**Comment by robertleeplummerjr** [comment]
on it

**Comment by robertleeplummerjr** [comment]
Resolved, and updated ph-pages so reflect it working: https://brain.js.org/

ty for finding this!

**Comment by robertleeplummerjr** [comment]
You shiney new version: https://github.com/BrainJS/brain.js/tree/1.0.4
