### ISSUE TITLE
Faster Testing

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#154]
![tenor](https://user-images.githubusercontent.com/2294139/36222183-bedd5d6a-117d-11e8-92e4-d86f9a9d0335.gif)

## *What* is wrong?

Tests take forever

## *Where* does it happen?

The tests where we use the async training

## *How* do we replicate the issue?

1. yarn test
2. wait
3. wait
4. wait
5. wait
6. wait
7. get up
8. go make a sandwitch
9. eat your sandwitch
10. grab a dewski
11. sit back down
12. wait
13. read the dictionary
14. wait
15. be happy the tests passed

## *How* important is this (1-5)?

probably a 42

## Expected behavior (i.e. solution)

1. yarn test
2. blink
3. realize you missed the test's finishing while you blinked

## Other Comments
We don't need to train so many things via async now that the async training and the regular training are using the same code paths.

**Comment by robertleeplummerjr** [comment]
Is this specifically on the `NeuralNetwork` class?

**Comment by freddyC** [comment]
The tests that are slow are all on the neural network class yes
