### ISSUE TITLE
Precise toFunction

### ISSUE THREAD

**Issue by freddyC** [BrainJS/brain.js#156]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/kfFhknV3Ztpq8/giphy.gif)

## *What* is wrong?

Sometimes the `toFunction` test fails.  It will output something like this usually:
![image](https://user-images.githubusercontent.com/2294139/36327439-e4abe882-131b-11e8-8767-35756d5ee2f3.png)

## *Where* does it happen?

`toFunction` I just said that, are you even paying attention?

## *How* do we replicate the issue?

Run the tests a bunch (I saw it probably more often then 1 in 10 times)

## *How* important is this (1-5)?

at least an `E`

## Expected behavior (i.e. solution)

The tests should not fail.  This shouldn't be fixed by changing the tests.  It would probably be fixed if we use `float32arrays` in the toFunction method.

**Comment by robertleeplummerjr** [comment]
Not currently needed from trained models as they are precise enough.  If more precision is needed, simply don't export to function.
