### ISSUE TITLE
how to use brain.js for any type of moderation 

### ISSUE THREAD

**Issue by matt212** [BrainJS/brain.js#165]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
nothing, just wanted to know if it is possible to use brain,js as image /nsfw content moderation tool.
if yes then where can i find some doc for the same !

## Other Comments

**Comment by robertleeplummerjr** [comment]
Rather than handling this specific use case here, why don't we change the target so that it can be used to moderating anything?  Since most nets have some form of cat detection, why not a dog moderator?  So we can stay focused on cats....

**Comment by bduff9** [comment]
I agree, my primary use case for looking into this library has to do with processing images so I'm looking for some guidance on how to properly convert images to input

**Comment by cashlionjp** [comment]
I was wondering the same thing.  I was thinking I can grayscale the images and flatten them into an array of pixels where each value represents brightness.

**Comment by robertleeplummerjr** [comment]
@cashlionjp Yea, that is kinda the basis of how to achieve it right off.  The next step would be to build the net in such a way it can either detect it is a moderated image and not show it, or censor the moderated bits.

I found this after a quick search: https://github.com/cytadela8/trypophobia

And then I found the model: 
```python
model = Sequential()
model.add(Conv2D(16, (3, 3), padding='same',
          input_shape=(resolution_x, resolution_y, 3)))
#model.add(Convolution2D(8, 3, 3, border_mode='same'))
model.add(Conv2D(16, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Dropout(0.15))
model.add(Conv2D(32, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Conv2D(32, (3, 3), padding='same'))
model.add(Dropout(0.25))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Conv2D(32, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Dropout(0.3))
model.add(GlobalAveragePooling2D())
#model.add(Flatten())
#model.add(Dropout(0.2))
for i in range(1):
    model.add(Dense(64))
    model.add(Activation('relu'))
    #model.add(Dropout(0.2))
#for i in range(1):
#    model.add(Dense(32))
#    model.add(Activation('relu'))
model.add(Dense(2))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
```

The [feed forward](https://github.com/BrainJS/brain.js/blob/nn-gpu-layers/src/feed-forward.js) neural network would probably be the perfect place to start with building this.  If I did a quick translation from their model to the new layer composition not yet landed, but very close, we'd have a good place to start.

**Comment by mubaidr** [comment]
If you still need help, feel free to re-open this issue.
