### ISSUE TITLE
Basic touch points

### ISSUE THREAD

**Issue by thepooltable** [BrainJS/brain.js#167]
I'd like to use touch point detection w/ browser.js, e.g 5 touch point: logging 5 pairs of clientX & clientY coordinates of the screen.

if the 5 touch points are in a circle form, it will be able to recognise and show: a is more then 0.5
if the touch points are in triangle form, it should be: b is more then 0.5

Am i correct to use, e.g 1 of 1000 diff testing values:  "input":[382,201,519,216,451,172,449,222,524,253], "output":{"a":1, "b":0}}]

Which activation can i use?
activation: 'sigmoid'  // Supported activation types ['sigmoid', 'relu', 'leaky-relu', 'tanh']

Should i be using new brain.NeuralNetwork(); ?

**Comment by josiahbryan** [comment]
@thepooltable - you're basically looking for a classifier. The `NeuralNetwork` architecture should work great for that. And your input looks great to me. Regarding classifier, just based on my testing, I've had better luck with `sigmoid` for classifications, as long as it has a moderate hidden layer (somewhere around (input dimension + output dimensions) / 2 for hidden). You can also try `tanh` - I haven't had much luck myself with `relu` and friends for classifications.

To experiment, build up a list of input/output pairs (~100 - ~1000), all labeled, chop about 75% off and use those pairs for training, then test using the other 25% or whatever you choose to test accuracy - then compare accuracy between activation methods to determine if tanh or sigmoid works better (or relu, etc)

**Comment by robertleeplummerjr** [comment]
This is something I've often wondered at times.  Really cool reply.

**Comment by thepooltable** [comment]
thanks for advice on e training method!

another qn, here, having 5 touch points on screen, will return me 5 pairs of X & Y coordinates.
Does the coordinates position in the array matters? or should pinpoint using the distances between each points - but this would defeat the purpose if 2 devices have about the same range of coordinates :/

From my perspective, i was hoping to train multiple device (with different points), that can be use on a large screen, and also regardless whichever directions the device lands on the screen.

**Comment by josiahbryan** [comment]
Pre-processing your data is often crucial to the success of your training.
I would recommend experimenting with what gives the best training success.
I would imagine order does matter. However, what you're asking is basically
bordering on image recognition, and I know others have trained Nets to do
scale and rotation invariant classification, however, I believe those
architectures were much more convoluted and complex than the simple hidden
layer setup we have here.

**Comment by thepooltable** [comment]
i agree it is a very complex training data here. 
"I know others have trained Nets to do
scale and rotation invariant classification, however" - did they achieve any result so far?
it seems to work nicely if the area to detect the points is small.

just sharing, rotation did not work out for me.
any further trainings will exceed the error threshold.

nonetheless, hope to use this brain.js again in my future projs. works great with simple data.
