### ISSUE TITLE
bitwise + tanh or any form of relu = training a little funky

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#168]
![A GIF or MEME to give some spice of the internet](http://www.reactiongifs.com/r/mfnky.gif)

## *What* is wrong?
Training happens with tanh and relu, but when running, odd results

## *How* do we replicate the issue?
Run `yarn test` on https://github.com/BrainJS/brain.js/tree/168-funky-learning

## *How* important is this (1-5)?
4

## Expected behavior (i.e. solution)
learning goes down, correct results come out

## Other Comments
This may have to do with the use of zeros

**Comment by satyakesav** [comment]
Hi, Can I contribute to this project by working on this Issue?

**Comment by robertleeplummerjr** [comment]
Absolutely!

**Comment by satyakesav** [comment]
Hi Robert,

Could you give me some pointers on learning about this project. I am new to this project and want to know whether as a newbie, it is very hard issue or a solvable one. I am not new to deep learning or javascript but new to their combination.

Thanks

**Comment by robertleeplummerjr** [comment]
The unit tests that reproduce the behavior are here: https://github.com/BrainJS/brain.js/compare/168-funky-learning#diff-1b50ed7dbc66400282adfc83edacc8baR28

The functions that seem to cause the problems are here:
* forward propagation relu https://github.com/BrainJS/brain.js/blob/168-funky-learning/src/neural-network.js#L227
* back propagation relu derivative  https://github.com/BrainJS/brain.js/blob/168-funky-learning/src/neural-network.js#L507
---
* forward propagation leaky-relu https://github.com/BrainJS/brain.js/blob/168-funky-learning/src/neural-network.js#L247
* back propagation leaky-relu derivative https://github.com/BrainJS/brain.js/blob/168-funky-learning/src/neural-network.js#L532
---
* forward propagation tanh https://github.com/BrainJS/brain.js/blob/168-funky-learning/src/neural-network.js#L267
* back propagation tanh derivative https://github.com/BrainJS/brain.js/blob/168-funky-learning/src/neural-network.js#L557

---

Weights are adjusted currently the same between all of the learning types: https://github.com/BrainJS/brain.js/blob/168-funky-learning/src/neural-network.js#L582

---
This may be unrelated, but is fun to talk about:
The same problem may exist (not yet confirmed) in the new layer composition architecture's layers: https://github.com/BrainJS/brain.js/tree/nn-gpu-layers/src/layer
And by relation, the layer composition activations: https://github.com/BrainJS/brain.js/tree/nn-gpu-layers/src/activation
