### ISSUE TITLE
React Native Example

### ISSUE THREAD

**Issue by lnghrdntcr** [BrainJS/brain.js#171]
#**This is not an issue**
I think that the exporting the NN to json is an amazing feature, do we have any possibility that Brain.js will come to React Native? 

Is there any browser dependency in Brain.js?

Cheers, Fra

**Comment by jusso-dev** [comment]
I just raised an issue about exporting to JSON not being the in the right format, but React Naive is just javascript, and this library support ES6 so have you verified that it does't work in RN?

**Comment by robertleeplummerjr** [comment]
This must be solved, and is a top priority.  Is there a sort of react-native container that demo's this not working?  My assumption is that the whole lib is es6 and should run fine but only as cpu for the time being.  Gpu will come soon when opencl is added to gpu.js.

**Comment by robertleeplummerjr** [comment]
More clearly answering:
>I think that the exporting the NN to json is an amazing feature, do we have any possibility that Brain.js will come to React Native?

There is nothing preventing this, and likely it will just work.  Any testers?

>Is there any browser dependency in Brain.js?

No.

**Comment by jusso-dev** [comment]
@robertleeplummerjr if i get a working example, can i submit a pull request and have it in an "Examples" folder? I'd love to contribute to this library and know my way around React.

**Comment by robertleeplummerjr** [comment]
That would be fantastic!  Neural networks are great, but unless the platform is accessible everywhere, I feel much of the work is in vain.  I look forward to seeing some examples!

**Comment by robertleeplummerjr** [comment]
I changed the title to include example, so now we have an action item.

**Comment by Sam-Hoult** [comment]
I wanted to include Brain.js into my react-native but no go. Made a fresh react-native project (react-native-cli) but for the import it's getting this error whenever the library is imported into the project
```
error: bundling failed: Error: Unable to resolve module `stream` from `/Users/samhoult/web/learning/testing_brain_native/node_modules/brain.js/dist/train-stream.js`: Module does not exist in the module map
```
This wasn't a dependency for the project so got past that doing `yarn add stream`

This was followed by `gpu.js` unable to find the `preset 'env'` which was cured with `yarn add babel-preset-env`

Followed by `thaw.js` complaining about `preset 'es2015'` which I cured with `yarn add babel-preset-stage-0`

Which got me to the files building but met with: 
![image](https://user-images.githubusercontent.com/1436841/38169824-698e59fc-3529-11e8-96eb-95fb5537034f.png)

I've uploaded this example to a repo:
https://github.com/Sam-Hoult/React-Native-BrainJS

**Comment by jusso-dev** [comment]
I'm working on this now, I've almost got a working example, you just remove the import statement for stream in the index.js for the main exports, as it's a dependant for the training package, obviously you wouldn't be training on a phone so it's not really needed. I'm having problems importing the trained model but I've almost solved it

**Comment by robertleeplummerjr** [comment]
You guys rock.

**Comment by Sam-Hoult** [comment]
@jusso-dev Great!
When you say you wouldn't be training on a phone, is that with reference to the `net.toJSON()` and `net.fromJSON(trained)`? (I only found out about this project yesterday so still fresh but really want to put it into production)

**Comment by jusso-dev** [comment]
Yes that's correct Sam. I'm uploading the code soon for approval, I think you'll be pleasantly surprised ;) I had some fun with this little project

**Comment by robertleeplummerjr** [comment]
@jusso-dev We really look forward to seeing it!

>obviously you wouldn't be training on a phone

I think this would likely be more like "obviously you wouldn't likely be training on a phone".  There could always be the possibility.

**Comment by robertleeplummerjr** [comment]
Handled here: https://github.com/BrainJS/BrainJSReactNative

**Comment by petja** [comment]
I'd like to do some training on the users' phones. Should I open new issue for that?

**Comment by jusso-dev** [comment]
@petja I'd highly advise not doing that, as React Native communicates to Native code over the Javascript bridge which is expensive in it's own right.

Can you please provide a rough usage example for why you'd like to do this?
