### ISSUE TITLE
Release the Wiki for public editing?

### ISSUE THREAD

**Issue by hellonearthis** [BrainJS/brain.js#178]
![A GIF or MEME to give some spice of the internet](https://media1.tenor.com/images/406dea3c20cda3680a54de5f0c2ddd91/tenor.gif?itemid=5059284)

## *What* is wrong?
The Github wiki is locked from editing.  If it was open then better docs, examples and links to other tutorials could be added.    Like [Machine Learning Tutorial - Making a recommendation engine IN THE BROWSER](https://www.youtube.com/watch?v=lvzekeBQsSo) or [Machine Learning Tutorial for Beginners - USING JAVASCRIPT!](https://www.youtube.com/watch?v=9Hz3P1VgLz4)

> GitHub Wikis are a place in your repository where you can share long-form content about your project, such as how to use it, how it's been designed, manifestos on its core principles, and so on. Whereas a README is intended to quickly orient readers as to what your project can do, wikis can be used to provide additional documentation.
https://help.github.com/articles/about-github-wikis/

**Comment by robertleeplummerjr** [comment]
Done.
