### ISSUE TITLE
Install from source/repo

### ISSUE THREAD

**Issue by christianbender** [BrainJS/brain.js#179]
How can I install brain.js from source? From this repository?
At the moment I can run the tests. But how can I use it?

greetings

Christian

**Comment by hellonearthis** [comment]
https://www.youtube.com/watch?v=9Hz3P1VgLz4
https://www.youtube.com/watch?v=lvzekeBQsSo

**Comment by mubaidr** [comment]
using npm: 
```json
"brain.js": "git+https://git@github.com:BrainJS/brain.js.git"
```
or you can download zip of this repo and require the `brain/dist/index` file from it.

**Comment by robertleeplummerjr** [comment]
via npm: `npm install brain.js --save`
via yarn: `yarn add brain.js`
via html: download `browser.js` from the repository, and include it in your project `<script src="browser.js"></script>`

Enjoy machine learning.

**Comment by robertleeplummerjr** [comment]
@mubaidr you are a fast one, sir.  ;)

**Comment by christianbender** [comment]
@ALL 
Thanks for many informations and tips. I jump right in.

**Comment by robertleeplummerjr** [comment]
you are welcome!
