### ISSUE TITLE
Training Brain

### ISSUE THREAD

**Issue by Amglsox** [BrainJS/brain.js#180]
Hello.

I am using the brain to perform some data classifications and a doubt arose during the training.
I am performing the data insertion in this way below (as an example), with a loop inserting and each position of the vector a new value.
```
array.push([{input: { r: 0.03, g: 0.7 }, output: { black: 1 }}]);
```
Already in the Brain training part, I'm passing the array declared above, according to the code below. Is there a problem with that?
```
net.train(array, {
                            // Defaults values --> expected validation
      iterations: 20000,    // the maximum times to iterate the training data --> number greater than 0
      errorThresh: 0.005,   // the acceptable error percentage from training data --> number between 0 and 1
      log: false,           // true to use console.log, when a function is supplied it is used --> Either true or a function
      logPeriod: 10,        // iterations between logging out --> number greater than 0
      learningRate: 0.3,    // scales with delta to effect training rate --> number between 0 and 1
      momentum: 0.1,        // scales with next layer's change value --> number between 0 and 1
      callback: null,       // a periodic call back that can be triggered while training --> null or function
      callbackPeriod: 10,   // the number of iterations through the training data between callback calls --> number greater than 0
      timeout: Infinity     // the max number of milliseconds to train for --> number greater than 0
});
```
If we pass the training values, variable by variable, will we have different results in the neural network?
What does Brain actually do with the training data, when I perform the training using an array with the data or instead of values separately?

**Comment by robertleeplummerjr** [comment]
At first glance it looks like you are doubling up on arrays from this line:
`array.push([{input: { r: 0.03, g: 0.7 }, output: { black: 1 }}]);`

Change it to:
`array.push({input: { r: 0.03, g: 0.7 }, output: { black: 1 }});`

**Comment by robertleeplummerjr** [comment]
Did this fix your problem?

**Comment by mubaidr** [comment]
If you still need help, feel free to re-open this issue.
