### ISSUE TITLE
Support for evolutionary algorithms like Neat

### ISSUE THREAD

**Issue by dan-ryan** [BrainJS/brain.js#181]
![walk evolution](http://i.hilariousgifs.com/me-vs-life-big-cube-hit.gif)

Will Brain.js look into adding evolutionary algorithms like [Neat](https://en.wikipedia.org/wiki/Neuroevolution_of_augmenting_topologies)? 

[Neatapatic](https://wagenaartje.github.io/neataptic/) was the best library for this but now is unmaintained so it would be nice if there was a replacement :)

Here is Neat learning Mario: 
https://www.youtube.com/watch?v=qv6UVOQ0F44

**Comment by robertleeplummerjr** [comment]
We would welcome it!  Would you be up for helping with the cause?

**Comment by dan-ryan** [comment]
My knowledge of the details is very limited. But I'm happy to help where I can.

This is the Neat paper:
http://nn.cs.utexas.edu/downloads/papers/stanley.ec02.pdf

This explains Neat:
http://blog.otoro.net/2016/05/07/backprop-neat/

The author of Neataptic explains the improvements he did:
https://towardsdatascience.com/neuro-evolution-on-steroids-82bd14ddc2f6

Here are some newer papers on neuroevolution:
https://medium.com/@moocaholic/2017-the-year-of-neuroevolution-30e59ae8fe18

I see both Brain.js and Neataptic have the same MIT licence, so that will help.

**Comment by thisisloze** [comment]
I would love this!!!!

**Comment by lynxionxs** [comment]
Any progress on this ?...

**Comment by robertleeplummerjr** [comment]
Getting back to the original question:

>Will Brain.js look into adding evolutionary algorithms like [Neat](https://en.wikipedia.org/wiki/Neuroevolution_of_augmenting_topologies)?

I don't have plans to add that at this time.
