### ISSUE TITLE
Input Size always 20

### ISSUE THREAD

**Issue by konnextv** [BrainJS/brain.js#187]
## *What* is wrong?
Whatever array I feed into net.run(), it will always only evaluate 20 items. It will fail on less and stay the same whatever the values after the 20th are.
I already found that one object property is NeuralNetwork.sizes which is [20,10,2] by default but I can't find a way to change this.

**Comment by robertleeplummerjr** [comment]
Can you share a code sample for context?

**Comment by konnextv** [comment]
My testing environment is pretty much this: https://itnext.io/you-can-build-a-neural-network-in-javascript-even-if-you-dont-really-understand-neural-networks-e63e12713a3

**Comment by konnextv** [comment]
@robertleeplummerjr I just saw your anwer to #188 - I guess I just need to fill the training strings with spaces to allow for longer inputs? I just checked, my shortest training string is exactly 20 characters.

Is there a way to get around this? Maybe use a different network? I want to analyze a string of any length.

+ No, I don't know much about how machine learning works, please excuse if I am asking questions that sound stupid to you :)

**Comment by mubaidr** [comment]
@konnextv 
@robertleeplummerjr posted an working code sample here: https://jsfiddle.net/8Lvynxz5/36/

You can use `encode` and `adjustSize` functions from this code. 

Also, please read this: https://github.com/BrainJS/brain.js/issues/188#issuecomment-380671850

**Comment by konnextv** [comment]
@mubaidr Yes I saw that. Just wondered if the network could handle another size of input in order to get the best results (adding spaces to the strings cannot be the best method imo)
Will also look at LSTM networks, however.

**Comment by robertleeplummerjr** [comment]
ty all for your input to help solve this!
