### ISSUE TITLE
Data is not Training or not "running" (two very simple jsfiddle-examples)

### ISSUE THREAD

**Issue by 0laf** [BrainJS/brain.js#191]
Hello guys, 

I hope someone can point me into the right direction. I have tried to setup a very basic example of LSTM but either its not training or its not "running" and when it was running it produced strange results.

I have set up a easy js-fiddle to reproduce the issue. 

https://jsfiddle.net/olafponeta/8azjhuq1/21/

Very strange but this actually produced results (sometimes) and if it did they where bad: 
https://jsfiddle.net/olafponeta/8azjhuq1/15/

So I decided to change the data as seen in version 21. 

I was expecting: 
[0.009,0.5?,0.747]
or similar.

Please help me understand what i am missing. 

best regards 

Olaf

**Comment by mubaidr** [comment]
Using the `NeuralNetwork` produces the expected results which is suitable network type for this type of data.  https://jsfiddle.net/8azjhuq1/48/

**Comment by robertleeplummerjr** [comment]
The recurrent neural network is probably the wrong target here is all.  By using the NeuralNetwork class, a simple feedforward neural network, you'll get what you want for this simple example.

**Comment by 0laf** [comment]
Thanks for your responses. Of course my example was not the real data but only to learn how to train the brain.js LSTM as i can't find any examples (with numeric problems).  

Basically I want to know if I need to add pairs of values as I did in my JsFiddle. As far as i red LSTM (RNN) is definitely the Network type i need to use for the real problem. 

I have three graphs with X-Axis representing the time while the Y-Axis has different meanings for every graph. I suspect the three graphs influence each other but i am not sure. I want to predict the next value(s) of one of the graphs while taking the whole behavior of all the three graphs into account. 

It is difficult for me to explain my experiment in short but i feel like that might not be necessary for you to guide me into the right direction. Please show me how to input Training-Data into brain.js - LSTM Network. 

best regards olaf
