### ISSUE TITLE
empty response from run()

### ISSUE THREAD

**Issue by multivoltage** [BrainJS/brain.js#197]
## *What* is wrong?
Maybe I did not undestand how it work. I try to get a match from boy and girls based on how much is beautiful a people.

## *Where* does it happen?
run() return an empty object

## *How* do we replicate the issue?
```
var boys = [
    { name: 'diego', beauty: 1},
    { name: 'tommy', beauty: 2},
    { name: 'davide', beauty: 3},
    { name: 'valerio', beauty: 4}
];

var girls = [
    { name: 'lodi', beauty: 1},
    { name: 'marina', beauty: 2},
    { name: 'gloria', beauty: 3},
    { name: 'bea', beauty: 4}
];


var inputs = [
    { boy: boys[0], girl: girls[0] },
    { boy: boys[0], girl: girls[1] },
    { boy: boys[1], girl: girls[0] },
    { boy: boys[1], girl: girls[1] }
];

net.train([
    {input: inputs[0], output: { match: 'no'  } },
    {input: inputs[1], output: { match: 'no'  } },
    {input: inputs[2], output: { match: 'yes' } },
    {input: inputs[3], output: { match: 'yes' } }
]);

var output = net.run({ boy: boys[0], girl: girls[0] });
console.log(output);
```

## *How* important is this (1-5)?
1

## Expected behavior (i.e. solution)
return a object like: { match: 'yes' } instead:
{ match: NaN } 

## Other Comments

**Comment by mubaidr** [comment]
What net are you using for this problem? 

Provide jsfiddle if possible.

**Comment by perkyguy** [comment]
Convert your strings to numbers. E.g. 'no' = 0

**Comment by perkyguy** [comment]
And what you probably will want to do is pass in only the `beauty` property (normalize it as well)

**Comment by mubaidr** [comment]
If you still need help, feel free to re-open this issue.

**Comment by kul-sudo** [comment]
Has anybody found a solution?
