### ISSUE TITLE
Is it possible to use brain.js to recognize words from an audio stream?

### ISSUE THREAD

**Issue by gilamran** [BrainJS/brain.js#198]
I want to stream my mic. to the library and I want to detect voice commands.
Is it possible using brain.js?

Thanks!

**Comment by robertleeplummerjr** [comment]
I suppose you could do something like this https://lab.miguelmota.com/spectrogram/example/ but feed it into the net.

**Comment by gilamran** [comment]
I'll have to stream it to the net... How do I do that?
And them tell the net about specific areas to equal a word... How do I do that?

**Comment by mubaidr** [comment]
Details: https://github.com/BrainJS/brain.js#streams

**Comment by robertleeplummerjr** [comment]
I'm not sure a `stream` and an `audio stream` are the same thing.

**Comment by mubaidr** [comment]
I mean, Audio should be converted to input data using above mentioned example and then it can be fed/streamed to network gor training.

**Comment by mihailnicamn** [comment]
anyone have something working with brain.js and spectogram parsing ? 😇
