### ISSUE TITLE
We need a proper logo!

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#20]

**Comment by JamesDonnelly** [comment]
Modifying the "community defined" JavaScript logo would probably be the best option as a lot of other JavaScript resources do that.

Here's what the "community defined" JavaScript logo looks like:

![JavaScript Logo](http://i.imgur.com/hgoGxfe.png)

I got this particular image from https://github.com/voodootikigod/logo.js/blob/master/registry.md, which lists a load of other modified versions as well.

I'm no graphics designer myself, but from this, I found [this brain image](https://pixabay.com/p-1299830) which requires no attribution and is free for commercial use. I then modified it to use the above logo's `#2e2e2c` colour. As I have no image editing software installed, I decided to make a JSFiddle which places this in the correct place on an easily-modifyable 200x200 `#f3df49` square. Here's the result:

![Brain.js logo in the style of the JavaScript logo](http://i.imgur.com/tolJmXU.png)

Here's the JSFiddle: https://jsfiddle.net/JamesD/q3n06jf4

**Comment by robertleeplummerjr** [comment]
beautiful!

**Comment by IonicaBizau** [comment]
@JamesDonnelly I love it!

**Comment by robertleeplummerjr** [comment]
@JamesDonnelly fantastic addition, added as the official logo on the readme: https://github.com/harthur-org/brain.js

ty ty ty!

**Comment by robertleeplummerjr** [comment]
Also added https://github.com/voodootikigod/logo.js/pull/111

**Comment by Dok11** [comment]
@robertleeplummerjr, @JamesDonnelly, just one size?
How about will make 16x16 (32x32) for favicon and other directions? :)

**Comment by robertleeplummerjr** [comment]
me like!

**Comment by robertleeplummerjr** [comment]
vector would be nice as well.

**Comment by Dok11** [comment]
Vector?
This is png
![brainjs](https://cloud.githubusercontent.com/assets/2697890/21853503/6616b7b0-d828-11e6-96a6-c9ee712b9113.png)

**Comment by robertleeplummerjr** [comment]
Right, but the original parts are not.

**Comment by janwirth** [comment]
The concept is pretty awesome. I gave vectorizing it a shot. 
![screen shot 2017-07-17 at 14 33 06](https://user-images.githubusercontent.com/7485959/28268044-fa31286a-6afc-11e7-9b46-92ca572c7456.png)
I would love your opinion and whether you consider using it.

**Comment by robertleeplummerjr** [comment]
Do you have the source vectors?  I love it!

**Comment by janwirth** [comment]
Sure, I just created this. AI or SVG? Should I create an MR?

I will adjust the proportions a little and tweak it here and there then.

**Comment by robertleeplummerjr** [comment]
We'll take what you give.  Svg would be awesome.

**Comment by janwirth** [comment]
Clean and valid SVG with the correct colors and proportions below :)
```svg
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 200 200">
<rect width="200" height="200" fill="#F3DF49"/>
<g>
  <polygon fill="#2E2E2C" points="104.8,110.4 134.1,133.6 134.1,148.7 94.8,163.9 74.3,164.9 58.5,143.7 73.4,123.3"/>
  <polygon fill="#2E2E2C" points="139.4,148.7 139.4,133.6 134.3,104.4 148.4,103.5 185,126 180.5,153.6 166.4,164"/>
  <polygon fill="#2E2E2C" points="163.1,167.6 137.3,153.2 101.3,166.6 142.8,177.7 148.4,186.2 155.2,186.2"/>
  <polygon fill="#2E2E2C" points="111.1,108.3 133.5,127 128.9,105.3"/>
</g>
</svg>
```

**Comment by robertleeplummerjr** [comment]
Ty again @FranzSkuffka and everyone else who made this possible.  Today we will release v1.0.0.


Its been a fun ride, but it has only just begun.
