### ISSUE TITLE
Error when calling run - 'runInput' is 'undefined'

### ISSUE THREAD

**Issue by 7ammer** [BrainJS/brain.js#205]
_Skip to link below for working example of issue..._

![bummer](https://media.giphy.com/media/6zvDSUtuMqp3O/giphy.gif)

## *What* is wrong?
When trying one of the examples in the read me I get an error.

## *Where* does it happen?

- Error is produced when using the `run` method is called.
- Property 'runInput' is undefined.
- On node or in the browser

## *How* do we replicate the issue?
https://runkit.com/jammer/5ae8f85ae8b48a001233f400

## *How* important is this (1-5)?
5 as its not working

## Expected behavior (i.e. solution)
No error

**Comment by 7ammer** [comment]
Any thoughts? I've love to try out the new time stepping methods!

**Comment by robertleeplummerjr** [comment]
I'm looking into this today, fyi.  Sorry it has taken so long, busy busy.

**Comment by 7ammer** [comment]
Hello, sorry to bump. I'm not sure if this is a bug or if I've done something wrong. Some clarification would be awesome.

Thanks :)

**Comment by robertleeplummerjr** [comment]
Ty for the bump.  It looks like the problem is that the input and output size should be set to 2 for this use case.  I've reproduced the issue in a test and will continue resolving there: https://github.com/BrainJS/brain.js/tree/205-larger-time-step

**Comment by robertleeplummerjr** [comment]
Sort of an "accidentally dynamic" design that we've stumbled upon is this:

There are two seemingly different means of predicting what comes next.  In the scenario of a single input/output, we have the following test passing:
```js
net.train([
  [1,2,3,4,5],
  [5,4,3,2,1],
]);
```

So if we feed the following values in after training:
```js
net.run([1,2,3,4]) -> 5
net.run([5,4,3,2]) -> 1
```

However, in your case, our net is larger (you want to predict `[3, 1]`), and we are wanting to get a different shape out of the net (array of 2 length).  This simply is a result of how we (me) have defined the net, and you've stumbled upon something I find very fascinating:
```js
net.train([
  [1, 3],
  [2, 2],
  [3, 1],
]);
```

then later, obviosly:
```js
net.run([
  [1, 3],
  [2, 2]
]) -> [3, 1]
```

This isn't yet handled in the net, but I'll resolve it shortly.  In the mean time: cool.

**Comment by robertleeplummerjr** [comment]
Ok, found it.  There is a quirky behavior right now where you need to wrap the training in s sub-array like this:

```js
const net = brain.recurrent.LSTMTimeStep({
  inputSize: 2,
  hiddenLayers: [5], // play with this value, or add some to deepen the net
  outputSize: 2
});
net.train([
  [
    [1, 3],
    [2, 2],
    [3, 1],
  ]
]);

net.run([[1, 3],  [2, 2]]); -> [3, 1]
```

I want to point out that the existing recurrent architecture that this uses is going to be shelved sometime soon for when v2 comes out and replaces it with superior api tooling and architecture.  In the mean time can you live with the simplicity of wrapping with the above intermediate array?  If so, we can close this, and ensure it is documented.

**Comment by 7ammer** [comment]
Hey @robertleeplummerjr, Thats super! Thanks for looking into this :)
I'm happy to close 👍

**Comment by robertleeplummerjr** [comment]
A pleasure.  I really think this type of time step is super important too because it allows you to look at multiple contexts (an input and output larger than 1) in order to formulate the next prediction.  Which is why I feel so strongly that this be a part of brain.

Imagine stock market prediction, but feeding _the whole_ market in.   What affects one stock negatively can affect the others positively.
