### ISSUE TITLE
LSTM train process takes very long time

### ISSUE THREAD

**Issue by suresh-anumolu** [BrainJS/brain.js#207]
Hi,

Is there any way can i speed up the model training process? I have been running for more than two hours for about 20-25 fields. i feel i am doing something wrong. Can you please advice? 

	var net = new brain.recurrent.LSTM();
	net.train([
    {input:'Loan Number', output:'LN'},
    {input:'Investor ID', output:'GN'},
    {input:'Program Type', output:'PT'},
    ............................................................
 ]);

Thank you
Suresh

**Comment by mubaidr** [comment]
I beleive changing your output format as following will fix the things for you:
```js
var net = new brain.recurrent.LSTM();
net.train([
{input:'Loan Number', output:{LN: 1}},
{input:'Investor ID', output:{GN: 1}},
{input:'Program Type', output:{PT: 1}},
```

**Comment by rolandjitsu** [comment]
I'm also experiencing something similar. My input is:

```text
SV (Suisse) SA\nRestaurant Campus Biotech\nChemin des Mines, 9\n1202 Geneve\nCHE-110.062.405 TVA\nCHF\nMenu Tech\n11.00\nTotal CHF\n11.00\nTotal Euro\n10.10\n1 - Espèce\n11.00\nProfit Center: 1 Restaurant\nCod - %\n(1) 7.70\nTVA 8.0%\nA.T.\n10.21\nT.T.C.\n11.00\nTVA\n0.79\n15.01.2018 12:16 #:64557 Op:272801C:2 S:27\n280\nServi par: Votre Team SV\nMerci de votre visite!\n
```

and the output would be `11.00`.

**Comment by mubaidr** [comment]
@rolandjitsu Please open a new issue, with the required info and if possible a simple jsfiddle.
