### ISSUE TITLE
Need for opinions and suggestions from experienced developers

### ISSUE THREAD

**Issue by antoniodeluca** [BrainJS/brain.js#21]
In the past I have used Brain.js and some other JavaScript based machine learning libraries but unfortunately I have found them not matching my needs. That's why, working on my personal projects, I have developed the idea of creating a different approach by myself. So, sorry to be here to talk about another project but I would really like to receive some opinions and suggestions from experienced people that, being into this specific field, could help me to set useful and shared expectations. By the way, thanks for the great support given to Brain.js so far. The library is called DN2A and is on https://github.com/dn2a/dn2a-javascript

**Comment by robertleeplummerjr** [comment]
Looks well thought out.  I see there is a lot of todo's yet to be do'ed, what is your goal with this library?

**Comment by robertleeplummerjr** [comment]
Closing for the time being.  Hope to hear more soon.
