### ISSUE TITLE
`NeuralNetwork` cannot continue training

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#211]
Reproduced here: https://jsfiddle.net/t8yar5j0/

**Comment by robertleeplummerjr** [comment]
I believe this to be an older version of brain.js and has since been resolved.

**Comment by PawanWagh** [comment]
Nope. I have tried this version of brain.js `https://cdn.rawgit.com/BrainJS/brain.js/develop/browser.js`. Please visit the jsfiddle link again the issue still persists.

**Comment by PawanWagh** [comment]
Here's another fiddle https://jsfiddle.net/La5a3bkj/1/

**Comment by robertleeplummerjr** [comment]
Starting tests to uncover the issue: https://github.com/BrainJS/brain.js/compare/211-training-continue?expand=1

**Comment by mubaidr** [comment]
The provided jsfiddle works fine: https://jsfiddle.net/mubaidr/La5a3bkj/6/


I am closing this issue, in case you need further help, please don't hesitate to re-open this issue or create a anew one.
