### ISSUE TITLE
Input hash, output String?

### ISSUE THREAD

**Issue by owen-m1** [BrainJS/brain.js#212]
How can I make it so my input can be a hash and my output can be a string?

**Comment by robertleeplummerjr** [comment]
What type of hash?

**Comment by owen-m1** [comment]
A javascript object containing number values

**Comment by mubaidr** [comment]
You can try mapping/encoding your hash objects to simple strings.

**Comment by mubaidr** [comment]
I am closing this issue, please ping if you still need help, we will happily help and re-open this issue.
