### ISSUE TITLE
Do I have to normalize date ? Do I even need to ?

### ISSUE THREAD

**Issue by Ginko-Baby** [BrainJS/brain.js#218]
//This is just an example:
var data = [
	{input: { year: 2018, month: 06, day: 09 }, output: { Bicep: 1, Back: 1 }},
	{input: { year: 2018, month: 06, day: 10 }, output: { Chest: 1, Shoulder: 1 }},
	{input: { year: 2018, month: 06, day: 11 }, output: { Rest: 1 }}
];

var net = new brain.NeuralNetwork();
net.train(data);

var output = net.run({ year: 2018, month: 12, day: 28 }); 

Do I need to "normalize" the date as well ?
from:
input: { year: 2018, month: 06, day: 09 } //I hope I can just use this directly. 
to:
input: { year: 0.2018, month: 0.5, day: 0.2903225806 } //This would be terrible.
//Assumes Year 10,000 is 1, Month 12 is 1, and Day 31 is 1 [which in itself is an incorrect overall assumption.]

**Comment by Ginko-Baby** [comment]
No help here, but for anyone reading this, I try this without normalization, the returned data is still usable !
Looks like the input data doesn't necessarily have to be normalized after all.

**Comment by robertleeplummerjr** [comment]
nice find!
