### ISSUE TITLE
modernize our packing and release systems

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#223]

**Comment by mubaidr** [comment]
If you mean script building for release, we can use [parcel-bundler](https://github.com/parcel-bundler/parcel), which is super easy to use (zero configure) and its fast! 

Also, I can help by adding dev & build scripts using parcel.

**Comment by robertleeplummerjr** [comment]
Much of the system currently feels so manual, if this is a step towards automation...  Bring it on!

**Comment by mubaidr** [comment]
I am on it! 👍

**Comment by mubaidr** [comment]
Analyzing the code base and scripts, I believe following things needed to be done: 

- [x] Update Read-me to include CDN link
- [x] Update package JSON to include Browser field
- [x] Replace browserify/uglify with Parcel-Bundler
- [x] Add Dev & Build scripts
- [x] Reduce files distributed with the npm package install. 
- [x] Update brain.js imports in examples
- [x] Validate that all tests run fine

This will make sure: 

- When using npm we don't need to load minified or build version and `index.js` will be the entry point for the script. This will also ensure that `brain.js` is built using the developer environment (babel etc)
- For direct usage in Browser 
	- a CDN link will be available. 
	- a build/minified will be available in `dist` directory. 
- existing `browser.js` & `browser.min.js` files will be removed from the root directory. 

Please let me know if you have any questions about these tasks.

**Comment by robertleeplummerjr** [comment]
I need tests back for the `FeedForward` class, `Recurrent` class, `praxis` folder, and `layer` folder.
They should equal 1 to 1 like you are doing with the new directory.

**Comment by mubaidr** [comment]
Tracked here: https://github.com/BrainJS/brain.js/projects/1#card-10984506

**Comment by robertleeplummerjr** [comment]
I don't mind resolving this.  It may be easier for me to do it because it looks like the version of `nn-gpu-layers` was slightly outdated.

**Comment by robertleeplummerjr** [comment]
Ok, I've restored the tests, but have not changed them.  I as well ensured that the important stuff from nn-gpu-layers made it in to develop.  If you'd like to resume, by all means.

**Comment by mubaidr** [comment]
Have you also removed redundant files? (I think recurrent dir inside src).

I will working on tests now.

**Comment by robertleeplummerjr** [comment]
I did.  Lets keep them for the time being, both tests and source.  We aren't totally covering all the use cases yet, so just for convenience in reference of design lets keep them for the time being.

**Comment by robertleeplummerjr** [comment]
fantastic!

When you have time, can you jump on hangouts so we can quickly coordinate efforts?

**Comment by mubaidr** [comment]
sure, in few moments.
