### ISSUE TITLE
finish new `Recurrent` class and remove `brain.recurrent`

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#224]
We need to ensure we have simplified replacements for all classes:
brain.recurrent.RNNTimeStep
brain.recurrent.LSTMTimeStep
brain.recurrent.GRUTimeStep
brain.recurrent.RNN
brain.recurrent.LSTM
brain.recurrent.GRU

**Comment by mubaidr** [comment]
I believe this done? @robertleeplummerjr

**Comment by robertleeplummerjr** [comment]
Not yet, after mnist I'll work on this.
