### ISSUE TITLE
CDN/Download link broken.

### ISSUE THREAD

**Issue by SCMorgan** [BrainJS/brain.js#228]
## *What* is wrong?

Apologies for not closely following the prescribed format.

The documented CDN link is dead, as is the github download link.
Is the library only now available through package managers?

**Comment by mubaidr** [comment]
Please use links from here: https://github.com/BrainJS/brain.js/tree/master

We have `develop` branch setup as default. Sorry for inconvenience. Will be fixed shortly. 

@robertleeplummerjr Please update the default branch to `master`

**Comment by SCMorgan** [comment]
That's perfect, thanks for your speedy response.

**Comment by robertleeplummerjr** [comment]
updated
