### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#234]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
README.md's first example does not use the config `var net = new brain.NeuralNetwork(>>>config<<<);`

## *Where* does it happen?
n/a

## *How* do we replicate the issue?
n/a

## *How* important is this (1-5)?
2

## Expected behavior (i.e. solution)
Should be documented right, minor confusion for first timers.

## Other Comments

**Comment by mubaidr** [comment]
Acknowledged, will be fixed soon.
