### ISSUE TITLE
Pull Request: train-stream.js and neural-network.js

### ISSUE THREAD

**Issue by binarybehemoth** [BrainJS/brain.js#239]
## *What* is wrong?
The stream could not be ended. Its ending should be signalled with stream.end() instead of stream.write(null). Even then, the code in the library files seem to be buggy.

## *Where* does it happen?
train-stream.js: 157, 175
neural-network.js: 175

## *How* do we replicate the issue?
Just try out stream-example.js in the newest version of node.js.

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
train-stream.js:157...................formatData --> _formatData
train-stream.js:175...................initialize --> _initialize
neural-network.js: 175...........
   value: function _initialize() {  
   -->
   value: function _initialize(s=null) {
      this.sizes = s;

## Other Comments
I wanted to do a pull request but I don't know how.  I hope the above will fix everything.

**Comment by mubaidr** [comment]
Sounds great contribution. Please fork this project, change the code where required (nothing else) and create a pull request. This way you will be listed as contributor to this project. 👍 

If you are not comfortable with that, let us know we will integrate it ourself.

**Comment by binarybehemoth** [comment]
Actually there are more issues than what I showed above. I managed to solve them for my own use but the changes may not be compatible for other users.

**Comment by mubaidr** [comment]
Can you please create a pull request, we will be happy to take a look. There must be something that is helpful to this library. :)

If its working for you, then surely it has got something good enough to share. Thanks

**Comment by robertleeplummerjr** [comment]
Can you share what you changed?  We can try and cover use cases with them if they aren't too complex.

**Comment by mubaidr** [comment]
Tracked here: https://github.com/BrainJS/brain.js/pull/243
