### ISSUE TITLE
BrainJS in Node-Red

### ISSUE THREAD

**Issue by cjkini** [BrainJS/brain.js#245]
Hi guys,
Nice meeting you all here.

Has anyone here tried to use BrainJS in Node - Red flow ? Can you guys share any example how to do this using node red.

My objective are :
1. To create a model to predict :
Input= numerical number range from 50-60, Output= 1
Input= numerical number range from 30-50, Output= 2
Input= numerical number range from 0-30, Output= 3

2. Use the above prediction model, to predict a realtime mqtt input data

Your help are much appreciated.

Thanks to everyone

Regards,
SD

**Comment by cjkini** [comment]
I already downloaded this to my Node-red palete https://flows.nodered.org/node/node-red-contrib-neuralnet

Can anyone share ,how to create a NN model using this palete.?

Your help are much appreciated.

Thanks to everyone

Regards,
SD

**Comment by mubaidr** [comment]
Welcome to our project!

I don't think we have examples of using brain.js with node-red. But we will surely like to help you achieve your goal. 

The package you have mentioned is based on much older version of brian.js. I, myself, will try to understand the requirements of the node-red and update the package as necessary. 

Please be patient.

**Comment by cjkini** [comment]
Hi @mubaidr ,
Thanks for your support.

Regards.

**Comment by mubaidr** [comment]
Hi there, please try this package: https://github.com/mubaidr/node-red-contrib-brain-js

(This is fork of the above mentioned package, all credits to the original author)

**Comment by cjkini** [comment]
Hi @mubaidr ,
Thanks for your support. I manage to integrate Node-Red and Brain JS.

This is how i do :
1. Download Brain JS file at here  https://www.npmjs.com/package/brainjs
2. Save the Brain JS folder inside the Node-Red folder
3. Edit Node-Red setting.js file to include Brain JS library and save : 
```
functionGlobalContext: {
        // os:require('os'),
           brainjs:require('brain.js'), 
```
4. Go to Node-Red, design the flow using the function node. And function is like this : 

```
var brain=context.global.get('brainjs');
var fs=context.global.get('fs');
const net = new brain.recurrent.LSTM({
  inputSize: 1,
  hiddenLayers: [20, 5, 1],
  outputSize: 1
});

const trainingData = [
         [0,"low"],
 [2,"low"],
 [4,"low"],
 [12,"medium"],
 [14,"medium"],
 [16,"medium"],
 [22,"high"],
 [24,"high"],
 [30,"high"]
 
];

const results = net.train(trainingData, { log: true });

var lstmo=net.run([12]);
msg.payload = lstmo;

```
We must use this function to call Brain Js library. 
`var brain=context.global.get('brainjs');`

5. Fire the prediction.

I hope this will help.

Thanks

**Comment by mubaidr** [comment]
Awesome! 

Thanks for sharing guide to use `brain.js` with `node-red`

**Comment by Jeroendeeerste** [comment]
@cjkini  Could you perhaps share the whole node red flow you are using? Very interested, but i still can not fully find out how to get it working,
