### ISSUE TITLE
Neural Network Error

### ISSUE THREAD

**Issue by cjkini** [BrainJS/brain.js#249]
Hi guys, 

I am trying to run the below example : 

```
var config = {
    binaryThresh: 0.5,     // ¯\_(ツ)_/¯
    hiddenLayers: [3],     // array of ints for the sizes of the hidden layers in the network
    activation: 'sigmoid' // Supported activation types ['sigmoid', 'relu', 'leaky-relu', 'tanh']
}
//create a simple feed forward neural network with backpropagation
var net = new brain.NeuralNetwork(config);

net.train([{input: [0, 0], output: [0]},
           {input: [0, 1], output: [1]},
           {input: [1, 0], output: [1]},
           {input: [1, 1], output: [0]}]);

var output = net.run([1, 0]);  // [0.987]
```
However, the code is bugged with this error : 

`"TypeError: Cannot read property 'constructor' of undefined"`

Can anyone help me, how to debug this?

Thanks for your help ya. Appreciate it.

**Comment by mubaidr** [comment]
This is the jsfiddle with the same code and it works fine: https://jsfiddle.net/mubaidr/rL721qwd/3/

Please provide this info:
- What version are you using (brain, node, browser)
- how are you installing brain.js

**Comment by cjkini** [comment]
Hi @mubaidr ,
Thanks. I solve this issue by upgrading to an new node version.

**Comment by mubaidr** [comment]
Awesome! We will add the minimum required nodejs version to the read me.
