### ISSUE TITLE
Cannot read property 'LSTM' of undefined

### ISSUE THREAD

**Issue by simonchabrol** [BrainJS/brain.js#250]
Hello,
 
 I just try the following example : 

```
var brain = require('brainjs')

net = new brain.recurrent.LSTM();

net.train([
    'doe, a deer, a female deer',
    'ray, a drop of golden sun',
    'me, a name I call myself',
  ]);
  
var output = net.run('doe'); 

console.log(output)
```

But I get the following error : 

`TypeError: Cannot read property 'LSTM' of undefined`

How can I solve this ?

**Comment by robertleeplummerjr** [comment]
`var brain = require('brain.js')` maybe?

**Comment by simonchabrol** [comment]
No I don't think, because it works with` brain.NeuralNetwork`

**Comment by mubaidr** [comment]
@robertleeplummerjr is right as `brainjs` is not the same as `brain.js` (this repo)

Install the correct package please.

**Comment by simonchabrol** [comment]
Thanx, it works !

**Comment by robertleeplummerjr** [comment]
woot woot!

**Comment by iplanwebsites** [comment]
The issue (`TypeError: Cannot read property 'LSTM' of undefined`) seems to be back in the latest version (2.0.0-beta.2 is working fine). Did the syntax for strings change?

**Comment by SudhanshuBlaze** [comment]
> The issue (`TypeError: Cannot read property 'LSTM' of undefined`) seems to be back in the latest version (2.0.0-beta.2 is working fine). Did the syntax for strings change?

Yes I also have the same issue!! How did you fix it? @iplanwebsites
