### ISSUE TITLE
Ensure that numberic values are between 0 and 1

### ISSUE THREAD

**Issue by simonchabrol** [BrainJS/brain.js#253]
Hello,

To use Brain.js, I need to convert numeric values to 0 and 1. But I haven't found a good solution to convert numeric values from large files. For example, I struggle with this dataset:
```
"Channel": 2,
"Region": 3
"Fresh": 12669,
"Milk": 9656,
"Grocery": 7561,
"Frozen": 214,
"DetergentsPaper": 2674,
 "Delicassen": 1338
```
Sometimes, I read that people divide values by 10, 100 or 1000, but I doubt it's a relevant solution. Do you have ideas ?

Thank you,

**Comment by robertleeplummerjr** [comment]
Iterate on the values, find the largest value, then divide by that?  What are you trying to accomplish?

**Comment by simonchabrol** [comment]
Hi,

I already try something like this (with my previous example): 

```
for (let i = 1; i < customers.length; i++) {
	customersData.push({
    input: {
      ch: customers[i].Channel / 10,
      re: customers[i].Region / 10,
      fr: customers[i].Fresh / 10000,
      ml: customers[i].Milk / 10000,
      gr: customers[i].Grocery / 10000,
      frz: customers[i].Frozen / 10000,
      dtp: customers[i].DetergentsPaper / 10000,
    },
    output: {
	  del: customers[i].Delicassen / 10000,
    }
  })
}
```
But it doesn't work very well. I got a lot of iterations, and an error rate close to 0.05. My goal is to lower the error rate and iterations needed.

**Comment by mattgrande** [comment]
I think what Robert was suggesting was to find the largest value for each thing beforehand. Snippet:

```
let maxChannel = 0;
// ... and all the other properties
customers.forEach(customer => {
    if (customer.Channel > maxChannel) {
        maxChannel = customer.Channel;
    }
    // ... and all the other properties
});

const customersData = customers.map(customer => {
    return {
        input: {
            ch: customers[i].Channel / maxChannel,
            ...
        }
    }
})
```

That will ensure that each value is between 0 and 1, and that the largest value for each property is exactly 1.

**Comment by simonchabrol** [comment]
Ok ! It's clearer now. Thank you for the code. I will test it !

**Comment by mubaidr** [comment]
Great! Closing this issue, please feel free to open if you need any further help.
