### ISSUE TITLE
Round numbers in output

### ISSUE THREAD

**Issue by simonchabrol** [BrainJS/brain.js#254]
Hello,

This is not really a problem or an issue. In my case, I have an output that varies from 1 to 0, like this: {Continue: 0.999995768070221, Stop: 0.000004229932983434992}

I would have liked to know if there was a solution to round these numbers, and get the following display for example: {Continue: 1, Stop: 0}

I did not find anything in the documentation, and I wondered if such a solution exists.

Thanks for your advices,

**Comment by mubaidr** [comment]
Yes, there is an addon available for that. Please view/search readme for `likely`. 

(I am on phone cant post link)

**Comment by simonchabrol** [comment]
Find it ! Thanx :)
