### ISSUE TITLE
How see error value and number iterations after training ?

### ISSUE THREAD

**Issue by tyt34** [BrainJS/brain.js#255]
In time training I see  error value, so:
  ```
net.train(myarray, {
          log: true,
          });
```
But, how to see in the future error value and number iterations?
How can I see this? How to keep it?

**Comment by tyt34** [comment]
:(

**Comment by mubaidr** [comment]
`net.train` returns what you need. just assign it to some variable:

```js
const res = net.train(myarray, {
        log: true,
        });
```

**Comment by tyt34** [comment]
Yes. 
And I will see the values throughout the training
But I ask:
how to see this varible after train? Without use ` log: true,`
How save this varible?

**Comment by mubaidr** [comment]
Like this? 

```js
console.log(res)
```

**Comment by mubaidr** [comment]
Example: (please see line no. 15)

https://jsfiddle.net/jn056e7L/8/

**Comment by tyt34** [comment]
Thankyou
