### ISSUE TITLE
Unable to load Trained Model (LSTMTimeStep) from JSON File

### ISSUE THREAD

**Issue by albertp89** [BrainJS/brain.js#262]
## *What* is wrong?
I trained a model and saved to a file using 
`JSON.stringify(net.toJSON());`

I've confirmed the object is properly read in and loaded.
When trying to run `net.run(someData)` it gives this error
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'runInput' of undefined`

Maybe I'm doing something wrong...

## *Where* does it happen?
When trying to load a trained model from a JSON file of type LSTMTimeStep

## *How* do we replicate the issue?
Train a model using LSTMT, JSONify it and try to load it back in.
Can see console output running the following JSFiddle
JSFiddle: http://jsfiddle.net/usrbjkt5/18

## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)
Model is properly loaded and able to be run.

## Other Comments

**Comment by mubaidr** [comment]
Thanks for providing the jsfiddle, we are looking into this issue.

**Comment by robertleeplummerjr** [comment]
The model loads, but the prediction isn't long enough:
```js

var net = new brain.recurrent.LSTMTimeStep();

net.train([
  [1, 2, 3]
]);

var output = net.run([1, 2]);  // 3
console.log(output);
var model = net.toJSON();

net = new brain.recurrent.LSTMTimeStep();
net.fromJSON(JSON.parse(JSON.stringify(model)));
console.log(net.run([1, 2], 3));
```

Works fine ^.  This `3` is the length of the input + the output length.  I think this is a bug that needs solved.

**Comment by mrorigo** [comment]
I was stuck on this, then found the `keepNetworkIntact: true` option for `learn()`

**Comment by robertleeplummerjr** [comment]
`keepNetworkIntact` is now removed, and this should just work as of now.
