### ISSUE TITLE
Error rate fluctuation

### ISSUE THREAD

**Issue by simonchabrol** [BrainJS/brain.js#265]
Hello,

Sometimes, I notice that between trainings, it is possible to observe fluctuations in the results. Here is an example :

```
{ error: 0.004999279467972932, iterations: 6500 }
{ Win: 0.48747244477272034, Loss: 0.5125441551208496 }

{ error: 0.00499901753758613, iterations: 6348 }
{ Win: 0.4875994622707367, Loss: 0.5123955607414246 }

{ error: 0.004998189792153667, iterations: 8187 }
{ Win: 0.4831335246562958, Loss: 0.516595721244812 }

{ error: 0.07775032963693915, iterations: 20000 }
{ Win: 0.6663448214530945, Loss: 0.33365845680236816 }
```
It's the same data set. So, my question is : is it normal to have, sometimes, an error above the error threshold ?

Thank you for advice !

**Comment by robertleeplummerjr** [comment]
This is normal, and in fact one of the (in my mind and I love to see it) coolest things about machine learning.  What is happening is that brain is learning to compartmentalize or segregate a set of logic into a simpler subset, and when it does there is a large efficiency increase.

Picture like something in the real world, bubbles.  When bubbles touch together, they first touch each other create a rather odd looking multi bubble structure, sharing sides and looking fairly odd or complex (error rate increase), and then they begin to obsorb into a single larger bubble (error rate decrease).  Simple, and complete.

**Comment by simonchabrol** [comment]
Thank you for your response ! Because I have to do a professional presentation on neural networks, and I wasn't sure about how to present the thing.

**Comment by robertleeplummerjr** [comment]
Very cool, and let me know how it goes!  Also, if you have any more questions, feel free to ask.

**Comment by robertleeplummerjr** [comment]
Also feel free to include a link to your presentation.
