### ISSUE TITLE
Given a sequence of numbers t(0) thru t(n), predict t(n+1)

### ISSUE THREAD

**Issue by gcox** [BrainJS/brain.js#266]
![Obviously](https://user-images.githubusercontent.com/251512/44746524-95f02000-aad8-11e8-925f-3ff83feac990.gif)

I'm trying to take a sequence of dates (represented as numbers) and predict the next date, which is unknown at the time of prediction.

I expected to do this:
```javascript
net.train([
  [date0, date1, ... dateN]
]);
net.run([date0, date1, ... dateN]); // -> Something near dateN + 1
```
Sadly, that throws an exception (```TypeError: Cannot read property 'runInput' of undefined at LSTMTimeStep.run...```)

Of course, all the examples I see here look like this:
``` javascript
net.train([
  [1, 2, 3]
]);
net.run([1, 2]); // -> 3
```
I don't understand why the last line isn't ```net.run([1, 2, 3]); // -> Something close to 4```. I assume I'm missing the point of the TimeStep networks, but they are documented as being able to predict future values...which doesn't seem to be demonstrated by the examples IMO.

**Actual question**
Is what I'm trying to do possible with this library?

**Comment by robertleeplummerjr** [comment]
Can you throw your example into a jsfiddle for quick reproduction?

**Comment by gcox** [comment]
Sure, here you go: [jsfiddle](https://jsfiddle.net/gcox18/muoLdksr/28/)

**Comment by robertleeplummerjr** [comment]
You just need to add the length of the entire input + output.  Example `net.run([1, 2, 3], 4); // -> 3.435204029083252`

**Comment by robertleeplummerjr** [comment]
This isn't well documented since the recurrent stuff was in beta, and is now nearly all rewritten.  In either case, this should probably be added to documentation for future humans.

**Comment by gcox** [comment]
Ah, I see. I definitely misinterpreted that 2nd argument. Postponing my lobotomy for now.

Thanks for the quick attention!

**Comment by robertleeplummerjr** [comment]
Ty for the interest! Wait till we get GPU architecture released!
