### ISSUE TITLE
LSTM Network incorrectly prepends "stop-inputstart-output" to output

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#267]
When loading a network from JSON - the output is prepended with the text "stop-inputstart-output"

The following gist is my working example:
https://gist.github.com/ytsruh/9c8f123c0f7555e861d5bb76dc526b21

Thanks for the help & support in advance

**Comment by robertleeplummerjr** [comment]
Should be now resolved in https://github.com/BrainJS/brain.js/pull/268
Let me know if this issue persists.  Note: You will need to train from new json.
