### ISSUE TITLE
Can't Deploy on Server

### ISSUE THREAD

**Issue by sulaimanO** [BrainJS/brain.js#269]
## *What* is wrong?
`remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 126
remote:        npm ERR! brain.js@1.2.6 postinstall: `opencollective postinstall
remote:        npm ERR! Exit status 126
remote:        npm ERR!
remote:        npm ERR! Failed at the brain.js@1.2.6 postinstall script.
remote:        npm ERR! This is probably not a problem with npm. There is likely                                                 additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.GFxab/_logs/2018-08-30T00_34_10_063Z-d  `

## *Where* does it happen?
Can't deploy node js REST API on Heroku because of the issue above

## *How* important is this (1-5)?
5

Thank you for great work, this npm package is simple and powerfull 
Thank you for all developers who work on this package

**Comment by robertleeplummerjr** [comment]
Resolved https://github.com/BrainJS/brain.js/pull/270
Sorry about the failure.  I didn't realize the package was essentially an ad, removed with extreme prejudice.  Please let me know if there are any other issues.

**Comment by sulaimanO** [comment]
It works !!

thank you Robert
