### ISSUE TITLE
Different activation functions

### ISSUE THREAD

**Issue by philiiiiiipp** [BrainJS/brain.js#27]
Hey, 

first of, cool work :-)! As far as I see it brain.js is currently using a sigmoid/logistic activation function. I think it would be quite beneficial to.
1. Document that this one is used
2. Create different ones

I could implement some of them like tanH which are working in the range of (0,1) which is currently used as output.

**Comment by robertleeplummerjr** [comment]
I'm currently working on implementing tanH in [the recurrent branch](https://github.com/harthur-org/brain.js/tree/recurrent):
Forward propigate a matrix: https://github.com/harthur-org/brain.js/blob/recurrent/lib/recurrent/matrix/tanh.js
Backpropagate a matrix: https://github.com/harthur-org/brain.js/blob/recurrent/lib/recurrent/matrix/tanh-b.js

Currently is 90% or so working (weights aren't zeroing out and result in infinity after a few runs) and will be done soon (maybe a week or two?) I think after I make headway there, I can address this.

**Comment by robertleeplummerjr** [comment]
Just fyi, have not forgotten.  A minor surgery and a bunch of planning later, this is still on the board.

**Comment by robertleeplummerjr** [comment]
Also, pull requests are always welcome.

**Comment by robertleeplummerjr** [comment]
Booya! https://github.com/harthur-org/brain.js/tree/other-activation-functions
Doesn't yet work, but the most of the methods and math is there.

**Comment by robertleeplummerjr** [comment]
https://github.com/harthur-org/brain.js/pull/87



Would you be so kind as to give a code review and any insights?

**Comment by robertleeplummerjr** [comment]
example:
```js
const net = new brain.NeuralNetwork({
  activation: 'leaky-relu'
});
```
