### ISSUE TITLE
Training iterative output?

### ISSUE THREAD

**Issue by kmaher9** [BrainJS/brain.js#272]
A question rather than an issue; is there any way to receive an output while the training is ongoing? For example, I've called  `net.train(inputs)`, but my inputs are 200 files in 2 classes. I understand this may be a slightly big input set for an LSTM in JS, but it has been running for about 15 minutes now.

I would like to know if this has hung or encountered an error, but without a contemporaneous output such as `training on [input] ...` I don't know how I can tell.

Again this is a question/maybe a request, but not an issue.

**Comment by mubaidr** [comment]
Yes, check the `log` option: https://github.com/BrainJS/brain.js#training-options

- Set it to true to console the output of each iteration. 
- Set it as function to run call back on each iteration.
