### ISSUE TITLE
Stream example doesn't work.

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#274]
![Sad times](https://i.imgur.com/18eaY.gif)

## *What* is wrong?
Stream example doesn't work.

## *Where* does it happen?
Running the example script on Windows 10 (git bash, node v10.5.0).

## *How* do we replicate the issue?
https://github.com/BrainJS/brain.js/blob/da8daa7b3923667a62d7b51f5f4fba9009d43457/examples/cli/stream-example.js

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
It should work.

## Other Comments
Error says:
```
TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
```

**Comment by robertleeplummerjr** [comment]
Now working, please reopen if you find any issues.  The api did change a little.
