### ISSUE TITLE
Why ...error: NaN...?

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#278]
![358d2b66-6606-4f1c-9841-cb9b9de25a92](https://user-images.githubusercontent.com/42932420/46062286-fde66480-c171-11e8-8163-c3b8122b14ee.jpeg)

**Comment by robertleeplummerjr** [comment]
Inputs are not normalized.  Take the highest value of the inputs, and divide each by that number.  

Why this needs to be done either automatically or manually: Imagine whispering a beautiful novel to someone right in their ear, then yell at the top of your voice randomly and see how much of the beauty they appreciate.  Or imagine yelling across a casum to someone that you need help, and then whispering why and what you need, and see how much the person understands.

Digital neural networks operate on the same principles as real ones.  Ensuring values are of the same magnitude prevent headaches.
