### ISSUE TITLE
LSTMTimeStep - errors in instantiating+ training (prob doing smth noob-stoopid?)

### ISSUE THREAD

**Issue by kitt-th** [BrainJS/brain.js#283]
## *What* is wrong?
instantiating an LSTMTimeStep net causes a runtime error:

/Users/user/node_modules/brain.js/dist/recurrent/lstm-time-step.js:23
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
                                                                                            ^

(the ^ is pointing to "throw new TypeError)

TypeError: Cannot call a class as a function
    at _classCallCheck (/Users/user/node_modules/brain.js/dist/recurrent/lstm-time-step.js:23:99)
    at Object.LSTMTimeStep (/Users/user/node_modules/brain.js/dist/recurrent/lstm-time-step.js:33:5)
    at Object.<anonymous> (/Users/user/bots/mLearning/brain/xbtDeltas1.js:9:29)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)

## *Where* does it happen?

here... when instantiating

const net = brain.recurrent.LSTMTimeStep( { inputSize: xbtData.length,
	hiddenSizes: [20, 20],
	outputSize: 1,    learningRate: 0.01,
	decayRate: 0.999
} );

xbtData is an array of arrays like this:

[ [ 0.4512294117647059, 0, 0 ],
  [ 0.46941764705882355,
    0.46941764705882355,
    0.0002872737719046281 ],
.........
  [ 0.47466470588235293,
    0.47466470588235293,
    -0.00028459622910004256 ] ]

## *How* important is this (1-5)?

5

## Expected behavior (i.e. solution)
normal instantiating of the net?? 

## Other Comments
I'm pretty new to this.... so please forgive me if I've missed something v.obvious!

Cheers

**Comment by mubaidr** [comment]
Please use `new` keyword, as: 
```Js
const net = new brain.recurrent.LSTMTimeStep( { inputSize: xbtData.length,
hiddenSizes: [20, 20],
outputSize: 1, learningRate: 0.01,
decayRate: 0.999
} );
```

**Comment by kitt-th** [comment]
great - thanks!
 - I do have a new question ;)

when it comes to training the net, I get an error referring to the error rate, whether I call it without options set or not -  thus:

------------------------------------------

/Users/user/node_modules/brain.js/dist/recurrent/rnn.js:475
        if (isNaN(error)) throw new Error('network error rate is unexpected NaN, check network configurations and try again');
                          ^

Error: network error rate is unexpected NaN, check network configurations and try again
    at LSTMTimeStep.train (/Users/user/node_modules/brain.js/dist/recurrent/rnn.js:475:33)
    at Object.<anonymous> (/Users/user/bots/mLearning/brain/xbtDeltas1.js:64:7)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

--------------------------------------

I get the same error with either of these calls....

```js
net.train( [ xbtData ] );
```
OR

```js
net.train( xbtData );
```
OR

```js
net.train([
xbtData, {
      iterations: 20000,   
      errorThresh: 0.005,   
      log: true,         
      logPeriod: 10,        
      learningRate: 0.3,   
      momentum: 0.1,        
      callback: null,       
      callbackPeriod: 10,   
      timeout: Infinity     
}
]);
```

--------------------------------------

Is there something obvious I've missed here too?

Cheers

**Comment by robertleeplummerjr** [comment]
I believe the issue is a misuse of the api.  This is your usage.

```js
net.train([ trainingData, trainingOpts ]);
```

This is the supported usage:


```js
net.train([ trainingData ], trainingOpts);
//or
net.train(trainingData, trainingOpts);
```

**Comment by kitt-th** [comment]
Hi, I get the same errors sending my training data alone (as shown above) using default options by omission, or putting the options in a config object. Any ideas?

------------------------------------------

const config = {      iterations: 20000,
      errorThresh: 0.005,
      log: true,
      logPeriod: 10,
      learningRate: 0.3,
      momentum: 0.1,
      callback: null,
      callbackPeriod: 10,
      timeout: Infinity
}

net.train( xbtData, config) // also tried ->  net.train( xbtData )



------------------------------------------
/Users/user/node_modules/brain.js/dist/recurrent/rnn.js:475
        if (isNaN(error)) throw new Error('network error rate is unexpected NaN, check network configurations and try again');
                          ^

Error: network error rate is unexpected NaN, check network configurations and try again
    at LSTMTimeStep.train (/Users/briausermay/node_modules/brain.js/dist/recurrent/rnn.js:475:33)
    at Object.<anonymous> (/Users/user/bots/mLearning/brain/xbtDeltas1.js:74:7)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

**Comment by robertleeplummerjr** [comment]
Can you create a jsfiddle or similar that reproduces the issue?  We can work through this together!

**Comment by kitt-th** [comment]
Sure!

I took some of the training data and put it in an array so we know what we're working with

https://jsfiddle.net/#&togetherjs=6SutILgFJA

**Comment by kitt-th** [comment]
that jsfiddle link expired... will get another one up and post

**Comment by robertleeplummerjr** [comment]
I think the problem is simply input and output dimensions. 
 If I change them to 1, it seems to work fine: https://jsfiddle.net/robertleeplummerjr/Lhekuw3g/1/

**Comment by kitt-th** [comment]
ah thanks v.much! I'll get onto tweaking and examining tomorrow :)

**Comment by robertleeplummerjr** [comment]
cool!
