### ISSUE TITLE
LSTM Took a lot of time in Raspberry pi 3

### ISSUE THREAD

**Issue by ahmetcanaksu** [BrainJS/brain.js#285]
![slowly](https://media.tenor.com/images/2798fa534283517b890f34dca3249fe0/tenor.gif)

## *What* is wrong?

Training tooks a lot of time is there any solution for that ?

## *Where* does it happen?

In LSTM when I trying to train 4 arrays in my text recommendation engine on raspberry pi 3

## *How* do we replicate the issue?

 
Too simple !

```js
var tdata = ["text","text text"," text text text"," text text text text"," text text text text text"," text text text text text text"]

const lstm = new brain.recurrent.LSTM({
	hiddenLayers: [4,3],
});
const result = lstm.train(tData,{ iterations: 5000, learningRate: 0.3});
const json = lstm.toJSON();
```

## *How* important is this (1-5)?

5 "for real i will send the project for interview"

## Other Comments

In testing I put hidden Layers and raise the iterations. Actually I don't know what is side effects to my code

**Comment by roysG** [comment]
@ahmtcn123, 
How did you speed up the process?

I have the same issue.. it takes long time for simple process..

**Comment by ahmetcanaksu** [comment]
> @ahmtcn123, How did you speed up the process?
> 
> I have the same issue.. it takes long time for simple process..

It didn't have a gpu support back then. So I never solved the speed issue
