### ISSUE TITLE
Process not continuing while training

### ISSUE THREAD

**Issue by ahmetcanaksu** [BrainJS/brain.js#287]
![c](https://media.giphy.com/media/KBx7fQoLxuV7G/giphy.gif)

## *What* is wrong?
Process not continuing while training

## *How* important is this (1-5)?
5 - I have to complete my project
## Other Comments
It will be nice to get example

**Comment by robertleeplummerjr** [comment]
Can you reproduce with jsfidde?

**Comment by ahmetcanaksu** [comment]
https://repl.it/repls/OptimalRelevantDonateware Like I said process will continuing when train done . Im trying to find A way to keep continue the process

**Comment by robertleeplummerjr** [comment]
This _should_ work, but I believe you have found a bug:

```js
var brain = require("brain.js")

const lstm = new brain.recurrent.LSTM({
hiddenLayers: [4, 3],
});

console.log('beginning training');
const trainingData = ["a1","b2","c3","d4","e5","f6","g7"];
const result = lstm.train(trainingData, {
  iterations: 1000,
  learningRate: 0.3,
  errorThresh: 0.07,
  log: true
});
const json = lstm.toJSON();
console.log('training finish', result);
console.log(lstm.run("a"));
console.log(lstm.run("b"));
console.log(lstm.run("c"));
console.log(lstm.run("d"));
console.log(lstm.run("e"));
console.log(lstm.run("f"));
console.log(lstm.run("g"));

console.log("Process continuing, error should be close to what is above");
const newLstm = new brain.recurrent.LSTM();
newLstm.fromJSON(json);
newLstm.train(trainingData, {
  iterations: 1000,
  learningRate: 0.3,
  errorThresh: 0.06,
  log: true
});
console.log(newLstm.run("a"));
console.log(newLstm.run("b"));
console.log(newLstm.run("c"));
console.log(newLstm.run("d"));
console.log(newLstm.run("e"));
console.log(newLstm.run("f"));
console.log(newLstm.run("g"));
```

**Comment by ahmetcanaksu** [comment]
I asked wrong . I'm trying to say how can I get continuous process while training. When I apply my code everything works but Script waiting for training

**Comment by robertleeplummerjr** [comment]
Oh ok, just add `log: true` to your training options.  What is happening is the net is training sync, blocking that from executing until after it's trained.

**Comment by robertleeplummerjr** [comment]
In the example I have above, you'll see I shortened the `iterations`, so it would avoid this.

**Comment by ahmetcanaksu** [comment]
My dialog engine works with same script with my page so while training my page not oppening . I think using child process will work fine

**Comment by robertleeplummerjr** [comment]
I like that idea.

**Comment by ahmetcanaksu** [comment]
Thanks for support again!!  I can not wait for v2 :)
