### ISSUE TITLE
append trained data to the existing model

### ISSUE THREAD

**Issue by hvadym** [BrainJS/brain.js#291]
![MEME](https://cdn-images-1.medium.com/max/1600/1*eJfR3ui_2SsPAyMYF5R00A.jpeg)

## *What* is wrong?
Can`t save model.

## *Where* does it happen?
In the a NeuralNetwork when trying to run a net in node.js on my win pc

## *How* do we replicate the issue?

1. get data from csv
2. train 
3. save to file
4. load from file 
5. predict

It`s OK. But if I want to continue training? How I can append trained data to the existing model?  

## *How* important is this (1-5)?
4

**Comment by robertleeplummerjr** [comment]
Can you give us a code sample via jsfiddle or similar?

**Comment by hvadym** [comment]
> Can you give us a code sample via jsfiddle or similar?

yes. Here is part of code https://jsfiddle.net/ykeqb356/

**Comment by robertleeplummerjr** [comment]
![](https://media0.giphy.com/media/4560Nv2656Gv0Lvp9F/giphy.gif)

Here are your droids.

https://jsfiddle.net/robertleeplummerjr/ykeqb356/16/


Looks like it was just a little mixup with variable names and methods is all.  Let me know if that isn't satisfactory.

**Comment by robertleeplummerjr** [comment]
Please note: I did change the functions around a little but only to try and accentuate the api to help.  I hope not to defamate any work.

**Comment by hvadym** [comment]
> Please note: I did change the functions around a little but only to try and accentuate the api to help. I hope not to defamate any work.

soooo. Can you provide an example, how to append data to trained model?
Thank you)

**Comment by robertleeplummerjr** [comment]
Easy enough: https://jsfiddle.net/robertleeplummerjr/ykeqb356/20/
