### ISSUE TITLE
Encoded string neural network give NaN

### ISSUE THREAD

**Issue by WaqqasI** [BrainJS/brain.js#292]
**insert gif here**

## *Where* does it happen?
Training and running a neural network with encoded strings is returning NaN

## *How* do we replicate the issue?
Here's the code:
```js
let brain = require('brain.js');

let trainingData = 
    [{input: "hello", output: {ontopic: [1]} },
    {input: "hi", output: {ontopic: [1]} },
    {input: "lol", output: {ontopic: [1]}},
    {input: "wassup", output: {offtopic: [1]}}]

function encode(arg) {
    return arg.split('').map(x => (x.charCodeAt(0) > 255 ? 0.1: x.charCodeAt(0) / 255)); // encodes the letters into numbers from the charcode, and if the charcode is too high it just gives 0.1
 }
 
function processTrainingData(data) {
    return data.map(d => {
        return {
            input: encode(d.input),
            output: d.output
        }
    })
 }

let net = new brain.NeuralNetwork();

net.train(processTrainingData(trainingData));
let exec = net.toFunction();
console.log(exec(encode('hey')));
```
Gives out NaN for ontopic and offtopic
## *How* important is this (1-5)?
Uh, a 3?

## Expected behavior (i.e. solution)
It should've given the numbers when running it

**Comment by robertleeplummerjr** [comment]
For using a feed forward neural network, the inputs and outputs need to be the same size.  To get around this just use a recurrent neural network:

https://jsfiddle.net/robertleeplummerjr/zbwh9ugt/15/

```js
let trainingData = 
    [{input: "hello", output: 'ontopic' },
    {input: "hi", output: 'ontopic' },
    {input: "lol", output: 'ontopic'},
    {input: "wassup", output: 'offtopic'}];

let net = new brain.recurrent.LSTM();

net.train(trainingData, {
  log: true,
  errorThresh: 0.014,
  iterations: 500
});
let exec = net.toFunction();
console.log(net.run('hey'));
console.log(exec('hey'));
console.log(net.run('wassup!'));
console.log(exec('wassup!'));
```

**Comment by WaqqasI** [comment]
Hm, but even if I make the inputs the same size, it still doesn't work. And I'd rather not use recurrent, because it takes a long time to train and ends up with things like `opic`

**Comment by robertleeplummerjr** [comment]
Easy enough: https://jsfiddle.net/robertleeplummerjr/zbwh9ugt/21/

Just have to make sure you ensure they are all the same length.  I see what the problem was, it was with output data:  The output on a FeedForward network needs to be either an array _or_ an object.  You defined it as an object with an array inside it.  Correct, and I hope this helps you.

**Comment by WaqqasI** [comment]
Oh cool, thanks for the help!
