### ISSUE TITLE
Error calling .toJSON for big data.

### ISSUE THREAD

**Issue by ArtReeX** [BrainJS/brain.js#296]
![](https://i.gifer.com/4aQq.gif)

## *What* is wrong?
I sent the neural network LSTM for training 7000 examples, saving it after each iteration. After an hour spent on one iteration, the called method .toJSON returns the exception "Array buffer allocation allocation failed".

## *Where* does it happen?
This happens in recurrent.LSTM(), after learning and calling the .toJSON method.

## *How* do we replicate the issue?
const net = new brain.recurrent.LSTM();
net.train([patterns](https://github.com/BrainJS/brain.js/files/2552110/patterns.txt), {
      "iterations": 1,
      "errorThresh": 0.1,
      "log": true,
      "logPeriod": 1,
      "learningRate": 0.3,
      "momentum": 0.1,
      "callbackPeriod": 1,
      "timeout": null
    });
brain.toJSON(); // error - Array buffer allocation failed

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
The method must correctly return an object so that I can save it to disk.

## Comment
My application that is based on your neural network has encountered this problem. I really hope for a quick decision so that I can continue working :)

**Comment by robertleeplummerjr** [comment]
Can you share more details of your system, perhaps privately (my id @ google mail)?  We may need to do something creative to allocate the json, or perhaps there is a memory leak that needs addressed.

**Comment by ArtReeX** [comment]
> Can you share more details of your system, perhaps privately (my id @ google mail)? We may need to do something creative to allocate the json, or perhaps there is a memory leak that needs addressed.

Of course, I'll email you.

**Comment by robertleeplummerjr** [comment]
I see what is happening.  The data you are sending in to be used via a `LSTM` network, and what it wants to do is build unique values for each input.  This isn't ideal with decimal data that doesn't repeat, because each value gets its own neuron.  What you want is a `LSTMTimeStep` network.  This should take considerably less time, and will look something like this:

```
const net = new brain.recurrent.LSTMTimeStep();
// patterns will need to change, or the api will need to be made easier.  I favor the latter
net.train(patterns, {
"iterations": 1,
"errorThresh": 0.1,
"log": true,
"logPeriod": 1,
"learningRate": 0.3,
"momentum": 0.1,
"callbackPeriod": 1,
"timeout": null
});
brain.toJSON(); // error - Array buffer allocation failed
```

Example: https://jsfiddle.net/robertleeplummerjr/Lr7fod20/22/
