### ISSUE TITLE
optimum hiddenLayers

### ISSUE THREAD

**Issue by cnkostas** [BrainJS/brain.js#297]
hi i try to train a neural network the sample of import data are
{input: {a:0.26,b:0.31,c:0.23,d:0.14,e:0.12,f:0.13},output:{m:1}},
{input: {a:0.13,b:0.43,c:0.63,d:0.14,e:0.12,f:0.13},output:{k:1}},
{input: {a:0.15,b:0.34,c:0.53,d:0.11,e:0.12,f:0.21},output:{l:1}}

the inputs are about 2000 so how mach hiddenLayers nodes i need?

**Comment by robertleeplummerjr** [comment]
I think that will take some experimentation.  I'm not sure there is a fixed rule.  It depends on the quality of the data, what you are training for, and how easy it can be deciphered.

**Comment by cnkostas** [comment]
i am trying to predict weather the data are moisturize pressure  and others

**Comment by robertleeplummerjr** [comment]
How many measurements are you inputting?
