### ISSUE TITLE
How do I generate text

### ISSUE THREAD

**Issue by torinberger** [BrainJS/brain.js#298]
## *What* is wrong?
I dont know how to generate text using brain.js, I would like to train the neural net with text, e.g a book. Then ask the bot to generate an output. E.g generate a book

## *How* important is this (1-5)?
1, I think this would be really funny if given the right input. It's not really important.

## Other Comments
I love this framework, thanks for creating something so awesome.

**Comment by magicmark** [comment]
maybe you're looking for markov chains?

e.g. https://github.com/substack/node-markov

**Comment by torinberger** [comment]
Hmm not exactly what I'm looking for, very close however.

**Comment by robertleeplummerjr** [comment]
This is basically the use case described here: https://github.com/BrainJS/brain.js/blob/master/examples/childrens-book.js
