### ISSUE TITLE
fromJSON does not work with LSTM

### ISSUE THREAD

**Issue by Enitoni** [BrainJS/brain.js#299]
I'm trying to use a LSTM network to just feed messages from a discord server, as a fun experiment to see what it can come up with. The problem is when I save the data using `toJSON` and then restoring it, it seems like the data is incompatible with what `fromJSON` expects.

```ts
const network = new brain.recurrent.LSTM();
const data = await getDataSomehow()

network.fromJSON(data)
```

`getDataSomehow` loads the json file, parses it and returns the object.
After doing this, this error is put in console whenever `run` is called: 
![image](https://user-images.githubusercontent.com/5295397/48306713-e99dd180-e53d-11e8-8c61-c761bcc45bc0.png)

Furthermore, when I try training with new data, if it encounters a character that was not in the original training data, it gives me `Unrecognized character`.

What am I doing wrong?

**Comment by robertleeplummerjr** [comment]
What does your training data look like?

**Comment by robertleeplummerjr** [comment]
The other issue mentioned about the `DataFormatter` throwing an error should be solved more recently when dealing with strings, by adding a neuron for unknown sequences.  If this isn't working for your data set, I imagine we just need to ensure it is covered.

**Comment by Enitoni** [comment]
Hi, the training data is just random pieces of messages that I selected from my discord chat. I had to add all the allowed characters at the top, and I believe because of this, the network isn't really learning properly, a lot of the results have gibberish sentences, but I have to include it otherwise I get that unrecognized error.

![image](https://user-images.githubusercontent.com/5295397/48316184-75683a00-e5e0-11e8-9387-59416291080d.png)

I should mention that this runs on a discord bot which periodically collects messages and trains the network with them, but I'm not sure if calling train actually improves the network or replaces it.

**Comment by robertleeplummerjr** [comment]
What does your network setup look like?

**Comment by Enitoni** [comment]
It's a bit complicated, which is why I omitted it, but here you go:

```ts
const readFile = promisify(fs.readFile);
const writeFile = promisify(fs.writeFile);

const NETWORK_JSON_PATH = "./network.json";
const MESSAGE_LIMIT = 50;

export class ChatTrainingService extends Service {
  private hasTrained = false;

  private logger!: ChannelLoggingService;
  private timer: any;

  private network = new brain.recurrent.LSTM({
    activation: "sigmoid"
  });

  private messages: string[] = INITIAL_TRAINING_DATA;

  public async serviceDidInitialize() {
    this.logger = this.bot.getService(ChannelLoggingService);
  }

  public async serviceDidStart() {
    if (!this.hasTrained) this.train();
  }

  @bind
  public add(message: string) {
    const safeMessage = sanitizeChatMessage(message);

    if (this.messages.length < MESSAGE_LIMIT) {
      this.messages.push(safeMessage);
    }
  }

  @bind
  public run(message: string) {
    const safeMessage = sanitizeChatMessage(message);
    return this.network.run(safeMessage);
  }

  @bind
  private resetTimer() {
    clearTimeout(this.timer);
    this.timer = setTimeout(this.train, 600000);
  }

  @bind
  /** Consume messages collected and train the network with them */
  private async train() {
    this.hasTrained = true;

    const messages = [...this.messages];
    this.messages = [];

    if (messages.length === 0) return this.resetTimer();

    await this.logger.logInfo("Training...", "Wavey may become unresponsive");
    await this.bot.client.user.setGame("Training...");

    try {
      const result = this.network.train(messages, {});
      this.logger.logSuccess("Trained", JSON.stringify(result, null, 2));
    } catch (error) {
      this.logger.logError("Failed to train", error.toString());
    }

    this.bot.client.user.setGame("");
    this.resetTimer();
    this.save();
  }

  private async load() {
    try {
      const data = await readFile(NETWORK_JSON_PATH, { encoding: "utf-8" });
      const json = JSON.parse(data);

      this.network.fromJSON(json);
      this.logger.logSuccess("Restored training data");
    } catch (error) {
      console.log(error);
      this.logger.logError("Failed to load training data");
    }
  }

  private async save() {
    const data = this.network.toJSON();
    const stringified = JSON.stringify(data);

    await writeFile(NETWORK_JSON_PATH, stringified);

    this.logger.logSuccess("Saved training data");
  }
}
```

The public methods `add` and `run` is called elsewhere. The load function is not used because of said issue.

**Comment by jorgelahoz** [comment]
The same here, the issue appears when exportinf/importing to/from JSON. For example:

```
const BrainJS = require("brain.js");
var net = new BrainJS.recurrent.LSTM();
var trainOps = {
    iterations: 20000,
    errorThresh: 0.011,
    log: true,
    logPeriod: 1,
    timeout: Infinity     // the max number of milliseconds to train for --> number greater than 0
};
var data = [
    'doe, a deer, a female deer',
    'ray, a drop of golden sun',
    'me, a name I call myself',
];
net.train(data, trainOps);
var output = net.run('doe');  // ', a deer, a female deer'
console.log(output);
var json = net.toJSON();
net.fromJSON(json);
var output = net.run('doe');  // ', a deer, a female deer'
console.log(output);
```

Returns
```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at LSTM.run (/code/node_modules/brain.js/src/recurrent/rnn.js:311:27)
```

**Comment by felangel** [comment]
I'm seeing this issue as well and after taking a quick look it seems like `DataFormatter.fromJSON` does not read `specialIndexes` which causes an exception to be thrown in `rnn.js`.

**Comment by felangel** [comment]
@robertleeplummerjr I've created a PR which seems to address the issue at https://github.com/BrainJS/brain.js/pull/302.

**Comment by robertleeplummerjr** [comment]
Reproduced.  Great find @felangel and everyone who worked on this.  Merging now, and will have a new version out within the next 10 minutes.

**Comment by robertleeplummerjr** [comment]
Reproduction url: https://jsfiddle.net/robertleeplummerjr/jcvu0tx6/1/

**Comment by robertleeplummerjr** [comment]
Fixed url: https://jsfiddle.net/robertleeplummerjr/jcvu0tx6/2/
