### ISSUE TITLE
Consider merging in all the PRs submitted to harthur's original brainjs

### ISSUE THREAD

**Issue by ClimbsRocks** [BrainJS/brain.js#30]
First of all, so excited to see someone doing this! Having maintained several open source projects myself, I completely understand why harthur would decide to move on from spending her time maintaining these. But her projects are so useful that they shouldn't be left to languish. Very happy to see the community picking up the torch!

One suggestion I have (if you haven't done it already) is to merge in all the PRs that were submitted to harthur's original brain repo. It should be pretty doable with just a little bit of git fu. They wouldn't show up as PRs that were merged in, just external branches that were added to master, but I think that's ok. 

Or another alternative, you could also just comment on all the old PRs and ask the original authors to resubmit them to the harthur-org repo. 

Either way, thanks for picking up the torch here! Glad to see actively supported machine learning in JavaScript :)

**Comment by IonicaBizau** [comment]
I agree! 👍

**Comment by robertleeplummerjr** [comment]
love it!

**Comment by robertleeplummerjr** [comment]
I went through each issue and pr yesterday and today, and I believe we are off on a good path to get them into brain.js.  We already have two closed pr's!

**Comment by ClimbsRocks** [comment]
That's awesome! I'm super excited to see this project being supported over by the community, and in a very respectful way.

**Comment by robertleeplummerjr** [comment]
Very kind and encouraging words, ty!

**Comment by robertleeplummerjr** [comment]
I believe we have achieved this, I will continue to monitor the original repo in time.
