### ISSUE TITLE
outputs out of range with NeuralNetwork()

### ISSUE THREAD

**Issue by cnkostas** [BrainJS/brain.js#300]
i am getting strange outputs ranges from NeuralNetwork
more training more values out of range my training data are from 0 to 0.9 what's wrong?
https://jsfiddle.net/1xr9zuvy/
console output from net.run

 { sun: 0.9480375647544861,
  cloud: 0.0000012484682656577206,
  rain: 0.002350462833419442,
  t1_0: 0.009168339893221855,
  t1_1: 0.2973463833332062,
  t1_2: 0.33873674273490906,
  t1_3: 0.14784488081932068,
  t1_4: 0.031805701553821564,
  t1_5: 6.39397701451827e-11,
  t1_6: 1.6494860761561564e-13,
  t1_7: 0.000015186551536316983,
  t1_8: 0.0006069779628887773,
  t2_0: 0.198526531457901,
  t2_1: 0.653838038444519,
  t2_2: 0.09187424182891846,
  t2_3: 1.5359564731198816e-9,
  t2_4: 7.427101156309845e-10,
  t2_5: 0.000038855301681905985,
  t2_6: 0.0000015368534604931483,
  t2_7: 0.0006563678616657853,
  t2_8: 0.000013165104064682964 }

**Comment by robertleeplummerjr** [comment]
What network are you using?  What does your network setup lookup look like?

**Comment by cnkostas** [comment]
i have post a working fiddle thanks, i have try to edit layers,activation etc but the same the more training the more out of range
net102=new brain.NeuralNetwork()
net102.train(data, {
  activation: 'sigmoid', 
  iterations: 30000, 
  errorThresh: 0.005, 
  log: true,
  logPeriod: 10, 
  learningRate: 0.3, 
  momentum: 0.1, 
  callback: null, 
  callbackPeriod: 1000, 
  timeout: Infinity 
});

**Comment by robertleeplummerjr** [comment]
Sorry, didn't see it.  On phone with kids running around playing and screaming.

**Comment by cnkostas** [comment]
have a nice time.Please check it when/if you have time.

**Comment by robertleeplummerjr** [comment]
Which values look out of range to you?

**Comment by cnkostas** [comment]
the output mast be between 0 and 1 right?
t1_5: 6.39397701451827e-11,
t1_6: 1.6494860761561564e-13,
t2_3: 1.5359564731198816e-9,
t2_4: 7.427101156309845e-10,

question 1
can i use NeuralNetworkGPU() from node?
question 2
can i merge 2 trained nn?
question 3
can i split the train job NeuralNetwork() in 4 threads cpu?

**Comment by robertleeplummerjr** [comment]
Those are exponentials.  They look like they much larger than they in fact are (I struggle with it too).  It is the "e-" that gives them away.  The form they are taking is like a scientific notation for a very very very tiny number.

If you put them in a console, and use `.toFixed()` you can get something more legible:

```js
(6.39397701451827e-11).toFixed(20)
"0.00000000006393977015"
(1.6494860761561564e-13).toFixed(20)
"0.00000000000016494861"
(1.5359564731198816e-9).toFixed(20)
"0.00000000153595647312"
(7.427101156309845e-10).toFixed(20)
"0.00000000074271011563"
```

I believe javascript uses this notation for performance.

>can i use NeuralNetworkGPU() from node?

In node, it will fallback to CPU mode, but that will change soon when gpu.js get's opencl support, which will be after brain.js v2 (working hard on it) lands. So yes, but not will full support.  If you do find a bug, be sure to turn it in, I'll ensure it is resolved shortly.

>can i merge 2 trained nn?

Using the existing training methods, I don't believe so.  However, we will be adding resilient back propagation soon, which will allow for this.

>can i split the train job NeuralNetwork() in 4 threads cpu?

Not yet, but when resilient back propagation is added, yes.   As it allows you to essentially add nets together for reuse.  Our main sponsor is really wanting this, and I'm going to see about having it added before v2.

This sounds like a lot of work, but if you'd like to get involved the invitation is open to you or anyone reading.

**Comment by robertleeplummerjr** [comment]
I believe this issue is actually a case of mistaken identity, and closing for the time being.

**Comment by cnkostas** [comment]
ok not working in node working in chrome or some where else or will work after brain.v2?can i train there with NeuralNetworkGPU and how an example if working.

of course i will get involved  .when i have free time i will tell you

**Comment by robertleeplummerjr** [comment]
Ok, will look at this after work today, and will have this resolved with tests.  Ty for bringing it to my attention.

**Comment by robertleeplummerjr** [comment]
I believe this might be a duplicate of https://github.com/BrainJS/brain.js/issues/282

**Comment by robertleeplummerjr** [comment]
I'll continue tracking there.

**Comment by cnkostas** [comment]
thank you
