### ISSUE TITLE
brain.NeuralNetworkGPU()

### ISSUE THREAD

**Issue by cnkostas** [BrainJS/brain.js#306]
i run the script with brain.NeuralNetworkGPU() to chrome and working but run from cpu

i nave amd card win7x64 chrome i need nvidia,linux to work?

**Comment by robertleeplummerjr** [comment]
I apologize, but which is not working?  Make sure you update to latest brain.js and rerun `npm i` or `yarn`.  In node it will currently fallback to CPU, this will change after v2.

**Comment by cnkostas** [comment]
sorry for my bad English i will explain.

what is the deference of NeuralNetwork() and NeuralNetworkGPU()?is that the first  one using the cpu and the other the gpu?

because when i run the script https://github.com/BrainJS/brain.js/blob/master/examples/gpu.html in chrome with the last browser.js the script is running and i have results but the job done by cpu's 1 thread just like NeuralNetwork() and the gpu is not loaded.

**Comment by robertleeplummerjr** [comment]
>what is the deference of NeuralNetwork() and NeuralNetworkGPU()?is that the first one using the cpu and the other the gpu?

In node, there will be very little difference.  One (`NeuralNetwork`) runs using standard loops which are defined inside of brain.js.  The other (`NeuralNetworkGPU`) runs using gpu.js's architecture, which in node mode, _will fall back to CPU_, but in your browser will continue using WebGL2, or WebGL1, or fallback to CPU if neither of those are available.  It should be noted too that `NeuralNetworkGPU` will be _somwhat slower for XOR_.  It is like putting a teaspoon of water down a firehose.  It just isn't that much data, and a bunch of data is where the GPU thrives.

In the browser, when using `NeuralNetworkGPU`, it will post an error telling you that it did in-fact fall back to CPU if that was actually the case, so look for that as it is a key sign it fell back.

All in all, the classes should function nearly identical.  Its purpose was to push gpu.js forward (or any technology that used the GPU with javascript) to a point that an architecture could be supported, and that has been were I have been spending most of my time in brain.js as of late.

This past couple of weeks, I did notice some stability issues I wanted to address, which fostered v1.5.0, and possible a few more maintenance releases, but I'm spending most of my time on the GPU architecture getting it ready for brain.js v2.

Does this answer your questions and or help at all?

**Comment by cnkostas** [comment]
i understand a lot thanks i will test further the  NeuralNetworkGPU.So i have a suggestion  a function  that test accuracy on the fly in callback training function

**Comment by robertleeplummerjr** [comment]
They exist:
* GPU: https://github.com/BrainJS/brain.js/blob/f46edb90981d28f739d90e7052b692f4595b4c38/test/neural-network-gpu/index.js#L14
* CPU: https://github.com/BrainJS/brain.js/blob/f46edb90981d28f739d90e7052b692f4595b4c38/test/base/bitwise.js#L51

**Comment by cnkostas** [comment]
thanks

**Comment by robertleeplummerjr** [comment]
Thank you as well.  It is thorough issues like this that help make killer ideas happen!
