### ISSUE TITLE
toJSON not working on NeuralNetworkGPU in Chrome 70

### ISSUE THREAD

**Issue by koriwi** [BrainJS/brain.js#310]
## *What* is wrong?
Can't call toJSON() on NeuralNetworkGPU

## *Where* does it happen?
Windows10 and MacOs Mojave in Chrome 70 on GTX1060 or Intel iGPU

## *How* do we replicate the issue?
- Train a NNGPU in your browser.
- console.log(net.run(bla)) -> successfull output
- net.toJSON() -> `Cannot read property '0' of undefined`
It happens here:
https://github.com/BrainJS/brain.js/blob/78f369f4a624ded30e9b828950ad828c6fb83953/src/neural-network.js#L923

I think it tries to access index 0 of the [1] layer. But as you can see there is nothing to access.

```
JSON.stringify(this.weights) =>
"[null,{"texture":{},"size":[736,368],"dimensions":[736,368,1],"output":[736,368],"webGl":{},"kernel":null,"type":"NumberTexture"},{"texture":{},"size":[368,230],"dimensions":[368,230,1],"output":[368,230],"webGl":{},"kernel":null,"type":"NumberTexture"}]"
```

## *How* important is this (1-5)?

5 because i can't save my training data at all :( 
## Expected behavior (i.e. solution)

Output me the json so i can save the training

## Other Comments
I'm very new to NN

**Comment by robertleeplummerjr** [comment]
I'll fix this later today.  Ty for finding.

**Comment by koriwi** [comment]
No Problem :)
Thanks for your always fast response!
Brain.js rocks. And biggest partly because of you!
