### ISSUE TITLE
Join two neural networks

### ISSUE THREAD

**Issue by fgigg** [BrainJS/brain.js#314]
Hey guys. Im having an issue. I've gone through all the documentation and issues and I haven't found a way to join two neural networks together. Please can you help

**Comment by robertleeplummerjr** [comment]
In what way would you join them?

**Comment by fgigg** [comment]
Thanks for the speedy response. Im doing the training in segments and saving it to json files. When I load a file and l load another to a different net, I would like to be able to join them with all the training intact. Is this at all possible?

**Comment by fgigg** [comment]
The reason why im asking is so that many people can train a network in segments and then just join them together to create a single network. Thus completing a project faster.

**Comment by robertleeplummerjr** [comment]
If you train in segments, you will be fitting to just that dataset.  I believe you will likely always get very weird results in real world scenarios, especially if we use more than one layer.  Consider:

* Does some of my data repeat?  Will my training sets be guaranteed not to?
* If I have 3 layers, each with three neurons, and one instantiates and trains with a heavy activation on the first neuron, where in another scenario, they train to activate on the last neuron, what is the result if I "join" them?  Do I add them, subtract them, sum and divide?
* What are the affects on the neurons in the layers after this layer I've just "joined"?

I think what you'll find is that probabilistic math deals heavy in approximations that "hope" for tiny changes, and when large ones are introduced it has a catastrophic effect on the capabilities of the net. In other words it may be possible, but I've not ever seen or read about it, though I welcome it if you can find it.

Now, having said that, and understanding better your goals, what I believe you want is to use CrossValidation: https://github.com/BrainJS/brain.js/blob/master/README.md#cross-validation or simply train the net on a segment of your data, save it (export json), import it later (again via json) and repeat.
