### ISSUE TITLE
NN not working after loading from json

### ISSUE THREAD

**Issue by Alexqw101** [BrainJS/brain.js#315]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?

I train network and do `net.run(element)` and it return good number (for example 0.57).
I save network to JSON `let json=net.toJSON()` and load it `net.fromJSON(json)` and make `net.run(element)` and it return 1.00 in output with same NN json data.
## *Where* does it happen?

When I trying save and load NN.
Windows 10 node version 11.3.0
## *How* do we replicate the issue?

- try load and save from examples (I tried it and it's works)
## *How* important is this (1-5)?

4
## Expected behavior (i.e. solution)

Save and load NN, and  `net.run(element)` with succesful output.

## Other Comments
My listing code for run, save, load
```
          // NN initialized: let net = new brain.NeuralNetwork();

            //run with training NN
            let output = net.run([0.7, 0.1, 0.1, 0.2]);
            console.log(parseFloat(output).toFixed(2)); //return 0.57

            //save and load NN
            const jsonFileContent = JSON.stringify(net.toJSON());
            const json_from_save = JSON.parse(jsonFileContent);

            const net_from_save = new brain.NeuralNetwork();
            net_from_save.fromJSON(json_from_save);
            let output_from_save = net_from_save.run([0.7, 0.1, 0.1, 0.2]);
            console.log(parseFloat(output_from_save).toFixed(2)); //return 1.00
```

**Comment by Alexqw101** [comment]
After loading from json NN activation set to "sigmoid", but in json activation is "leaky-relu"
![image](https://user-images.githubusercontent.com/36042493/49803834-022e2100-fd62-11e8-8242-0e2c7f81098b.png)

**Comment by robertleeplummerjr** [comment]
I have a fix for this, and will post it probably tomorrow sometime.  Internet it a bit spotty at the moment.
