### ISSUE TITLE
More Documentation about GPU setup

### ISSUE THREAD

**Issue by LooOOooM** [BrainJS/brain.js#318]
## *What* is wrong?
Cannot get gpu-fallback to fly, even I did install "npm install" and installed cuda running on Gforce GT 730 

## *Where* does it happen?
 Win 10 (nodejs 10)

## *How* do we replicate the issue?
fresh install nodejs 10; latest cuda, frash clone brain.js, npm install  

## *How* important is this (1-5)?
 3 

## Expected behavior (i.e. solution)
 A more detailed dokumentation is needed on what excactly is needed and needs to be installed to get this running 

## Other Comments
I would be very thankful if you could help me to get this running.

**Comment by robertleeplummerjr** [comment]
I found the issue and will have a fix in before the day is through: https://github.com/BrainJS/brain.js/pull/322

**Comment by robertleeplummerjr** [comment]
https://github.com/BrainJS/brain.js/pull/322 ended up resolving this, which was released here: https://www.npmjs.com/package/brain.js/v/1.6.1

Tested in node via just now (been busy with work and work ;) ):
```js
const brain = require('./index');

const xorTrainingData = [
  { input: [0, 1], output: [1] },
  { input: [0, 0], output: [0] },
  { input: [1, 1], output: [0] },
  { input: [1, 0], output: [1] }];

const net = new brain.NeuralNetworkGPU();

const status = net.train(xorTrainingData, { iterations: 5000, errorThresh: 0.01 });

console.log(status);

console.log(net.run([0,1]));
console.log(net.run([0,0]));
console.log(net.run([1,1]));
console.log(net.run([1,0]));
```

Which outputs:
```
$ node test.js
Warning: gpu not supported, falling back to cpu support
{ error: 0.009854999254457653, iterations: 4200 }
Float32Array [ 0.9068859815597534 ]
Float32Array [ 0.0763167291879654 ]
Float32Array [ 0.12777996063232422 ]
Float32Array [ 0.9099745154380798 ]
```

As we'd expect.  I'm going to go ahead and close, but please keep me up to date if there are any updates here, good or bad.

ty!

P.S. To clarify, this is CPU fallback mode, but this _will not_ be an issue much longer.  We WILL have node GPU support soon: https://github.com/gpujs/gpu.js/issues/52#issuecomment-450354302
