### ISSUE TITLE
Steam-example write(null) stream error node v6.9.2

### ISSUE THREAD

**Issue by Kalevera** [BrainJS/brain.js#32]
I recently cloned the repository and went to run the stream example and got an error that the stream write could not receive a null value. I suspect it's because streams have changed in that last few node iterations. 

Any suggestions on a fix? I seems that taking out the write(null) from stream-example fixes the error but then it doesn't fire the statistics of the stream iterations or provide a toJSON output. 

Will work on more details when on computer.

**Comment by robertleeplummerjr** [comment]
I've honestly never even used streams.  But pr's are gladly accepted.  Post your findings here, and I'll be sure to help.

**Comment by pinqy520** [comment]
`stream.write()` is ok @Kalevera

**Comment by robertleeplummerjr** [comment]
Seems to be fine. Closing.
