### ISSUE TITLE
Output is NaN when analysing strings

### ISSUE THREAD

**Issue by robertt** [BrainJS/brain.js#320]
## *What* is wrong?
My output for the ran model is NaN, but the training error seems to be okay.

## *Where* does it happen?
In a NeuralNetwork when trying to run a net in node.js on my desktop (windows)

## *How* do we replicate the issue?
I am using typescript, but the code is here: https://gist.github.com/Haxified/a5bb1aab2bd6c8a2328efe09ee280f60

This is the output: https://gist.github.com/Haxified/f17dea47d395e0a70066ce0d6fd80a91

## *How* important is this (1-5)?
3

## Expected behaviour (i.e. solution)
The output shouldn't be NaN.

**Comment by robertleeplummerjr** [comment]
The encode function isn't adding zero's for sufficient length.  So "hey", is normalized to an array with a length of 3.  Here is a working version: https://jsfiddle.net/robertleeplummerjr/s74gahoL/16/

**Comment by robertt** [comment]
No but thats what the fixLengths() function does

**Comment by robertleeplummerjr** [comment]
It was not being applied to when the `.run()` method was called.

**Comment by robertt** [comment]
It does though, because it ran the serialize function when it did .run() 

```export const serialize = data => fixLengths(encodeData(data))```

**Comment by robertleeplummerjr** [comment]
The entire `analyse` function you have defined as:

```typescript
export const analyse = async (data) => {
    return net.run(serializer.encode(data));
}
```

Note `serializer.encode(data)`, which is defined as: 

```typescript
export const encode = (d: string) => {
    const newArr: number[] = [];
    d.split('').map(c => {
      newArr.push((c.charCodeAt(0) / 255))
    })
    return newArr
}
```

Here you define a new array, `newArr`, split `d` by every character, then `push` those value's keycode divided by readable character index (255) directly to `newArr`, HOWEVER, you then return `newArr`.  THIS IS IMPORTANT.  Going back to your `analyse` function:

```typescript
export const analyse = async (data) => {
    return net.run(serializer.encode(data));
}
```

You are returning the encoded value _directly into the `net.run()` method, never ensuring its values are the correct length_.  **This is precisely why your code is failing.**

The code I introduced does check this length, and push additional 0's to the array, thus providing the correct array size.

I think what may be advantageous is checking the input size before running the net, this error would have been identified early on.  What do you think?
