### ISSUE TITLE
Bug: Combination of serializing / simplified output data does not work 

### ISSUE THREAD

**Issue by mbflex** [BrainJS/brain.js#327]
I am using brain.js for digit-recognition (see: https://www.kaggle.com/c/digit-recognizer)

I am using brain.js like this:

```
new brain.NeuralNetwork(()
net.train([
             {input:[0,0,0,0,1,0 ..], output: {"9:1}},          // digit 9
             {input:[0,0,0,0,0,0,1 ..], output: {"6":1}},       // digit 6
             ...
```

Similar to your example:

```
net.train([{input: { r: 0.03, g: 0.7 }, output: { black: 1 }},
           {input: { r: 0.16, b: 0.2 }, output: { white: 1 }},
           {input: { r: 0.5, g: 0.5, b: 1.0 }, output: { white: 1 }}]);
```

I found this works fine - except in the case of a combination with serializing / loading in the state of a trained network with JSON:

```
    const json = net.toJSON();
    net.fromJSON(json);

```
If serializing is needed, the output part for the train data records must not be declared as above shown in the let's says simplified version '{"9":1}' or "{white: 1}. Instead of this, the output part must be _completey_ declared, e.g.

`output:  {"0":0, "1":0, "2":0, "3":0, "4":0, "5":0,"6":0, "7":0, "8":0, "9":1};`

Otherwise, you get unpredictable results after reloading the serialized model, like all "9" are calculated as "4" and all "2" are calculated as "3" etc.
`

**Comment by mbflex** [comment]
Code for testing -
Uncomment the two marked lines, and you will get opposite results:

```
'use strict';

const brain = require('brain.js');

const traindata = [
        {input: [.34,.12], output:{"1":1}},  //1 stands for "greater"
        {input: [.12,.34], output:{"0":1}},  //0 stands for "less"
        ];

for (let i=1; i<1000; i++)
{
    let a = Math.random();
    let b = Math.random();
    let input = [a,b];
    let output = a>b ? {"1":1} : {"0":1};
    traindata.push({input:input, output:output})
}


const net = new brain.NeuralNetwork();
net.train(traindata,{iterations:10, logPeriod:1, log:true});

// --> uncomment the next two lines - you will get opposite results
// const json = net.toJSON();
// net.fromJSON(json);

console.log(net.run([.12,.34]));  // less -> should be "0"
console.log(net.run([.34,.12]));  // greater -> should be "1"
```

**Comment by robertleeplummerjr** [comment]
The issue is somewhat to do with duck typing and and the key "0".  The net expects that if you use objects, use keys other than "0", but if you use arrays, obviously you'd have "0" as a key.  You are using objects with key "0", and the net is falling into an unhandled state (limbo?).

The easy answer is: just use keys, like "zero", "one", "two", etc.: Working example: https://jsfiddle.net/robertleeplummerjr/18xz4qfe/29/

If this isn't acceptable, we (me) will need to simply handle the state.
