### ISSUE TITLE
Better errors for function parameters

### ISSUE THREAD

**Issue by rwest202** [BrainJS/brain.js#328]
## *What* is wrong?
Utility functions should notify you when you make some basic mistakes, like forgetting to pass in a required parameter.

## *Where* does it happen?
`likely` is one of the functions. It may be happening in more.

## *How* do we replicate the issue?
brain.likely(input)
This will give you an error like so,
```
var output = net.run(input);
                 ^
TypeError: Cannot read property 'run' of undefined
```
However, it should give you an error like, `Required parameter 'net' is undefined'
## *How* important is this (1-5)?
3. All considered it's not too difficult to look at the stack trace. But it's important for usability in a library.

## Expected behavior (i.e. solution)
Errors that look like this, `Required parameter 'net' is undefined'

## Other Comments

**Comment by robertleeplummerjr** [comment]
I really think this is a good suggestion.  If you don't mind, I'd like to reopen.

**Comment by mbflex** [comment]
I am afraid that the TypeError message comes from the underlaying Java Script framework and can't be changed by the developers of the brain.js library, obviously.

Please note also, that the variable `net`  in `net.run(input)` is not a "function parameter" but the object which provides the method.

**Comment by rwest202** [comment]
Yes, but you can catch the error before it happens. For example in `src/likely.js` you could add an if statement like so.

```javascript
/**
 *
 * @param {*} input
 * @param {brain.NeuralNetwork} net
 * @returns {*}
 */
export default function likely(input, net) {
  if (!net) {
    throw new TypeError(`Required parameter 'net' is of type ${typeof net}. Must be of type 'brain.NeuralNetwork'`)
  }
  let output = net.run(input);

  // rest of code
}
```

**Comment by mubaidr** [comment]
implemented in: https://github.com/BrainJS/brain.js/pull/540
