### ISSUE TITLE
LSTM with many numeric inputs

### ISSUE THREAD

**Issue by spiffytech** [BrainJS/brain.js#331]
![A GIF or MEME to give some spice of the internet](https://i.imgflip.com/2q1vj0.jpg)

## *What* is wrong?
Training LSTM crashes with `RangeError: Invalid typed array length: 2191129290`

## *Where* does it happen?
Training an LSTM network with a large number of numeric inputs.
```
const net = new brain.recurrent.LSTM();
net.train(trainingData, {log: true, logPeriod: 10, errorThresh: 0.015})
```

## *How* do we replicate the issue?
I'm trying to make a stock predictor that takes the values of many stocks from an index over time and predicts the value of a single stock from that index. 

```
trainingData = [
    {
        ...250 entries,
        "input": [
            ...186 entries,
            0.9870007020215843,
            0.9389686422327372,
            0.8840746576172583,
            0.8452726439590653,
            0.864106081390032,
            0.8433385108923875,
            0.840011664099297,
            0.5924212287115362,
            0.720080101378307,
            0.8713809384347494,
            0.9760400973461584
        ],
        "output": [
            0.8577972609652063
        ]
    }]
```

## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)
I'd expect the LSTM network to successfully train on this data. Intuitively, I'd expect 197 input neurons and 1 output neuron trained on 250 pieces of data, which doesn't sound unreasonable.

## Other Comments
I liked the Scrimba course, very inspiring.

I saw the LSTM "caution" on the project README, but it wasn't clear to me whether the caution was about number of values, or number of inputs. I'd also appreciate if LSTM is wrong for this, advice on what the right architecture is.

**Comment by spiffytech** [comment]
It looks like I'm using the LSTM incorrectly. I was under the impression the trainer would sequence my timeseries training set, but instead it looks like training data pieces are trained independently, with each input array being an independent sequence of events.

In that case, is there a way to use an LSTM while supplying additional input neurons representing additional data? E.g., for stocks, a sequence of prices plus a moving average.

**Comment by robertleeplummerjr** [comment]
You are simply using the wrong neural network.   Use `brain.recurrent.LSTMTimeStep`.

https://github.com/BrainJS/brain.js/blob/master/src/recurrent/lstm-time-step.js
