### ISSUE TITLE
Failure to resume training

### ISSUE THREAD

**Issue by Prentillion** [BrainJS/brain.js#333]
## *What* is wrong?
Neural Network doesn't seem to lose old training progress when training is continued with more data

## *Where* does it happen?
Training a neural network then continuing to train it later.
Same result produced when loaded from JSON, new training significantly overrides old training

```javascript
net.train([
...
]);

net.train([
...
])
```

## *How* do we replicate the issue?
Example with an XOR gate
```javascript
const net = new brain.NeuralNetwork();

net.train([
    {input: [0, 0], output: [0]},
    {input: [0, 1], output: [1]},
    {input: [1, 0], output: [1]}
]);

net.train({input: [1, 1], output: [0]});

console.log(net.run([1, 0]));
```

Current result:
```
[ 0.03540751338005066 ]
```
Expected result:
```
Expect to be near to 1
```
## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)

Continuing to train the neural net should not completely override what training has been done already.

It can be fixed by training with the whole data set on the second time but this obviously takes a lot longer to compute
```javascript
const net = new brain.NeuralNetwork();

net.train([
    {input: [0, 0], output: [0]},
    {input: [0, 1], output: [1]},
    {input: [1, 0], output: [1]}
]);

net.train([
    {input: [0, 0], output: [0]},
    {input: [0, 1], output: [1]},
    {input: [1, 0], output: [1]},
    {input: [1, 1], output: [0]}
]);

console.log(net.run([1, 0]));
```

Output:
```
[ 0.9319882392883301 ]
```

## Other Comments
Log error also starts significantly high on second round of training

Inital training of XOR:
```
iterations: 10, training error: 0.2304970590057908
iterations: 20, training error: 0.22787304424770718
iterations: 30, training error: 0.22734293034487388
...
iterations: 1010, training error: 0.005272660033630898
iterations: 1020, training error: 0.0051577028514087075
iterations: 1030, training error: 0.0050470909409198
```

Continued training
```
iterations: 10, training error: 0.9645061463300095
iterations: 20, training error: 0.9593827602339076
iterations: 30, training error: 0.9525140087905726
...
iterations: 150, training error: 0.007853373593889934
iterations: 160, training error: 0.006529269205814148
iterations: 170, training error: 0.00557478249546689
```

**Comment by geokontop** [comment]
I think that you should't expect that kind of partial training behaviour.

You are asking the network to train itself and that is what it does. It readjusts taking into account only the new training set. The previous training serves as initialization, which is quite insignificant. Its influence faints with each iteration if the validity of the old dataset statements is not reaffirmed. As a result, the newly adjusted network does not comply to the previous training set. 

This is the expected behaviour. Training is overall, it overides previous trainings.  You have to provide, each time, the hole training set. :-)

**Comment by robertleeplummerjr** [comment]
Well started @geokontop, this is in fact by design.  Training data must be explicit.

**Comment by Jangwa** [comment]
If I have a huge data set, are you expecting developer to declare an array of one million numbers in JS script? Why it cant be Read input one by one and train accordingly?

**Comment by mubaidr** [comment]
@Jangwa You can load data from file and then pass it to network or if the data/file is huge, you should use stream training: https://github.com/BrainJS/brain.js#streams This is issue is demanding completely different than you interpreted.
