### ISSUE TITLE
Neural network

### ISSUE THREAD

**Issue by vorticalbox** [BrainJS/brain.js#334]
say I was using the colour example and there was a colour that would look fine with both black and white how would I have the training data?

```
{input: { r: 0.03, g: 0.7, b: 0.5 }, output: { black: 0.5, white:0.5 }}
```

or 

```
{input: { r: 0.03, g: 0.7, b: 0.5 }, output: { black: 1, white: 1 }}
```

**Comment by mubaidr** [comment]
Second one should be the chosen one. Because both colours are Correct 100% (1) in this case not 50% (0.5). 👍

**Comment by mubaidr** [comment]
@robertleeplummerjr confirm please

**Comment by robertleeplummerjr** [comment]
TL;DR: use `{ black: 1, white: 1 }` for this case

TS;DR:
If you are classifying using binary, the second one would be correct, but you may not get out what you think, or want.  I've ran into situations where if given `{ output: { black: 1, white: 1 } }` in training, I get: `{ black: .5, white: .5 }` when running.  I'm not honestly sure why training led to it, and I cannot reproduce here: https://jsfiddle.net/robertleeplummerjr/aw3u6jkm/
