### ISSUE TITLE
Binary input, output is NaN

### ISSUE THREAD

**Issue by arya-s** [BrainJS/brain.js#343]
## *What* is wrong?
Output is NaN. I'm not quite sure why, it seems to be similar to #320 and #292 but my training data input and my run input are of same length.

## *Where* does it happen?
In a NeuralNetwork when trying to run on equal length input data representing binary numbers.

## *How* do we replicate the issue?
The code is here:
http://jsfiddle.net/juxbmhd5/

## *How* important is this (1-5)?
2

## Expected behavior (i.e. solution)
Output states should not be NaN.

**Comment by mubaidr** [comment]
Your input format was wrong, updated here: http://jsfiddle.net/juxbmhd5/1/
