### ISSUE TITLE
Let's learn a game

### ISSUE THREAD

**Issue by vorticalbox** [BrainJS/brain.js#345]
## *What* is wrong?

I was actually thinking today about using brain.js to learn how to play tic-tac-toe

The input would be simple with an array like

```
[
    ['###'], 
    ['#O#'], 
    ['##X]
]
```

# is empty
O player
X the network.

I'm not sure this is possible currently just really looking for tips on how to start.

## *How* important is this (1-5)?
I plan on using brain.js networks at work* so 4 to me probably 1 to everyone else.

*not to play games.

**Comment by robertleeplummerjr** [comment]
I think this can be well solved here: https://github.com/BrainJS/brain.js/issues/317
