### ISSUE TITLE
Question about next steps

### ISSUE THREAD

**Issue by ktodyruik** [BrainJS/brain.js#346]
Hi. This is just a question. I hope this is an appropriate place to ask it. 

I'm new to neural networks and ML. Brain.js, the docs, and "A fun and practical introduction to Brain.js" has been a great hands-on way to get started and learn about this subject area. I have two questions I was wondering if I could get some help with.

1. What are some suggested next steps to continue learning about neural networks and ML?

2. In addition to JS I'd also like to do some programming in Python. I've been a bit overwhelmed with the libraries and ecosystem related to neural networks and ML in Python. Is there a library similar to Brain.js that would be a recommended path to doing similar programming in Python?

Thanks in advance for the help.

**Comment by mubaidr** [comment]
@robertleeplummerjr has written some awesome tutorials (beginner friendly) to understand neural networks and brain.js: https://brain.js.org#/tutorial
