### ISSUE TITLE
LSTMTimeStep fromJSON not working

### ISSUE THREAD

**Issue by 1080772AntonioDidier** [BrainJS/brain.js#347]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
fromjson not working with LSTMTimeStep

## *Where* does it happen?
net.fromJSON returns undefined

## *How* do we replicate the issue?
var net = new brain.recurrent.LSTMTimeStep({
        inputSize: 2,
        hiddenLayers: [10],
        outputSize: 2
    });

    net.train([
        [1, 3],
        [2, 2],
        [3, 1]
    ]);

    var output = net.run([[1, 3], [2, 2]]);
    console.log(output)
    require('fs').writeFileSync("E:/lstm.json",JSON.stringify(net.toJSON()), function (err) {
        if (err) {
            console.log(err);
            process.exit();
            return console.log(err);
        }
    });

    net = new brain.recurrent.LSTMTimeStep({
        inputSize: 2,
        hiddenLayers: [10],
        outputSize: 2
    });
    var data=require('fs').readFileSync("E:/lstm.json", 'utf8');
    console.log(net.fromJSON(JSON.parse(data)));
    net=net.fromJSON(JSON.parse(data));
    output = net.run([[1, 3], [2, 2]]);
    console.log(output);
    process.exit();

## *How* important is this (1-5)?
4

## Expected behavior (i.e. solution)
load the network from the json and run.

## Other Comments

**Comment by mubaidr** [comment]
Please show error log.
