### ISSUE TITLE
NeuralNetwork.toJSON() fails for newly created neural networks

### ISSUE THREAD

**Issue by DavyKoravand** [BrainJS/brain.js#348]
## *What* is wrong?
Newly constructed NeuralNetwork objects will give an error when stringifying it as JSON. This happens when using .toJSON or JSON.stringify().

## *Where* does it happen?
In the NeuralNetwork. My OS seems irrelevant here, but I'm running Windows 10.

## *How* do we replicate the issue?
`JSON.stringify(new brain.NeuralNetwork());`

## *How* important is this (1-5)?
2

## Expected behavior (i.e. solution)
I'd think it should create a JSON object with metadata about the neural network, even if it is untrained.

## Relevant part of stack trace

As seen below, it's trying to index [0] of null.

> node_modules\brain.js\dist\neural-network.js:1084
>           nodes = (0, _range2.default)(0, this.sizes[layer]);
> 
> TypeError: Cannot read property '0' of null

**Comment by mubaidr** [comment]
Seems like to caught the bug? would like to create a pull request? 🥇 

Otherwise @robertleeplummerjr will handle this

**Comment by binary-person** [comment]
Well, what's the point of turning a blank neural network into JSON for future use? I don't see any reason for it. I suggest that you handle this error for empty Neural Networks than try to figure out what is wrong.
If you train it some data, the error goes away.

**Comment by scheng123** [comment]
Close #348

**Comment by DavyKoravand** [comment]
> Well, what's the point of turning a blank neural network into JSON for future use? I don't see any reason for it. I suggest that you handle this error for empty Neural Networks than try to figure out what is wrong.
> If you train it some data, the error goes away.

It's still an unintended bug in the code.

**Comment by binary-person** [comment]
I agree. I'll suggest returning a blank JSON than to create a blank template. It seems more simple that way

**Comment by Boot-Error** [comment]
Is this issue fixed?
https://github.com/BrainJS/brain.js/blob/017c00895dfeb4981fc22cf69ba1870db8754c89/src/neural-network.js#L84

**Comment by binary-person** [comment]
Mind if anyone does a pull?

**Comment by Boot-Error** [comment]
> Mind if anyone does a pull?

This issue should be closed right?
Interestingly, this was implemented 2 years ago https://github.com/BrainJS/brain.js/commit/4d94d16c390fd5a20f122bcc9e514c9fb5d36bfb

I think I failed to reproduce the error

**Comment by binary-person** [comment]
No, since it is not fixed yet.

**Comment by Boot-Error** [comment]
> No, since it is not fixed yet.

What could be a possible fix to this?

>  I'll suggest returning a blank JSON than to create a blank template. It seems more simple that way

A blank json?

**Comment by robertleeplummerjr** [comment]
You need to call `net.initialize()`, if you'd like to export an untrained neural network.  Example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-348
