### ISSUE TITLE
Publish the latest release on npm

### ISSUE THREAD

**Issue by IonicaBizau** [BrainJS/brain.js#35]
Before doing that I'd recommend:

 - having clear installation steps
 - improving documentation
 - have clear examples

**Comment by IonicaBizau** [comment]
@robertleeplummerjr Once you say the master branch is ready, I can double check the docs and examples. :grin:

**Comment by robertleeplummerjr** [comment]
Can you give it a once over at this point?

**Comment by IonicaBizau** [comment]
@robertleeplummerjr Should we publish maybe a beta? Is `1.0.0` ready yet?

**Comment by robertleeplummerjr** [comment]
@IonicaBizau, love it!  Flip the switch when ready!

**Comment by robertleeplummerjr** [comment]
fantastic!
