### ISSUE TITLE
Hidden Layers missing when passed in under train().

### ISSUE THREAD

**Issue by hellsan631** [BrainJS/brain.js#351]
![where did they go?](https://media.giphy.com/media/Yiw4aLjpxldhC/giphy.gif)

## *What* is wrong?
```hiddenLayers``` isn't respected when passed into train(data, config).

## *Where* does it happen?
Most recent version of Brain.js

## *How* do we replicate the issue?

```javascript
// provide optional config object (or undefined). Defaults shown.
const config = {
    hiddenLayers: [6, 3],
    errorThresh: 0.05,
    activation: 'relu',
    iterations: 1000,
};

const input = [
  {input: [0, 0], output: [0]},
  {input: [0, 1], output: [1]},
  {input: [1, 0], output: [1]},
  {input: [1, 1], output: [0]}
];

const net = new brain.NeuralNetwork();

net.train(input, config);

console.log(net.toJSON())

// logs below, may not be 1:1
const json = "brain": {
      "sizes": [
		2,
        2, // should show hidden layers here.
      ],
      "layers": [
		//...
	  ],
	  "outputLookup": true, 
      "inputLookup": true,
      "activation": "relu", // respects other options
      "trainOpts": {
        "iterations": 1000, // respects other options
        "errorThresh": 0.05, // respects other options
        "log": true,
        "logPeriod": 100,
        "learningRate": 0.35,
        "momentum": 0.1,
        "callbackPeriod": 1,
        "beta1": 0.9,
        "beta2": 0.999,
        "epsilon": 1e-8
      }
    }
  };


```

## *How* important is this (1-5)?
4

## Expected behavior (i.e. solution)
Warning should be thrown that the hidden layers were passed in as a config during train()
and not set upon creation of the neural network.

OR

If there are no size for the current NET, the first instance of train() with a config & hidden variables should set this.

**Comment by robertleeplummerjr** [comment]
I'm not sure how to take this.  You can define hidden layers as such:

```js

const net = brain.NeuralNetwork({ inputSize: 1, hiddenLayers: [4,5,6], outputSize: 1 });
```

Too many ways to define something cause it to be difficult to manage and maintain.
