### ISSUE TITLE
brain.recurrent.LSTMTimeStep does not have trainAsync method

### ISSUE THREAD

**Issue by Garbolino** [BrainJS/brain.js#356]
## *What* is wrong?
brain.recurrent.LSTMTimeStep() does not have trainAsync method.

## *Where* does it happen?
running in meteor 1.8.0.2

## *How* do we replicate the issue?
const net = new brain.recurrent.LSTMTimeStep();
net
    .trainAsync(data, options)
    .then(res => {
      // do something with my trained network
    })
    .catch(handleError);

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
to have a way to async train for LSTMTimeStep

## Other Comments

**Comment by robertleeplummerjr** [comment]
I would rather build this into `brain.Recurrent`, than take on the amount of work it would take to get it into `brain.recurrent.RNN` and it's family.  I started several times, and each time ran into problems where I'm just duplicating code everywhere.
