### ISSUE TITLE
NaN with 2D arrays and 3D arrays with brain.NeuralNetwork

### ISSUE THREAD

**Issue by binary-person** [BrainJS/brain.js#357]
![Angry face blank meme](https://i.ibb.co/Km27hN7/why-isn-t-this-working.jpg)

## *What* is wrong?

Training with 2D, 3D data similar to {input: [[0, 1], [0, 1]], output: [1]} gives NaN error
## *Where* does it happen?

When training data
## *How* do we replicate the issue?

```
var net = new brain.NeuralNetwork();
net.train([
     {input: [[0, 1, 0], [1, 0, 1]], output: [1]},
     {input: [[1, 0, 1], [0, 1, 0]], output: [0]}
]); // error returns NaN
net.run([[0, 1, 0], [1, 0, 1]]); // Expected output should be around 1

```
## *How* important is this (1-5)?

2 as this is just an idea, but by solving this issue, would open up to more possibilities with the brain.js library, such as image recognition, which I am scratching my head on how train the image.
## Expected behavior (i.e. solution)

The error isn't NaN, and the NeuralNetwork should have made sense of the data.

## Other Comments
The point of this issue is more like trying to train a 2D image for image recognition. You see, an image has x's and y's, so in order to input an image in, a 2D array input is a must.

**Comment by robertleeplummerjr** [comment]
Can you simply flatten the data?  Brain.js v2 has multidimensional support.

**Comment by mubaidr** [comment]
2d array is not necessary. Just flatten and then it should work as expected. I have tested training with at-least 128x128 and it works this way. Just get the buffer (Pixel array) for the image.

**Comment by binary-person** [comment]
Are you sure about flattening the array pixels of an image? I'm trying to input two images with different dimensions. I can't wrap my head around the fact that someone would able to interpret a flattened image. I would think that I need to tell the neural network when one row ends and another starts.

**Comment by mubaidr** [comment]
Yup, pretty sure. This is very similar to what I have achieved in my side-project; https://github.com/mubaidr/image-parsing

Here is example of converting image to array (I am also converting image to black n white): https://github.com/mubaidr/image-parsing/blob/master/src/utilities/index.js#L194

**Comment by binary-person** [comment]
Training seems to be working, but not the image recognition part. #359

**Comment by robertleeplummerjr** [comment]
We'll continue the image recognition on that issue.  Ty for your help on this guys!
