### ISSUE TITLE
Weird output with image classification

### ISSUE THREAD

**Issue by binary-person** [BrainJS/brain.js#359]
I am currently working on image classification. So I have some images of bland and cats. (Bland is just a picture with a single color background on it.) I first reduce the pixels of the images to 240x240. Then, feed in the data to the NeuralNetwork. When I try to test it with a picture of another cat it has never seen before, it outputs bland with 92% possibility. I can't fathom why the NeuralNetwork can't differentiate an image with a single colored background compared to a picture of a cat. I don't understand what am I doing wrong here.
All the code is on codepen:

https://codepen.io/scheng123/pen/VgdMKv

**Comment by robertleeplummerjr** [comment]
How much training data are you giving the neural network?

**Comment by binary-person** [comment]
Section of code on codepen:
```
cats[0] = await getImagePixels(toCors('https://i.ibb.co/xmTD67n/0.jpg'));
cats[1] = await getImagePixels(toCors('https://i.ibb.co/xM4BLjB/1.jpg'));
cats[2] = await getImagePixels(toCors('https://i.ibb.co/Jrj9d5s/2.jpg'));
cats[3] = await getImagePixels(toCors('https://i.ibb.co/g9yd7T9/3.jpg'));
cats[4] = await getImagePixels(toCors('https://i.ibb.co/3pbKcLB/4.jpg'));
bland[0] = await getImagePixels(toCors('https://i.ibb.co/89VDZNF/0.png'));
bland[1] = await getImagePixels(toCors('https://i.ibb.co/Byddx3G/1.png'));
bland[2] = await getImagePixels(toCors('https://i.ibb.co/qrbySgm/2.jpg'));
bland[3] = await getImagePixels(toCors('https://i.ibb.co/0sYjpHv/3.jpg'));
imageTestBland = await getImagePixels(toCors('https://i.ibb.co/Nm9L1Fk/graytestbland.jpg'));
imageTestCats = await getImagePixels(toCors('https://i.ibb.co/fpn2RcY/catstest-1.jpg'));
```
So there are 5 image and 4 bland images.
Link to codepen: https://codepen.io/scheng123/pen/VgdMKv

**Comment by mubaidr** [comment]
Hmm this looks like a job for Convolutional Neural Networks. 

If you convert bland to some b/w images it might work.

**Comment by binary-person** [comment]
Does brain.js have convolutional neural networks? I'll try training them using b/w images.

**Comment by robertleeplummerjr** [comment]
Convolutions are on the way, but not landed yet (look for convolution): https://github.com/BrainJS/brain.js/wiki/Roadmap#v2-status.  I agree, b/w, but also you could try it with [CrossValidation](https://github.com/BrainJS/brain.js#cross-validation).

**Comment by binary-person** [comment]
Hmm, I don't really know what CrossValidation does. Can you briefly explain what it is?
I cannot wait for v2 to roll in!

**Comment by binary-person** [comment]
The results from grayscale were equally as weird. I checked the data for the bland images and they were as expected, all the same values. The cat images however varies. Is there something with a NeuralNetwork not being able to detect an image with the same repeating color pixels with a dataset that has values that vary? I'm pretty sure I'm doing something wrong here.
RGB color encoder function:
```
function rgbEncode(r, g, b){ // Convert to grayscale
    return ((r+g+b)/3) / 255;
}
```

**Comment by robertleeplummerjr** [comment]
The first alarm for me is: `hiddenLayers: [3, 5],` on a 255 x 255 image, which are 65,025 pixels.  This is like asking the net to decipher an entire encyclopedia, with it only understanding the letter "c".  It would seem you need to give it more neurons.

A word of caution, however, is that it will get a little slow in your browser.  Trying something like a node process that can run in the background may be a bit more forgiving.
