### ISSUE TITLE
What if we move brain.js into a separate organization?

### ISSUE THREAD

**Issue by IonicaBizau** [BrainJS/brain.js#36]
As this projects grows (again), I guess it would make sense to have an organization for it.

Things like `brain-examples`, `brain-visualizations` could be stored there as well, in separate repos.

**Comment by robertleeplummerjr** [comment]
Love it!

**Comment by robertleeplummerjr** [comment]
Rather than organizations, why not just further repositories?  That way things stay neat and tidy under a single organization, with more repos.

**Comment by robertleeplummerjr** [comment]
Well then, started with https://github.com/harthur-org/rnn-viewer & https://github.com/harthur-org/brain.retro.js.  We'll just continue the trend.  Ty!
