### ISSUE TITLE
[discussion] I'm confused. Why is NeuralNetworkGPU slower?

### ISSUE THREAD

**Issue by ashah888** [BrainJS/brain.js#363]
Could someone help me understand why using NeuralNetworkGPU to train data in node is slower than using NeuralNetwork? When I run an example, using NeuralNetworkGPU is clearly slower than NeuralNetwork, at least on my computer.

I thought the point of using GPU is to make things faster? Why is using NeuralNetworkGPU making things slower?

**Comment by robertleeplummerjr** [comment]
Slower on what scale?  What are you training/running the net with?

**Comment by ashah888** [comment]
I trained about 20 sentences, one with GPU, one without.
Set iterations at 5000 and errorThresh at 0.0001.

NeuralNetworkGPU finished in about 7 seconds.
NeuralNetwork finished in about 2-3 seconds.

Could you please explain what happened there?

**Comment by robertleeplummerjr** [comment]
How big is a sentence?  Likely the size of the input to the neural network isn't large enough to justify the added cost of using the GPU.  It'd be like launching a rocket to go next door to your neighbors.

**Comment by ashah888** [comment]
So should I always use NeuralNetworkGPU over NeuralNetwork in all cases?

This is important decision to me because I'm currently super frustrated that my model isn't finishing the training on approx. 1 million sentences. It's been 2 days and it still hasn't finished.

I'm so frustrated at this training speed that I'm considering learning a new language like Python or GoLang or R to do my machine learning.

Given this much data, do you think I should do machine learning in another language? Or do you think NeuralNetworkGPU will give me the performance boost that I need?

**Comment by ashah888** [comment]
Another question. Assuming that the answer to above Q is "yes" (that I should use NeuralNetworkGPU in all cases and that using it is always faster) -- what about LSTM? Does LSTM use GPU? I noticed LSTM is extremely slow. Can it (or is it) be sped up by GPU? If not, when will it be?

**Comment by zhanghaiyan123** [comment]
Someone can tell me if brain. JS can support training data in the following format（input is the user's browsing behavior of each module on a page, output is the preference ranking of each module）. Look forward to reply. Thank you.

trainData={
    input: {
      block_A: {move:0.4,click:4,count:10},
      block_C: {move:0.6,click:7,count:8},
      block_M: {move:0.9,click:3,count:4},
      block_B: {move:0.4,click:7,count:16},
    },
    output: { block_C,block_B,block_A,block_M}
  },{
    input: {
      block_A: {move:0.14,click:14,count:20},
      block_C: {move:0.6,click:7,count:10},
      block_M: {move:0.8,click:15,count:17},
      block_B: {move:0.91,click:15,count:24},
    },
    output: { block_M,block_B,block_A,block_C}
  }

**Comment by 59337xyz** [comment]
Someone can tell me if brain. JS can support training data in the following format (input is the user's browsing behavior of each module on a page, output is the preference ranking of each module). Looking forward to reply, thank you.
{
    input: {
      block_A: {move:0.4,click:4,count:10},
      block_C: {move:0.6,click:7,count:8},
      block_M: {move:0.9,click:3,count:4},
      block_B: {move:0.4,click:7,count:16}
    },
    output: { block_C,block_B,block_A,block_M}
  },{
    input: {
      block_A: {move:0.14,click:14,count:20},
      block_C: {move:0.6,click:7,count:10},
      block_M: {move:0.8,click:15,count:17},
      block_B: {move:0.91,click:15,count:24}
    },
    output: { block_M,block_B,block_A,block_C}
  }

**Comment by evdem** [comment]
hi Robert,
4 hiddenLayers [100,100,100,100] DNN BrainJS draft demo (hand writing recognition) at https://www.ibiblio.org/e-notes/webgl/brain/hand4.html
On AMD A6-5200 APU I get
On CPU / Iterations=1262, Time=12.3 s.
On GPU / Iterations=1380, Time=31.6 s.
toString ? :)
Don't you like to add this (elaborated) demo?

**Comment by robertleeplummerjr** [comment]
Ok, I don't think it isn't supported in the version of google angle we are on.

The missing feature implementation from google angle: https://github.com/google/angle/blob/7c37ca1836402b654dbbf5f00007e09bdf2a7051/src/compiler/translator/tree_ops/EmulateGLFragColorBroadcast.cpp

Specifically: https://github.com/google/angle/blob/7c37ca1836402b654dbbf5f00007e09bdf2a7051/src/compiler/translator/tree_ops/EmulateGLFragColorBroadcast.cpp#L114

We could shim in something like this, but ultimately I'd like to keep our stuff as vanilla as possible.

Neither the feature or the unit test are in our version, fyi.

**Comment by robertleeplummerjr** [comment]
Sorry, wrong thread.

**Comment by robertleeplummerjr** [comment]
For GPU to be faster it is right around 512x512 with the added overhead of working on a GPU.  This is simply something we have to deal with at this time.
