### ISSUE TITLE
Why is there no CNN?

### ISSUE THREAD

**Issue by VEXLife** [BrainJS/brain.js#368]
![A GIF or MEME to give some spice of the internet](url)

## Other Comments

**Comment by robertleeplummerjr** [comment]
Working on it, but finishing up GPU node support first.  Help welcome and wanted!

**Comment by VEXLife** [comment]
Thank you. I've found that brain.js is easy to use. I hope brain.js will be better in the future, and I'm looking forward to the convolutional neural network in brain.js!
Besides, I'm willing to help.

**Comment by mubaidr** [comment]
https://github.com/BrainJS/brain.js/issues/352

**Comment by VEXLife** [comment]
@mubaidr Thanks.
