### ISSUE TITLE
Documentation of neural network configurations

### ISSUE THREAD

**Issue by WowItsDoge** [BrainJS/brain.js#369]
Is there an overview, how the config object for the constructors of the neural network are defined?

This would be interesting:

- Has brain.NeuralNetwork and brain.recurrent.RNN the same config attributes?
- What is the description of the inputSize attribute?

Thank you for the great work with this library, it is realy amazing!

**Comment by mubaidr** [comment]
Documentation update is planned. Hopefully with the version 2.0 release we will have documentation update too.

**Comment by mubaidr** [comment]
Just an update, this is still in progress. Also since we are working on typescript conversion (https://github.com/BrainJS/brain.js/issues/551), that means we will have typing support for all codes. 👍

**Comment by learningdesignlabs** [comment]
For now, can we at least list here, what the definition of the inputSize vs outputSize attributes are?

**Comment by robertleeplummerjr** [comment]
This is covered in the [readme](https://github.com/BrainJS/brain.js/blob/master/README.md).
