### ISSUE TITLE
[help wanted] How can I use brain.js to generate poetry?

### ISSUE THREAD

**Issue by blismatic** [BrainJS/brain.js#371]
![A GIF or MEME to give some spice of the internet](https://static1.squarespace.com/static/561e6ee0e4b02426d143b4f4/5a1f7dcac830253d32d3e963/5a6a29ebe4966b97c46c65e2/1516907069693/Poetry-gif.gif?format=500w)

## Can I use brain.js to generate poetry?

Hi, I'm a (somewhat) novice in javaScript, but for my high school final project, I wanted to try to make a program that could generate poetry. Is this possible to do with brain.js, and if so, what type of neural network would I need to look into to accomplish this? This is my first time using a js library, so all of this is a bit foreign to me, but I am very interested in how brain.js can be applied to something like language and poetry.

Any help is appreciated, thank you !

**Comment by WowItsDoge** [comment]
This question could not be answered generaly, I guess.
There are multiple options to try to generate poetry with neuronal networks.

Maybe this example could provide some usefull idea how to start:
https://github.com/BrainJS/brain.js/blob/master/examples/childrens-book.js

**Comment by blismatic** [comment]
@WowItsDoge 
> This question could not be answered generaly, I guess.
> There are multiple options to try to generate poetry with neuronal networks.
> 
> Maybe this example could provide some usefull idea how to start:
> https://github.com/BrainJS/brain.js/blob/master/examples/childrens-book.js

I've taken a look at that example, and it seems that the neural network only finds what line the given input is found in, and then repeats that line. This doesn't really seem like it "writing" a children's book to me, or am I misinterpreting how the neural net is working? Maybe with a larger amount of training data the outcome would be different?

**Comment by WowItsDoge** [comment]
Maybe you want to create something like this:
https://hackernoon.com/automated-text-generator-using-markov-chain-de999a41e047

But I am not shure if this library already supports Markov Chains.

**Comment by blismatic** [comment]
@WowItsDoge I suppose that Markov Chain example is more of what I want to accomplish. How does the brain.js example involving a children's book differ from the Markov Chain in terms of the output they give?

**Comment by CamK06** [comment]
> ![A GIF or MEME to give some spice of the internet](https://camo.githubusercontent.com/7db2cf7c0b8b3b5c2d324d73dc34e960549a757a/68747470733a2f2f737461746963312e73717561726573706163652e636f6d2f7374617469632f3536316536656530653462303234323664313433623466342f3561316637646361633833303235336433326433653936332f3561366132396562653439363662393763343663363565322f313531363930373036393639332f506f657472792d6769662e6769663f666f726d61743d35303077)
> 
> ## Can I use brain.js to generate poetry?
> Hi, I'm a (somewhat) novice in javaScript, but for my high school final project, I wanted to try to make a program that could generate poetry. Is this possible to do with brain.js, and if so, what type of neural network would I need to look into to accomplish this? This is my first time using a js library, so all of this is a bit foreign to me, but I am very interested in how brain.js can be applied to something like language and poetry.
> 
> Any help is appreciated, thank you !

Seems no one is willing to actually help you with just brain.js, [here's a script I made to generate text from input text.](https://pastebin.com/35mSQDtw) The trainingData constant can be replaced with a ``const trainingData = require('trainingData.json')`` if you want to put the data in a json string array (which looks like ``["text1", "text2", "text3]``)

Anyways, this script will replicate your data really well although you might want to increase the amount of iterations if you have a lot more data than in the example. Just to make viewing your training easier I made it so each iteration's train gets logged in console and in a log file (``TrainingLog.txt``) 

Anyways, hope this helps :)


Edit: If you're interested here's an example of something it might output with that example data ``Below, a Shistling wind``

I also forgot to mention you might want to modify the maxPredictionLength accordingly if you're getting results that are too long (or even too short, I don't know what kind of poetry you're feeding this thing)

**Comment by mubaidr** [comment]
Also this could be helpful: https://github.com/BrainJS/brain.js/issues/375
