### ISSUE TITLE
[Help wanted] qnamaker.ai possible with brain.js?

### ISSUE THREAD

**Issue by dayaki** [BrainJS/brain.js#372]
Hi everyone, just wondering brain.js can do something similiar to [qnamaker.ai](qnamaker.ai), if possible, can you help with a pseudo code on how to go about it?

**Comment by robertleeplummerjr** [comment]
Absolutely!  In fact, All you need are tons of leading questions and answers, and then just feed them into a LSTM network, like [this example from docs](https://github.com/BrainJS/brain.js#for-training-with-rnn-lstm-and-gru):

```js
const net = new brain.recurrent.LSTM();

net.train([
  { input: 'I feel great about the world!', output: 'happy' },
  { input: 'The world is a terrible place!', output: 'sad' },
]);

const output = net.run('I feel great about the world!');  // 'happy'
```

Let me know if that doesn't work for you.  I look forward to hearing about your finding!
