### ISSUE TITLE
Plz help how do i save my train json to file?

### ISSUE THREAD

**Issue by ArsalanMaqsood** [BrainJS/brain.js#376]
const lstm = new brain.recurrent.LSTM();
lstm.fromJSON(myjson);
const result = lstm.train(trainingData, {
iterations: 15000,
log: details => console.log(details),
errorThresh: 0.011
});

const updatedjson = lstm.toJSON();

//, { flag: 'a+' }
fs.writeFile("results.json", JSON.stringify(updatedjson), function (err) {
if (err) throw err;
console.log('The "data to write" was appended to file!');
});

result.json file needs to have train data for new training and old training

how can i do this?

**Comment by ArsalanMaqsood** [comment]
please le me know how do i save train model / json to external file to use for later use?

**Comment by mubaidr** [comment]
`fs.appendFile` will try to append data to existing file. You probably want to use `fs.writeFile`

**Comment by ArsalanMaqsood** [comment]
> `fs.appendFile` will try to append data to existing file. You probably want to use `fs.writeFile`

but when i writeFile, it replace entire dataset

**Comment by mubaidr** [comment]
Yes, this is correct and this is what you want (unless you explain it otherwise, please correct me If I am wrong). 
- Train a network
- Export as json
- Later create new network
- load state from json
- train with more data
- export to json

The final json will be the only required file as it contains updated network from both the tranings. 

i.e. You don't need to merge the output json.

**Comment by ArsalanMaqsood** [comment]
can you give me your contact number i will call you?
________________________________

**Comment by ArsalanMaqsood** [comment]
when i have json
how to train with more data ??
and combine them to single updated trained json file?


________________________________

**Comment by ArsalanMaqsood** [comment]
yes right, can you provide example code for lstm??
________________________________

**Comment by mubaidr** [comment]
Please check this example here with the same requirements as yours: https://jsfiddle.net/robertleeplummerjr/jcvu0tx6/2/

**Comment by haouarihk** [comment]
you just :
1- read the train.json file
2- train the new data 
3 - add the new data to the read data from the train.json file
4- export all data to train.json using `fs.writeFile`
