### ISSUE TITLE
Using Neural Networks to Predict Match Results

### ISSUE THREAD

**Issue by easyitis** [BrainJS/brain.js#378]
## *What* is wrong?

Nothing at all - brain.js is wonderful

## *Where* does it happen?

In a new site called cricresult.com - where brain.js is used to predict cricket results based on past data.

## *How* do we replicate the issue?

Just load cricresult.com or look (and contribute) to the code here https://github.com/easyitis/cricresult

## *How* important is this (1-5)?

5 for die-hard IPL fans, 1 for the rest

## Expected behavior (i.e. solution)

It works fine - but appreciate some help in tuning the neural networks - current error rates are 2-5%

## Other Comments

**Comment by robertleeplummerjr** [comment]
This seems like something that a Time step Network could solve much more efficiently, at first glance.

**Comment by easyitis** [comment]
We're just getting started with NN. Can you point to reference material which can help choose the best Network? Such as a decision tree.

**Comment by CamK06** [comment]
> We're just getting started with NN. Can you point to reference material which can help choose the best Network? Such as a decision tree.

You can probably get something useful out of this tutorial on brain.js (correct timestamp is in the URL so it will automatically go there) https://youtu.be/RVMHhtTqUxc?t=695 you'll just have to find a way to convert that into something like a json so it can be updated with new match results, the more training data, the better the predictions

**Comment by robertleeplummerjr** [comment]
@Derpy-Canadian That tutorial may give good results, but when there is data that happens _over time_ I tend to lean towards that likely it may have some sort of historical trend to it, which I think is why time step would be a better choice.  The time step ([example](https://github.com/BrainJS/brain.js/blob/ab09bfc74a0d29d4731dcbdebfa17aeba7f7b1ef/examples/predict-numbers.js#L12)) tracks changes over time, and not just classifying them as the FeedForward neural network would do.

I think in either case you'll get something useful, but keep in mind we cannot foretell the future.... However, we can be really good at guessing it.

Going to go ahead and close this as I believe we have sufficiently answered the question.
