### ISSUE TITLE
LSTM with GPU

### ISSUE THREAD

**Issue by CamK06** [BrainJS/brain.js#379]
![A GIF or MEME to give some spice of the internet](https://media1.tenor.com/images/7300e7c54737854f384dd28ba024a18d/tenor.gif)

## How can I use LSTM with my GPU?

I've been training some LSTM networks but it has been very slow, is there a way I could GPU accelerate it or make full use of my CPU to train to make it run significantly faster?

**Comment by mubaidr** [comment]
This is in progress and there are already open discussions regarding this: 
https://github.com/BrainJS/brain.js/issues/363
https://github.com/BrainJS/brain.js/issues/364

**Comment by CamK06** [comment]
> This is in progress and there are already open discussions regarding this:
> #363
> #364

Thank you for your quick response! Is there any way to make it faster using my CPU as I mentioned or is it at a fixed speed?

**Comment by mubaidr** [comment]
Unfortunately no. :( Just wait for GPU version of brain, which should be very soon.
