### ISSUE TITLE
Generate Strings Based On Training

### ISSUE THREAD

**Issue by CamK06** [BrainJS/brain.js#380]
![A GIF or MEME to give some spice of the internet](https://cdn.discordapp.com/attachments/408267495288602626/561660005166612490/D2313TgUgAAGe92.jpeg)

## Generate Strings Based On Training
Basically what I am wondering is if it is possible to take a list of strings as an input and over time train to eventually form sentences\phrases and whatnot, I have already heard of markov chains but is there a way to do it with brain.js?

**Comment by mubaidr** [comment]
Please check the LSTM examples here: https://github.com/BrainJS/brain.js#for-training-with-rnn-lstm-and-gru

**Comment by CamK06** [comment]
Maybe I am missing something there but I can’t find an example of what I want.

Basically what I am asking is if it’s possible to feed a brain.js a bunch of let’s just say inspirational quotes or lyrics and have it generate quotes and lyrics?

**Comment by mubaidr** [comment]
@robertleeplummerjr please

**Comment by robertleeplummerjr** [comment]
I the feature you would like could be similar to: https://github.com/BrainJS/brain.js/blob/master/examples/childrens-book.js

But you'd like _new_ outputs, that is the difference.

There is an undocumented feature here: https://github.com/BrainJS/brain.js/blob/master/src/recurrent/rnn.js#L295

Where you can adjust `isSampleI = true`, and then toy around with different values in `temperature` (default is 1) that will start to give you new values as output that you could try.

An example taken from the above: https://jsfiddle.net/robertleeplummerjr/z3tvpaLy/3/

I believe this should close this issue for the time being, let me know if it does not.

**Comment by robertleeplummerjr** [comment]
Example of first run:
```
run 1: Jane saw Doug and Spot el moment for alf Jeat nt for all.
run 2: Doug saw Doug.
run 3: Spot sas lookinlD.
run 4: It was aod mone.
```

Nonsense, but fine tuning the parameters could give you something quite a bit better.

**Comment by CamK06** [comment]
Hm, thats interesting, I'll look into it. This is not too important as I have not tried that yet so this might not be necessary but just in case I can't get it working, this is pretty much what I want, is to do something like this https://www.youtube.com/watch?v=a0EyfdQ0QTQ and just let it run and show a new set of text on each iteration, so if what you sent me cannot do that please link me to something that might be able to

Edit: sorry if this is explained terribly, I am absolutely terrible at explaining things in text. Somehow actually speaking in person makes it easier, not sure why but I know a lot of people are like that lol hope the youtube video helps better describe it

Edit 2: Yeah, unless I am missing something very important, this does not do what I would like

**Comment by CamK06** [comment]
Forget everything I said above ^ I seem to have found out what to do to get it to work as I want, currently I am using `log: console.log(lstm.run('', true, 1.5))` to log its attempt on every run similar to in the video and other similar videos, are there any downsides to this and is there a better way? Also before I get into some lengthy training, does this attempt to recreate the input text or does it use it to generate text similar to it, again like in the video.

**Comment by robertleeplummerjr** [comment]
What kind of results are you seeing?  Glad it is working for you!

**Comment by CamK06** [comment]
> What kind of results are you seeing? Glad it is working for you!

As of now it appears when I put just one string as training data it will slowly try to replicate that and learn a little bit about how to reproduce it but it will always start "un-learning" and falling back in progress as far as the recreation goes, this is probably a result of short training time

As far as multiple strings, it is very slow but that's because of no GPU acceleration or whatever it is (like I mentioned in my previous issue about GPUs #379) and it will always do one string at a time and in the end it will reproduce them with no issue but it wont sort of merge them, once again like I want as shown in that youtube video and many others. If you'd like I can send you my code so you can see if something is wrong with it. Basically as an example I have just taken a bunch of recent Elon Musk tweets and ran the program from there with no results that please me. I've put smaller amounts of small strings (2-4) and by the end of training it ends up just outputting the completed strings one at a time.

So let's say I have strings 'Yes, the program worked correctly', 'No, the program did not work correctly', it will output this

Iteration #XX: Yes, the program worked correctly
Iteration #XX: No, the program did not work correctly

and never a mix of the two or something derived from it like I am wanting.


Unrelated to this issue but just a question: When GPU support is added, will AMD GPUs be natively supported? That's been the main thing keeping me away from Tensorflow since I have an RX 580






Edit: just going to add the code in case your response is sent while I am asleep

```
const brain = require("brain.js");

const trainingData = [
    "Yes, the program worked correctly",
    "No, the program did not work correctly"
]
  var trainNumber = 0;
  const lstm = new brain.recurrent.LSTM();
  const result = lstm.train(trainingData, {
    iterations: 15000,
    log: details => runLSTM(),
  });


  function runLSTM()
  {
    trainNumber++;
    console.clear();
    console.log('Iteration #${trainNumber}: ${lstm.run('', true, 1.5)}'); // Adjusted quotes on this so it would work in a git code block
  }
```

Edit 2: Nevermind, it randomly decided to mix it and gave me this 

https://prnt.sc/n6o4qo

**Comment by robertleeplummerjr** [comment]
>When GPU support is added, will AMD GPUs be natively supported?

You can try and check support for your card by installing in a test program via npm `npm i gpu.js` and running something like this:

```js
const { GPU } = require('gpu.js');
const gpu = new GPU({ mode: 'gpu' });
const kernel = gpu.createKernel(function() {
  return 1;
});
const result = kernel();
console.log(result[0]);
```

If you run that, and get an output of "1", with no warnings on the console, then you should be clear for GPU on your card.

**Comment by CamK06** [comment]
> ```js
> const { GPU } = require('gpu.js');
> const gpu = new GPU({ mode: 'gpu' });
> const kernel = gpu.createKernel(function() {
>   return 1;
> });
> const result = kernel();
> console.log(result[0]);
> ```

I just get ``Error: kernel.output not an array`` on both of my PCs (one has a Radeon RX 580, the other has a Radeon 5000 series (not sure the exact model, I just know its a terrible card, but eh its a work computer so its fine)
