### ISSUE TITLE
Suggestion for a training model

### ISSUE THREAD

**Issue by arthurkafer** [BrainJS/brain.js#381]
## The project
Contextualizing the project, I have a positioning system in a straight production line, divided by five independent stations that do different things in the prodution. Right now I'm using Bluetooth Low Energy beacons and BLE gateways, using their Received Signal Strength Intensity (RSSI) to estimate their positions. 
The important thing that I have to show is in what station of the line a product is. The system is constantly analyzing the RSSIs of my 3 gateways, and to set the station of a product I'm doing some validations like this, according to the RSSI: 

```
if (gateway_1< -37.5 && gateway_1>= -62) // the important one for the prodution
{ 
    if ((gateway_2< -52 && gateway_2 > -70) && (gateway_3< -69 && gateway_3> -76) && (gateway_1 > gateway_2)) // other validations for the station
        station= 1; // it could be 1-5
}
if (gateway_2< -55 && gateway_2 > -70)
{
    if ((gateway_1< -55 && gateway_1> -68) && (gateway_3<= -67 && gateway_3> -75)(gateway_2 - gateway_1 > -3)) 
        station= 2;
}
```

Some intervals are large due to the noisy ambient I'm working with, and with that, the intensities could fit in two stations. For example, if we have -57dBm in gateway 1, -56dBm in gateway 2 and -71dBm in gateway 3, station could be 1 or could be 2. In this cases I would like to test Neural Networks and see what is the possibility of the product be positioned in one station or another.
There are some other validations for the production line, like jumping important stations in the line, returning the product to a previous station, occupying a station that is already occupied, and some others.

## *What* is wrong?
I'm trying to use Neural Networks in my positioning system, but I don't know the best way to train my net. Right now I'm testing with the same intervals that I have in the main project. I setted the closest intensity as -30dBm (then 1 = -30dBm, 0.5 = -60dBm, 0.333 = -90dBm and so on) and my training is like this: 

```
[
{input: [0.8000, 0.5769, 0.4348], output: {station1: 1, station2: 0, station3: 0, station4: 0, station5: 0}},
{input: [0.4839, 0.4285, 0.3947], output: {station1: 1, station2: 0, station3: 0, station4: 0, station5: 0}},
{input: [0.5454, 0.5454, 0.4477], output: {station1: 0, station2: 1, station3: 0, station4: 0, station5: 0}},
{input: [0.4412, 0.4285, 0.4000], output: {station1: 0, station2: 1, station3: 0, station4: 0, station5: 0}}
]
```

## *Where* does it happen?
In a Neural Network, running in node.js.

## *How* do we replicate the issue?
To replicate it, I made an example code, just to see if the possibilities would fit in the station positioning.

```
const brain = global.get('brainjs');
const config = {
    hiddenLayers: [10],     // array of ints for the sizes of the hidden layers in the network
};

var net = new brain.NeuralNetwork(config);  
// input: [Gateway_1, Gateway_2, Gateway_3]
// 1 = -30 // 0.5 = -60
net.train(
    [
        {input: [0.8000, 0.5769, 0.4348], output: {station1: 1, station2: 0, station3: 0, station4: 0, station5: 0}},
        {input: [0.4839, 0.4285, 0.3947], output: {station1: 1, station2: 0, station3: 0, station4: 0, station5: 0}},
        
        {input: [0.5454, 0.5454, 0.4477], output: {station1: 0, station2: 1, station3: 0, station4: 0, station5: 0}},
        {input: [0.4412, 0.4285, 0.4000], output: {station1: 0, station2: 1, station3: 0, station4: 0, station5: 0}},
        
        {input: [0.4838, 0.6250, 0.4838], output: {station1: 0, station2: 0, station3: 1, station4: 0, station5: 0}},
        {input: [0.4167, 0.4918, 0.4109], output: {station1: 0, station2: 0, station3: 1, station4: 0, station5: 0}},
        
        {input: [0.4347, 0.5660, 0.5172], output: {station1: 0, station2: 0, station3: 0, station4: 1, station5: 0}},
        {input: [0.3703, 0.4545, 0.4285], output: {station1: 0, station2: 0, station3: 0, station4: 1, station5: 0}},
        
        {input: [0.4545, 0.5172, 0.6667], output: {station1: 0, station2: 0, station3: 0, station4: 0, station5: 1}},
        {input: [0.3703, 0.4285, 0.4687], output: {station1: 0, station2: 0, station3: 0, station4: 0, station5: 1}}
    ]
);
var output = net.run([0.416873449, 0.5995717344, 0.46979865]);
node.warn(output);
```

To calculate the number between 0-1, I did `number = -30/intensity`.

The values to input could be values inside those intervals, but to get a real situation, these following inputs could be in two stations by my program and by the NeuralNetwork

`[0.416873449, 0.5995717344, 0.46979865]` -> should be in Station 4
`[0.462809917, 0.5526315789, 0.45454545]` -> should be in Station 3
`[0.421475163, 0.4729729729, 0.53401144]` -> should be in Station 5

The results with this training are pretty accurate, but I would like to know if there is a better way to train it, like instant values showing the station, like this:

```
net.train(
    [
        {input: [0.416873449, 0.5995717344, 0.46979865], output: {station1: 0, station2: 0, station3: 0, station4: 1, station5: 0}},
        {input: [0.462809917, 0.5526315789, 0.45454545], output: {station1: 0, station2: 0, station3: 1, station4: 0, station5: 0}},
        {input: [0.421475163, 0.4729729729, 0.53401144], output: {station1: 0, station2: 0, station3: 0, station4: 0, station5: 1}}
    ]
);
```

In this training, I would put correct intensities for each station, and then test it with other values that are being analyzed by the program itself. I'm running a test that instantly verifies the station of a product according to their intensities, and the results are good, but not how I need it. I expect the problem being the lack of training data, and with more data for training, better the results will be.

## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)

I think the result should be the possibility of those 3 intensities fit in one station, but not in two, or three of them. Besides that, more training, or actually, *better training* should return much better results. 

## Other Comments

Appreciate your attention for my issue, brain.js is a very interesting library to work with, and I expect to learn more about it and use it for lots of projects. 

Thanks a lot.

**Comment by mubaidr** [comment]
You are doing perfectly fine. Two things I noticed:
- You do not need to specify all the output options for each training input, just mention the successful option. i.e. 
```js
[
{input: [0.8000, 0.5769, 0.4348], output: {station1: 1}},
{input: [0.5454, 0.5454, 0.4477], output: {station2: 1}},
]
```
- Output returned by the network contains the correctness probability of each output according to the input data. For example, If the network thinks that the input lies in both station 1 and 2 it will return something like this: 
```js
{station1: 0.9, station2: 0.8, station3: 0, station4: 0, station5: 0}
```

You have to pick the top one from the returned list. In above mentioned sample values, `station1` is the top value.

**Comment by arthurkafer** [comment]
Thanks, I'll change that and develop the NN better.
