### ISSUE TITLE
toSVG not working for loaded models

### ISSUE THREAD

**Issue by KokoDoko** [BrainJS/brain.js#384]
## toSVG not working when loading a model

When I use a config object to create a neural net, I can use toSVG to draw the network. This code works:

```
const config = {
        inputSize: 3,
        inputRange: 3,
        hiddenLayers: [4],
        outputSize: 3
};
const svgoptions ={
        fontSize : "12px",
        width : 600,
        height : 400,
        radius : 6,
        line : {width:0.5, color:"rgba(0,0,0,1)" },
        inputs : {color:"rgba(0,127,0,0.6)", label:[]},
        hidden : {color:"rgba(255,127,80,0.6)"},
        outputs : {color:"rgba(100,149,237,0.6)" }
}
const net = new brain.NeuralNetwork(config)
div.innerHTML = brain.utilities.toSVG(net, svgoptions)
```

Now, when I load a model from a JSON file, I get these errors:

```
const net = new brain.NeuralNetwork(config)
net.fromJSON(res)
div.innerHTML = brain.utilities.toSVG(net, svgoptions)
```

> Unhandled Promise Rejection: TypeError: Array.from requires an array-like object - not null or undefined

How can I load a model from JSON and draw it as an SVG?

**Comment by herenickname** [comment]
Up!

**Comment by robertleeplummerjr** [comment]
This is resolved in v2 alpha 6.  Complete with unit tests: https://github.com/BrainJS/brain.js/blob/92a2ada834722e230caf524936fe24a8c3c9d614/__tests__/utilities/to-svg/to-svg.js#L10
