### ISSUE TITLE
Error NaN, is this a bug?

### ISSUE THREAD

**Issue by korner-brazers** [BrainJS/brain.js#385]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/xUOwGf96MMgihPWUCI/giphy.gif)

## *What* is wrong?
When I start training, the error NaN comes back. This happens in 50% of cases, and I do not understand why, I have an example where I convert the image into the same array, and everything works there.

In the example I managed to get the data at which an error occurs, maybe I am not transmitting the data correctly? Or is this a bug?

## *Where* does it happen?
I'm testing in Google Chrome browser

## *How* do we replicate the issue?
https://jsfiddle.net/4385yhxs/

## *How* important is this (1-5)?
2

## Expected behavior (i.e. solution)
Output states should not be NaN.

**Comment by korner-brazers** [comment]
After several hours of attempts to start, i found out one feature.
Data must be the same length. Is this such a feature or a bug?)

**Comment by mubaidr** [comment]
Its the requirement: This makes sure that network is able to map all the inputs to output.
