### ISSUE TITLE
LSTM Not Able To Produce Strings Over 98 Characters Long

### ISSUE THREAD

**Issue by CamK06** [BrainJS/brain.js#386]
![A GIF or MEME to give some spice of the internet](https://www.igobyplane.com/wp-content/uploads/2016/04/73e.jpg)

## *What* is wrong?

LSTMs can only generate 98 character strings
## *Where* does it happen?

In LSTM Neural Networks
## *How* do we replicate the issue?

By running [this](https://pastebin.com/sY8fjA6e "this") code with any training data in data.json, for example: [ "Michael", "Bill", "John" ] 
## *How* important is this (1-5)?

3 3/4
## Expected behavior (i.e. solution)

I expected the LSTM to be able to generate a string with pretty much the maximum characters a computer can handle (if there even is a real limit with a string itself and not hardware)

**Comment by bdistin** [comment]
I assume this has to do with this option: https://github.com/BrainJS/brain.js#rnn-lstm-or-gru-output-too-short-or-too-long Have you played with this value at all?

**Comment by robertleeplummerjr** [comment]
This is precisely the answer.  Closing as I believe it was sufficiently answered.  Ty @Derpy-Canadian and @bdistin!

**Comment by CamK06** [comment]
Oh, didn't know that was an option. Thanks!
