### ISSUE TITLE
How to improve the result?

### ISSUE THREAD

**Issue by korner-brazers** [BrainJS/brain.js#387]
Hello everyone, I want to improve the result of finding, but so far the successful result is at the level of 60-70%

Earlier, I asked how to transfer data correctly https://stackoverflow.com/questions/55781990/how-to-take-the-data

The result was better when I replaced the activation function with **tanh**.

Then did more examples and reduced the parameters (**errorThresh,learningRate**)

The training time increased and the number of iterations increased, but at least one hour, at least 3 hours of training, did not increase the quality of the finding.

Maybe I do not twist those parameters? and will it make sense if you run the training on the server? say for 24 hours of training?

**Comment by mubaidr** [comment]
Please explain you scenario and we will try to help.
