### ISSUE TITLE
Example is not actually reinforcement learning

### ISSUE THREAD

**Issue by samfultonjr** [BrainJS/brain.js#391]
I just stumbled upon the basic examples and I watched the one for reinforcement learning. But I noticed he simply just adds the unseen data in halfway through and it doesn't seem to be actual reinforcement learning. I could be totally wrong in my understanding of reinforcement learning, but from what I have done and seen this does not seem like reinforcement learning. 

https://scrimba.com/p/pVZJQfg/cpkKyHd

**Comment by robertleeplummerjr** [comment]
@samfultonschool It is a good point, I think I was using the "reinforcement" somewhat liberally.  Ty for bringing it to my attention.
