### ISSUE TITLE
Conversational Bot Help

### ISSUE THREAD

**Issue by Ashish117** [BrainJS/brain.js#392]
Is it possible to store all input speech and train it to respond back with a sensible response?

**Comment by CamK06** [comment]
This is technically possible with code like [this](https://github.com/BrainJS/brain.js/blob/master/examples/childrens-book.js) you would just need to train it on a LOT of questions, statements, etc

**Comment by Ashish117** [comment]
With input and output method? it will take a long time to train when the
data is huge.

>

**Comment by CamK06** [comment]
yeah that's another issue, GPU acceleration for LSTMs is apparently being worked on but I was told that it would come out soon probably a month and a half ago iirc

**Comment by mubaidr** [comment]
GPU acceleration landed in Alpha version: https://github.com/BrainJS/brain.js/issues/364#issuecomment-519687253
