### ISSUE TITLE
Line processing on NeuralNetwork()

### ISSUE THREAD

**Issue by Jebati** [BrainJS/brain.js#395]
Hello. There is a code that does not work:

```
const brain = require('brain.js');

function encode(arg) {
  return arg.split('').map(x => (x.charCodeAt(0) / 256));
}

function processTrainingData(data) {
  return data.map(d => {
      return {
          input: encode(d.input),
          output: d.output
      }
  })
}

const trainingData = [
  { input: 'We have the answers for you!', output: [1] },
  { input: 'Whoo, decisions in our group', output: [1] },
  { input: 'To me in HP, for answers', output: [1] },
  { input: 'Yeah, I would say that, but I wont', output: [0] },
  { input: 'Lol, yes you digrad', output: [0] },
  { input: 'I think everything is ok', output: [0] },
];

const net = new brain.NeuralNetwork();
net.train(processTrainingData(trainingData), {
  log: true
}); // iterations: 0-20000, training error: NaN

console.log(net.run(encode('1'))); // Float32Array [ NaN ]
console.log(net.run(encode('2')));// Float32Array [ NaN ]
```

Please tell me what the problem is. 
When input is 1 character, everything works
LSTM I do not want to use it, because it gives a piece of string sometimes ...

**Comment by mubaidr** [comment]
I am not sure, But try defining data as:
```js
const trainingData = [
  { input: 'We have the answers for you!', output: {yes: 1}},
  { input: 'Whoo, decisions in our group', output: {yes: 1} },
  { input: 'To me in HP, for answers', output: {yes: 1} },
  { input: 'Yeah, I would say that, but I wont', output: {no: 1} },
  { input: 'Lol, yes you digrad', output: {no: 1} },
  { input: 'I think everything is ok', output: {no: 1} },
];
```

And let us know about the training error.

**Comment by Jebati** [comment]
> I am not sure, But try defining data as:
> 
> ```js
> const trainingData = [
>   { input: 'We have the answers for you!', output: {yes: 1}},
>   { input: 'Whoo, decisions in our group', output: {yes: 1} },
>   { input: 'To me in HP, for answers', output: {yes: 1} },
>   { input: 'Yeah, I would say that, but I wont', output: {no: 1} },
>   { input: 'Lol, yes you digrad', output: {no: 1} },
>   { input: 'I think everything is ok', output: {no: 1} },
> ];
> ```
> 
> And let us know about the training error.

Did not help.
[screenshot ](https://pp.userapi.com/c849324/v849324194/18fdf7/MpTdOTU8KqI.jpg)

**Comment by mubaidr** [comment]
nevermind, its in correct format. 

Also this network will require all inputs to be of same length.

Regards
Muhammad Ubaid Raza

________________________________

**Comment by mubaidr** [comment]
Please keep in mind these key points when working with LSTM: https://github.com/BrainJS/brain.js#for-training-with-rnn-lstm-and-gru
