### ISSUE TITLE
Technical question. 

### ISSUE THREAD

**Issue by pedrocarvajal** [BrainJS/brain.js#396]
Hi, I have a problem that I want to solve. but I do not know if this library will help me! I have a serious data (training) that are similar to this:

http://prntscr.com/nqbyhf

I have more elements with that structure. and each one has an "associated performance" .. if it is a good set of data then the "performance" is positive .. if it is not a good data set then the performance is negative.

The idea is that by passing a new set of data the code will result in a set of data that "can be" a set with good performance or not.

For what I say I used this example http://prntscr.com/nqbz7j passing an "array" with all the data set that I have http://prntscr.com/nqbzhy and when I want to do the ".run ()" I pass this data to you. http://prntscr.com/nqbzoi

Now what I do not understand is because always ... the results are VERY SIMILAR OR EQUAL. I think they should be different .. because there may be a data set with bad configuration and a set of data with good configuration.

Look at the results: http://prntscr.com/nqc0cv

**Comment by mubaidr** [comment]
Yes it is: https://medium.com/@tech_fort/classifying-text-with-neural-networks-and-mimir-in-javascript-94c9de20c0ac
