### ISSUE TITLE
[Feature Request] - Typescript type definition file - ITrainStreamOptions should extend INeuralNetworkTrainingOptions

### ISSUE THREAD

**Issue by michaelonubogu** [BrainJS/brain.js#397]
![Alt Text](https://media.giphy.com/media/BpadRS0HKJ7Irh150L/giphy.gif)

## *What* is wrong?
The ITrainStreamOptions interface does not allow one to add neural net-specific training options to the neural net of the train stream - even though internally, the Train stream inherits default options from the INeuralNetworkTrainingOptions interface. 

When not using strict typing, adding INeuralNetworkTrainingOption properties i.e. errorThreshold, iterations - to the TrainStream object does in fact affect the neural net's training characteristics used in the Train stream.

## *Where* does it happen?
When using TrainStream

## *How* do we replicate the issue?
Create a TrainStream and view the options of the trainStream at runtime

## *How* important is this (1-5)?
2

## Expected behavior (i.e. solution)
ITrainStreamOptions should probably extend INeuralNetworkTrainingOptions.

## Other Comments
I wanted to ask first to see if this is necessary. If it is, I could do a PR. Up to the team I guess.

**Comment by mubaidr** [comment]
Sound good to me, can you create a PR please?

**Comment by mubaidr** [comment]
Should be fixed after we complete emigration to typescript (very soon). 

https://github.com/BrainJS/brain.js/issues/551
