### ISSUE TITLE
Change or re-publish npm package

### ISSUE THREAD

**Issue by nemo** [BrainJS/brain.js#4]
Likely need to work with npm team to figure this out – but ideally, `npm i brain` installs this package vs. the old one.

**Comment by IonicaBizau** [comment]
After talking to the npm support, the result is the old package will remain in the current state. The current owner wants to keep her module in that state.

After discussing how to name this package, we decided to name it `brain.js`. So, I `npm publish`ed it under the `brain.js` name on npm. :rocket: 

@harthur-org/devs  If any of you wants to have superpowers on npm, feel free to :bell: me and I will `npm owner add` you. :grin:
