### ISSUE TITLE
Training error : NaN with numeric values

### ISSUE THREAD

**Issue by lucydjo** [BrainJS/brain.js#406]
Hi.

I try to learn to detect the gender of names.
The TrainingData looks like this

    { input: [ 2, 26, 11, 8, 13, 4 ], output: { h: 0, f: 1 } },
    { input: [ 2, 4, 17, 8, 18, 4 ], output: { h: 0, f: 1 } },
    { input: [ 2, 4, 18, 0, 8, 17, 4 ], output: { h: 1, f: 0 } },
    { input: [ 2, 26, 18, 0, 17 ], output: { h: 1, f: 0 } },
    { input: [ 2, 7, 0, 13, 19, 0, 11 ], output: { h: 0, f: 1 } },
    { input: [ 2, 7, 0, 13, 19, 26 ], output: { h: 0, f: 1 } },
    { input: [ 2, 7, 0, 17, 11, 8, 13, 4 ], output: { h: 0, f: 1 } },
    { input: [ 2, 7, 0, 17, 11, 14, 19 ], output: { h: 1, f: 0 } },

My code : https://gist.github.com/lucaspojo/1a4c7c848f18074ccd195eb8d7828b6a

Do you know what I'm doing wrong?

Thx!

FIXED : https://github.com/BrainJS/brain.js/issues/320

**Comment by robertleeplummerjr** [comment]
Ty for the links!
