### ISSUE TITLE
Why my AI stupid? ( First name classification by gender )

### ISSUE THREAD

**Issue by lucydjo** [BrainJS/brain.js#407]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/IYIlvuWc21U4g/giphy.gif)

## *What* is wrong?
After giving all the dataset and developing the code according to my project. I have found that the AI is supide...

## *Where* does it happen?

**### Try no. 1**
> { femme: 0.8133203387260437, homme: 0.1866796463727951 }
> { femme: 0.02010645903646946, homme: 0.9798933267593384 }

**### Try no. 2**

> { femme: 0.9773803353309631, homme: 0.022619640454649925 }
> { femme: 0.7254955172538757, homme: 0.27450400590896606 }

**### Try no. 3**

> { femme: 0.9934973120689392, homme: 0.0065026720985770226 }
> { femme: 0.05790224298834801, homme: 0.9420979022979736 }

**### Try no. 4**

> { femme: 0.812171995639801, homme: 0.18782798945903778 }
> { femme: 0.000006735194801876787, homme: 0.9999932646751404 }

## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)
I don't think the ia is in need of more raw data. Because she comes to this misled about names she knows.

I think we should apply a gender factor to it.

-1 = Girl
0 = Neutral
1 = Boy 

If a male first name is always detected as a female first name, increase the value by 0.1.
With a trustworthy human intervention to teach him!

**What do you think of that?**

Code + CSV : https://gist.github.com/lucaspojo/3f516a0af3e33cd83bd056f92894a406

## Other Comments
If no one helps me to make it better, I had to eutanate it. I don't want her to live in this cruel world with this IQ...

**Comment by robertleeplummerjr** [comment]
I think you will quickly run into a situation where you have a massive neural network that is trying to work out something quite simple.  I think a better approach would be either a natural language or recurrent neural network.  The recurrent net will likely be the easiest.

Try this approach: https://github.com/BrainJS/brain.js#for-training-with-rnn-lstm-and-gru and you'll end up with something like:
```js
const net = new brain.recurrent.LSTM();

net.train([
  { input: 'Maryam', output: '2' },
  { input: 'Milo', output: '1' },
]);

const output = net.run('Mariam');  // '2'
```

**Comment by robertleeplummerjr** [comment]
Closing for the time being as I believe we have a proposed solution.  Feel free to re-open if it does not work.

**Comment by lucydjo** [comment]
Thx @robertleeplummerjr for your reply.

The LSTM was my first attempt. Unfortunately the results were not good or even totally random.

If I used a NeuralNetwork it was in order to do the opposite.

Generated a Female or Male name. But the predictions must already be correct.

I have to find a solution to improve the result
