### ISSUE TITLE
[suggestion] network idea (not concerned but maybe have it when everything rn is done. it's whatever)

### ISSUE THREAD

**Issue by lmaoyeet** [BrainJS/brain.js#408]
## *What* is wrong?
nothing

## *Where* does it happen?
everywhere

## *How* do we replicate the issue?
doing anything

## *How* important is this (1-5)?
1 (i wouldn't mind if it came in v3 even)

## Expected behavior (i.e. solution)
we need convolutional networks or even layers

## Other Comments
im really loving this library, absolutely stellar work

**Comment by robertleeplummerjr** [comment]
Convolution layers are being added in v2, they are mostly tested, and will be completed tested soon.  This sounds like a hint for the perfect plug for the roadmap, currently focused on the solidification of v2: https://github.com/BrainJS/brain.js/wiki/Roadmap
