### ISSUE TITLE
[PLZ HELP] My result output gets exact and always 1 insteat of 0.xxxx

### ISSUE THREAD

**Issue by LooOOooM** [BrainJS/brain.js#409]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
My input data is normalized to values between 0 and 1. I got about 500000 training data lines
The expect output is a decition of 3 ways: red, green, blue.
However my result is allways from the first iteration onwarth:
`Red : 1 , green : 2.915958816629427e-7 , blue : 3.679960524673176e-13`
please take atention to the excat 1 (Red)
Then the answer is always "Red" with excact 1, why this happens? and what can I do about it?
PS: there are even some thousend more "green" samples then Red samples. the shape of the complet data is about like this:
Red: green: blue
4:4:2

## *Where* does it happen?
Serve, CentosM nodejs 8.x

## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)
at least Random answers in each output late and no excact 1 or 0 but like 0.87888897 or 0.9992773 or 0.00023531

I would be very happe if somebody could help me !

**Comment by mubaidr** [comment]
Please share some sample data and your code.

**Comment by LooOOooM** [comment]
After I shuffeled the traindata I reseive an expected behalver. II think there where so many "reds" in follow that this destriey the internal brain. even after a while a series of "green" could not fix it anymore as the weights internally where already shifted to stron to "red"

**Comment by LooOOooM** [comment]
THX

**Comment by robertleeplummerjr** [comment]
Ty guys for taking care of this!
