### ISSUE TITLE
[Question] Resume training of recurrent LSTM with expanded data set?

### ISSUE THREAD

**Issue by lipnyCzlowiek** [BrainJS/brain.js#410]
Hi all,

I love the library - just a quick question.
If I train recurrent LSTM, can I then create net from json, expand data set and continue training?

Thanks

**Comment by lipnyCzlowiek** [comment]
Nevermind - you can't do it with recurrent LSTM.

**Comment by robertleeplummerjr** [comment]
This should be working now, a LSTM should be able to transfer to and from JSON.  Can you expound on your use case, and what isn't working?

Can you expound on "expand data set and continue training"?
