### ISSUE TITLE
Try to choose a suitable ui component by values or options

### ISSUE THREAD

**Issue by GELight** [BrainJS/brain.js#414]
Hi,

I do not have many knowledge about neuronal networks but I like your library because it looks very simple to use for this thinks.

I work on a private open source project to render a UI based on a description by jsoin.
The base idea "currently" is to have a shema where you can describe one specific component with all his possible properties etc. 

Such a structure can be looks like this:
```
[
    {
        "type": "video",
        "options": {
            "titel": "Lustiges Video",
            "description": "Ein cooles lustiges Video mit einem Hasen.",
            "path": "https://www.w3schools.com/html/mov_bbb.mp4",
            "resolution": "320x240",
            "runtime": "10.26s",
            "size": "131.509.108",
            "author": "Mario Linz"
        }
    },
    {
        "type": "text",
        "options": {
            "text": "This is a short text."
        },
        "units: [
            {
                "type": "text",
                "options": {
                    "text": "This is an other test example as a child of an other component."
                }
            }
        ]
    },
    {
        "type": "link",
        "options": {
            "title": "Neuronal Network with Brain.js",
            "url": "https://github.com/BrainJS/brain.js"
        },
        "units: [
            {
                "type": "text",
                "options": {
                    "text": "This text is an example of a child component of the parent link component."
                }
            }
        ]
    }
]
```
In this example each components are defined specific by the "type" property.
The UI app use this property to use the related component to render all available options for this component. 

So far so good.

**Now I have a thought or question to improve that all:**
Suppose there is no specification of a component like obove. Do you think its possible to use Brain.js to finde out the right component type when there are only options available without a specific type? 

If yes .... how can be a good way?
Maybe can you give me a tipp with brain.js?

Best regards,
Mario

**Comment by mubaidr** [comment]
I think so. Try this training data:
```js
[
  {
    input: {
      titel: 1,
      description: 1,
      path: 1,
      resolution: 1,
      runtime: 1,
      size: 1,
      author: 1,
    },
    output: {
      video: 1,
    },
  },
  {
    input: {
      title: 1,
      url: 1,
    },
    output: {
      link: 1,
    },
  },
  {
    input: {
      text: 1,
    },
    output: {
      text: 1,
    },
  },
]

```

**Comment by GELight** [comment]
Hi,

Many thanks for your tipp and help for this.
I think it works so far.

Best regards,
Mario
