### ISSUE TITLE
Is it possible to find shortest path using brain js?

### ISSUE THREAD

**Issue by dhivehi** [BrainJS/brain.js#416]
Is it possible to find shortest path using brain js? If so, how it could be achieved?

**Comment by robertleeplummerjr** [comment]
>Is it possible to find shortest path using brain js? If so, how it could be achieved?

Short answer: Yes!

Long answer:
While you may find the shortest path with a NeuralNetwork, a neural network (what is in brain.js as of now) _isn't ideal for this that I've seen_, but one of my favorite algorithms can (sufficiently) find this with some ease, and it is fantastically simple: [ACO, or Ant Colony Optimization](https://en.wikipedia.org/wiki/Ant_colony_optimization_algorithms)

What do I mean by "a neural network isn't ideal for this that I've seen"?
* Analogy 1: It is like using a tank when all you need is a bike
* Analogy 2: It'd be like using 1 gauge electrical cable for knitting a sweater
* ~Analogy 3~ Nearly identical problem: It's like asking a human to solve the traveling salesman problem by just thinking about it

Neural networks can be immensely sophisticated, that isn't what you want.  You want a naturally fine tuned algorythm that exactly solves this problem.

I've actually debated on implementing an ACO in brain.js (I even implemented one sometime back here: https://github.com/robertleeplummerjr/idea.js), even though it isn't really a neural network, but rather, just a fantastic algorithm found in nature.  However maybe we'll add it in v3 if there is interest.

Some would argue about which is better, or if a neural network could do this and be optimum at it, here is a demo I wrote that actually compares the three common approaches:
1. neural network (I think this uses a variation of reinforcement learning)
2. metaheuristic (some call this a genetic algorythm, [which is poor choice in naming](https://www.quora.com/Whats-the-core-idea-behind-genetic-algorithms/answer/Robert-Plummer-5))
3. ACO

You can quickly see who wins: http://robertleeplummerjr.github.io/idea.js/examples/travellingSalesman.html

**Comment by robertleeplummerjr** [comment]
I do want to point out I don't think the neural network implementation is optimum, however.  That was before I became much involved in brain.js.
