### ISSUE TITLE
[TS] inputRange/learningRate/decayRate isn't defined

### ISSUE THREAD

**Issue by Berkmann18** [BrainJS/brain.js#418]
![A GIF or MEME to give some spice of the internet](http://analyticsindiamag.com/wp-content/uploads/2017/06/1o40ej.jpg)

## *What* is wrong?
Missing or misplaced `inputRange`/`decayRate` config property.
EDIT: [`learningRate`](https://github.com/BrainJS/brain.js/blob/master/index.d.ts#L61) on the other hand, isn't part defined in neither `INeuralNetworkOptions` or `IRNNDefaultOptions`.

## *Where* does it happen?
When compiling a TS file like:
```ts
import brain, { INeuralNetworkOptions, IRNNDefaultOptions } from 'brain.js';

const trainingData = [
  {input: [0, 0], output: [0]},
  {input: [0, 1], output: [1]},
  {input: [1, 0], output: [1]},
  {input: [1, 1], output: [0]}
];

// provide optional config object (or undefined). Defaults shown.
const config: INeuralNetworkOptions = {
  binaryThresh: 0.5,
  hiddenLayers: [3], // array of ints for the sizes of the hidden layers in the network
  activation: 'sigmoid' // supported activation types: ['sigmoid', 'relu', 'leaky-relu', 'tanh'],
};

// create a simple feed-forward neural network with backpropagation
const weakNN = new brain.NeuralNetwork(config);

weakNN.train();

const weakOutput = weakNN.run([1, 0]); // [0.987]

const medConfig: IRNNDefaultOptions = {
  inputSize: 2, //or
  inputRange: 4, //or 2
  hiddenLayers: [4, 4], //or [4]?
  outputSize: 2, //or 4?
  learningRate: .01,
  decayRate: .999
}

const medNN = new brain.NeuralNetwork(medConfig);

medNN.train(trainingData);

const medOutput = medNN.run([1, 0]);

console.log('weak/med output=', weakOutput, medOutput);
```

## *How* do we replicate the issue?

1. set up a TS project like https://github.com/Berkmann18/BrainPlay/
2. run `tsc --watch`

## *How* important is this (1-5)?

2

## Expected behaviour (i.e. solution)

The property would be in the declaration of `IRNNDefaultOptions` or simply not in the examples.

## Other Comments

**Comment by robertleeplummerjr** [comment]
Resolved in v2 alpha 8.  Ty for finding this!
