### ISSUE TITLE
Unexpected Behavior unable to save training data (offline example)

### ISSUE THREAD

**Issue by opiepj** [BrainJS/brain.js#419]
I'm new to this so I hope this is a small issue, nevertheless will be thorough.

Goal: I want to create a sample of training recommendations offline, load it into a web app and run it without any training on the browser. However, I want to be able to submit data back to a server where the model can train on new additional data. Inspired by [BrainJSReactNative](https://github.com/BrainJS/BrainJSReactNative).

## *What* is wrong?

Seeing some unexpected behavior when trying to train data offline with newly appended training data. The workaround is retraining the model from scratch with new data, which seems odd.
 
I'm  using this [example](https://github.com/BrainJS/BrainJSReactNative/blob/master/index.js) from the React Native repo to do the following:

1. Import existing trained data _(Trained model with lyrics by ACDC and Lee Kernaghan)_
2. Train Data with new training data _(same as old training data + Slayer lyrics)_
3. Run Model with Slayer lyrics which should score slayer the highest

Problem(s):
1. "Slayer" is not part of the output at all
2. "Slayer" is not added to the model weights, in fact, the training model stays virtually the same as before.

**Training Data:**
- 4 ACDC lyrics (pre-trained)
- 10 Lee Kernaghan lyrics (pre-trained)
- 2 Slayer lyrics  (new)

**Sample input:**
```javascript
// Example input - pre-encoded - each word is encoded to a number when it hits the train runtime
{ input: `Up in the morning and out to school
        The teacher is teaching the golden rule
        American history and practical maths`,
    output: {ACDC: 1}}
```

**Training:**
```javascript
net.train(processTrainingData(trainingData), {
  iterations: 20000,
  learningRate: 0.1,
  logPeriod: 1,
  momentum: 0.1,
  log: true,
  errorThresh: 0.00000000000001,
  timeout: Infinity,
  callback: ((state) => {
    console.log(state);
  })
});
```

**Running:**
```javascript
let results = net.run(encode(`Surgery, with no anesthesia
    Feel the knife pierce you intensely
    Inferior, no use to mankind
    Strapped down screaming out to die
    Angel of Death
    Monarch to the kingdom of the dead
    Infamous butcher,
    Angel of Death`));

console.log(results);
```
**Output:**
![image](https://user-images.githubusercontent.com/7416676/61398668-5281da00-a881-11e9-978e-fec99dda5e5d.png)

**Saving:**
```javascript
fs.writeFileSync('trained-model.json', JSON.stringify(net.toJSON()));
```
Slayer is not added to weights, nothing has changed.
![image](https://user-images.githubusercontent.com/7416676/61398974-f79cb280-a881-11e9-8f75-0b98e6fbfe89.png)

## *Where* does it happen?

Running this [code](https://github.com/BrainJS/BrainJSReactNative/blob/master/index.js) when adding training data.

## *How* do we replicate the issue?

Running this [code](https://github.com/BrainJS/BrainJSReactNative/blob/master/index.js) when adding training data.
Example training data appended to `trainingData`:
```javascript
  {
    input: `Surgery, with no anesthesia
    Feel the knife pierce you intensely
    Inferior, no use to mankind
    Strapped down screaming out to die
    Angel of Death
    Monarch to the kingdom of the dead
    Infamous butcher,
    Angel of Death`,
    output: {Slayer: 1}
  },
  {
    input: `Crowded tombs
    Sickening ways to achieve
    The [Explicit]
    Seas of blood, bury life
    Smell your death as it burns
    Deep inside of you
    Abacinate, eyes that bleed
    Praying for the end of
    Your wide awake nightmare
    Wings of pain, reach out for you
    His face of death staring down,
    Your blood running cold
    Injecting cells, dying eyes
    Feeding on the screams of
    The mutants he's creating
    Pathetic harmless victims
    Left to die
    Rancid Angel of Death
    Flying free`,
    output: {Slayer: 1}
  }
```

## *How* important is this (1-5)?

5 - can't do offline training, have to train models from scratch if training data changes. Which is a pain.

## Expected behavior (i.e. solution)

The model should append new training data. Shouldn't have to start from scratch every time.

## Other Comments
Searched through the issues, was unable to find a solution

**Comment by opiepj** [comment]
**Update**: the only workaround I see is just accepting the fact you can't freeze the models state, you can only freeze its weights. Which means any new training data you insert you have to retrain the entire model from scratch, replace the model entirely.

**Comment by robertleeplummerjr** [comment]
I'm working on a fix for this.

**Comment by robertleeplummerjr** [comment]
What needs to happen is this:  The encoder simply needs all possible results at the start (a-z, 0-9, some punctuation, spaces, and a general input... for things the net doesn't understand), and you are golden.  I'll get you a sample.

**Comment by robertleeplummerjr** [comment]
Interesting, I thought they were using a LSTM, but they are using a regular feedforward net...

**Comment by robertleeplummerjr** [comment]
Ok, after looking at the example and the type of data being sent in, I think I'd simply say the network is somewhat incompatible with the training data in how it is being encoded.  The reason is this:  The network may not even be using the patterns being sent in to determine the artist, _it may actually just be using the length of where there is data_.  It is hard to say, because a simple feed forward network doesn't really have a "fully connected layer", or a "dense layer", it uses simple matrix multiplication.  However, using a recurrent network, though it may be slower, will yield MUCH better results.  In fact, let me prove it to myself...

**Comment by ahmetcanaksu** [comment]
Can I replace lstm with neu gpu ? Seems like we will wait for gpu lstm. In this time I want to try neu in my project. Is it possible to predict next letters like lstm on neu? 

Welcome
Welc + ome

**Comment by robertleeplummerjr** [comment]
There are still some missing layers with the GPU LSTM, not yet, but SOON.

**Comment by robertleeplummerjr** [comment]
Booya! https://jsfiddle.net/robertleeplummerjr/dhn7k1yq/10/

First time I ran it, I got: "obby cerrin", with zero configuration, and probably overfitting.  In short, they (we) just need to use a more applicable net is all.
