### ISSUE TITLE
LSTM output

### ISSUE THREAD

**Issue by marcospassos** [BrainJS/brain.js#421]
Is there any way to specify the maximum number of matches and length the network should output?

I'm looking for something like:

```js
const trainingData = [
    'foo bar1 bar 11',
    'foo bar2 bar 22',
    'foo bar3 bar 33'
];

const lstm = new brain.recurrent.LSTM();
const result = lstm.train(trainingData, { iterations: 1000 });

lstm.run('foo', {maxResults: 3, maxLength: 4}); // ['bar1', 'bar2', 'bar3']
lstm.run('foo', {maxResults: 3, maxLength: 20}); // ['bar1 bar11', 'bar2 bar22', 'bar23']
```

I've also noticed that specifying a list of tokens causes an error, is it expected?

```js
const trainingData = [
    ['foo', 'bar1', 'bar 11'],
   //...
];

// Error brain.js:6403 Uncaught Error: unrecognized character "u"
const lstm = new brain.recurrent.LSTM();
const result = lstm.train(trainingData, { iterations: 1000 });
```

**Comment by Rocketblaster247** [comment]
In the training data, does any of non shown data contain a "u".

**Comment by robertleeplummerjr** [comment]
>Is there any way to specify the maximum number of matches and length the network should output?

The underlying issue that was causing the repeated matches has been resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-alpha.5, essentially it was just using `brain.recurrent.RNN` which is known not to be stable by the fundamental math that makes it up.

>I've also noticed that specifying a list of tokens causes an error, is it expected?

Seems to be a bug.  Will look at this next.

**Comment by robertleeplummerjr** [comment]
>Is there any way to specify the maximum number of matches and length the network should output?

https://github.com/BrainJS/brain.js#rnn-lstm-or-gru-output-too-short-or-too-long

```js
const net = new brain.recurrent.LSTM();

// later in code, after training on a few novels, write me a new one!
net.maxPredictionLength = 1000000000; // Be careful!
net.run('Once upon a time');
```

>I've also noticed that specifying a list of tokens causes an error, is it expected?

That is not expected, will find a solution shortly.

**Comment by robertleeplummerjr** [comment]
Fixed in https://www.npmjs.com/package/brain.js/v/2.0.0-alpha.7, unit tests added: https://github.com/BrainJS/brain.js/blob/92a2ada834722e230caf524936fe24a8c3c9d614/__tests__/recurrent_deprecated/rnn.js#L608

**Comment by marcospassos** [comment]
Thank you, @robertleeplummerjr!
