### ISSUE TITLE
LSTMTimeStep Training Options

### ISSUE THREAD

**Issue by Shadaeiou** [BrainJS/brain.js#423]
![Help plz](https://media.giphy.com/media/czBIi0WnXX8L6/giphy.gif)

## *What* is wrong?
Caveat: I'm not an expert and am just barely familiar with deep learning AI algorithms so I apologize in advance. I'm trying to train LSTMTimeStep some stock data (daily closing prices from July 2014 to January 2019). 

Things I've tried:
- Chunking the training data into different sizes e.g. 

```
// Chunk size of 5
net.train([
    [110.01, 109.98, 108.18, 111.91, 105.42],
    [110.01, 109.98, 108.18, 111.91, 105.42],
    [110.01, 109.98, 108.18, 111.91, 105.42],
    [110.01, 109.98, 108.18, 111.91, 105.42]
]);

// Chunk size of 2
net.train([
    [110.01, 109.98],
    [110.01, 109.98],
    [110.01, 109.98],
    [110.01, 109.98],
    [110.01, 109.98]
]);
```
I've had the most success with Chunking the data into 2 data points per ??data point?? again I'm not sure what to call each item in the main train array.

- Different errorThresholds most of the time if I pick a low errorThreshold it never hits it and just stops training after 20000 iterations and if I pick a higher errorThreshold well I don't get very good results.
- Tweaking learningRate and momentum. Changing these made it so the training error basically never went down so I assume that I probably shouldn't touch those.

My main question is what would be the best route, given a stock's closing price from July 2014 - January 2019 (knowing that different stocks such as Amazon are trading at $2,000/share and GE is trading at $10/share), to train a model consistently to be the most accurate.

## *Where* does it happen?
Using the LSTMTimeStep neural network.

## *How* do we replicate the issue?
[https://jsfiddle.net/pasouxjv/1/](https://jsfiddle.net/pasouxjv/1/)

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
I think there is probably a specific setup that I'm not familiar with that's best suited for the use case that I'm trying to accomplish

## Other Comments
Again sorry about my ignorance this is just part of my journey into learning more about machine learning and neural networks. I appreciate any feedback about how I could possibly get this up and running most efficiently. Thanks!

**Comment by robertleeplummerjr** [comment]
I think this issue was solved in v2 alpha 4, can you try latest and try again?  Either one of your training patters should be fine, it was an internal issue.
