### ISSUE TITLE
How to use JSON method to store a trained net?

### ISSUE THREAD

**Issue by rafaelgomesfernandes** [BrainJS/brain.js#424]
## The code im trying to understand is: 
const json = net.toJSON();
net.fromJSON(json);

**Comment by mubaidr** [comment]
> const json = net.toJSON();

You can save this `json` (write to file) for later usage. 

> net.fromJSON(json);

Create a new net of similar type stored in json. e.g. `const net = new brain.NeuralNetwork()` and then you can load net from json. i.e. `net.fromJSON(json);`
