### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: value1.concat is not a function

### ISSUE THREAD

**Issue by GELight** [BrainJS/brain.js#425]
Hi,

I have a problem by using net.run("...") ( brain.recurrent.LSTM ) inside a forEach.
Is this a problem on my code or do I have to use brain.js not like this?

**What I try to do?** 
I like to analyze each values of an json object.

**This are the related code snippets of my classes:**
```
// File with "analyze" class:
const AnalyzeValueNet = new brain.recurrent.LSTM();

getBestInputTypeByValue (value: string | number): string {
    return AnalyzeValueNet.run(value);
}
```
And this is the place where I try to analyze each values of my JSON object:
```
analyzeObject(json: JSON): void {
  Object.keys(this.json).forEach(index => {
      if (typeof this.json[index] === 'string' || typeof this.json[index] === 'number') {
        let bestInputType = analyze.getBestInputTypeByValue(this.json[index]);
        this.setParam(bestInputType, this.json[index]);this.json[index]
      }
    });
}
```
If I run my script, the following error occours  in line 
```
let bestInputType = analyze.getBestInputTypeByValue(this.json[index]);
```

You have an idea what goes wrong?

Best regards,
Mario

**Comment by robertleeplummerjr** [comment]
I think this:
```ts
getBestInputTypeByValue (value: string | number): string {
```
Should be this:
```ts
getBestInputTypeByValue (value: string | number[]): string {
```

BUT you should have caution when using a `brain.recurrent.LSTM` with arbitrary floating decimal values, they are read in as characters of string with `brain.recurrent.LSTM`.  A `brain.recurrent.LSTMTimeStep` reads them as actual decimal values in.

What is an example of one of these json objects?

**Comment by robertleeplummerjr** [comment]
Actually, I may be speaking out of turn, you can send a number in, but it is converted JIT to a string, sorry.  Been a long day at work :)

**Comment by GELight** [comment]
Hi,

Sorry for my late answer.
No problem, no problem ... I know that when you have to work a lot. First of all, I would like to say that my problem no longer exists. It was not brain.js. :)

Let me answer your question. I'll try to explain what my big goal is >>> **I try to map unspecified data to specified UI components.**

**For example**, a UI component has specific input parameters that the component can handle.

- Input-Parameter for a "**text**" component:
  - **text**
- Input-Parameter for a "**link**" component:
  - **text**
  - **url**
- Input-Parameter for a "**image**" component:
  - **url**
- Input-Parameter for a "**video**" component:
  - **text**
  - **url**
  - **description**
  - **resolution**
  - **size**
  - **author**

**Example of typically unspecified data (my test data in JSON format)**
```json
{
    "something: Sign in to your Google Account",
    "abc: A little cow",
    "test: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod.",
    "foo: http://www.google.de",
    "bar: Google is an Internet search engine of the US company Google LLC. Matching statistics show that Google is the market leader among Internet search engines and the most visited website in the world for search queries.",
    "nice: https://avatars3.githubusercontent.com/u/7214793?s=460&v=4"
}
```

**Three steps:**
1. In a first step, I try to assign the individual values ​​to the most suitable input type. (I replace the related index)
    - For example, "**abc**" could be the input type "**text**".
    - So could "**foo**", the input type "**url**".
    - So could "**nice**", the input type "**url**".

    **These are my current test training data for this analysis:**
    ```json
    [
        { "input": ".mp4", "output": "url" },
        { "input": "www.google.de", "output": "url" },
        { "input": "www.", "output": "url" },
        { "input": "http://www.", "output": "url" },
        { "input": "https://www.", "output": "url" },
        { "input": "abcdefghijklimopqrstuvwxyz", "output": "text" },
        { "input": "01234564789", "output": "text" },
        { "input": "Lorem ipsum dolor sit amet, consetetur sadipscing aliquyam erat, sed diam voluptua.", "output": "text" },
        { "input": "Muh sagt die Kuh", "output": "text" }
    ]
    ```
    **I use your example for this first step:**
    ```js
    const net = new brain.recurrent.LSTM();
    net.train([
      { "input": 'I feel great about the world!', "output": 'happy' },
      { "input": 'The world is a terrible place!', "output": 'sad' },
    ]);
    const output = net.run('I feel great about the world!');  // 'happy'
    ```

2. Now comes the hard part.
In the next step, I try to figure out which properties suit each other as intelligently as possible. The difficulty now is to find a logic that could find out which properties logically fit together.
In this example, these two properties could match and be assigned to the "link" component:
   - "url: http://www.google.de",
   - "text: Google is an Internet search engine of the US company Google LLC. Matching statistics show that Google is the market leader among Internet search engines and the most visited website in the world for search queries.",

   - I think it sounds like "science fiction" right now, but that's my idea behind it. It does not have to be perfect right away. :)

    At the end this can be a generated JSON for my UI layer:
    ```json
    {
        "id": "123123",
        "type": "link",
        "params": {
          "url": "http://www.google.de",
          "text": "Google is an Internet search engine of the US company Google LLC. Matching statistics show that Google is the market leader among Internet search engines and the most visited website in the world for search queries."
        }
    }
    ```

3. In the last step, I select the most suitable UI component via the input parameters compiled in the second step.

    I do this by a very good tip from you with these training data:
    ```json
    [
        {
          "input": {
            "titel": 1,
            "description": 1,
            "url": 1,
            "resolution": 1,
            "runtime": 1,
            "size": 1,
            "author": 1,
          },
          "output": {
            "video": 1,
          },
        },
        {
          "input": {
            "title": 1,
            "url": 1,
          },
          "output": {
            "link": 1,
          },
        },
        {
          "input": {
            "text": 1,
          },
          "output": {
            "text": 1,
          },
        },
      ]
    ```

As already mentioned, my problem is solved from my first post.
Sop far to my idea... :)

Best regards,
Mario

**Comment by robertleeplummerjr** [comment]
Ok, good to hear

**Comment by robertleeplummerjr** [comment]
Also, ty for your detailed response!
