### ISSUE TITLE
NeuralNetworkGPU log callback returns string instead of object

### ISSUE THREAD

**Issue by FinlayDaG33k** [BrainJS/brain.js#432]
![image](https://user-images.githubusercontent.com/13424273/62892922-46cee980-bd41-11e9-9783-e6051b9e39e4.png)

## *What* is wrong?

Using a callback for the `log` in `NeuralNetworkGPU` results in the data being passed being a string(?).  
Instead of getting the output `{iterations: 1, error: 0.00}` I'm receiving `iterations: 1, error: 0.00`, which prevents me from using the values given in my own output.

## *Where* does it happen?

When training the network.

## *How* do we replicate the issue?

```js
const net = new brain.NeuralNetworkGPU();
net.train(
      trainingData,
      { 
        iterations: 100,
        log: function(data) {
          console.log(data); // here there be issue
        },
        logPeriod: 1
      }
    );
```
## *How* important is this (1-5)?

3

## Expected behavior (i.e. solution)

An object being passed containing the finished `iteration` and `error`.

## Other Comments
I'm using `brain.js@2.0.0-alpha.2` and node version `12.8.0`.

**Comment by FinlayDaG33k** [comment]
This bug also seems to affect the `brain.recurrent.LSTM` in the current `master`.

**Comment by FinlayDaG33k** [comment]
Using `callback` instead of the `log` option gives the data just fine as expected.  
Is this intended behaviour or?

**Comment by robertleeplummerjr** [comment]
This is the intended behavior. Log is meant for human readability, callback is meant for programmatic interaction.  Thank you for being patient on this issue, I've been busy syncing the develop Branch with Master for the GPU updates.
