### ISSUE TITLE
toFunction () dows not work

### ISSUE THREAD

**Issue by AquaMCU** [BrainJS/brain.js#435]
![](https://img-9gag-fun.9cache.com/photo/aXjb6YP_700bwp.webp)

## Other Comments

This:
const exp = net.toFunction ();

console.log ("Example: 1 NET("+trainingID+"):" + net.run (trainingData[training...
console.log ("Example: 1 FUN("+trainingID+"):" + exp (trainingData[trainingID]...

Results in this:
Example: 1 NET(3):0.8407706618309021
Example: 1 FUN(3):0.11329327886078797

I am not a genius, but ... this is not the same number ;)

**Comment by robertleeplummerjr** [comment]
LOL!  Perfect gif.  Whhich class are using, what version of brain.js?

**Comment by AquaMCU** [comment]
Hi. Yes. I just love the Pepe Silvia picture. It is a blast to watch the clip on youtube ;)

Here are the facts:
--> "brain.js": "^2.0.0-alpha.5"
--> var net = new brain.NeuralNetwork ({9,3 });

BTW. you guys are awsome! I am looking forward to rock brain.js on GPU

**Comment by robertleeplummerjr** [comment]
For some reason I thought it was from Pacific Rim.  Reproduced here: https://jsfiddle.net/robertleeplummerjr/nqcp16sx/10/
