### ISSUE TITLE
IDEA: Create docker container for using GPU

### ISSUE THREAD

**Issue by AquaMCU** [BrainJS/brain.js#436]
## Other Comments

I think, since you guys will have a lot of trouble checking issues that are based on the HW and SW stack, it is nice to use docker, so you always have a similar user space. What do you think?

**Comment by robertleeplummerjr** [comment]
I love it!

**Comment by AquaMCU** [comment]
I will start working on it when the GPU stuff is stable in Version 2.0

**Comment by robertleeplummerjr** [comment]
Fantastic!

**Comment by rbjs** [comment]
Any update on using Brain.js with Docker ?
