### ISSUE TITLE
Need Community Help!  Brain.js v2 dimension need to be easier

### ISSUE THREAD

**Issue by robertleeplummerjr** [BrainJS/brain.js#439]
![A GIF or MEME to give some spice of the internet](https://media2.giphy.com/media/phJ6eMRFYI6CQ/giphy.gif)

## *What* is wrong?
Dimensions in v2 are defined like this:
```js
const net = new FeedForward({
  inputLayer: () => input({ width: 1, height: 1 }),
  hiddenLayers: [
    inputLayer => feedForwardLayer({ width: 1, height: 1 }, inputLayer),
  ],
  outputLayer: inputLayer =>
    new output({ height: 1 }, inputLayer),
  });
```
This is nice and all, and does adhere to the mathematical specification of the network, but I find `width`, `height`, and even `depth` not very intuitive, especially if you use a 1d Array ("length" ?).  We need a more appropriate term, especially when dealing with different sized inputs.  Perhaps that term is "length"?  The other odd thing is that the output above gives us (`const value = net.run()`) a 2d array `result[0][0]`, even if it is sized width and height of 1.  How can we make this better?  (Leaving this open for anyone who'd like to comment, between making GPU implementation faster, and unit testing and fixing parts of brain.js v2).

## *How* important is this (1-5)?
4

## Expected behavior (i.e. solution)
perhaps use length to define `height`? ("height" is appropriate because of how matrix multiplication works.)
`net.run()` outputs a single dimension array, perhaps, but can still deal with multidimensional inputs?

## Other Comments

**Comment by Berkmann18** [comment]
If `width` is (I assume) being used for the same object (i.e. matrix for the NN) that `height` is used for, then it makes more sense to keep `height`.
That being said, the `length` of the aforementioned matrix could be understood as either properties (unless it's a 1D array, in which case, it's straightforward).
