### ISSUE TITLE
Network can't learn how to add 1 to a number

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [BrainJS/brain.js#440]
I thought it would be easy to teach a network to forecast n + 1, n + 2, n + 3, etc.  But my error is always in the hundreds regardless of how many thousands of iterations I run.

`const brain = require('brain.js');`
`const net = new brain.recurrent.LSTMTimeStep({`
`  inputSize: 1,`
`  hiddenLayers: [1],`
`  outputSize: 1`
`});`
``
`//Same test as previous, but combined on a single set`
`const trainingData = [`
 ` [0, 1, 2, 3, 4, 5],`
`  [1000, 1001, 1002, 1003, 1004],`
`  [430, 431, 432, 434, 444],`
`  [2, 3, 4, 5],`
 ` [-10, -9, -8, -7, -6, -5, -4, -3],`
 ` [30, 31, 32, 33, 34, 35, 36, 37],`
`  [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],`
`  [140, 141, 142, 143, 144, 145, 146]`
`];`
``
`net.train(trainingData, { log: true, iterations: 1e4, errorThresh: 0.1 });`
`console.log( net.forecast([200, 201], 3)) ;`

Should output 202, 203, 204.  But instead it says something goofy like 5.4, 5.5, 5.6.

**Comment by robertleeplummerjr** [comment]
You need to normalize to values between 0 and 1 is all.

**Comment by MelerEcckmanLawler** [comment]
The tutorial I got this code from did not have normalized values.  It had 1, 2, 3, 4, 5 and 5, 4, 3, 2, 1 as the training set.
