### ISSUE TITLE
Cannot use npm install in node 12 environment

### ISSUE THREAD

**Issue by DaiZack** [BrainJS/brain.js#441]
> gl@4.3.3 install C:\ZD\node_modules\gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 libc= platform=win32)

C:\ZD\node_modules\gl>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\dieze\AppData\Local\Orange\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ZD\node_modules\gl
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\ZD\package.json'
npm WARN ZD No description
npm WARN ZD No repository field.
npm WARN ZD No README data
npm WARN ZD No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.3.3 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gl@4.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dieze\AppData\Roaming\npm-cache\_logs\2019-09-04T02_35_09_887Z-debug.log

**Comment by DaiZack** [comment]
lower down to node10, and npm install -g windows-build-tools
Install success

**Comment by mubaidr** [comment]
This seems like compatibility issue with `windows-build-tools`. For example it will work when installing 2017 version build-tools. more info here: https://github.com/BrainJS/brain.js/issues/429

For the very same reasons, we have planned to update readme to provide clear instructions on how to deal with install/build issues for version 2.

**Comment by ScienceMarc** [comment]
For me it worked to just do
`npm i brain.js@1.6.1`
Sure this is an older version but it isn't marked as "alpha"
Probably far from optimal

**Comment by mubaidr** [comment]
Yes, the current version works fine but the upcoming version (currently in alpha) will require these guidelines.

**Comment by Berkmann18** [comment]
This seems to be a Windows-specific issue as I managed to install the `stable` and `latest` versions of `brain.js` using Node 12.

**Comment by massaroni** [comment]
Cancel

**Comment by massaroni** [comment]
lol wtf my watch just decided to send this reply automatically, please disregard that!

**Comment by mubaidr** [comment]
https://github.com/BrainJS/brain.js/issues/429
