### ISSUE TITLE
Neural Network of type LSTMTimeStep returns `undefined` when run.

### ISSUE THREAD

**Issue by geosp** [BrainJS/brain.js#445]
## *What* is wrong?
Neural Network of type LSTMTimeStep returns `undefined`. when run. 

## *Where* does it happen?
It happens on my local environment but also in a runkit environment I setup for testing:
[Runkit Test](https://runkit.com/geosp/5d78e06eacef2f00136426ef)

## *How* do we replicate the issue?
Run here [Runkit Test](https://runkit.com/geosp/5d78e06eacef2f00136426ef) or as follows:

1. Clone repo https://github.com/geosp/hello_brain follow instructions in readme.
2. Run `npm start market`

## *How* important is this (1-5)?
5 - Urgent

## Expected behavior (i.e. solution)
The result of running a Neural Network of type LSTMTimeStep should not yield undefined.

## Other Comments
I tried both the latest version of Brain.JS and 1.6.1.

**Comment by geosp** [comment]
Found my issue. I was passing the input as an object not an array.

**Comment by robertleeplummerjr** [comment]
Ty for house-keeping!

**Comment by robertleeplummerjr** [comment]
But, thinking of your issue, a throw would have been helpful, correct?

**Comment by geosp** [comment]
@robertleeplummerjr  Correct, it will be nice have more advanced input validation. When I understand the implementation  better I could contribute with validation of inputs. Thank you for your response.  Your are doing an amazing job.
