### ISSUE TITLE
Change the signature of logging function from log(info:string)  to log(info:string, {iterations: number, error: number})})

### ISSUE THREAD

**Issue by geosp** [BrainJS/brain.js#446]
## *What* is wrong?
I'm visualizing training by observing the model's behavior via a plot of iterations vs. error. 
I expected the log function signature to have iterations and error as numeric values. 

## *Where* does it happen?
It happens any time a training option for log is provided as a function.

## *How* do we replicate the issue?
1. Clone my repository [hello_brain](https://github.com/geosp/hello_brain)
2. Follow readme instructions.
3. Run `hpvsmpg` example like this: `npm start hpvsmpg`

## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)
I created a work around in my code in the [train helper](https://github.com/geosp/hello_brain/blob/master/src/core/train.ts#L59)
I have also created a PR associated with this issue.

## Other Comments
This is what I'm accomplishing with this feature:
![brain_prediction](https://user-images.githubusercontent.com/20133884/64932218-76bf5000-d80b-11e9-8a21-28e8e14a05bd.png)
![brain_error_log](https://user-images.githubusercontent.com/20133884/64932228-80e14e80-d80b-11e9-99f4-4b99b2d34cc9.png)

**Comment by colus001** [comment]
I think you can use `trainingOptions.callback` instead. 

```
export interface INeuralNetworkTrainingCallback {
  (state: INeuralNetworkState): void;
}

export interface INeuralNetworkState {
  iterations: number;
  error: number;
}
```

I'm using like below.

```
const trainingOptions: INeuralNetworkTrainingOptions = {
  ...
  callback: (state) => progress.tick(callbackPeriod, {
    error: `error: ${state.error.toFixed(6)} / ${errorThresh}`,
  }),
  callbackPeriod,
};
```

**Comment by geosp** [comment]
Thank you for your response. I wonder why we need both log and callback. I would be nice to just keep callback and get rid of log.
