### ISSUE TITLE
brain.utilities.toSVG fails to generate SVG file

### ISSUE THREAD

**Issue by geosp** [BrainJS/brain.js#448]
## *What* is wrong?
brain.utilities.toSVG fails to generate SVG file

## *Where* does it happen?
Any time while invoking brain.utilities.toSVG 
Example [this line in my code](https://github.com/geosp/hello_brain/blob/master/src/core/train.ts#L57)
## *How* do we replicate the issue?
Invoke brain.utilities.toSVG

## *How* important is this (1-5)?
1

## Expected behavior (i.e. solution)
It should generate the SVG

## Other Comments
I have created a PR to fix this issue.

**Comment by mubaidr** [comment]
Thanks for the pull request: https://github.com/BrainJS/brain.js/pull/449

**Comment by geosp** [comment]
Thank you for the awesome job you guys have done.
