### ISSUE TITLE
Can't Install Brain.js

### ISSUE THREAD

**Issue by DocRoro** [BrainJS/brain.js#451]
I wanted to make an RNN in brain.js but I just can't... I accidentally installed brainjs and it worked perfectly, I can install all the packages except brain.js, in the error it says something like there is a problem in gl, and when I try to install gl it shows the same error! Please help me.

Update: I've been troubleshooting and it looks like I can't install gpu.js either??

Here is the Cache:

[2019-09-16T20_21_31_464Z-debug.log](https://github.com/BrainJS/brain.js/files/3618083/2019-09-16T20_21_31_464Z-debug.log)

**Comment by mubaidr** [comment]
https://github.com/BrainJS/brain.js/issues/429
