### ISSUE TITLE
Upgrade to gpu.js 2

### ISSUE THREAD

**Issue by sbrl** [BrainJS/brain.js#452]
![A GIF or MEME to give some spice of the internet](https://cdn.discordapp.com/attachments/413775157988163585/623585126126714881/unknown.gif)

## *What* is wrong?
Nothing per se, but since [gpu.js just hit version 2](https://github.com/gpujs/gpu.js/releases/tag/2.0.0), updating to it would yield a key benefit: GPU Acceleration in Node.js.

## *Where* does it happen?
In Brain.js using Node.js

## *How* do we replicate the issue?
1. Write a Brain.js test application
2. Run it in Node.js
3. Note that GPU acceleration is unavailable

## *How* important is this (1-5)?
While Brain.js works as-is, adding support for GPU acceleration in Node.js would really open  loads of doors in terms of what Brain.js is capable of. I'd say a 4.

## Expected behavior (i.e. solution)
GPU acceleration should be available in Node.js

## Other Comments

**Comment by mubaidr** [comment]
https://github.com/BrainJS/brain.js/issues/364
