### ISSUE TITLE
Question about continuous training

### ISSUE THREAD

**Issue by GELight** [BrainJS/brain.js#455]
Can you create an example or tutorial how does the continuous training / resume training work?
I can train my network initial but I do not know how can I train it better and better ... ? 

I found some articles on the web about this topic but each article speak about another or old or deprecated solution. Maybe I am blind but in the readme there is no example, right?

Best regards, Mario

**Comment by mubaidr** [comment]
- Train netrwork with one data set
- Save as json
- Load network from json
- Train network with old + new data

This should be working and new network should have improved learning.
