### ISSUE TITLE
Brain.js Web Version Download/Link Is a 404 Error

### ISSUE THREAD

**Issue by travis-heavener** [BrainJS/brain.js#457]
Hey all!
The website link for embedding the brain.js file is returning a 404 error on my end.
https://cdn.rawgit.com/BrainJS/brain.js/master/browser.js

In all of my previous projects as well I cannot access brain.js. When I open the link, it just says "404: Not Found"

This is happening across all of my projects, on all platforms.

**How to replicate**
Open this link
https://cdn.rawgit.com/BrainJS/brain.js/master/browser.js
And it should show a 404 Error.

Importance: 4

The web link should take you to a lengthy file that contains all of the Brain.js script, that you can embed in HTML for your projects.

## Other Comments

**Comment by mubaidr** [comment]
Please use this cdn for optimal delivery: https://unpkg.com/brain.js
