### ISSUE TITLE
Problem to save and load a trained net.

### ISSUE THREAD

**Issue by Dansk04** [BrainJS/brain.js#461]
## *What* is wrong?
I am trying to save and load a trained net with json.  The saved net looks like:

`{"sizes":[4,3,2],"layers":[{"cci":{},"mfi":{},"rsi":{},"volumen":{}},{"0":{"bias":0.25945496559143066,"weights":{"cci":-0.016659682616591454,"mfi":-0.002197920810431242,"rsi":-0.06555669009685516,"volumen":0.1313842236995697}},"1":{"bias":0.15689831972122192,"weights":{"cci":-0.022772900760173798,"mfi":0.1531689316034317,"rsi":0.11912703514099121,"volumen":0.20893627405166626}},"2":{"bias":0.056261807680130005,"weights":{"cci":0.22942498326301575,"mfi":0.21674063801765442,"rsi":0.21809406578540802,"volumen":0.12272806465625763}}},{"down":{"bias":-1.1790411472320557,"weights":{"0":-0.5385767817497253,"1":-0.7750157713890076,"2":-0.6357296705245972}},"up":{"bias":-1.2827247381210327,"weights":{"0":-0.8092914819717407,"1":-0.514805257320404,"2":-0.585485577583313}}}],"outputLookup":true,"inputLookup":true,"activation":"sigmoid","trainOpts":{"iterations":20000,"errorThresh":0.005,"log":false,"logPeriod":10,"learningRate":0.3,"momentum":0.1,"callbackPeriod":10,"beta1":0.9,"beta2":0.999,"epsilon":1e-8}}`

or it looks like this below, when I JSON.parse() it:

`{ sizes: [ 4, 3, 2 ],
  layers:
   [ { cci: {}, mfi: {}, rsi: {}, volumen: {} },
     { '0': [Object], '1': [Object], '2': [Object] },
     { up: [Object], down: [Object] } ],
  outputLookup: true,
  inputLookup: true,
  activation: 'sigmoid',
  trainOpts:
   { iterations: 20000,
     errorThresh: 0.005,
     log: false,
     logPeriod: 10,
     learningRate: 0.3,
     momentum: 0.1,
     callbackPeriod: 10,
     beta1: 0.9,
     beta2: 0.999,
     epsilon: 1e-8 } }`

The numbers needed are objects in these case.
With both styles I got problems when i try to load the data with: 

net.fromJSON()

## Expected behavior (i.e. solution)
Save and load the trained Net without a problem.

I hope you can help me with this issue.

**Comment by mubaidr** [comment]
It is perfectly fine, since you have logged this to console. node.js by default do not show deep nested objects. (Displayed as just [Object] or [Array] etc). 
To make sure save the network to file (after JSON.stringify) and then check contents of the file.
