### ISSUE TITLE
How to Export the Model

### ISSUE THREAD

**Issue by tonyc770** [BrainJS/brain.js#463]
I would like to be able to export the model after training in order to use in a C++ program running on a micro-controller. Is there a way to get the actual JavaScript function that I can then convert to C++?

Thanks...

**Comment by mubaidr** [comment]
Yes, `toFunction` is what you are looking for: https://github.com/BrainJS/brain.js#standalone-function

But converting JS to c++ would require manual update as JS is weak/typeless language, but have a look at this: https://github.com/andrei-markeev/ts2c
