### ISSUE TITLE
Web Worker support broken?

### ISSUE THREAD

**Issue by potch** [BrainJS/brain.js#465]
## *What* is wrong?
`ReferenceError: brain is not defined` when the browser version of brain is loaded in a Web Worker

## *How* do we replicate the issue?
I've prepared a minimal test case here: https://agreeable-apricot.glitch.me/

## *How* important is this (1-5)?
**2**? I saw at one point this was fixed (#146), but that change doesn't seem to be in the current release.

## Expected behavior (i.e. solution)
Running a traning in the browser on the main thread not great for performance, so if it's still possible to use this library in a worker, that would be ideal.

## Other Comments
Thanks for making such a great library!

**Comment by mubaidr** [comment]
@robertleeplummerjr please check

**Comment by mubaidr** [comment]
Please try to access brain using `self.brain`

**Comment by potch** [comment]
updating to the latest version of the library seems to have resolved the issue.
