### ISSUE TITLE
Can't train LSTMTimeStep on 2-inputs / 1-output

### ISSUE THREAD

**Issue by massaroni** [BrainJS/brain.js#467]
## *What* is wrong?

I can't train an LSTMTimeStep with a smaller number of outputs than inputs.  Is this a bug or human error on my part?

## *Where* does it happen?

master branch, nodejs v11.15.0, on a mac.

## *How* do we replicate the issue?

This script is derived from `predict-numbers.js`, and it works fine if `outputSize` = `inputSize`, but when I drop it down to `outputSize: 1`, then it breaks with the error, below.

```javascript
const assert = require('assert');
const brain = require('../../src');

const net = new brain.recurrent.LSTMTimeStep({
  inputSize: 2,
  hiddenLayers: [10],
  outputSize: 1
});

const trainingData = [
  [[1,5],[2,4],[3,3],[4,2],[5,1]],
  [[0,6],[1,5],[2,4],[3,3],[4,2]],
  [[2,4],[3,3],[4,2],[5,1],[6,0]],
];

net.train(trainingData, { log: true, errorThresh: 0.09 });

const closeToFiveAndOne = net.run([[1,5],[2,4],[3,3],[4,2]]);

assert(Math.round(closeToFiveAndOne[0]) === 5, `${ closeToFiveAndOne[0] } does not round to 5`);
//assert(Math.round(closeToFiveAndOne[1]) === 1, `${ closeToFiveAndOne[1] } does not round to 1`);
console.log(closeToFiveAndOne);

const forecast = net.forecast([[1,5],[2,4]], 4);
assert(Math.round(forecast[2][0]) === 5, `${ forecast[2][0] } does not round to 5`);
//assert(Math.round(forecast[2][1]) === 1, `${ forecast[2][1] } does not round to 1`);
assert(Math.round(forecast[3][0]) === 6, `${ forecast[3][0] } does not round to 6`);
//assert(Math.round(forecast[3][1]) === 0, `${ forecast[3][1] } does not round to 0`);
console.log('next 4 predictions', forecast);
```
The script above breaks with this error:
```bash
$ node predict-numbers-2input-1output.js 
.../src/recurrent/rnn-time-step.js:167
      if (isNaN(error)) throw new Error('network error rate is unexpected NaN, check network configurations and try again');
                        ^

Error: network error rate is unexpected NaN, check network configurations and try again
    at LSTMTimeStep.train (.../src/recurrent/rnn-time-step.js:167:31)
    at Object.<anonymous> (.../examples/javascript/predict-numbers-2input-1output.js:16:5)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

## *How* important is this (1-5)?

4 because I can still train it for the same number of outputs and inputs, but it would probably train a lot faster on a smaller number of outputs.  This problem is especially bad if you have a lot of inputs.  And if this is a real bug then it may be a symptom of a larger problem with the training logic.

## Expected behavior

I would expect to get a fully trained net that outputs arrays containing one number, corresponding to the first input node.

## Other Comments

**Comment by robertleeplummerjr** [comment]
>4 because I can still train it for the same number of outputs and inputs, but it would probably train a lot faster on a smaller number of outputs.

What would that training set look like?  The way that is is set now, with your training set:
```js
const trainingData = [
  [[1,5],[2,4],[3,3],[4,2],[5,1]],
  [[0,6],[1,5],[2,4],[3,3],[4,2]],
  [[2,4],[3,3],[4,2],[5,1],[6,0]],
];
```

It is as if you are commanding net to do the following:

1. Start running through some time step values
2. What comes after `[1,5]` (input, inputSize = 2)?
3. Make a guess, and keep it internal.  It guesses something likely off from `[2,4]` (output, outputSize = 2)
4. Compare that guess (output) with `[2,4]` (next input, inputSize = 2) and measure how far it is off and save that internally.
5. Go back to step 2, with next value, `[2,4]`, and repeat till `[5,1]`
6. Insert [`[0,0]` ](https://github.com/BrainJS/brain.js/blob/017c00895dfeb4981fc22cf69ba1870db8754c89/src/recurrent/rnn-time-step.js#L396) at end signifying end of input
7. Go back to step 1 with next input/output set (`[[0,6],[1,5],[2,4],[3,3],[4,2]]`, and finally `[[2,4],[3,3],[4,2],[5,1],[6,0]]`)

From what I can gather, how would you say to the net: "I want an input of `[1,5]` and an output of `[2]` for example?


P.S. I hope this doesn't sound condescending, this is something I've wanted, but didn't have yet the time dedicated to work out.

**Comment by massaroni** [comment]
Thanks @robertleeplummerjr I see what you're saying.  In that case, I may have misinterpreted what outputSize is for, and maybe it doesn't make sense in this use case?  I may take a look at some larger frameworks like tensorflow and pytorch, and see if/how they handle this use case.
