### ISSUE TITLE
Very large input training (80.000) for PointsCoud detection 

### ISSUE THREAD

**Issue by lucydjo** [BrainJS/brain.js#468]
![A GIF or MEME to give some spice of the internet](https://zupimages.net/up/19/42/jqyr.gif)

Hi !

I recently trained an AI to detect numerical numbers in an image. The input is a pixel array, the value is the color. 

> { input : [0, 0, 0, 0.23, 0.023 ...... ], output: { n4: 1  }

the input **size is 784,** because the images are **28*28 pixels.** And it works well with an accuracy rate of **83%**.

I would like to do object detection in a point cloud in the same way. **The problems are:**

- The size of the input is no longer 700, but much larger! Between 10k and 100k maybe more!
- The size of the input is never the same.

**Now, the questions :**

- Is brainjs able to support Input of 90,000 length ?
- Is it a problem to have a changing input size?

I am currently developing this project, I would like to have your opinions and theory! it will help me a lot !
Thx

**Comment by robertleeplummerjr** [comment]
>Is brainjs able to support Input of 90,000 length ?

It can in some cases, that describes a 300 x 300 image.  That is still pretty big.  Convolution on the GPU would help substantially, it is not totally done yet.

>Is it a problem to have a changing input size?

It can be if you don't normalize it.  However, if you just normalize your images before-hand, they'll be the same size.
