### ISSUE TITLE
net.toFunction Question

### ISSUE THREAD

**Issue by tonyc770** [BrainJS/brain.js#469]
I am using the net.toFunction in the following way:

var func = net.toFunction();
var strFunc = func.toString();

In the return string I see the inputs shown like this:
...(1+1/Math.exp((0.007241739425808191+0.07042734324932098***(input['0']||0)**+0.14556755125522614***(input['1']||0)**...

What is the difference between **input['0']** and **input['1']** in code? Is this the value at the array index? or is the entire input array placed in each input[]?

Thanks...

**Comment by robertleeplummerjr** [comment]
It is the array or input you send into the function.

**Comment by tonyc770** [comment]
Well, not sure it works, if the input is the array.

i.e.
var input =[100,3122,700,12,0,0,0,0,0];
.... (1+1/Math.exp((0.007241739425808191+0.07042734324932098*(input)+0.14556755125522614*(input)

I removed the input['0']||0, etc. and replaced with just input.
The function no longer works..., so it must be the array value at the index, not the entire array?
