### ISSUE TITLE
Python not detected!

### ISSUE THREAD

**Issue by naeem1098** [BrainJS/brain.js#471]
![A GIF or MEME to give some spice of the internet](URL)

## I have installed python 3.7 but when I do the npm i brain.js it gives this error "Can't find Python executable "python", you can set the PYTHON env variable."  and abort the installation. However, python is running in my terminal successfully.  

##This happened on Windows 10 1903, power shell.

## Tell me what to do to resolve the issue?

##5

## Other Comments

**Comment by mubaidr** [comment]
you need to install `python 2.7`. For more information please visit: https://github.com/BrainJS/brain.js#system-dependencies

**Comment by naeem1098** [comment]
I've Installed Python 2.7

**Comment by robertleeplummerjr** [comment]
Python is a dependency of https://github.com/stackgl/headless-gl, please see their installation instructions.  If you have an issue installing, please raise it there.
