### ISSUE TITLE
Is there a Self Organizing Network Like Hopfield in Brain.js?

### ISSUE THREAD

**Issue by tonyc770** [BrainJS/brain.js#474]
I'd like to utilize something like a Hopfield SOM in javascript.
Is there something available in Brain.js or other javascript library?

**Comment by robertleeplummerjr** [comment]
>I'd like to utilize something like a Hopfield SOM in javascript.

That'd be amazing!

> Is there something available in Brain.js or other javascript library?

Not in brain.js.  https://www.npmjs.com/package/encog may have a Hopfield netowrk.
