### ISSUE TITLE
Advice needed train an object of strings ?

### ISSUE THREAD

**Issue by yonjuukyuu** [BrainJS/brain.js#477]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
Hi there need an advice on how to achieve this, i got alot of data of clients sign in and signout, age, location, as well the frequency they use my product i wanted to test if i could predict whenever a new client as a high probability of signing out based on they frequency most likely and dates of sign in sign out, is something like this possible with brain.js ? 

## Other Comments

**Comment by vorticalbox** [comment]
do you have an example of the data? take a look at https://github.com/BrainJS/brain.js/blob/master/examples/javascript/predict-numbers.js
