### ISSUE TITLE
Slow learning despite providing a lot of training data / advice on data given

### ISSUE THREAD

**Issue by sts-ryan-holton** [BrainJS/brain.js#478]
## *What* is wrong?

I'm currently developing a simple javascript system using Brain JS to detect a bunch of values provided from various inputs by a user to detect whether they're likely to be able to afford a loan based on loan amount, repayment term and job details.

I'm starting with detecting a user's take home pay, it's going to be an input where a user can type their monthly take home page, e.g: £1,500

Based on sample training data, I'm trying to train the Brain to figure out whether the take home pay provided is acceptable, or not, the probability more like. I've put together some training data, and tried running it in the browser, the training appears very slow, and doesn't always return the correct results, I'm getting error thresholds around `0.015` and ideally need to return a correct result within around 30 seconds, I've tried using `toJSON` but I can't see any files being made, or anything in the browser storage that indicates this is working?

#### Deliverables:

- Need advice on my training data provided, or how to make it easier to train.
- Why doesn't the toJSON` appear to be doing anything?
- Ideally need to return a probability integer

## *Where* does it happen?

In the a NeuralNetwork when trying to run a net in Google Chrome on my Mac, I also sometimes cannot open the chrome browser dev tools/inspector because it appears to cause the computer to run extremely slowly? How could I improve this.

## *How* do we replicate the issue?

1. Load: https://codepen.io/sts-ryan-holton/pen/MWWPOWe
2. Open browser console (inspect element)
3. Wait 3 seconds, console should say: "starting..."
4. training will begin slowly, and won't return accurate value quickly.

## *How* important is this (1-5)?
4

## Expected behavior (i.e. solution)

I've provided a lot of data in the data sample, using the correct format, I've tried running this for 15 minutes, reloaded the browser and tried another 15 minutes, it doesn't seem to be learning `user has salary 400` when there's plenty of data provided.

## Other Comments

I'm new to Brain JS and this is my first attempt, not too sure the best way to structure data, or format, the end result likely will have possibly 5 user inputs, and a button that once clicked will pass values into `net.run()`

**Comment by vorticalbox** [comment]
you really should use a neural network for this.

using the data you provided (add a few more accept numbers)

```javascript
const rawData  =[
    { input: [803], output: { "prevent": 1 } },
    { input: [1056], output: { "prevent": 1 } },
    { input: [713], output: { "prevent": 1 } },
    { input: [0], output: { "prevent": 1 } },
    { input: [1188], output: { "prevent": 1 } },
    { input: [713], output: { "prevent": 1 } },
    { input: [624], output: { "prevent": 1 } },
    { input: [1188], output: { "prevent": 1 } },
    { input: [624], output: { "prevent": 1 } },
    { input: [713], output: { "prevent": 1 } },
    { input: [803], output: { "prevent": 1 } },
    { input: [1314], output: { "prevent": 1 } },
    { input: [713], output: { "prevent": 1 } },
    { input: [1353], output: { "prevent": 1 } },
    { input: [1188], output: { "prevent": 1 } },
    { input: [1452], output: { "prevent": 1 } },
    { input: [1314], output: { "prevent": 1 } },
    { input: [1353], output: { "prevent": 1 } },
    { input: [713], output: { "prevent": 1 } },
    { input: [713], output: { "prevent": 1 } },
    { input: [803], output: { "prevent": 1 } },
    { input: [1445], output: { "prevent": 1 } },
    { input: [1452], output: { "prevent": 1 } },
    { input: [1320], output: { "prevent": 1 } },
    { input: [1056], output: { "prevent": 1 } },
    { input: [1188], output: { "prevent": 1 } },
    { input: [924], output: { "prevent": 1 } },
    { input: [1056], output: { "prevent": 1 } },
    { input: [713], output: { "prevent": 1 } },
    { input: [1188], output: { "prevent": 1 } },
    { input: [924], output: { "prevent": 1 } },
    { input: [1495], output: { "prevent": 1 } },
    { input: [1056], output: { "prevent": 1 } },
    { input: [2369], output: { "accept": 1 } },
    { input: [1716], output: { "accept": 1 } },
    { input: [1602], output: { "accept": 1 } },
    { input: [1602], output: { "accept": 1 } },
    { input: [2247], output: { "accept": 1 } },
    { input: [1538], output: { "accept": 1 } },
    { input: [2216], output: { "accept": 1 } },
    { input: [6000], output: { "accept": 1 } },
    { input: [5476], output: { "accept": 1 } },
    { input: [2344], output: { "accept": 1 } },
    { input: [29746], output: { "accept": 1 } },
    { input: [4765], output: { "accept": 1 } },
    { input: [3778], output: { "accept": 1 } },
    { input: [8467], output: { "accept": 1 } },
]

// find the max number to normalize our data 
// NN works better with numbers between 0 and 1
// or pick a number that is probably higher than the max
const maxNumber = rawData.reduce((acc, curr) => curr.input[0] > acc ? curr.input[0] :acc, 0)
const normalise = (n) => n / maxNumber;
const traininData = rawData.map((data) => {
  return {
    input: [normalise(data.input)],
    output: data.output,
  }
})

console.log(traininData)

const brain = require('brain.js');
const net = new brain.NeuralNetwork({ hiddenLayers:[1,2]  })
net.train(traininData, { 
  log: true,
  logPeriod: 1000,
  })
console.log(net.run([normalise(100)])) // { prevent: 1, accept: 3.853681262988573e-12 }
console.log(net.run([normalise(1602)])) // { prevent: 0.00017567739996593446, accept: 0.9998244047164917 }
// a number larger than the max training
console.log(net.run([normalise(50000)])) // { prevent: 3.736487161343227e-11, accept: 1 }
```

the first number '100' gets 100% to prevent
the second gets a 99% accept

and takes around 300 ms to train in node or  ~100ms in FF

https://codepen.io/vorticalbox/pen/yLLrpby
