### ISSUE TITLE
Brain JS causes Google Chrome to become unresponsive

### ISSUE THREAD

**Issue by sts-ryan-holton** [BrainJS/brain.js#479]
## *What* is wrong?

When Brain JS is training, Google Chrome browser tab becomes unresponsive/crashes and only becomes responsive again after training is complete, which could take many minutes.

## *Where* does it happen?

When running in Google Chrome from `index.html` file

## *How* do we replicate the issue?
1. Copy contents from code example into a `*.html` file locally on Macbook: https://codepen.io/sts-ryan-holton/pen/RwweqEX
2. Run in browser

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)

The browser tab should remain responsive during training as deploying Brain JS to a production site could cause the whole browser tab to crash on slower systems.

## Other Comments

**Comment by mubaidr** [comment]
> Training is computationally expensive, so you should try to train the network offline (or on a Worker) and use the toFunction() or toJSON() options to plug the pre-trained network into your website.

There are following ways to avoid this:
- Train offline and then load exported network: https://github.com/BrainJS/brain.js#json
- Use web-workers for training: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by sts-ryan-holton** [comment]
@mubaidr  I've already looked at both parts of the documentation, and have tried using the JSON feature in another issue I've opened and can't see any difference, please provide a code example on how to use this?

**Comment by mubaidr** [comment]
In your case it seems like data is not enough. Network is not able to reach error threshold. Please enable  `log: true` in training option, as specified here: https://github.com/BrainJS/brain.js#training-options
