### ISSUE TITLE
Buffer undefined when using JSON

### ISSUE THREAD

**Issue by sts-ryan-holton** [BrainJS/brain.js#480]
## *What* is wrong?
When loading JSON into Brain JS, I get the following error: `Cannot read property 'buffer' of undefined` despite converting JSON and removing double quotes, my JSON and code follows:

**JSON**

```json
[{"input":"[0,7,1,3]","output":"[0]"},{"input":"[1,0,5,6]","output":"[0]"},{"input":"[0,7,1,3]","output":"[0]"},{"input":"[0,7,1,3]","output":"[0]"},{"input":"[1,4,5,2]","output":"[0]"},{"input":"[1,0,5,6]","output":"[0]"},{"input":"[1,2,6,8]","output":"[0]"},{"input":"[1,7,1,6]","output":"[1]"},{"input":"[1,3,2,0]","output":"[0]"},{"input":"[0,9,2,4]","output":"[0]"},{"input":"[0,8,9,2]","output":"[0]"},{"input":"[1,6,0,2]","output":"[1]"}]
```

**CODE**

```javascript
var allSalaries = JSON.stringify(self.setData.salaries)
var formattedSalaries = allSalaries.replace(/"/g, '');
const netSalary = new brain.NeuralNetwork({hiddenLayers: [3, 4]})
netSalary.train(formattedSalaries, {
  iterations: 20000,
  errorThresh: 0.004,
  log: true,
  logPeriod: 10,
  learningRate: 0.3,
  momentum: 0.1,
  callback: null,
  callbackPeriod: 10,
  timeout: Infinity
})
const outputSalary = netSalary.run([0,5,0,0])
```

## *Where* does it happen?
In the a NeuralNetwork when trying to run a net in node.js on my mac

## *How* do we replicate the issue?
See above code

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
It should be able to read the JSON without having to manually put JSON into brain code

**Comment by mubaidr** [comment]
I think you forgot to `parse` json before feeding it to `brain.js`

```js
var formattedSalaries = JSON.parse(allSalaries.replace(/"/g, ''));
```

**Comment by theoparis** [comment]
I'm having the same problem... with similar data, except its already a json array and is not a string:
[{ input: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0] }]

**Comment by mubaidr** [comment]
^ please share the example code.

**Comment by omniphx** [comment]
Happened to me too but turns out I had a typo: `outputs` instead of `output`
