### ISSUE TITLE
Best practice for Brain JS? Multiple instances or one instance?

### ISSUE THREAD

**Issue by sts-ryan-holton** [BrainJS/brain.js#482]
## *What* is wrong?

I'm looking at building a machine learning system to calculate the probability of X from a front-end form with multiple inputs that a user can interact with, provide values and hit a button. I'm looking at some general advise on how's best to do this, for instance, I have the following inputs:

1. Input A (number)
2. Input B (number)
3. Input C (select)
4. Input D (number)

A user can type a number into each of the **number** fields, and select a number from the select field.

I need Brain JS to be able to calculate all of these and output a probability based on some initial training data. Is it best to use an Array of Objects? (https://github.com/BrainJS/brain.js#data-format) and have one Brain initialisation, or have multiple brain instances on the page, each dealing with each input, and then add them all up at the end and do some javascript to get a probability? An example format I was thinking with the Array of Arrays is like this:

```javascript
const output = net.run({input:[[0,5,0,0], [1,0,0,0], [1,0,0,0], [0,4,0,0]], output:[1]}) // this would output 1 (a high probability, I'd provide training data for additional examples)
``` 

**Or...**

Do I train individual values such as:

```javascript
const output = net.run({input:[0,5,0,0], output:[1]}) // this would output 1 (a high probability, I'd provide training data for additional examples)
const output1 = net.run({input:[1,0,0,0], output:[0]}) // this would output 1 (a high probability, I'd provide training data for additional examples)
const output2= net.run({input:[1,0,0,0], output:[1]}) // this would output 1 (a high probability, I'd provide training data for additional examples)
const output3 = net.run({input:[0,4,0,0], output:[1]}) // this would output 1 (a high probability, I'd provide training data for additional examples)

// then add all of the outputs and divide by 4 to get a probability.
```

**Comment by vorticalbox** [comment]
I would use the first example, all 4 as inputs.
