### ISSUE TITLE
Brain JS float output isn't always consistent when running net.run()

### ISSUE THREAD

**Issue by sts-ryan-holton** [BrainJS/brain.js#483]
## *What* is wrong?

Training results sometimes return the opposite float result when training. For instance, take the following training data:

```javascript
// init Training Pattern
const net = new brain.NeuralNetwork({hiddenLayers: [3, 4]})

const trainingData = [
  { input: [0.5000, 0.01], output: [0] }, // Loan, Term
  { input: [0.5000, 0.06], output: [0] }, // Loan, Term
  { input: [0.5000, 0.07], output: [1] }, // Loan, Term
  { input: [0.5000, 0.18], output: [1] }, // Loan, Term
  { input: [0.5000, 0.24], output: [1] }, // Loan, Term
  { input: [0.5000, 0.36], output: [1] }, // Loan, Term
  { input: [0.5000, 0.48], output: [0] }, // Loan, Term
  { input: [0.5000, 0.52], output: [0] }, // Loan, Term
  { input: [0.5000, 0.60], output: [0] } // Loan, Term
]

net.train(trainingData, {
  log: true
})

console.log(net.run([0.5000, 0.18]))
```

The above will return mostly: `0.99`, but sometimes returns `0.67`, this would cause the system I'm building to be inaccurate. Is there anyway to ensure it returns `0.99` more consistently as the output has `1` linked to this?

## *Where* does it happen?

I'm training the network on a Node JS script running in the terminal on my Macbook Pro.

## *How* do we replicate the issue?

I'm using Node JS version: 10.15.3 and NPM version: 6.4.1

Create a node JS script with the following, use NPM to install:

**your-script.js**

```javascript
const brain = require('brain.js')

// init Training Pattern
const net = new brain.NeuralNetwork({hiddenLayers: [3, 4]})

const trainingData = [
  { input: [0.5000, 0.01], output: [0] }, // Loan, Term
  { input: [0.5000, 0.06], output: [0] }, // Loan, Term
  { input: [0.5000, 0.07], output: [1] }, // Loan, Term
  { input: [0.5000, 0.18], output: [1] }, // Loan, Term
  { input: [0.5000, 0.24], output: [1] }, // Loan, Term
  { input: [0.5000, 0.36], output: [1] }, // Loan, Term
  { input: [0.5000, 0.48], output: [0] }, // Loan, Term
  { input: [0.5000, 0.52], output: [0] }, // Loan, Term
  { input: [0.5000, 0.60], output: [0] } // Loan, Term
]

net.train(trainingData, {
  log: true
})

console.log(net.run([0.5000, 0.18]))
```

And then run `node your-script.js` in the terminal

## *How* important is this (1-5)?

5

## Expected behavior (i.e. solution)

I should be seeing **more** of the expected output rather than the complete opposite float value.
I shouldn't be seeing a float with the value of: `0.67` in the above example, it should ideally be above `0.80` at least?

## Other Comments

I'm yet to add more data to my training and `net.run()` and would like to ensure I'm creating something that follows best practice with Brain JS

**Comment by vorticalbox** [comment]
Your hidden layers aren't optimal, you have 2 inputs and 1 output. changing them to

```
new brain.NeuralNetwork({hiddenLayers: [2, 1]})
```

returns 0.69 - 0.67 consistently for me for your given input

**Comment by sts-ryan-holton** [comment]
@vorticalbox I'll give this a go, thanks :+1:  I'm new to this package, and find the documentation a little technical despite me being a technical person haha! https://github.com/BrainJS/brain.js#options
