### ISSUE TITLE
Time series analysis

### ISSUE THREAD

**Issue by iGureEV** [BrainJS/brain.js#485]
Hello!

Is the library capable of solving the following problem (computational problem)?

Given daily data (x1, x2, x3), data on decades (x4) and once given data (x5, x6). Data are collected for the half year. At the end of the half-year, Y1 is obtained. Collected data for several years.

An example is a hotel. Guests pay daily (rooms of different sizes-different fee - x1, x2). Daily wages are charged to employees - x3. Food and water are purchased every ten days - x4. Every six months, utility bills are paid, repairs are made - x5, x6 (for simplicity, we believe that this happens at the beginning of the interval). Every six months a financial report is made and the profit is calculated - y1.

The problem is that me need to predict y1 before the end of the half-year on an arbitrary day.

PS
I'm leaning towards LSTM. And I hope that all data can be reduced to a minimum interval (day, in this example) - consider all X daily. But I can't figure out how to submit numerical data to the network.

And Yes-I do not need to classify the input data, and short-circuit them in the network...

![Screenshot_506](https://user-images.githubusercontent.com/35802704/69607689-d9686f80-1036-11ea-84af-1a432bfda090.png)

Original:

Здравствуйте!

Способна ли библиотека решить следующую задачу (вычислительную задачу)?

Даны ежедневные данные (x1,x2,x3), данные по декадам (x4) и единожды заданные данные (x5, x6). Данные собираются за полугодие. В конце полугодия получается y1. Собраны данные за несколько лет.

Пример - гостиница. Постояльцы платят ежедневно (номера разного размера - плата разная - x1, x2). Ежедневно начисляется заработная плата работникам - x3. Раз в десять дней закупаются продукты питания и вода - x4. Раз в полгода оплачиваются коммунальные счета, делается ремонт - x5, x6 (для упрощения считаем, что это происходит в начале интервала). Раз в полгода делается финансовый отчет и вычисляется прибыль - y1.

Проблема в том что нужно предсказать y1 до окончания полугодия в произвольный день.

П.С.
Я склоняюсь к LSTM. И надеюсь, что все данные можно свести к минимальному интервалу (день, в данном примере) - считать все X ежедневными. Но у меня не получается понять как подать числовые данные в сеть.

И да - мне нужно не классифицировать входные данные, а обсчитывать их в сети...

**Comment by robertleeplummerjr** [comment]
Do you have more than 1 years previous history to go off of?

**Comment by iGureEV** [comment]
Yes, there are data for 4 years, for several objects.

**Comment by robertleeplummerjr** [comment]
My gut says to simply create a time series neural network for every different type of data needed.

**Comment by iGureEV** [comment]
I do not understand how to do it...

**Comment by vorticalbox** [comment]
@iGureEV do you have an example of your data? I'm finding it hard to work out what data you're trying to train with.

**Comment by iGureEV** [comment]
Example

> {
>     2018_1: { ... },
>     2018_2: { ... },
>     2019_1: {
>         rent1: [19200,19200,19200,19200,12000,12000,7200,15600,15600,7200,7200,8400,7200,8400,8400,8400,10800,21600,21600,21600,21600,19200,15600,7200,7200,8400,7200,8400],
>         rent2: [19800,18000,18000,18000,14400,12600,12600,12600,14400,14400,14400,9000,18000,18000,18000,19800,19800,12600,18000,18000,18000,14400,14400,14400,14400,14400,14400,14400],
>         salary: [-9000,-9000,-9000,-9000,-8400,-8400,-7700,-8400,-8400,-7700,-7700,-7700,-7700,-8000,-8000,-8000,-8400,-8600,-9000,-9000,-9000,-8600,-8600,-7700,-7700,-7700,-7700,-7700],
>         food: [-27743,-32682,-23009.5],
>         repair: [-47000],
>         annuity: [-175000]
>         profitability: 266765.5
>     }
> }

> Input: rent1, rent2, salary, food, repair, annuity
> Output: profitability 

If bring the data to a one-dimensional form - network (brain.NeuralNetwork) performs calculations. But only at the end of the period. A forecast is required at any time of the period. Data dimensions can vary - leap year, unexpected repairs, employee bonuses, spoiled products, etc. I think that requires network with memory. But I do not understand how to transfer even simpler sets of sequences into it.

Perhaps it will be more understandable another example: forecasting yields: ezhednenye weather data, fertilization before sowing, treatment against pests, etc. the Essence is that it varies long perodov to obtain the result, and the data themselves have different frequency. The principle is the same.

**Comment by iGureEV** [comment]
Is it possible to train a neural network at least on data with the same period and predict the result on an incomplete period?

**Comment by iGureEV** [comment]
Is it possible to solve this problem at all with the help of this library or not?
