### ISSUE TITLE
Can't import the library?

### ISSUE THREAD

**Issue by MarbleRunnerGame** [BrainJS/brain.js#486]
## *What* is wrong?

I do not know how to `require` the package.

## *Where* does it happen?
At the beginning of my code

## *How* do we replicate the issue?
Try to add `require('brain.js');` in your code.

## *How* important is this (1-5)?
5 because I can't even use it.

## Expected behavior (i.e. solution)

`require('brain.js');` should have imported the package, but it did not.

**Comment by vorticalbox** [comment]
require is a feature on nodejs so you'll have to install nodejs on your machine and start with 

```javascript
node filename.js
```

or if you wish to use it in the browser

```
    <script src="https://unpkg.com/brain.js"></script>
```

where you can simply use this in your javascript/HTML file

```
const net = new brain.NeuralNetwork({hiddenLayers:[1,2] })
```

**Comment by AteurGames** [comment]
> require is a feature on nodejs so you'll have to install nodejs on your machine and start with
> 
> ```js
> node filename.js
> ```
> 
> or if you wish to use it in the browser
> 
> ```
>     <script src="https://unpkg.com/brain.js"></script>
> ```
> 
> where you can simply use this in your javascript/HTML file
> 
> ```
> const net = new brain.NeuralNetwork({hiddenLayers:[1,2] })
> ```

You did not even answer my question. I had nodejs installed, and apparently the answer was `require('brain')`.

**Comment by Fuchsium** [comment]
Sorry, what I meant was what string is used to import the library, since `require();` was never used in the docs or anything. I had nodejs installed already. Turns out it was `require('brain');`.

Edit: this is an alt
