### ISSUE TITLE
fromJSON not working on CrossValidate when timeout is Infinity

### ISSUE THREAD

**Issue by redsoul** [BrainJS/brain.js#490]
## *What* is wrong?
fromJSON not works whens load a network from file
This happens because of the JSON.stringify doesn't support Infinity values

## *Where* does it happen?
Using Cross validation, loading a model from JSON

## *How* do we replicate the issue?
```
const brain = require ('brain.js');
const fs = require ('fs');
const mnist = require ('mnist');

let set = mnist.set (10000, 0);
let trainingData = set.training;
const netOptions = {
  hiddenLayers: [20],
};
const trainingOptions = {
  iterations: 20,
  log: true,
  timeout: Infinity,
};

const crossValidate = new brain.CrossValidate (brain.NeuralNetwork, netOptions);

fs.readFile ('mnist.json', (err, mnistJSON) => {
  if (!mnistJSON) {
    crossValidate.train (trainingData, trainingOptions, 10);
    net = crossValidate.toNeuralNetwork ();
  } else {
    net = crossValidate.fromJSON (JSON.parse (mnistJSON));
  }

  console.log (net.run (mnist[5].get ()));

  fs.writeFile (
    'mnist.json',
    JSON.stringify (crossValidate.toJSON ()),
    err => {
      if (err) throw err;
      console.log ('Network saved!');
    }
  );
});
```

## *How* important is this (1-5)?
I consider this a 4 because without the ability to load models, this framework became useless.

### Possible solution:
neural-network.js, line 343
```
updateTrainingOptions (options) {
    const trainDefaults = this.constructor.trainDefaults;
    options.timeout = options.hasOwnProperty ('timeout') &&
       typeof options.timeout === 'number'
       ? options['timeout']
       : trainDefaults['timeout'];

    for (const p in trainDefaults) {
      if (!trainDefaults.hasOwnProperty (p)) continue;
      this.trainOpts[p] = options.hasOwnProperty (p)
        ? options[p]
        : trainDefaults[p];
    }
    this.validateTrainingOptions (this.trainOpts);
    this.setLogMethod (options.log || this.trainOpts.log);
    this.activation = options.activation || this.activation;
  }
```

**Comment by mubaidr** [comment]
Can you please post the error message here?

**Comment by redsoul** [comment]
.../node_modules/brain.js/dist/neural-network.js:407
          throw new Error('[' + p + ', ' + options[p] + '] is out of normal training range, your network will probably not train.');
          ^

Error: [timeout, null] is out of normal training range, your network will probably not train.
    at NeuralNetwork.validateTrainingOptions (.../node_modules/brain.js/dist/neural-network.js:407:17)
    at NeuralNetwork.updateTrainingOptions (.../node_modules/brain.js/dist/neural-network.js:361:12)
    at NeuralNetwork.fromJSON (.../node_modules/brain.js/dist/neural-network.js:1146:14)
    at CrossValidate.fromJSON (.../node_modules/brain.js/dist/cross-validate.js:217:16)
    at .../mnist.js:43:25
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

**Comment by rodrigolive** [comment]
I'm getting the exact same error when exporting to a JSON file. It seems the JSON stringification/parsing process to/from a file is destroying the data somehow, because it works if you just use the "live" object.

**Comment by mubaidr** [comment]
This is fixed in the latest alpha builds. https://github.com/BrainJS/brain.js/blob/master/src/neural-network.js#L375

**Comment by bor8** [comment]
/reopen please

Got the same error or problem in the newest `2.0.0-beta.2`.
