### ISSUE TITLE
Very slow training (100h)

### ISSUE THREAD

**Issue by FabianL1** [BrainJS/brain.js#491]
## *What* is wrong?
Training takes super long - roughly 100h

## *Where* does it happen?
In the a NeuralNetwork when trying to run a net in node.js on my mac

## *How* do we replicate the issue?

```
  await getDataSet(type);

  const listings  = await getFilteredListings(type);
  const normalizer = new Normalizer(listings);

  normalizer.setOutputProperties(['runningTime']);
  normalizer.normalize();

  const inputs = normalizer.getBinaryInputDataset();
  const outputs = normalizer.getBinaryOutputDataset();
  const metadata = normalizer.getDatasetMetaData();

  fs.writeFileSync(METADATA_FILE[type],JSON.stringify(metadata));

  const trainingData=[];
  for(let i=0;i<inputs.length;i++){
    trainingData.push({input:inputs[i],output:outputs[i]});
  }
  const options={
    hiddenLayers:[180,60],
  };

  const net = new NeuralNetworkGPU(
    options
  );

  net.train(trainingData,{
    iterations: 60000, // the maximum times to iterate the training data --> number greater than 0
    errorThresh: 0.001, // the acceptable error percentage from training data --> number between 0 and 1
    log:true,
  });
```

Data has 13 Features and roughly 100MB data (60k items)

## *How* important is this (1-5)?
4

## Expected behavior (i.e. solution)
I would expect that this runs faster - even with CPU on Mac. Tried an amazon GPU instance - same. It is very very slow. Am I expecting too much of brain.js? What can this library handle?

**Comment by robertleeplummerjr** [comment]
Does it run any faster using just the CPU version?

**Comment by FabianL1** [comment]
Unfortunately not. Both versions are very slow. Is this too big for this library?

**Comment by robertleeplummerjr** [comment]
I think I'd look into Cross Validation: https://github.com/BrainJS/brain.js#cross-validation, perhaps it is that your network is not learning the right principles.  It can take longer to train in some cases, but usually it cuts down on fragility.  Also:

>Data has 13 Features

You have a network configured for `hiddenLayers:[180,60],`, that sounds like the network is far larger than it needs to be, if 13 features are the input neuron count.  180 and 60 are far higher than I generally see that would be advantageous for such a small amount of input data.

**Comment by FabianL1** [comment]
True - but the input data has no strong correlation (did research before which features to put in). If I make it smaller (hidden layers) it will not reduce error rate at certain point (0.1). 
So figure this by try and compare. But I will try with a smaller one again to see if this goes faster and maybe also error goes down.
But still - is this generally such a "big" network that it can not be handled? I saw the once from tf with much more units in the hidden layers (image recognition).

**Comment by robertleeplummerjr** [comment]
It should handle this input size fine, and even the size of network, I'm more referring to the amount of data: 100MB.  I'm not sure iterating on any neural network is going to be amazingly fast with that amount of small-ish data.

**Comment by FabianL1** [comment]
Ok ya true. Sorry 100MB is not really correct. 100MB is the size before filtering. After filtering I can not really say. 13 Features - 50k objects - everything binary. Should be okish right?

**Comment by robertleeplummerjr** [comment]
Yea, that seems ok.  Would there be a way to possibly get more detail about the background of the system?  I'd really like to see the implementation and even run a profiler on it to get more insight as to why it is so slow.  If you are interested, you can reach out to me via gmail of the same handle.  We'll make sure to post findings here as well.

**Comment by FabianL1** [comment]
Great - yes will do that in the next 2 days. Appreciate your great help!:)

**Comment by mubaidr** [comment]
Closing until more information is provided.
