### ISSUE TITLE
[Question] append to training data while training

### ISSUE THREAD

**Issue by TadaWasRaped** [BrainJS/brain.js#496]
![A GIF or MEME to give some spice of the internet](https://cdn.discordapp.com/attachments/662025184756367370/662647319862181918/fluf.gif)

Is there any way to append to the training data while its training?

**Comment by Dimaskao** [comment]
As far as I know, no.  If you want to add something, you need to add data to the array and re-train it

**Comment by mubaidr** [comment]
^ This or you can load a trained network and pass new data.
