### ISSUE TITLE
How to save a trained neural network?

### ISSUE THREAD

**Issue by Dimaskao** [BrainJS/brain.js#497]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?

I have a code that recognizes the numbers in the photo. Each time brain.js starts, it takes a very long time to learn. Is it possible to separately train brain.js and then just connect it?
## *How* important is this (1-5)?

3
## Expected behavior (i.e. solution)

It would be nice if someone helped write the code or left useful links

## Other Comments

**Comment by robertleeplummerjr** [comment]
You just need to serialize to json and deserialize from it: https://github.com/BrainJS/brain.js#json

To safe the json to a file, for example, you'd just need to use `const contents = JSON.stringify(json);`
