### ISSUE TITLE
Which Neural Network for a *simple* image recognition?

### ISSUE THREAD

**Issue by ashah888** [BrainJS/brain.js#499]
I'm trying to do a very very very very simple image recognition machine learning model using Brain.js.

I understand CNN is the best way to go for image recognition but Brain.js doesn't offer that option.

So what is the correct neural network I should use to do a *very simple* image recognition in Brian.js?

Also, while the images will be extremely simple, there will be many outputs.

**Comment by mubaidr** [comment]
It has been discussed in detail in this thread: https://github.com/BrainJS/brain.js/issues/176#issuecomment-377196357

Use `new brain.recurrent.RNN()` and feed pixel data to the network. e.g. 
```
[ { input: [ 1, 0, 0, 0 ], output: { 'a': 1} },
  { input: [ 0, 1, 0, 0 ], output: { 'b': 1 } },
  { input: [ 0, 0, 1, 0 ], output: { 'c': 1 } },
  { input: [ 0, 0, 0, 1 ], output: { 'd': 1 } } ]
```

Newer versions will have an option to directly input images.

**Comment by robertleeplummerjr** [comment]
@ashah888 and @mubaidr, it is not advisable to use `new brain.recurrent.RNN()`, but rather `new `brain.NeuralNetwork()` for the time being.  If you wanted to use a recurrent network, `new brain.recurrent.LSTM()`.  `new brain.recurrent.RNN()`, as all vanilla RNN's do, suffers from exploding or disappearing gradient.

Also a recurrent network only is able to output what it inputs, so if you wanted to recognize an image, you'd be outputting... an image, or something similar to an image.

>I understand CNN is the best way to go for image recognition but Brain.js doesn't offer that option.

I'm hard at work on the CNN components, which is a complement to the feedforward networks, of which `brain.NeuralNetwork` is.  When it is done, it will be available to use with `brain.FeedForward`, which will be for composing custom networks.
