### ISSUE TITLE
when I get new information, do i only provide that to the .train method? Or do i use the entire dataset

### ISSUE THREAD

**Issue by ELI7VH** [BrainJS/brain.js#500]
## *What* is wrong?
when I get new information, do i only provide that to the .train method? Or do i use the entire dataset?

if i give it the entire dataset again it only takes 1 iteration, if i give it the entire dataset plus 1 iteration, the same thing happens. in both cases, it changes the error very slightly

## Expected behavior (i.e. solution)
when I give my nn the entire dataset again, i expect it to use it like a fresh training, instead it shows only 1 iteration and a slightly lower error level.

## Other Comments

**Comment by robertleeplummerjr** [comment]
The entire data set plus the new data.

**Comment by ELI7VH** [comment]
Thank you for your reply @robertleeplummerjr! and great tool you've made here!

Just for clarity
```js
net.train(sql('select * from datasets'))
// record gets added
net.train(sql('select * from datasets'))
```

is this correct?

**Comment by mubaidr** [comment]
For more information. You can export trained network to json and then later when you hve new data just load the network and train with only new data. https://github.com/BrainJS/brain.js/issues/455#issuecomment-538223488

If you don't want to export/load network then you have to pass whole data set (containing both old and new)

**Comment by ELI7VH** [comment]
@mubaidr thanks, I understand how to load trainings from json... that's not really the question.

can you please clarify? 

is this accurate?
```js
net.train([3 records])
// 2 new records are created
net.train([2 records]) // only new records NOT including 3 records in the previous "train"
```

**Comment by ELI7VH** [comment]
after some experimentation it looks like the answer is use ALL the datasets, even on a trained model. always use the entire dataset. 

so:

```js
net.train([10 records])
// 3 new records are created
net.train([13 records]) // use the entire dataset every time to train.
```

**Comment by robertleeplummerjr** [comment]
>You can export trained network to json and then later when you hve new data just load the network and train with only new data.

This isn't really safe as it will start to have a bias towards the new information.  The safest means is as was stated by @ELI7VH:

>after some experimentation it looks like the answer is use ALL the datasets
