### ISSUE TITLE
Does Adding Data Build on Training?

### ISSUE THREAD

**Issue by keithkelly31** [BrainJS/brain.js#504]
I was wondering if I train a network using an initial data set and save the network to JSON.  Can I load the network from JSON then train the network using only new data and save that result to JSON?  Will the network after the new training be only the result of the new data or will it build on the previously trained network? 

I have researched this question, but have found answers that are out of date or didn't clearly answer my question.

**Comment by robertleeplummerjr** [comment]
You need to include all the data each time you train for it not to start being overfit for the new data.
