### ISSUE TITLE
brain.js locks up computer.

### ISSUE THREAD

**Issue by solarai** [BrainJS/brain.js#506]
![a gif to make life better.](https://media1.giphy.com/media/oVtYtD1k0SSDivz4rS/giphy.gif)

## *What* is wrong?
When I run the learn-math.js example, it locks up the browser, because it's training. Other scripts stop working, and sometimes chrome pulls up a 'Page not responding', even though in the console it is working.

## *Where* does it happen?
It happens while I'm training the Neural Network.

## *How* do we replicate the issue?
Just fork the math.js example, and run it. You will notice that it locks up the browser.

## *How* important is this?
I think a 4? It's not like 'brain.js not working', it just interferes with other scripts and the webpage. 

## Expected behaviour.
Maybe a way to train it every other second? Or a way to pause training every *x* milliseconds?

**Comment by robertleeplummerjr** [comment]
This has been solved (in one way) with https://github.com/BrainJS/brain.js#async-training, though this method has not yet been added to the recurrent neural network.  Let me know if that doesn't solve your problem.
