### ISSUE TITLE
Question about LSTM and sentiment detection

### ISSUE THREAD

**Issue by ashah888** [BrainJS/brain.js#511]
Sorry I'm new to Machine Learning.

I noticed when i follow the LSTM sentiment detection tutorial, the output is often empty or strange broken words when the input is something that is different from one of the trained inputs.

Why is that the case and is there no way to avoid this issue? Can't the model just return the closest match if it's not sure?

**Comment by robertleeplummerjr** [comment]
The issue template is there to help us help you.  Here it is in case you missed it.

<img width="638" alt="Screen Shot 2020-02-25 at 6 23 48 AM" src="https://user-images.githubusercontent.com/679099/75243412-dac14980-5797-11ea-8ac4-e2e318572515.png">

**Comment by robertleeplummerjr** [comment]
>I noticed when i follow the LSTM sentiment detection tutorial

What tutorial, where?

>the output is often empty or strange broken words

Which output?  How do we reproduce?

>Why is that the case and is there no way to avoid this issue?

Without knowing what we're debugging, answering this question is next to impossible.
