### ISSUE TITLE
Empty ouput with recurrent.LSTM()

### ISSUE THREAD

**Issue by lucydjo** [BrainJS/brain.js#513]
![A GIF or MEME to give some spice of the internet](https://media1.giphy.com/media/J2D7HjS6sOsnjSadcA/giphy.gif?cid=790b7611cd4ffa87499be474299c2d9f5e0b577620ddca8d&rid=giphy.gif)

Hi !
## *What* is wrong?
The output is empty every time, i have try with 
> net.maxPredictionLength = 1000000000

Output is empty, or it's a result like this:  _e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e  e e_  

Train json format : https://gist.github.com/lucaspojo/09ada4e48a06ecaafb0f7c6281da8905
```
function train(data) {
  // create configuration for training
  const config = {
    iterations: 5,
    log: true,
    logPeriod: 1,
    layers: [10]
  };
  const network = new brain.recurrent.LSTM();
  network.train(data, config);
  const json = network.toJSON()

  global_network = network;

  fs.writeFile('train.json', JSON.stringify(json), function (err) {
    if (err) return console.log(err);
    console.log('## IA TRAINING SAVED TO train.json ##');
  });
}
```
and for "run"
```
const BRAIN_json = JSON.parse(fs.readFileSync('train.json'))
const network = new brain.recurrent.LSTM();
network.fromJSON(BRAIN_json);
network.maxPredictionLength = 100 / 10000/ 1000000 / 10000 ect...;
 const output = network.run(text);
```

## *How* important is this (1-5)?
3

Thx for helping !

**Comment by robertleeplummerjr** [comment]
Unable to reproduce with data set referenced.  Please feel free to re-open if you can give us a means of reproduction.
