### ISSUE TITLE
LSTMTimeStep network error rate is unexpected NaN

### ISSUE THREAD

**Issue by ashah888** [BrainJS/brain.js#517]
## *What* is wrong?
LSTMTimeStep returns error "network error rate is unexpected NaN"

## *Where* does it happen?
Node JS

## *How* do we replicate the issue?
Copy and paste this "example code" from the git README

```
const net = new brain.recurrent.LSTMTimeStep({
  inputSize: 2,
  hiddenLayers: [10],
  outputSize: 2,
})

net.train([[1, 3], [2, 2], [3, 1]])

const output = net.run([[1, 3], [2, 2]]); // [3, 1]

```

Execute this code, you will get an error.

## *How* important is this (1-5)?
5 ... Why is the example code in README failing????

## Expected behavior (i.e. solution)
It should work, as written in the README example.

## Other Comments

**Comment by robertleeplummerjr** [comment]
This now works fine.  Here is an example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-356
