### ISSUE TITLE
Training model with output values being greater than 1 returns a result of less than 1

### ISSUE THREAD

**Issue by matthewdowns** [BrainJS/brain.js#518]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?

If I train a network with various inputs and the outputs are all above `1`, then `net.run(...)` returns some decimal number starting with 0.99999...

## *Where* does it happen?

When I try to train a neural network with the given outputs being [3,4,5,6]

## *How* do we replicate the issue?

```js
const net = new NeuralNetwork();
net.train([
    {
        input: [1,2,3,4,5],
        ouptut: [3]
    },
    {
        input: [2,3,4,5,6],
        ouptut: [4]
    },
    {
        input: [3,4,5,6,7],
        ouptut: [5]
    },
    {
        input: [4,5,6,7,8],
        ouptut: [6]
    },
]);
console.log(net.run([2,3,4,5,6])); // returns [0.999999994634693241234...]
```

## *How* important is this (1-5)?

4

## Expected behavior (i.e. solution)

I expected it to return [4], or something close to 4...

## Other Comments

**Comment by robertleeplummerjr** [comment]
Sigmoid (the default activation for `NeuralNetwork`) only supports outputs of 0 to 1.  You'll need to use a different activation method, or normalize to between 0 and 1.  This is standard practice with neural networks.

Working normalize/denormalize example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-518

**Comment by robertleeplummerjr** [comment]
Here is a leaky-relu example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-518-leaky-relu

**Comment by jastine-mkiramweni** [comment]
Oh dear, brain.js doesn't have a linear activation function, so it will be difficult for you to predict numbers, especially those below -1 or above 1.
