### ISSUE TITLE
Confusion about delta time - can I reset it somehow?

### ISSUE THREAD

**Issue by ErikLarsson82** [BrainJS/brain.js#520]
## *What* is wrong?
Very confused about delta time and re-creating the network vs. restarting the application.

## *Where* does it happen?
I'm training a network and saving the result to a JSON file. I restart the program, detect that I have a JSON file on disc and load that instead of creating a new network. During training I gather some data and train, repeating this gathering and training many times during the lifecycle of the program.
I understand that some parameters depend on delta time, for example learning rate.

```
net = new brain.NeuralNetwork(myConfig).fromJSON(myJson)
net.train(someData, config)
saveJson(net.toJSON())
//... some time passes
net = new brain.NeuralNetwork(myConfig).fromJSON(myJson)
net.train(someData, config) //                     <------ this time the learning rate will be decreased

```
However, if i restart the program, the training starts with high learning rate and there will be lots of activity in the training.

How can i **force** this reset while the program is still running?

## *How* do we replicate the issue?
Not sure. Very specific conditions (see above)

## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)
I expect the same behaviour from delta time when loading a new node program with a JSON file as the behaviour then creating a new network instance from a JSON file in an already running program.

**Comment by robertleeplummerjr** [comment]
You could do this with smaller sized `iterations`, and manage the training lifecycle yourself and simply call `.train()` for shorter bursts.
