### ISSUE TITLE
Is the trainAsync method available for LSTM?

### ISSUE THREAD

**Issue by robin-scharf** [BrainJS/brain.js#525]
![Me Sad](https://media.giphy.com/media/9Y5BbDSkSTiY8/giphy.gif)

## *What* is wrong?
trainAsync not available for LSTM?
<img width="576" alt="image" src="https://user-images.githubusercontent.com/13047378/77523919-c94a8a80-6e86-11ea-8e96-383327781b6f.png">

## *Where* does it happen?
- macOS v10.15.3
- VScode v1.43.2
- node v12.16.1
- brainjs v2.0.0-alpha.12

## *How* do we replicate the issue?
(1.) 
```
const brain = require('brain.js')
const network = new brain.recurrent.LSTM()
const jsonfileReader = require('jsonfile')

 var mappedTrainingData = await jsonfileReader
    .readFile(trainingDataPath)
    .then(res => {
      console.log('File loaded!')
      console.log('Mapping training data...')
      return res.map(elm => ({
        input: elm.title,
        output: elm.type
      }))
    })
    .then(res => {
      console.log('Mapping completed!')
      return res
    })
    .catch(error =>
      console.error(`ERROR: Error reading training data file: ${error}`)
    )
console.log('Training network...')
network
    .trainAsync(mappedTrainingData)
    .then(res => {
      console.log('Training completed!')
      networkJSON = network.toJSON()
    })
```

## *How* important is this (1-5)?
2

## Expected behavior (i.e. solution)
It would be great if async training is available for the other modes besides NeuralNetwork as well.

**Comment by bdotsamir** [comment]
Hi there. async training for LSTM isnt currently available. I had this issue four months ago and found this PR: https://github.com/BrainJS/brain.js/pull/382. Looks like there hasn't been any activity for quite a while.
To get around this, I was told to use child_processes as worker_threads don't clone the module properly. (See: https://github.com/BrainJS/brain.js/issues/507)

**Comment by mubaidr** [comment]
@jennasisis Please let us know if this can be improved in any way we will look into this matter.

**Comment by saschamander** [comment]
@jennasisis Did you find any solution for this? 

I'm currently struggling with this issue, since you can't require any libraries inside a worker. Tried to pass brain.js as argument but got following error:
`DOMException [DataCloneError]: function activate(weight) {
  return weight > 0 ? weight : 0.01 * weight;
} could not be cloned.`

**Comment by bdotsamir** [comment]
I did yes, I ended up using node.js's built-in child_process module, using the fork method. It looks as if you're in the browser though, so I'm not sure that's an option for you.

**Comment by saschamander** [comment]
@jennasisis
Fortunately I am on node.js :)

I will try it with the child_process-Module.
Thanks for the hint.

**Comment by saschamander** [comment]
@jennasisis 
Thx again, worked like a charm. For anyone working on this here is my code:

**parent.js**
```javascript
exports.retrainAi = (iterations = 100, callback = undefined) => {
	const { fork } = require('child_process')

	const forked = fork('./child.js', [
		iterations.toString(),
	])

	forked.on('message', (msg) => {
		console.log(msg)
	})

	forked.on('exit', function () {
		if (callback) callback()
	})
}
```

**child.js**
```javascript
const fs = require('file-system')
const brain = require('brain.js')

// Get number of iterations from args
let iterations
try {
	iterations = parseInt(process.argv[2]) || 100
} catch (error) {}

try {
	// Init network
	const network = new brain.recurrent.LSTM({})
	// Load training data
	const trainingData = require('./trainingData.json')
	// Train network
	network.train(trainingData, {
		iterations: iterations,
		log: (stats) => process.send(stats),
		logPeriod: 1,
	})
	// Save trained network
	fs.writeFileSync('./trainedNetwork.json', JSON.stringify(network.toJSON()))
} catch (error) {
	// Catch errors
	process.send(error)
} finally {
	// End child process
	process.exit()
}

```

**Comment by robertleeplummerjr** [comment]
Thanks @saschamander for your example.  I've tried several times to get this working in LSTM, without success because of the complexity of the net.  This I think will be a standard feature of both `FeedForward` and `Recurrent` classes when they reach stability.
