### ISSUE TITLE
The right architecture for the prediction program. And the error is - value1.concat is not a function and Cannot read property 'backpropagateIndex' of undefined

### ISSUE THREAD

**Issue by tyt34** [BrainJS/brain.js#529]
![alt text](https://static.irk.ru/media/img/site/gallery/30452/e8d0d70a-aa62-4dc2-ba0c-3d8edeedc2a7_jpg_805x1000_x-False_q85.jpg)

## *What* is wrong?
I don’t know which architecture to choose.
I do not know the ideal input and output for my task. 

## *Where* does it happen?
node 10.15.2
brain.js 2.0.0-alpha.12

## *How* do we replicate the issue?
I have event. It consists of 2 parts. It happens 0 or 1. I would like to predict the result of it. 
_**I made a program with this logic:**_ 
I take last N events. And make an array of them. For example:
1 - 0, 0 (last)
2 - 1, 0
3 - 1, 1
4 - 0, 1
5 - 1, 1
6 - 0, 0

training data:
input (3-6) - [1, 1, 0, 1, 1, 1, 0, 0] , output (2) - [1, 0]
input (2-5) - [1, 0, 1, 1, 0, 1, 1, 1] , output (1) - [0, 0]
question: 
[0, 0, 1, 0, 1, 1, 0, 1]
and I get array [0.88, 0.77]
(I write about this in https://github.com/BrainJS/brain.js/issues/248)
Moreover, I have interesting setting. Long array (_la_), and number of case (_noc_).
_la_ - number events in one array (in my example - 4)
_noc_ - number of arrays in training data (in my example - 2)
Further, I test this program use different _la_ and _noc_. Usually 2 - 9 (I think that 1 is bad idea). And, I test last 11 events and search best setting, which used for predict.

Effectiveness this program sometimes surprises me, sometimes frustrating. With reservations, I would say 60-90%. 

code example

```
  var net1 = new brain.NeuralNetwork();
  var res1 = net1.train(arr1, {
        iterations:   60000,
        errorThresh:  0.0001,
        hiddenLayers: hiddenLayers,
        learningRate: 0.051,
        activation:   "tanh",
  })
```
hiddenLayers - I use default. I could not find anything better than the default.
And I think, if I use high _la_ and _noc_ I must use other errorThresh and iterations. But I nothing change.
Activation -  "tanh", because I test all. "tanh" - The Best.

After I see this https://github.com/BrainJS/brain.js/issues/528
I think use object and add more information about event. But I have problem. 

For example:
```
const brain = require('brain.js');
var obj1 = {xyz: 1, a1: 0, a2: 1}
var obj2 = {xyz: 1, a1: 0, a2: 1}
var obj3 = {xyz: 1, a1: 0, a2: 0}
const trainingData = [obj1,obj2,obj3];
const lstm = new brain.recurrent.LSTM();
const result = lstm.train(trainingData, {
  iterations: 1500,
  log: true,
  errorThresh: 0.011
});
console.log(result);
```
I get:

> ../node_modules/brain.js/src/recurrent/rnn.js:243
    equations[0].backpropagateIndex(0);
                 ^
TypeError: Cannot read property 'backpropagateIndex' of undefined

or

```
const brain = require('brain.js');
var obj1 = {input: {xyz: 1}, output: {a1: 1, a2: 0}}
var obj2 = {input: {xyz: 1}, output: {a1: 0, a2: 0}}
var obj3 = {input: {xyz: 1}, output: {a1: 0, a2: 1}}
const trainingData = [obj1,obj2,obj3];
const lstm = new brain.recurrent.LSTM();
const result = lstm.train(trainingData, {
  iterations: 1500,
  log: true,
  errorThresh: 0.011
});
console.log(result);
```
I get:

> node_modules/brain.js/src/utilities/data-formatter.js:97
>         value1.concat(['stop-input', 'start-output']),
>                ^
> 
> TypeError: value1.concat is not a function

## *How* important is this (1-5)?
5 for me, 0.1 for world

## Expected behavior (i.e. solution)
1) Ideally, I want to use the chain of recent events with the greatest efficiency.

2) Or there would be an opportunity, to receive in the beginning the usual prediction. Then when I find out _xyz_ use his in my program, for greater efficiency. 

3) In short, I want to discover something new.

**Comment by robertleeplummerjr** [comment]
`const lstm = new brain.recurrent.LSTM();`  is usually expecting a string, or something near it that can be converted is all.  It is incompatible with objects.

**Comment by tyt34** [comment]
> `const lstm = new brain.recurrent.LSTM();` is usually expecting a string, or something near it that can be converted is all. It is incompatible with objects.

Is there any possibility to conduct training in two-dimensional arrays?

```
const brain = require('brain.js');
const net = new brain.NeuralNetwork();
net.train([{input: { r: [1,1], g: [1,0] }, output: { b: 1 }}]);
const output = net.run({ r: [0,1], g: [0,1]});
console.log(output); //  { b: NaN }
```
```
const brain = require('brain.js');
const net = new brain.NeuralNetwork();
net.train([{input: {r: [1], g: [1] }, output: { b: 1 }}]);
const output = net.run({r: [0], g: [0]}); 
console.log(output); // { b: 0.91 }
```
```
const brain = require('brain.js');
const net = new brain.NeuralNetwork();
var ar = [1,2,3] 
var obj1 = {input: ar, output: {a:1}}
net.train(obj1);
const output = net.run(ar);
console.log(output); // { a: 0.9 }
```
```
const brain = require('brain.js');
const net = new brain.NeuralNetwork();
var ar = [[1,1], [2,1], [1,3]] // n w
var obj1 = {input: ar, output: {a:1}}
net.train(obj1);
const output = net.run(ar);
console.log(output); // { a: NaN }
```

**Comment by robertleeplummerjr** [comment]
Reproduced, and looking into fix.

**Comment by robertleeplummerjr** [comment]
I just saw my previous response, lol.  Been a bit covered up with work.  It seems you just need to use the LSTMTimeStep network: https://observablehq.com/@robertleeplummerjr/brain-js-issue-529-solution
