### ISSUE TITLE
Could `rowPluck` benefit from vectorization?

### ISSUE THREAD

**Issue by GirkovArpa** [BrainJS/brain.js#533]
![Star Wars Task Manager Meme](https://i.imgur.com/LXWAxte.png)

## *What* is wrong?
99.9% chance nothing is wrong.

## *Where* does it happen?
`src/recurrent/matrix/row-pluck.js`

## *How* important is this (1-5)?
1

## Other Comments

Just wondering if that function `rowPluck` could be vectorized, and if so, benefit from it?

**Comment by robertleeplummerjr** [comment]
It probably could.  Do you want to give it a stab?  Sorry it has taken so long to get back to this.

**Comment by robertleeplummerjr** [comment]
Since this was answered with
>It probably could. 

I'll go ahead and close.
