### ISSUE TITLE
RNN with binary stream data

### ISSUE THREAD

**Issue by hikaru150s** [BrainJS/brain.js#534]
![Credit to awwmemes.com](https://pics.awwmemes.com/found-node-module-on-github-looking-at-theeasy-usage-imgflip-com-65746907.png)

## *What* is wrong?
_To be honest, this is not an **easy** implementation for me (sigh)_

So, I've managed to build a pipeline between a Readable Stream as input for my network. Let's say that the input is actually a `Buffer` this time, so basically it's only array of numbers. Trying to run this on RNN but still being implemented (really, tell me when it's done. I'm waiting for it!). For now, I'm running it on Time-step RNN.

So here's the problem:
I'm trying to follow [this example](https://github.com/BrainJS/brain.js/issues/398) but found the source they're talking about is more likely a big JSON file. I made some implementation [here](https://github.com/hikaru150s/rnn-comp) and found about two problems here.

1. My first attempt resulting in a [uncontrolled backpressure state](https://github.com/hikaru150s/rnn-comp/blob/master/src/index.ts#L31-44), and Brain.js said an error about `this.log is not a function` (traced [here](https://github.com/BrainJS/brain.js/blob/master/src/train-stream.js#L86)). The `size` and `count` are in different result due to uncontrolled backpressure.
2. The second attempt is trying to leveraging pipeline by `pipe` the stream directly from `ReadableStream` into neural net. The result was shocking: process immediately exit after stream is closed on second iteration.

## *Where* does it happen?

I'm running the solution in Node v13.11.0 for win32-x64

## *How* do we replicate the issue?

1. Clone [this repo](https://github.com/hikaru150s/rnn-comp)
2. Build typescript using `npx tsc` (you can ignore errors emitted here)
3. Run `node dist/index.js`

## *How* important is this (1-5)?

Importance: 3

## Expected behavior (i.e. solution)

The network expected to train when scripts executed, get `exit` instead.

## Other Comments
Just curious: How do we implement the `pipelines` here? Am I doing something wrong?
Thanks in advance

**Comment by mubaidr** [comment]
You are streaming a zip file to network. Please use `zlib` to stream input data.

**Comment by hikaru150s** [comment]
Pardon me, my example are kind of bad.
The actual file I want to stream is not a zip (nor any content inside zip if you _unzip_ it), but a _real_ binary file. I can't use the real file (due to restriction) so I used a zip file instead.

**Comment by robertleeplummerjr** [comment]
If you can cast it to a Float32Array, then you can probably use it fine.
