### ISSUE TITLE
Advice on building an automated chat bot with Brain JS - large strings

### ISSUE THREAD

**Issue by sts-ryan-holton** [BrainJS/brain.js#535]
## *What* is wrong?

I'm trying to figure out whether Brain JS would be the best approach to build an automated chat bot that can be trained to respond to different queries and how to go about doing it, outputted to a JSON as a trained network and then uploaded to a web server.

My initial thinking is that a user would have an input and would be able to ask questions, they could be string lengths of 100 characters.

## *How* important is this (1-5)?

3

## Expected behavior (i.e. solution)

So this is what I was initially thinking as the input and output format:

```js
{ input: "Hi, are you able to help me?", output: "Of course, what can I assist you with today?" }
```
Now there could be hundreds of these objects for possible inputs that a user could give, and limited outputs, but is this too much for Brain JS in terms of training speed?

**Comment by jedjoud10** [comment]
It would indeed take a lot of time, I know from experience. Tried to do that with a discord bot a while ago, did not turn well. It took so much time (Maybe because of my prehistoric CPU ?) but it would be possible using right settings and good hardware. I think. I hope

**Comment by sts-ryan-holton** [comment]
@jedjoud10 Do you have an example of how you'd go about doing the training? Would it be a case of providing many input and output objects + `net.run('The user input message')` to train? When I did this it seemed like it would've taken 30 mins on an i7 Macbook Pro...

**Comment by mubaidr** [comment]
There are also other issues that can be helpful in this regard, please check: 

https://github.com/BrainJS/brain.js/issues/235
https://github.com/BrainJS/brain.js/issues/217

**Comment by jedjoud10** [comment]
Well first off I tried making it with an LSTM with not that much neurons, but even with only 10 iterations it was tremendously slow. I guess I'm going to have no AI girlfriend then :(

**Comment by mubaidr** [comment]
There is a chatbot framework which uses brain.js under the hood, you might want to look at it. https://github.com/intelligo-systems/intelligo

**Comment by robertleeplummerjr** [comment]
I feel that there was a sufficient answer here and will go ahead and close.

**Comment by unpaid6607** [comment]
https://github.com/DigitalMoleMan/learny
