### ISSUE TITLE
Can't install brain.js correctly

### ISSUE THREAD

**Issue by jedjoud10** [BrainJS/brain.js#538]
![image](https://user-images.githubusercontent.com/34755598/80773272-630cf380-8b27-11ea-8f4a-11169c21530f.png)

## *What* is wrong?
Errors popping up when trying to install brain.js from the VSCode terminal.  When I make a sample .js file with just "const brain = require(brain.js)" it tells me that the module "gpu.js" is missing, so I installed it using "npm i gpu.js", I then reran the program and it tells me that brain.js itself is missing

## *Where* does it happen?
In the VSCode terminal (Though I tried to run it in the CMD and same results), on Windows 10, on my potato laptop
## *How* do we replicate the issue?
- Step 1 : Make a folder
- Step 2 : Install brain.js using "npm i brain.js"
- Step 3 : Errors go exist

## Expected behavior (i.e. solution)
It should've installed brain.js correctly. What I'm more confused about is that I installed it without errors before, so I really don't know why it's weird now
## *How* important is this (1-5)?
5. I mean I can't run brain.js so I guess it's pretty important

## Other Comments
![image](https://user-images.githubusercontent.com/34755598/80773638-7a001580-8b28-11ea-9c23-52617b87aea1.png)

**Comment by rajeshjaga** [comment]
I Have the same problem using npm i brain.js, in the npm log it says 

> verbose exit [1,true]

found a solution 
do ### npm i --package-lock-only
and try npm audit check if its has any error

**Comment by mubaidr** [comment]
You don't need to install `gpu.js` manually. `Brain.js` will install all dependencies itself, just make sure other build dependencies are available. 

This error message indicates that `npm` failed to build `gpu.js`. Please follow instructions here for installation. 
https://github.com/BrainJS/brain.js#Installation-note

and also: 
https://github.com/BrainJS/brain.js/issues/458

Also feel free to reopen this issue, if you need more help. 

P.S. nice meme 😄

**Comment by jedjoud10** [comment]
Yay thanks this worked : Had to install C++ and NodeJs VS Build tools 2019 and run the command from the installation notes and reinstalled brain.js. Thanks !

**Comment by mubaidr** [comment]
Cool, happy coding. Do let us know if we can improve getting started guide.
