### ISSUE TITLE
Question: number[][][] vs number[][]

### ISSUE THREAD

**Issue by amatiash** [BrainJS/brain.js#541]
![what](https://i.giphy.com/media/glmRyiSI3v5E4/giphy-downsized.gif)

**1. What is the difference between:**

```javascript
const trainingData = [[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]]
```
and:

```javascript
const trainingData = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]
```

?

Data is similar to [this example][1]: 

The output is the same:

```javascript
console.log(net.run([[0, 1], [2, 3], [4, 5], [6, 7]])) // => [8, 9]
console.log(net.forecast([[0, 1], [2, 3]], 3))         // => [[4, 5],[6, 7],[8, 9]]
```

**2. What will happen with if you split data this way?**

```javascript
const trainingData = [
  [[0, 1], [2, 3], [4, 5]],
  [[6, 7], [8, 9], [10, 11]]
];
```

Output you get:

```javascript
net.run([[0, 1], [2, 3], [4, 5], [6, 7]]) // => [10, 11]
net.forecast([[0, 1], [2, 3]], 5)         // => [[4, 5], [8, 9], [10, 11], [10, 11], [10, 11]]
```

---

Let me answer my own questions and you will correct me if I'm wrong.

@robertleeplummerjr taught me to think about it in _movie-style._
So:

**1.** Let's represent `[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]` as `'movie'`
Then our data will look like this:

```javascript
const trainingData = ['movie'];
```
and:

```javascript
const trainingData = 'movie'
```

accordingly.

In the first case **we can add** a second one, a third one and so on:

```javascript
const trainingData = ['movie', 'movie2', 'movie3'];
```

With the second case we strictly define that there is **only one** movie.

Let's go on.

**2.** Continuing our though, we replace `[[0, 1], [2, 3], [4, 5]]` with `'The Matrix'` and 
`[[6, 7], [8, 9], [10, 11]]` with `'The Matrix Reloaded'`.

Each movie contains episodes: `[0, 1]`, `[2, 3]` and so on.

So, in case:

```javascript
net.run([[0, 1], [2, 3], [4, 5], [6, 7]]) // => [10, 11]
net.forecast([[0, 1], [2, 3]], 5)         // => [[4, 5], [8, 9], [10, 11], [10, 11], [10, 11]]
```

we ask: _"What will be next episode(s) if we have a single movie with the provided ones?"_
The output we have is, kind of, expected.

I have doubts about 'single movie' to be a correct term, but, probably, the best for this example.

---

What do you think guys?

[1]:https://github.com/BrainJS/brain.js/blob/master/examples/javascript/predict-numbers.js#L11

**Comment by robertleeplummerjr** [comment]
>1. What is the difference between:

This is an array of a single input, which is then fed in 2 at a time before backpropagating that it is finished:
```js
const trainingData = [[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]]
```

This is an array of six inputs, here there really isn't enough information for this to be a recurrent neural network, as you'd only every send in 1 number to get the next (essentially a classification problem):
```js
const trainingData = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]
```
