### ISSUE TITLE
Problem with JS example rendering-svg

### ISSUE THREAD

**Issue by wirtaw** [BrainJS/brain.js#542]
## *What* is wrong?
Doesn't properly work [rendering-svg](https://github.com/BrainJS/brain.js/blob/master/examples/javascript/rendering-svg.html)

## *Where* does it happen?
Then load and click 

## *How* do we replicate the issue?

- Copy html, brain-browser.js
- Load html with form
- Click 

## Expected behavior (i.e. solution)
Empty textarea `inp-labels` (copy all input names solve)

### Browser: 
Chrome  81.0.4044.129 (64-bit)

### Brain.js: 
copy from brain-browser.js [dist](https://github.com/BrainJS/brain.js/tree/master/dist) 

## *How* important is this (1-5)?
1

**Comment by mubaidr** [comment]
Fixed in: https://github.com/BrainJS/brain.js/commit/b5e213e8988eeeab9038c0eb5fb5832d6e7bc486
