### ISSUE TITLE
Training is finished in 1 iteration

### ISSUE THREAD

**Issue by amatiash** [BrainJS/brain.js#546]
![easy](https://i.giphy.com/media/xoDYZmMzdeCmk/giphy-downsized.gif)

## *What* is wrong?
Training is finished in 1 iteration and only with 1 neurone. Tested with a large dataset of 10k rows.

## *Where* does it happen?
In `NeuralNetwork` with non-binary values that are in range from `0` to `1` (`num > 0 && < 1`)

## *How* do we replicate the issue?
Created a pen for this: https://codepen.io/amatiash/pen/MWaGzdW

## Expected behavior (i.e. solution)
Training **process** is expected and error rate to be in the right range.
`net2` is expected to train like `net1` (See the pen above)

### Brain.js: 
`2.0.0-alpha.12` and `1.6.1`

## *How* important is this (1-5)?

4

## Other Comments

From docs:

> ..both of which can be either an array of **numbers from 0 to 1**...

So I don't get the point why there is even a difference?
Please, explain.

Best regards

----------
**Note: `net2` is able to train when you decrease `errorThresh` to a ridiculously small number!**

**Comment by mubaidr** [comment]
Looks good to me. If i increase error threshold, iterations increases. (Even reaches 20000 iterations limit with 0.001 error)

**Comment by amatiash** [comment]
> Looks good to me. If i increase error threshold, iterations increases. (Even reaches 20000 iterations limit with 0.001 error)

Yes, agree. But doesn't this confusing? Why `net2` initiates with such a small `errorThresh`?

**Comment by robertleeplummerjr** [comment]
The error threshold initiates with 1, the random value picked by the net is just too close to the error threshold of 0.08.  Also, that high of error threshold with that high of error rate would probably be completely impractical to achieve good results.  The net is doing exactly what it was built to do in this case.

**Comment by robertleeplummerjr** [comment]
If you must stay with 1 neuron, increase the error rate.  Otherwise, use more neurons/layers.
