### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by Andrew-He** [BrainJS/brain.js#548]
As title said, let me know if it works fine for you.

**Comment by mubaidr** [comment]
This sure will help in code maintenance. 

Here is what we can do:
- Do it in incremental steps. 
- Add `tsconfig`, with `allowjs`
- Transform & commit one by one
- Make sure builds are not broken at any time. 

@Andrew-He Please share if you have any suggestions, so we can prepare to implement this. 
@robertleeplummerjr please

**Comment by robertleeplummerjr** [comment]
@Andrew-He what would be your timeline in helping to achieve this?  Keep in mind [Hofstadter's law](https://en.wikipedia.org/wiki/Hofstadter%27s_law)
@mubaidr Are you currently working on anything in brain?
I've still been overloaded at work, now may be a good time to just rip off the band-aid.

**Comment by mubaidr** [comment]
Cool. I am working on making code compatible with `eslint` config as per upon our hangouts conversation. Should be done soon, then we can move on with this.

**Comment by Andrew-He** [comment]
> @mubaidr Are you currently working on anything in brain?
> I've still been overloaded at work, now may be a good time to just rip off the band-aid.

I 'm a front end guy at work, recently  neural network draws my attentions while preparing intro topic in machine learning to the team, and then I found brain.js, pretty cool project. I have some experience in typescript, so it might help the project in terms of code maintenance. 

> @Andrew-He what would be your timeline in helping to achieve this? Keep in mind [Hofstadter's law](https://en.wikipedia.org/wiki/Hofstadter%27s_law)

I will start off by, as @mubaidr  mentioned,  add tsconfig; then transformed the files one bye one with unit test perhaps.

**Comment by mubaidr** [comment]
@Andrew-He Please wait. I am working on stuff related to `eslint` and `tsconfig`.

**Comment by mubaidr** [comment]
You are welcome to contribute now, please pick any module or portion for convertion. https://github.com/BrainJS/brain.js/pull/550

**Comment by mubaidr** [comment]
Also: https://github.com/BrainJS/brain.js/issues/551
