### ISSUE TITLE
How run train method multiple times for one net?

### ISSUE THREAD

**Issue by Dok11** [BrainJS/brain.js#55]
```
var net = new brain.default.NeuralNetwork();

var iter = 0;
walk.walkSync('./data', function(basedir, filename, stat) {
	var trainingData = require('./data/'+filename);
	
	var trainResult = net.train(
		trainingData, {
			initialization: (iter === 0),
			keepNetworkIntact: (iter > 0)
		}
	);
	
	iter++;
});
```

I expect that this may train nn on different files with trainig data, but in result nn I had nn what trained for first file with trainig data. As if all new runs train not saved, but busy CPU and time.

What I need to do for this?

P.S. I do fs walk because trainig data very large - 2GB.

**Comment by robertleeplummerjr** [comment]
I suspect that the training data is different in each file, ultimately that means that the network needs to change size.

**Comment by Dok11** [comment]
Differed only output. For example

- for file data1.json output for all inputs is {"id123": 1}
- for file data2.json output for all inputs is {"id124": 1}
etc.

So I need set size at initialization of nn?

**Comment by robertleeplummerjr** [comment]
If you were to use `brain.NeuralNetwork` which is the feed forward neural net, iterate through your training data, and find all the different input and output keys.  When you input or output of your sample data has a property, give the training data that value.  When it does not, give it a zero for the missing data.

```js
net.train([{
  input: {
    value1: 1,
    value2: 0
  },
  output: {
    id123: 1,
    id124: 0
  },
  input: {
    value1: 0,
    value2: 1
  },
  output: {
    id123: 0,
    id124: 1
  }
]);
```

Ultimately, I think you found something we can try and improve though.  Very cool, and very common looking, use case.

**Comment by robertleeplummerjr** [comment]
I think the current answer to this, in the way that you are defining networks, it is like asking how to restructure a neural network, after it has already been structured to train it further.  Currently this isn't implemented.
