### ISSUE TITLE
Training begins and ends with no effect

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#554]
![A GIF or MEME to give some spice of the internet](https://external-preview.redd.it/N_bB0Oszfuks9wLTax6viC4Hh9FzHgpMcpYiuUHoQQU.jpg?auto=webp&s=22d6a707521ffee7ea809ec405a10477ee7bd2b8)

## *What* is wrong?

Training begins and ends with no effect, display iterations: 10, training error: 0
## *Where* does it happen?

Browser
## *How* do we replicate the issue?

https://jsfiddle.net/1r0zkwqc/

## Version information
Newest
### Browser: 
Chrome 83

## *How* important is this (1-5)?

3

**Comment by VladyslavLukyanenko** [comment]
```
brain-browser.min.js:16 Uncaught Error: Error compiling vertex shader: null
    at n.value (brain-browser.min.js:16)
    at Function.value (brain-browser.min.js:16)
    at Function.value (brain-browser.min.js:16)
    at Function.value (brain-browser.min.js:16)
    at Function.get (brain-browser.min.js:16)
    at e.value (brain-browser.min.js:16)
    at new e (brain-browser.min.js:16)
    at new a (brain-browser.min.js:225)
    at ?editor_console=:103```

**Comment by Krzysiek-T** [comment]
With NeuralNetwork doesn't work either

**Comment by ghost** [comment]
> ```
> brain-browser.min.js:16 Uncaught Error: Error compiling vertex shader: null
>     at n.value (brain-browser.min.js:16)
>     at Function.value (brain-browser.min.js:16)
>     at Function.value (brain-browser.min.js:16)
>     at Function.value (brain-browser.min.js:16)
>     at Function.get (brain-browser.min.js:16)
>     at e.value (brain-browser.min.js:16)
>     at new e (brain-browser.min.js:16)
>     at new a (brain-browser.min.js:225)
>     at ?editor_console=:103```
> ```

With brain.NeuralNetwork() doesn't work either

**Comment by VladyslavLukyanenko** [comment]
It was a comment for the developers so they can look into it straight away

**Comment by robertleeplummerjr** [comment]
You have at least two problems that need addressed.  The first is in how data is defined:

1. The input is an object with a property of hash, which is an array of numbers
2. The output is an object, with a property that scales from 0 to the count of inputs

Referenced:
```
train_data.push( { input: { hash : hashed_word[0] }, output:{ autor : count++ } } );
```

What you want is an array of numbers, at least for the NeuralNetworkGPU class, for both input and output, and you want these to be scaled from 0 to 1.  This seems to work with reasonable results:
```
train_data.push( { input: hashed_word[0], output:{ autor : [count++ / a.length] } } );
```

I would, however, use caution for the output being just an incremental value that will always be 1 to 1, like you've defined in the example.  Perhaps that is just for helping convey the bug, but that practice will essentially give you overfitting.
