### ISSUE TITLE
doesn't build on OS X

### ISSUE THREAD

**Issue by clive-g-brown** [BrainJS/brain.js#556]
npm install - tries to build gl : fails at 

clang: error: no such file or directory: 'Drive/dev/node/neon_brain/node_modules/gl/deps/include'

there is only a 'windows' folder in gl/deps/

make: *** [Release/obj.target/webgl/src/native/bindings.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/Cellar/node/14.3.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxxxxxxx/dev/node/neon_brain/node_modules/gl
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE

**Comment by lakesare** [comment]
Hm, on `npm install` `2.0.0-beta.1` builds well for me (not everything runs smoothly however, most `__tests__/layer/*` fail).

**Comment by lakesare** [comment]
Ok ok, so it depends on the node version.
**Node 14.6.0** builds, but gives you a couple of warnings (and some tests will fail).   
**Node 8.6.0** builds with less warnings, but tests will immediately fail with `TypeError: _gracefulFs(...).realpathSync.native is not a function`.  
**Node 10.22.0** will build WITHOUT warnings, but some tests will still fail, e.g. `FAIL  __tests__/layer/dropout.js` with something like this:
![image](https://user-images.githubusercontent.com/7578559/89134831-b9803880-d541-11ea-9ebe-d6ac8ddacc4d.png)

@robertleeplummerjr, @mubaidr, hi! Is there some node version that works for you locally (for both the build & tests)?

`Package.json` gives the expected node version at `"node": ">=8.6.x"`, but I don't think that works.

**Comment by mubaidr** [comment]
@lakesare Sorry for inconvenience, tests are not completely done yet. some tests are expected to fail on each node version. 

**_If the `brain.js` installs and builds fine for you, then its all good._** 

We have plans to improve test coverage and quality, but could not manage time yet.

**Comment by Madan-bhat** [comment]
i am also suffering from the same issue

**Comment by Madan-bhat** [comment]
any way anybody has to solve this
