### ISSUE TITLE
Image Detection

### ISSUE THREAD

**Issue by cpgb85** [BrainJS/brain.js#557]
I'm trying to write a simple image detection program with this library. It's a fantastic library, the syntax makes sense unlike most other libraries.  

What is the most simple way to write image detection?  I know i can get the RGB values for an image and pass them in as an array of numbers to brain, but it won't work if the images are different sizes.  Am i missing something?

**Comment by mubaidr** [comment]
Convolution network is not available yet in Brain.js but you can try NeuralNetwork class with the CrossValidator. Please see this for more info: https://github.com/BrainJS/brain.js/issues/352
