### ISSUE TITLE
Problem(?) of leaky ReLU Implementation

### ISSUE THREAD

**Issue by cuteday** [BrainJS/brain.js#560]
## *What* is wrong?

I"m not sure if this is a bug > <\
When I look at the source code in `neural-network.js`, I found the leaky relu is calculated as
`currentOutputs[node] = sum < 0 ? 0 : alpha * sum;` in function `_runInputLeakyRelu(input)`(also in the `calculateDelta`function), But I think by definition it should be
`currentOutputs[node] = sum < 0 ? alpha * sum : sum;`. 
I wonder if this is on purpose or a bug? 

## *How* important is this (1-5)?

2

## Other Comments

Thanks author! I liked this JS framework ^ ^

**Comment by mubaidr** [comment]
Confirmed. Fixed in https://github.com/BrainJS/brain.js/pull/613
