### ISSUE TITLE
Adding Example under the BrainJS examples section

### ISSUE THREAD

**Issue by iSumitBanik** [BrainJS/brain.js#562]
## Cryotherapy Success Rate Prediction using BrainJS 🧠

I have worked on a project which predicts the success rate of Cryotherapy. It uses the UCI Machine Learning dataset and uses the brainJS framework to predict the successful outcome.

 ![](https://img.shields.io/github/languages/code-size/iSumitBanik/Cryotherapy-Success-Rate?style=flat-square) ![](https://img.shields.io/github/languages/top/iSumitBanik/Cryotherapy-Success-Rate?style=flat-square) <br>
I hope this project gets added under the examples section. You can find the project repo [here](https://github.com/iSumitBanik/Cryotherapy-Success-Rate) 

Want to try out this web app? Visit [here](https://cryotherapy.surge.sh/)

Regards,
Sumit Banik

**Comment by mubaidr** [comment]
Added: https://github.com/BrainJS/brain.js/blob/master/README.md#more-examples

**Comment by iSumitBanik** [comment]
Thanks. Is there a different step to get added in examples under the website?

**Comment by mubaidr** [comment]
Its different but very simple. Just add a new example in the list (as others and jsfiddle link maybe). It will be published with the next release. 

https://github.com/BrainJS/brain.js.org/blob/master/src/store.js
