### ISSUE TITLE
Where do I go to read BrainJS news and what's coming next?

### ISSUE THREAD

**Issue by ashah888** [BrainJS/brain.js#563]
Is there a blog or a change log or a list of planned changes or any kind of news that's regularly updated for BrainJS?

**Comment by robertleeplummerjr** [comment]
https://github.com/BrainJS/brain.js/wiki/Roadmap

**Comment by ashah888** [comment]
Don't you think this project **needs** a proper website, blog to offer proper community engagement that it needs to grow and become more legitimate?

**Comment by mubaidr** [comment]
We do have website. But a blog would be nice, but at the time none of the contributors have enough time to post articles. Maybe in the future we will launch a blog.

**Comment by robertleeplummerjr** [comment]
Yes.  Wanna get involved?
