### ISSUE TITLE
How to normalize

### ISSUE THREAD

**Issue by nezzard** [BrainJS/brain.js#565]
Hi, is it possible to normalize dataset of dynamic ids?
Every day It’ll get new ids 1567, 1568, ... so I can’t get final Id.
I thought to normalize like this  100/1567 but don’t know if this correct way

**Comment by drumrock** [comment]
You can take some very large and non-reachable (in practice) ID as "1" and divide all IDs by this value.

For example, 100000000. So you'll be normalizing your real IDs like 1567/10000000.

**Comment by nezzard** [comment]
> You can take some very large and non-reachable (in practice) ID as "1" and divide all IDs by this value.
> 
> For example, 100000000. So you'll be normalizing your real IDs like [1567/10000000](tel:1567/10000000).

Will Brain js work fine in this way?

**Comment by drumrock** [comment]
Depends on definition of "fine" :-)

**Comment by mubaidr** [comment]
If it is an ID if will not be effective in the input. But usually this method works fine. (get large value in data set and divide all values)
