### ISSUE TITLE
It is not possible to save the net as JSON while training!!

### ISSUE THREAD

**Issue by bor8** [BrainJS/brain.js#566]
![Pritty good](https://media.giphy.com/media/3ohhwGwvnyjI6l9bFu/giphy.gif)

## *What* is wrong?

It is not possible to do save the net as JSON while training!!

## *Where* does it happen?

```
fs.writeFileSync('/net.json', JSON.stringify(net.toJSON()));
```

## *How* do we replicate the issue?

```
const stats = net.train(trainingData, config);  // is synchronous
```

## Expected behavior (i.e. solution)

```
Give possibility to save net every now and then while training.
```

## *How* important is this (1-5)?

1 - waiting for async

## Other Comments

Have to do training in another Docker container for async.

**Comment by CatScan-crypt** [comment]
Quite don't understand what you specifically refer to as "net", 
However if you mean "net iterations" then this should help:
___
net.train(trainingData, {
iterations: 45000,
    learningRate: 0.007,
    errorThresh: 0.000001,
     log: (stats) => console.log(stats)
});
___
If you mean "net Weights & Biases" then i don't know any thing 
in brain that deals with prop hoisting of weights and biases.

Hope it helps in anyway 🦾

**Comment by bor8** [comment]
Well, thanks. I just did a for loop which starts with big error threshold and reduces it with each outer iteration. I save the network in every outer iteration. Maybe I can improve it by using a custom callback function. Closed.
