### ISSUE TITLE
When useing NeuralNetworkGPU it returns NaN 😖

### ISSUE THREAD

**Issue by CatScan-crypt** [BrainJS/brain.js#570]
![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)
### What is wrong?
Running NeuralNetworkGPU option returns a NaN but LSTM doesn't.

### Where does it happen?
In output when running the code provided below.

### How do we replicate the issue?

const brain = require('./src');
//const net = new brain.recurrent.LSTM();
const net = new brain.NeuralNetworkGPU();

net.train([
  { input: 'I feel great about the world!', output: 'happy' },
  { input: 'The world is a terrible place!', output: 'sad' },
],{log: (stats) => console.log(stats),iterations: 100,});

const output = net.run('I feel great about the world!'); // 'happy'

console.log(output);

### How important is this?
2 out of 5

### More details:  
gpu-fallback works fine,
When i use LSTM allso works.

Looks like a simple syntax error,
I can see that gpu-fallback uses an array to pass data,
Even one value so i guess it has something to do with it. 
Although when i tried to apply an array to the code above 
LSTM returns blank output and GPU returns one value of NaN.

Great work guys, thank you for this project 🐱‍🏍

**Comment by gerald-dotcom** [comment]
Can confirm the issue....Happening the same.

**Comment by robertleeplummerjr** [comment]
`brain.NeuralNetwork` is compatible with numbers, `brain.recurrent.LSTM` is compatible with strings.  You are using the networks in an erroneous way.
