### ISSUE TITLE
To Function doesn't work

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#572]
![A GIF xd](https://www.animatedimages.org/data/media/499/animated-fun-image-0217.gif)

## *What* is wrong?
Converting Networks to standalone functions doesn't work

## *Where* does it happen?
When trying to do it, an error is thrown:

```
/home/golem/Documents/Nikki/node_modules/brain.js/src/recurrent/rnn.js:631
const { states } = equation;

TypeError: Cannot destructure property 'states' of 'equation' as it is undefined.
```

## *How* do we replicate the issue?
What I do, before calling "**toFunction**" is:
- Include Brain.js and fs
- Creating a const called "trainingData" which is basically the content of a pre-trained file
- Creating the net, and calling "**fromJSON**" with the trainingData as parameter

### Nodejs: 
v14.6.0

### Brain.js: 
v1.2.2

## *How* important is this (1-5)?
4?

**Comment by mubaidr** [comment]
Can you please try the latest beta version? 

P.S. That gif 😆
