### ISSUE TITLE
crossValidate.toJSON().sets appears to return incorrect data type

### ISSUE THREAD

**Issue by nabeelvalley** [BrainJS/brain.js#573]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?

Based on the docstrings, the `crossValidate.toJSON().sets` result should return an `ICrossValidateStats` object with the following properties:

```ts
export interface ICrossValidateStats {
  truePos: number;
  trueNeg: number;
  falsePos: number;
  falseNeg: number;
  total: number;
}
```

However, it appears to instead return an object that looks like this:

```js
{ total: 152, testSize: 38, trainSize: 114 }
```

Which I can't see defined anywhere in the `d.ts` file, seems like an incorrect type definition/issue with the function return/I'm doing something wrong

## *Where* does it happen?
I am running in a VSCode Devcontainer, here is the container file:

```json
{
	"name": "Node.js 12",
	"dockerFile": "Dockerfile",
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	"extensions": [
		"dbaeumer.vscode-eslint"
	]
}
```

And here is the `Dockerfile`

```docker
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-12
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
   && apt-get -y install --no-install-recommends build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config \
   && apt-get autoremove -y \
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog
```

## *How* do we replicate the issue?

Here's the code for the network definition (from the docs mostly):

```js
// .... get data
const config = {
    binaryThresh: 0.5,
    hiddenLayers: [1],
    activation: 'sigmoid'
};

const crossValidate = new brain.CrossValidate(
    brain.NeuralNetwork,
    config
);

crossValidate.train(data, { log: true });

const json = crossValidate.toJSON();
console.log(json.stats); // { total: 152, testSize: 38, trainSize: 114 }

const net = crossValidate.toNeuralNetwork();
```

## Expected behavior (i.e. solution)

I would have expected the function to return an `ICrossValidateStats` object with the props stated above

### Nodejs: 

v12.16.3

### Browser: 

None (running on Node.js)

### Brain.js: 

2.0.0-beta.1

## *How* important is this (1-5)?

3, not a functional issue but is a bit annoying

**Comment by mubaidr** [comment]
Confirmed. We are migrating our code base to typescript, which will fix these type of issues. You can follow the progress/ contribute here: https://github.com/BrainJS/brain.js/issues/551
