### ISSUE TITLE
Large training set returns fails, returning NaN for training errors and `run()`

### ISSUE THREAD

**Issue by reginsmol** [BrainJS/brain.js#574]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/CFpxc7SmOm7C0/giphy.gif)

## *What* is wrong?

Large training set returns NaN for training errors and `run()` method, whereas a smaller set with the same format is successful.
## *Where* does it happen?

While training the NeuralNetwork
## *How* do we replicate the issue?

- Create an instance of `NeuralNetwork` with default settings
- Train the NeuralNetwork with default training settings using [this training set](https://paste.gg/p/anonymous/6aaeb5ffea45436eb22729174f9931b6)

## Expected behavior (i.e. solution)

Trains the network successfully 
## *How* important is this (1-5)?

2
## Other Comments

I'm sure this is a problem with my data, I'm just unsure as to why. Thank you in advance for your help!

**Comment by IanFLee** [comment]
I personally solved this error by:

`
            const trainingData = await generateTrainingData()

            const str = JSON.stringify(trainingData)

            const json = JSON.parse(str)

            var train = net.train(json, { log: (stats) => console.log(stats), iterations: 20000, errorThresh: 0.01 })
`

Though I did not repro with your data set, this is just what worked in my personal project

**Comment by robertleeplummerjr** [comment]
Your training set shows strings.  `NeuralNetwork` is not compatible with strings but works with numbers.  I'd probably just cast them to a number and try.  Closing due to misuse of library and lack of activity.
