### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by arifikhsan** [BrainJS/brain.js#575]
Hello, i created a simple game using LSTMTimeStep.

Code: https://github.com/arifikhsan/batu-gunting-kertas-nuxt
URL: https://rockpaperscissors-ai.now.sh/

Can this game be included in the example? Thanks.

**Comment by mubaidr** [comment]
Added. Thanks

**Comment by luccas222** [comment]
how about updating it to work in nuxt 3 ? this is awesome!!!
