### ISSUE TITLE
Timeseries (RNN, LSTM,...) with float values?

### ISSUE THREAD

**Issue by max-hans** [BrainJS/brain.js#576]
## *What* is wrong?
Does the warning beneath apply to only RNN, LSTM,... **or also** their respective "Timeseries" partners?

> CAUTION: When using an array of values, you can use ANY value, however, the values are represented in the neural network by a single input. So the more distinct values has the larger your input layer. If you have a hundreds, thousands, or millions of floating point values THIS IS NOT THE RIGHT CLASS FOR THE JOB. Also, when deviating from strings, this gets into beta

**Question: Since this is not the right class - which one is the right one?**

## *Where* does it happen?
/

## *How* do we replicate the issue?
/

## Expected behavior (i.e. solution)
Instructions should be clearer (can take care of that). Is somebody working on an implementation on time-series prediction of large sets of values (like in the neural network class from 0 to 1)

## *How* important is this (1-5)?
1

## Other Comments
I would love to help with the readme since some things are not completely clear. However, I don't know what is going on under the hood =)

**Comment by robertleeplummerjr** [comment]
What type of value are you sending into the neural network?  Likely, if these are arrays of decimals, it would be a timestep neural network.

**Comment by robertleeplummerjr** [comment]
Just use `brain.recurrent.LSTMTimeStep`.  It is mature enough to handle this now.
