### ISSUE TITLE
What does it mean by Brain.JS initially use 0?

### ISSUE THREAD

**Issue by gerald-dotcom** [BrainJS/brain.js#578]
I'm new to AI world and currently going through a Brain.JS Tut on Youtube. While learning all these stuff, I encountered some difficulty at https://www.youtube.com/watch?v=6E6XecoTRVo&t=2833s

I fail to understand what he actually mean. I have no idea what the use of using 1 for all that dates.

All the examples I witnessed didn't used anything like the presenter shown. 

Can somebody clarify on this?

**Comment by gerald-dotcom** [comment]
Funny enough, running his example on Node doesn't return expected output. I get random outputs while he get const output.

I wonder if he using a trap here

**Comment by robertleeplummerjr** [comment]
Can you post reproduction steps?

**Comment by gerald-dotcom** [comment]
> Can you post reproduction steps?

Funny enough, It was you did that video series. I found it now. 

So glad to have you. 

Here is the code but I'm more interested to learn what you mean by BrainJS init with 0, see the video link with exact pos where you said it,

```
const brain = require('brain.js')

const restaurants = {
    "Brilliant Yellow Corral": "Monday",
    "Penny’s": "Tuesday",
    "Right Coast Wings": "Wednesday",
    "The Delusion Last Railway Car": "Thursday",
    "Fun Day Inn": "Friday",
    "JHOP": "Saturday",
    "Owls": "Sunday"
};
const trainingData = [];

for (let restaurantName in restaurants) {
    const dayOfWeek = restaurants[restaurantName];
    trainingData.push({
        input: { [dayOfWeek]: 1 },
        output: { [restaurantName]: 1 }
    });
}

const net = new brain.NeuralNetwork({ hiddenLayers: [3] });

const stats = net.train(trainingData);

console.log(stats);

console.log(net.run({ 'Monday': 1 }));

function restaurantForDay(dayOfWeek) {
    const result = net.run({ [dayOfWeek]: 1 });
    let highestValue = 0;
    let highestRestaurantName = '';
    for (let restuarantName in result) {
        if (result[restuarantName] > highestValue) {
            highestValue = result[restuarantName];
            highestRestaurantName = restuarantName;
        }
    }
    
    return highestRestaurantName;
}

console.log(restaurantForDay('Monday'));
```

**Comment by robertleeplummerjr** [comment]
The link you provided is not related to the code that you have referenced, at least that I could find.  Can you double check it perhaps?

**Comment by gerald-dotcom** [comment]
Can you check 28:33 of that video? 

Well you should know it just by link but I guess youtube issues

**Comment by robertleeplummerjr** [comment]
Excellent!  Ty for the minute/second mark.  What is means is this:

Let's say you have three different training properties, `foo`, `bar`, and `baz`, and you feed them into the neural network as training data like this:
```js
net.train([
  { input: { foo: 1 }, output: ...},
  { input: { bar: 1 }, output: ...},
  { input: { baz: 1 }, output: ...},
]);
```

What _actually_ gets sent into the network is this, automatically:
```js
net.train([
  { input: { foo: 1, bar: 0, baz: 0 }, output: ...},
  { input: { foo: 0, bar: 1, baz: 0 }, output: ...},
  { input: { foo: 0, bar: 0, baz: 1 }, output: ...},
]);
```

The zero's correspond to inputs that are automatically filled in, to keep api usage somewhat clever/friendly.
