### ISSUE TITLE
Pass current net to callback function

### ISSUE THREAD

**Issue by Dok11** [BrainJS/brain.js#59]
[neural-network.js#L171](https://github.com/harthur-org/brain.js/blob/master/src/neural-network.js#L171)
```
if (callback && (i % callbackPeriod == 0)) {
    callback({ error: error, iterations: i });
}
```

Is it possible – send current net state to callback function?

Let me explain.
I divide my training data to real training data and test data.
And I want run nn on test data in some period for look real error.

Code for example what I want:
```
if (callback && (i % callbackPeriod == 0)) {
    callback({ error: error, iterations: i }, this);
}
```

**Comment by Dok11** [comment]
Close please, it's easier than I thought!

```
var net = new brain.NeuralNetwork();
var trainResult = net.train(trainingData, {
	callback: function() {
		// net.run() is work!
	}
});
```

**Comment by robertleeplummerjr** [comment]
ty for finding!

**Comment by Dok11** [comment]
@robertleeplummerjr how can I stop `train()` in a callback function?

**Comment by robertleeplummerjr** [comment]
Currently there isn't a built in means.  You could throw an exception that could be caught.
