### ISSUE TITLE
Converting "imported" Recurrent TimeStep Networks from JSON to standalone functions doesn't work

### ISSUE THREAD

**Issue by lesmo** [BrainJS/brain.js#597]
![giphy](https://user-images.githubusercontent.com/2228196/93000880-b5f0b180-f4f0-11ea-9a6f-8442c5b8e072.gif)

## *What* is wrong?
Converting "imported" Recurrent TimeStep Networks from JSON to standalone functions doesn't work

## *Where* does it happen?
When trying to run `net.toFunction()`:

```console
TypeError: Cannot read property 'states' of undefined
    at RNNTimeStep.toFunction (/Users/lesmo/Coding/Personal/bustabit/node_modules/brain.js/dist/brain.js:15121:29)
    at Object.exports.handler (/Users/lesmo/Coding/Personal/bustabit/src/export.js:60:20)
```

## *How* do we replicate the issue?

1. Create any `brain.recurrent` network and train it:
2. Get the JSON by running `net.toJSON()`
3. Create a new `brain.recurrent` network instance
4. Run `net.fromJSON()` to import the network
2. Run `net.toFunction()`
3. ???
4. Profit

```js
const brain = require('brain.js');

const net = new brain.recurrent.LSTMTimeStep();
net.train([[1, 2, 3]]);
const netJSON = JSON.stringify(net.toJSON());

const netimport = new brain.recurrent.LSTMTimeStep();
netimport.fromJSON(JSON.parse(netJSON));
const netFunc = netimport.toFunction(); // fail
```

## Expected behavior (i.e. solution)
Function should be successfully returned

**Comment by robertleeplummerjr** [comment]
This works with 2.0.0-beta.13, here is a working example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-598
