### ISSUE TITLE
Is is possible to use this library with Angular 8?

### ISSUE THREAD

**Issue by EmkaMk** [BrainJS/brain.js#600]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
Module not found: Error: Can't resolve 'brain.js' in project

## *Where* does it happen?
Trying to implement some of the examples for string classification as well as this example

https://stackblitz.com/edit/brainjs-angular?file=src%2Fapp%2Fapp.component.ts

## *How* do we replicate the issue?

Try to replicate this example https://stackblitz.com/edit/brainjs-angular?file=src%2Fapp%2Fapp.component.ts 
in Angular 8.

## Expected behavior (i.e. solution)
Code should not raise errors, app should be functional
## *How* important is this (1-5)?
5, since this library seems to provide everything I need, but can not run it! 
## Other Comments
Newbie in Angular, maybe I am doing something wrong, but Im literally copy/pasting the code and still get the same error.

**Comment by mubaidr** [comment]
It must be some temporary error or something but this example is running fine for me in Firefox browser. 

If you still have some issue, feel free to ask.
