### ISSUE TITLE
RangeError: Source is too large

### ISSUE THREAD

**Issue by gerald-dotcom** [BrainJS/brain.js#601]
## *What* is wrong?

RangeError: Source is too large

## *Where* does it happen?

In the a Neural Network when trying to train a net in GPU mode

## *How* do we replicate the issue?
- Step 1 

Create a dummy tanning data set that total around 32k records like below,

```
    {
        "input": [
            "boston apartments",
            "condos for sale in boston",
            "marblehead real estate",
            "massachusetts real estate"
        ],
        "output": "Condos"
    }
```

- Step 2 

Now, Import it and run it like below,

```
const brain = require('brain.js');
const natural = require('natural')
const jsonfile = require('jsonfile');
const trainingDataSet = require('./sample.json');

const net = new brain.NeuralNetworkGPU();


net.train({trainingDataSet}{ log: (stats) => console.log(stats), iterations: 20000 });

jsonfile.writeFile("./trainedNet.json", net.toJSON());
```

## Expected behavior (i.e. solution)

Should have run without this error

### Nodejs: 

v12.16.1

### Brain.js: 

2.0.0-beta.2

## *How* important is this (1-5)?

5

**Comment by mubaidr** [comment]
Please try using streams to pass data: https://github.com/BrainJS/brain.js#train-stream

**Comment by gerald-dotcom** [comment]
Works but without GPU.

https://github.com/BrainJS/brain.js/issues/570

**Comment by mubaidr** [comment]
Sorry, I missed that. Reopened issue. Please wait while we trace the issue.

**Comment by gerald-dotcom** [comment]
`neuralNetworkGPU: net
`
Doesn't work. I am getting an error which ask to provide valid neural network.

Other thing is that without using GPU but using LSTM, I'm not getting the state info but it create a network.
```

    const trainStream = new brain.TrainStream({
        neuralNetwork: net,
        floodCallback: function () {
            encodedData.forEach(function (data) {
                trainStream.write(data);
            })
            trainStream.endInputs();
        },
        doneTrainingCallback: function (stats) {
            console.log(
                `trained in ${stats.iterations} iterations with error: ${stats.error}`
              );
        },
    });
```

**Comment by robertleeplummerjr** [comment]
The original questions mentions a data shape of the following:
```
"input": [
            "boston apartments",
            "condos for sale in boston",
            "marblehead real estate",
            "massachusetts real estate"
        ],
        "output": "Condos"
```

This must be broken up, and used with `brain.recurrent.LSTM` for it to work.  `brain.NeuralNetwork` isn't compatible with strings.

Example of how data should look:
```
[
  { "input": "boston apartments", "output": "Condos" },
  { "input": "condos for sale in boston", "output": "Condos" },
  { "input": "marblehead real estate", "output": "Condos" },
  { "input": "massachusetts real estate", "output": "Condos" },
]
```
