### ISSUE TITLE
Issues with to-svg.js (not working in browser)

### ISSUE THREAD

**Issue by ArtMirror2000** [BrainJS/brain.js#616]
I'm new to web development and ML. 
I am trying to get the to-svg function working in Chrome browser.
I've been reading through all docs and previous Git-issues, but I can get it to work.
The Network itself ( LSTM) is working great.

For the to-svg I add the following code

const svgoptions ={
        fontSize : "12px",
        width : 600,
        height : 400,
        radius : 6,
        line : {width:0.5, color:"rgba(0,0,0,1)" },
        inputs : {color:"rgba(0,127,0,0.6)", label:[]},
        hidden : {color:"rgba(255,127,80,0.6)"},
        outputs : {color:"rgba(100,149,237,0.6)" }
}
document.getElementById("d2").innerHTML = brain.utilities.toSVG(net, svgoptions);

I get the following errors in console:

Uncaught ReferenceError: module is not defined

Uncaught TypeError: brain.utilities.toSVG is not a function

<h2>Is there a working code sample for browser with "to-svg.js" deployed ?</h2>

**Comment by mubaidr** [comment]
We do have example for svg rendering: https://github.com/BrainJS/brain.js/blob/master/examples/javascript/rendering-svg.html#L298 and it does works fine. You can try latest beta version.

Can you please create a jsfillde? or reproduce-able code?

**Comment by ArtMirror2000** [comment]
> We do have example for svg rendering: https://github.com/BrainJS/brain.js/blob/master/examples/javascript/rendering-svg.html#L298 and it does works fine. You can try latest beta version.
> 
> Can you please create a jsfillde? or reproduce-able code?



Thank you so much for your help. 
I am trying to create a ML sentence parser using the standard LSTM format as follows:

var net = new brain.recurrent.LSTM();
net.train([
  {input: "The man", output: "NP"},
  {input: "hit the ball with a stick.", output: "VP"},
  {input: "the ball", output: "NP"},
  {input: "with a stick.", output: "PP"},
  {input: "man", output: "N"},
  {input: "ball", output: "N"},
  {input: "stick", output: "N"},
  {input: "with", output: "P"},
]);

console.log("output = "+net.run("The man"));
console.log("output = "+net.run("stick"));
console.log("output = "+net.run("with"));

The net performs as expected, however training is slow.
I hoped to understand the inner workings of the  LSTM better by visualizing it, but I don't see LSTM among the options in the to-svg.

<h3> Is there a way to get the LSTM training process GPU accelerated in browser ?</h3?

**Comment by robertleeplummerjr** [comment]
As for the original question.  This has been resolved, here is a working example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-751-tosvg

> Is there a way to get the LSTM training process GPU accelerated in browser ?

We're working on that, but have no quick ETA.
