### ISSUE TITLE
"malloc: Incorrect checksum for freed object 0x10c2668b8" Bug when running lstm for 100 iterations

### ISSUE THREAD

**Issue by maxall41** [BrainJS/brain.js#643]
## _What_ is wrong?
I tried running an lstm network over an array with a couple of thousands data points for 100 iterations and it gave me this error:
```
node(99894,0x1100c6dc0) malloc: Incorrect checksum for freed object 0x10c2668b8: probably modified after being freed.
Corrupt value: 0x106034908
node(99894,0x1100c6dc0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    99894 abort      node main.js
```
But when I run it for only a couple of iterations it works fine.

## _Where_ does it happen?

 In the lstm when trying to run a net in node.js on my mac
## _How_ do we replicate the issue?
1. Create a main.js file and use npm to install Axios and brain.js
2. Paste this code into the main.js file
```
const brain = require('brain.js')
const axios = require('axios')
var t;
axios.get('https://raw.githubusercontent.com/minimaxir/mtg-gpt-2-cloud-run/master/generated_card_dumps/temp_1_0/cards_0.txt')
            .then(t = (response) => {
                var cards = response.data.split("~~~~~~~~")
                const lstm = new brain.recurrent.LSTM();
                console.log("starting training...");
                const result = lstm.train(cards, {
                iterations: 100,
                log: (details) => console.log(details),
                });
                console.log('Training result: ', result);
                console.log(lstm.run());

            })
            .catch(function (error) {
                // handle error
                console.log(error);
            })
```

### Nodejs:
14.5.0
### Browser:
Brave Browser v1.15.75
### Brain.js:
2.0.0-beta.2
## _How_ important is this (1-5)?
3

**Comment by robertleeplummerjr** [comment]
I believe the issue is that you need to increase the maximum prediction length when you run `net.train(trainingData, { maxPredictionLength: 200 })`: https://github.com/BrainJS/brain.js/blob/b7ace67e9f7a63e8730b7bbfb282472cc3dc496c/src/recurrent/rnn.ts#L112
