### ISSUE TITLE
'learningRate' is declared but its value is never used

### ISSUE THREAD

**Issue by grigori-gru** [BrainJS/brain.js#644]
https://github.com/BrainJS/brain.js/blob/349009fd5d5c3a1eb007c18e6f799296b6bbf39b/src/praxis/arthur-deviation-biases.ts#L40

It can be removed, in tests I try to pass only `layer` but compiler expect to pass `learningRate`.

**Comment by mubaidr** [comment]
Nice find! Willing to send a pull request?

**Comment by grigori-gru** [comment]
Yes, sure

**Comment by mubaidr** [comment]
https://github.com/BrainJS/brain.js/pull/649
