### ISSUE TITLE
dependency was not found

### ISSUE THREAD

**Issue by 24jr** [BrainJS/brain.js#656]
I `npm install brain.js` and its in my package.json and I have Xcode and python 2.7 installed and when I try and do `import brain from 'brain.js';` in my script (using vuejs not that it should matter) I get error 
```
This dependency was not found:

* brain.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/ML.vue?vue&type=script&lang=js

To install it, you can run: npm install --save brain.js
```
and I've tried the `npm rebuild` as the docs say to try as well and same thing

This is for browser of course not node not sure if that has something to do with it or not

**Comment by mubaidr** [comment]
whats the result of? `npm install --save brain.js`

**Comment by 24jr** [comment]
@mubaidr same thing

**Comment by 24jr** [comment]
This is vue component as a test with sample code copied from docs used in the function

```
<template>
  <p>ML test</p>
  <button @click="testData">testData</button>
</template>
<script>
import brain from 'brain.js';

export default {
  name: 'MLtest',
  setup() {
    function testData(){
      console.log('begin test')
      // provide optional config object (or undefined). Defaults shown.
      const config = {
        binaryThresh: 0.5,
        hiddenLayers: [3], // array of ints for the sizes of the hidden layers in the network
        activation: 'sigmoid', // supported activation types: ['sigmoid', 'relu', 'leaky-relu', 'tanh'],
        leakyReluAlpha: 0.01, // supported for activation type 'leaky-relu'
      };

      // create a simple feed forward neural network with backpropagation
      const net = new brain.NeuralNetwork(config);

      console.log('net created')
      net.train([
        { input: [0, 0], output: [0] },
        { input: [0, 1], output: [1] },
        { input: [1, 0], output: [1] },
        { input: [1, 1], output: [0] },
      ]);

      console.log('net trained')
      const output = net.run([1, 0]); // [0.987]
      console.log('net ran', output)
    }
    
    return {
      testData,
    }
  }
}
</script>
<style>

</style>
```
<img width="253" alt="Screen Shot 2020-11-01 at 5 08 50 PM" src="https://user-images.githubusercontent.com/34662182/97816718-0e2c7000-1c65-11eb-9867-1c9ffd79ff1b.png">
<img width="572" alt="Screen Shot 2020-11-01 at 5 11 28 PM" src="https://user-images.githubusercontent.com/34662182/97816749-4a5fd080-1c65-11eb-829d-ae3858c1baeb.png">

**Comment by 24jr** [comment]
Oh I think it has something to do with where I import the brain.js from. I guess I thought you just do it globally like that but maybe I have to access a specific folder. Or do something in main.js to make brain.js accessible from components

**Comment by Nelias** [comment]
This issue should be closed as it is clearly not the problem with library itself.

**Comment by ghost** [comment]
Hi, I have the same problem I can't find any solution, in a simple .js index everything works but it's impossible to put it in my project vue.js

**Comment by robertleeplummerjr** [comment]
Try this now.  This issue is related to https://github.com/stackgl/headless-gl.  If there are further installation issues with headless-gl, please raise an issue there.
