### ISSUE TITLE
Specify TrainStream Iterations?

### ISSUE THREAD

**Issue by timendez** [BrainJS/brain.js#658]
I'm trying to stream 25gb of data (before modeling) into a neural net via TrainStream. It takes about 30min/iteration, so I'm wondering if there's any way to tell it to stop training after just 5 iterations so that I can test it out and see if it's good enough.

There doesn't seem to be anything I can pass as TrainStream Options, so I'm just wondering if I'm overlooking something.

Thanks!

**Comment by timendez** [comment]
Additionally (let me know if this would be better as a new issue), is there any way to improve stream training performance? It takes about 1ms per call to `trainStream.write(thing);`

**Comment by robertleeplummerjr** [comment]
TrainStream has moved to its own project: https://github.com/BrainJS/train-stream
The options are as follows: https://github.com/BrainJS/train-stream/blob/993bc7fd4ff84b0d2093deb83318e6d648bcb4a2/src/index.ts#L5

If a new feature is requested or you would like to contribute it, please do so there.  Thank you.
