### ISSUE TITLE
Brain don't use imported training

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#662]
![A GIF or MEME to give some spice of the internet](https://i.ytimg.com/vi/NUYvbT6vTPs/maxresdefault.jpg)

## _What_ is wrong?

Im training my neural network, then exporting all the training with : 
`fs.writeFile('model.json', JSON.stringify(net.toJSON()), 'utf8', () => console.log('Model Has been Writen.'));`

When starting after importing the training

`if (use_oldTraining) {
  let fileContent = fs.readFileSync("model.json", "utf8");
  let fileContentJSON = JSON.parse(fileContent);
  net.fromJSON(fileContentJSON);
}`
 The brain is dumbo like he didn't recieved the training that i imported.

[At the end of the first training](https://i.imgur.com/94Chnel.png)
[After importing old training and running again the training](https://i.imgur.com/zjk4qqv.png)

## _Where_ does it happen?
When  trying to import the model

## _How_ do we replicate the issue?
- Step 1 Train the network
- Step 2 Export the result
- Step 3 Import the result
- Step 4 Train the network
- Step 5 brain.js goes brrrrrrrrr

**Comment by jefftmahoney** [comment]
Two things 
1) have you verified that `use_oldTraining` is true, and/or tried substituting a true boolean expression (e.g. 1 == 1) to ensure that your code block is indeed executing, and 
2) with `net.fromJSON(fileContentJSON);` ... does that get assigned anywhere?  It looks like you're calling `fromJSON()` without passing the return value to anywhere.

**Comment by ghost** [comment]
Hello, yes use_oldTraining is true and working and for the second part, here is my code

`
const brain = require('brain.js');
const fs = require('fs');
let fileContent = fs.readFileSync("model.json", "utf8");
let fileContentJSON = JSON.parse(fileContent);

const net = new brain.recurrent.LSTM();
net.fromJSON(fileContentJSON);
console.log(net.run("crée un text channel qui s'appelle testPratique"));

`

**Comment by jefftmahoney** [comment]
Cool.  So what happens when you try this:

```
const brain = require('brain.js');
const fs = require('fs');
let fileContent = fs.readFileSync("model.json", "utf8");
let fileContentJSON = JSON.parse(fileContent);

let net = new brain.recurrent.LSTM();
net = net.fromJSON(fileContentJSON); // re-assigning result of fromJSON() back to net
console.log(net.run("crée un text channel qui s'appelle testPratique"));
```

**Comment by ghost** [comment]
The brain looks stupid like i never imported the result of old works.

**Comment by jefftmahoney** [comment]
I was mistaken about `fromJSON()` (i.e. you were using it correctly).

I got this example below to work.  I'm using a Mac, and I have Node 10.15.3.  The `doInitialSetup` function trains a LSTM network and stores it in a file called `model.json` (like you did).  The `useExistingTraining` function creates a new LSTM that utilizes the training from `model.json`.  I don't know how closely this resembles what you've done so far, but hopefully it can help.

```
const brain = require('brain.js')
const fs = require('fs')

function doInitialSetup() {
  const trainingData = [
    'Jane saw Doug.',
    'Doug saw Jane.',
    'Spot saw Doug and Jane looking at each other.',
    'It was love at first sight, and Spot had a frontrow seat. It was a very special moment for all.'
  ]

  const lstm = new brain.recurrent.LSTM()
  const result = lstm.train(trainingData, {
    iterations: 1500,
    log: (details) => console.log(details),
    errorThresh: 0.012,
  })
  console.log('Training result:', result)

  const run1 = lstm.run('Jane')
  const run2 = lstm.run('Doug')
  const run3 = lstm.run('Spot')
  const run4 = lstm.run('It')
  console.log(`run 1: Jane${run1}`)
  console.log(`run 2: Doug${run2}`)
  console.log(`run 3: Spot${run3}`)
  console.log(`run 4: It${run4}`)

  fs.writeFile(
    'model.json',
    JSON.stringify(lstm.toJSON()),
    'utf8',
    () => console.log('Model written to file')
  )
}

function useExistingTraining() {
  let fileContent = fs.readFileSync('model.json', 'utf8')
  let fileContentJSON = JSON.parse(fileContent)
  let nooLstm = new brain.recurrent.LSTM()

  nooLstm.fromJSON(fileContentJSON) // use existing training

  const run1 = nooLstm.run('Jane')
  console.log(`run 1: Jane${run1}`)
  console.log(`run 2: Doug${run2}`)
  console.log(`run 3: Spot${run3}`)
  console.log(`run 4: It${run4}`)
}

```

**Comment by ghost** [comment]
Hello again..   Here is the result :
![x](https://i.imgur.com/QbqiRU4.png)

I don't really know what is wrong with my old code, probably that my IA is badly trained, im gonna make a help post on github to get more infos about what im doing wrong
