### ISSUE TITLE
Brain Not Learning :(

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#663]
Hello, this is really not a bug, but probably more a problem from my side.
Im trying to learn simple instructions to my AI.
Here is the code :
![image](https://user-images.githubusercontent.com/52961795/100346810-bf17f780-2fe4-11eb-9580-e699fb316e2c.png)
I basicly don't understand why my AI is never understanding what im asking him.
I don't know if its the method that i am using that is wrong or maybe not using correctly the training logic ?

Im trying to learn my IA to understand basic instruction for a discord bot (dont ask why xD)
So i want to make him understand my instruction and output tc> [LAST WORD OF THE TRAINING DATA]

That's it (.. For the moment :/)

Here are some output from brain.js : 
![image](https://user-images.githubusercontent.com/52961795/100346929-e66ec480-2fe4-11eb-83ed-681485989b54.png)
If anyone could help me or explain my mistakes, i will really appreciate it.
Thanks !

**Comment by Pradakicks** [comment]
I am also having a similar issue. Have you found a solution for this?

**Comment by Shroototem** [comment]
I seem to be very confused about getting the syntax correct for this.
`js
const brain = require('brain.js')
const fs = require('fs')

const net = new brain.NeuralNetwork()

var TraningData = [
    { input: [1], output: [1] },
    { input: [2], output: [4] },
    { input: [3], output: [6] },
    { input: [4], output: [8] },
    { input: [5], output: [10] }
  ]

net.train(TraningData, {
    iterations: 2000,
    callback: step => console.log(step)
})

// write to file system
fs.writeFileSync('trained-net.json', JSON.stringify(net.toJSON()));
`
`json
{ iterations: 1900, error: 32.80016565503139 }
{ iterations: 1910, error: 32.80016431987018 }
{ iterations: 1920, error: 32.80016060051804 }
{ iterations: 1930, error: 32.80016060050387 }
{ iterations: 1940, error: 32.800159360708996 }
{ iterations: 1950, error: 32.80015907458992 }
{ iterations: 1960, error: 32.80015773942913 }
{ iterations: 1970, error: 32.800157453312195 }
{ iterations: 1980, error: 32.80015716719337 }
{ iterations: 1990, error: 32.80015621350392 }
{ iterations: 2000, error: 32.800155927387195 }`

**Comment by robertleeplummerjr** [comment]
Work on adjusting hiddenLayers and learnIngRate.
