### ISSUE TITLE
cannot read property 'backpropagateIndex' of undefined & unhandled signature

### ISSUE THREAD

**Issue by ray-1337** [BrainJS/brain.js#665]
## _What_ is wrong?

Giving me an error when I'm using LSTM (cannot read property 'backpropagateIndex' of undefined)

And, giving me an error when I'm using LSTMTimestep (unhandled signature)

## _Where_ does it happen?

In an LSTM when trying to run a net train in Node.js.

## _How_ do we replicate the issue?

```const BrainJs = require('brain.js');
const NN = new BrainJs.recurrent.LSTM();
let data = require('./dataset.json'); // [ {phrase: "string", { ... } }, {phrase: "string", { ... } } ]

const config = {
  iterations: 60000,
  log: (details) => console.log(details),
  errorThresh: 0.012,
};

NN.train(data, config);

```

## Expected behaviour (i.e. solution)

Should have run without this error

### Nodejs:
v14.x

### Browser:
[]

### Brain.js:
2.0.0-beta.2

## _How_ important is this (1-5)?

4.5

**Comment by robertleeplummerjr** [comment]
Your training data is in the wrong shape.

```js
[ {phrase: "string",
```

Should be this (in this scenario):

```js
[ { input: "", output: "" } ]
```

Here is a working example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-665
