### ISSUE TITLE
aSync Training Problem

### ISSUE THREAD

**Issue by mertdogan** [BrainJS/brain.js#666]
![image](https://media1.tenor.com/images/8056ea1ac5d1aaee39b5b836077e821c/tenor.gif?itemid=3578206)

## _What_ is wrong?
trainAsync() not working. Generates Promise error in the console.log after train finishes. Also, result of run is different from normal train() result.

## _Where_ does it happen?
In the NeuralNetwork when trying to run a net in windows localhost pc

## _How_ do we replicate the issue?

Complete code below:
[indexasync.zip](https://github.com/BrainJS/brain.js/files/5646781/indexasync.zip)

`
<!DOCTYPE html>
<html lang="tr">
  <head>
    <title>brain.js</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//unpkg.com/brain.js"></script>
  </head>

  <body>
	<div id="output"></div>
	<div id="output2"></div>
    <script>
	
	var net = new brain.NeuralNetwork();

	net.trainAsync([{input: [0, 0], output: [0]},
			   {input: [0, 1], output: [1]},
			   {input: [1, 0], output: [1]},
			   {input: [1, 1], output: [0]}])
	.then((res) => {
		console.log(res);
		var output = res.run([1, 0]);  // [0.933]
		console.log(output);
	});
	;

	</script>
  </body>
</html>
`
## Expected behavior (i.e. solution)
I think something broken the code and a bug occured.

### Nodejs:
no
### Browser:
Chrome
### Brain.js:
2.0.0-beta.2 (from //unpkg.com/brain.js )

## _How_ important is this (1-5)?
4

## Other Comments
You are the best brain.js

**Comment by robertleeplummerjr** [comment]
This is no longer an issue.  Tested with latest (2.0.0-beta.12) here: https://observablehq.com/@robertleeplummerjr/brain-js-issue-666
