### ISSUE TITLE
recurrent.LSTM not GPU accelerated

### ISSUE THREAD

**Issue by p40sp40r0us** [BrainJS/brain.js#667]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/gKsJUddjnpPG0/giphy.gif)

## _What_ is wrong?

Not sure if this is a bug, or a feature not yet implemented.  From the commits, it appears version 2.0.0-beta.2 should be GPU accelerated for all network types.  However recurrent.LSTMTimeStep() is extremely slow compared to NeuralNetworkGPU...and just from the title doesn't appear it is.  It looks like the Recurrent class is active and is GPU accelerated?   [here](https://jsfiddle.net/2pLw9ec5/4/) is my attempt on jsfiddle to use the new Recurrent class, but it's giving me an error and not sure why.  I've also tried this on node, with same results.  So ... is the Recurrent class ready for testing and my syntax is wrong?

**UPDATE*** 

I was able to use the new Recurrent class on Node, by requiring the recurrent class and layer class directly from the src folders.  Must not be built in brain.js file or I still have something wrong in my code.  The recurrent class with 1 lstm-cell hidden layer uses about ~8-12% of my GPU (NVIDIA 1050TI), and 20% CPU on my test code... but: 
- is ~200x slower than recurrent.LSTMTimeStep() on the same training data. 
- has a severe memory leak... on the CPU version (recurrent.LSTMTimeStep) or even NeuralNetworkGPU memory stays constant at ~3gb, even after several hours.   On the GPU version, (recurrent using lstm-cell hidden layer) after 4 minutes it reaches 8 gb, and after 8 minutes my poor machine maxes out and I have to quit the app. 

Below is my code in how do we replicate the issue, which uses ~800 single array points... perhaps it needs to be larger for a better comparison?  Still, the memory leak is a big problem

## _Where_ does it happen?

On jsfiddle as well as node.

## _How_ do we replicate the issue?

[here](https://jsfiddle.net/2pLw9ec5/4/) for the very simple jsfiddle version which uses one of the __test__ scripts

The larger node sample below uses a .csv file to analyze baseball stats, the file being referenced in the code is all pitches to Mike Trout in 2020.  You'll need npm i csvtojson as a requirement as well. You can download the .csv file [here](https://baseballsavant.mlb.com/statcast_search?hfPT=&hfAB=&hfGT=R%7C&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfPull=&hfC=&hfSea=2020%7C&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=&game_date_lt=&hfInfield=&team=&position=&hfOutfield=&hfRO=&home_road=&batters_lookup%5B%5D=545361&hfFlag=&hfBBT=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=api_p_release_speed&sort_order=desc&min_pas=0#results) then click the link icon to save as .csv locally.  I ran this test file in the root folder of brain.js

//start code
const brain = require('brain.js')
const { Recurrent } = require('./src/recurrent');
const { add, input, multiply, output, random, rnnCell, lstmCell } = require('./src/layer')
const csvtojson = require('csvtojson')

//load baseball stats
csvtojson()
  .fromFile('./savant_data.csv')
  .then((jsonObj)=>{
    //do stuff

    //get one field... 
    let events = jsonObj.map(p=>p.events)

    //convert to 1s and 0s
    let training = events.map(p=>{
      switch(p){
        case 'single':
        case 'double':
        case 'triple':
        case 'home_run':
        case 'walk':
          return 1;break;
        default:
          return 0;
      }
    })
    //chunking into smaller chunks
    let trainingChunked = chunkData(training.slice(0,800),10)

    //create GPU net
    const netGPU = new Recurrent({
      inputLayer: () => input({ height: 1 }),
      hiddenLayers: [
        (inputLayer, recurrentInput) =>
          lstmCell({ 'height': 20}, inputLayer, recurrentInput),
      ],
      outputLayer: (inputLayer) => output({ height: 1 }, inputLayer),
    });

    //create CPU net
    const netCPU = new brain.recurrent.LSTMTimeStep({
      inputSize:1,
      hiddenLayers:[20],
      outputSize:1
    })

    //train CPU first
    console.log('CPU training')
    let tCPU = new Date()
    netCPU.train(trainingChunked,{
      'iterations':100,
      'log':(stats)=>{
        console.log('CPU: '+stats+' in '+((new Date()-tCPU)/1000/60).toPrecision(4)+' min')
      },
      'logPeriod':10
    })

    //train GPU 2nd
    console.log('GPU training')
    let tGPU = new Date()
    netGPU.train(trainingChunked,{
      'iterations':100,
      'log':(stats)=>{
        console.log('GPU: '+stats+' in '+((new Date()-tGPU)/1000/60).toPrecision(4)+' min')
      },
      'logPeriod':10
    }) 
    //not bothering to do anything with the nets, because they don't pass training
})

const chunkData = (data,_chunksize) =>{
    let chunkCt = Math.ceil(data.length/_chunksize)
    let chunkedData = []
    for(var i=0;i<chunkCt;i++)
    {
      chunkedData.push(
        data.slice(i*_chunksize,(i+1)*_chunksize)
      )
    }
    return chunkedData
}

My output:

![image](https://user-images.githubusercontent.com/46287837/102091221-8baed880-3dec-11eb-8fc2-bdffae1855b7.png)

## Expected behavior (i.e. solution)

example1: log a result.. something like {'error' 0.001}
example2: take less then 4 minutes for 20 repetitions... preferably <0.2 minutes like CPU version..  and not grow in memory use

### Nodejs:

v10.7.0

### Browser:

Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)

### Brain.js:

//unpkg.com/brain.js --> 2.0.0-beta.2

## _How_ important is this (1-5)?

3

**Comment by pbxx** [comment]
I am having this bug as well. I am on Windows using Node.js, and an Nvidia RTX 2060 super. 

I have confirmed that the GPU is not being utilized by checking MSI Afterburner while training a neural net, the GPU stays idle while the Node app uses ~25% cpu. 

I have opened a thread on stackoverflow about this same issue: https://stackoverflow.com/questions/65259566/brain-js-is-not-utilizing-gpu-for-training

**Comment by robertleeplummerjr** [comment]
`recurrent.LSTM` is not, nor will it ever be (unless someone ported it) GPU powered.  However, `Recurrent` (the class) is, and resembles a highly configurable `RNNTimeStep` network that was rethought out so to be more flexible.  In the past the type of neural network was strongly tied to its name, `recurrent.LSTM` for example, was strongly tied to the LSTM cells/layers, where as with the `Recurrent` class, the class is a runner for a network configuration, that can be rnn time step, gru time step, lstm time step, `RNN`, `LSTM`, `GRU`, or free styled to whatever means you'd like.  The `Recurrent` class still has a long way to go before it will reach the level of optimization that `recurrent.LSTM` offers, and as well the functionality, but it is a proper _reusable_ foundation to build on as brain.js matures.

Here is the [Roadmap](https://github.com/BrainJS/brain.js/wiki/Roadmap#recurrent-class-overview) which highlights where things are eventually headed.

We want GPU, but we want it done right, so that it challenges the industry for optimization AND ease of use.
