### ISSUE TITLE
determining line chart regions

### ISSUE THREAD

**Issue by gomestai** [BrainJS/brain.js#668]
Hello all,

I have time based data's and drawing a chart like below:
![data](https://user-images.githubusercontent.com/3295212/101279818-f1400b00-37d5-11eb-9f81-6a9c418745af.png)

As you see, human is able to separate regions by eye. I have thousands of data to draw hundreds of charts similar to this one. So I'm also able to make a training set with marked regions like 
`
data=[
{time:'2020-12-06 10:02:00', data:'10',region:'1'},
{time:'2020-12-06 10:02:01', data:'10',region:'1'},
{time:'2020-12-06 10:02:02', data:'8',region:'1'},
{time:'2020-12-06 10:02:03', data:'7',region:'1'},
{time:'2020-12-06 10:02:04', data:'6',region:'1'},
{time:'2020-12-06 10:02:05', data:'5',region:'2'},
{time:'2020-12-06 10:02:06', data:'4',region:'2'},
{time:'2020-12-06 10:02:07', data:'4',region:'2'},
{time:'2020-12-06 10:02:08', data:'4',region:'2'},
{time:'2020-12-06 10:02:09', data:'5',region:'2'},
{time:'2020-12-06 10:02:10', data:'5',region:'2'},
{time:'2020-12-06 10:02:11', data:'6',region:'2'},
{time:'2020-12-06 10:02:12', data:'7',region:'3'},
{time:'2020-12-06 10:02:13', data:'8',region:'3'},
{time:'2020-12-06 10:02:14', data:'9',region:'3'},
{time:'2020-12-06 10:02:15', data:'10',region:'3'},
{time:'2020-12-06 10:02:16', data:'10',region:'3'},
];
`

So how can I train brain.js with this kind of data to determine regions of new charts?

**Comment by robertleeplummerjr** [comment]
A possible means:
1. Use time as decimal normalized between 0 and 1 relative to the start time of the data.
2. Normalize `data` to between 0 and 1.
3. Make outputs match the number of regions, 1 if they are in the region, 0 if they are not.
