### ISSUE TITLE
Can we add guidance on importing in Angular?

### ISSUE THREAD

**Issue by jonathanconway** [BrainJS/brain.js#669]
When I tried importing Brain.JS into my fresh new Angular 11 project:

```
import { NeuralNetwork } from 'brain.js';
```

I kept getting this build error:

```
Can't resolve 'brain.js'
```

After about an hour of anguished searching and mucking around I finally discovered the fix, buried in an obscure [comment on an issue](https://github.com/BrainJS/brain.js/issues/80#issuecomment-320338028):

> If you'd like to use the es6 files, simply use import brain from 'brain.js/src'; or import brain from 'brain.js/src/index'; I think.

Can we document this somewhere so that the future Angular users won't struggle so much?

I'm happy to do this, if someone can help me find where. Do we perhaps need a new section in the Docs called 'Using with Angular' or 'Using with a framework' or similar?

Thanks

**Comment by mubaidr** [comment]
@jonathanconway You are welcome to submit PR for this.

**Comment by Nelias** [comment]
Same issue in Svelte.js
`Error: 'brain' is not exported by node_modules\brain.js\dist\src\index, imported by src\RecentComments.svelte`
Also there is no default export from "brain.js/src" of "brain". The `exports` also break the framework but it is their inner issue I think.

Everything works great in React with TypeScript, simply: `import brain from 'brain.js'`
and then `let net = new brain.recurrent.LSTM()` is all fine.

**Comment by robertleeplummerjr** [comment]
This should be resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.6.

**Comment by robertleeplummerjr** [comment]
Via: https://github.com/BrainJS/brain.js/pull/775
