### ISSUE TITLE
`GPU.js`

### ISSUE THREAD

**Issue by dyn0-dy** [BrainJS/brain.js#672]
Greetings, there's a issue with GPU, I think only basic neural network runs on GPU, if.
GPU.js is wonderful library, you could port other layers there.

Also I would like to see some custom layer building, like in Keras...

Maybe Hopkins networks, Markov chains, reinforced learning, all could be implemented on Brain.js

I can give you mathematics, but I don't see very much deep in how inheritance works in JavaScript, so I cannot do this.

Maybe even Bayesian would be wroth a try.

But primarily, it should all run with auto encoder, it should run on GPU, and it should support clustering so we could link normal brain cortexes in there.

I mean layers...

And maybe even feature, that output of later network, is input somewhere in the begining, and there's some sort of merge layer.

I can create automated learning with back-ups, it's almost done, I will even work on implementing database cursor as feed to training, but some things should be done...

Maybe even clustering algo's would come handy like DBSCAN or Optics.

**Comment by robertleeplummerjr** [comment]
GPU.js is being implemented, and custom layer building is the end goal and desire.  We have architectures for [FeedForward](https://github.com/BrainJS/brain.js/blob/6a5aefd9f9271774580b47d697c934b1a2b840d2/src/feed-forward.ts#L109) and [Recurrent Like](https://github.com/BrainJS/brain.js/blob/6a5aefd9f9271774580b47d697c934b1a2b840d2/src/recurrent.ts#L57) neural networks but others would be fantastic as well.

The whole idea in Brain.js's new architecture is reusability both in neural network and their layers.  So you can build whatever type of neural network architecture you'd like.  I look forward to hearing more of your ideas!

**Comment by robertleeplummerjr** [comment]
Since GPU.js is already used to build these new layers, and as well the entire of the GPU model, I'm going to go ahead and close this issue.
