### ISSUE TITLE
Brain worker

### ISSUE THREAD

**Issue by dyn0-dy** [BrainJS/brain.js#673]
Git brain worker, 
And then 'front' which could be master for workers.

I can make computation distribution system, but I don't really know brain.js...

It can be shared over network, with local peer discovery, or even browser-gpu support with server as merger of networks.

There can be two options, "fast cluster", "slow cluster" which would be different versions, based on processing speed.

Somewhere where worker could attach, e.g. it can go even in a way, that on few machines, there's backpropagation happening, and on another machines, there's testing and error reporting.

Registered worker and gpu worker by pinging master trough socket can offload work automatically.

That would be best option.

Neural Networks could be rewritten in C++ with GPU support, and ported as NAPI so NODE will maitain computation distribution, and it'll be industrial scale product in a while.

**Comment by mubaidr** [comment]
I think this feature request is in-line with multi-threaded training. 
https://github.com/BrainJS/brain.js/issues/417

Once the multi-htreading is ready, we can extend it to implement your idea. 

We are looking for contributors, PRs are welcomed!

**Comment by robertleeplummerjr** [comment]
Closed due to inactivity.
