### ISSUE TITLE
2D Convolution

### ISSUE THREAD

**Issue by dyn0-dy** [BrainJS/brain.js#674]
I can make pnge's and jpeg's into that, but what would really come handy would be 2D convultion, like optical cortex or whatever, that could even handle 2D LTSM networks in certain layers, people could then easily experiment with this combination, which could have wonderful outcomes. 

Maybe it'll get you some funding...

**Comment by robertleeplummerjr** [comment]
Most of the convolution network layers have been built, but there was an initiative that really took off to convert brain.js to typescript.  I've had to give the convolutions a back-seat while I work to get the rest of brain.js into typescript.  That progress can be seen here: https://github.com/BrainJS/brain.js/issues/551.

The actual convolution layer can be seen here: https://github.com/BrainJS/brain.js/blob/master/src/layer/convolution.ts and is to be used with the new layer composition `FeedForward` neural network, outlined here: https://github.com/BrainJS/brain.js/wiki/Roadmap.

In addition, the idea behind the new network types is that you could potentially send an imagine directly into the neural network.


We're greatly appreciative of funding and or help.
