### ISSUE TITLE
Typescript (Typings) Improvements

### ISSUE THREAD

**Issue by mubaidr** [BrainJS/brain.js#684]
We have recently migrated brain.js to TypeScript (https://github.com/BrainJS/brain.js/issues/551), code base is pretty large, so we would love your help! 💪

How to contribute?
- Fix any lint/Typescript error
- Remove redundant types (if any)
- Improve types usage

**Here you can find a guide on [how to contribute](https://github.com/BrainJS/brain.js/blob/master/CONTRIBUTING.md).**

Reach out to us!
Feel free to reach if you have questions or need help getting started. You can leave comments here or you can tag me in your PR if you need any help or you're not sure about something!

You can also get in touch on our [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/brain-js/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) & [![Slack](https://slack.bri.im/badge.svg)](https://slack.bri.im).

Happy Coding! 🤟

**Comment by bherbruck** [comment]
Hi @mubaidr, I see the gitter is a bit inactive and the slack link is broken (so is the contributing guide).

I would like to contribute to the typing side but have just a few questions:

1. How married is the project to using rollup? It would be possible to use `tsc` and have separate `tsconfig.json` for browser and nodejs (commonjs for nodejs and es6+ for browser)
2. I see a lot of `// @ts-expect-error` and the typings look _ok_ for many of them, was `// @ts-ignore` intended?

Just a couple things that stood out

**Comment by mubaidr** [comment]
Really appreciate your input and will to contribute. 

1. I would really recommend to stick with the current build system for now. We can work on it later once all code is ported and tests are up and running.
2. Currently there are some workarounds and hacks implemented in the code, we are looking for experts to handle these cases. 

Please go ahead and feel free to remove/ update/ improve typescript code and types

**Comment by robertleeplummerjr** [comment]
This is done in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.11

**Comment by robertleeplummerjr** [comment]
We can of-course revisit, but the migration has been completed, and is no longer the focus.
