### ISSUE TITLE
gru.ts typescript lint error

### ISSUE THREAD

**Issue by search27** [BrainJS/brain.js#691]
When I try to type 'npm run-script dist', got some error about ts-lint, I think.

`

> brain.js@2.0.0-beta.2 dist C:\workspace\brainjs\npmbrain\1\brain.js
> npm run build

> brain.js@2.0.0-beta.2 build C:\workspace\brainjs\npmbrain\1\brain.js
> run-p build:**

> brain.js@2.0.0-beta.2 build:browser C:\workspace\brainjs\npmbrain\1\brain.js
> rollup -c rollup.config.browser.js

> brain.js@2.0.0-beta.2 build:node C:\workspace\brainjs\npmbrain\1\brain.js
> rollup -c rollup.config.js

> brain.js@2.0.0-beta.2 build:typings C:\workspace\brainjs\npmbrain\1\brain.js
> tsc --declaration --emitDeclarationOnly --declarationMap

> ./src/index.ts → dist/brain.js, dist/brain.mjs...
> 
> ./src/index.ts → dist/brain-browser.mjs, dist/brain-browser.js, dist/brain-browser.min.js...
> __tests__/recurrent_deprecated/gru.ts:117:29 - error TS2345: Argument of type 'Matrix' is not assignable to parameter of type 'IMatrixJSON'.
>   Types of property 'weights' are incompatible.
>     Type 'Float32Array' is missing the following properties from type 'number[]': pop, push, concat, shift, and 5 more.
> 
> 117         compare(json.input, net.model.input);
>                                 ~~~~~~~~~~~~~~~
> 
> __tests__/recurrent_deprecated/gru.ts:121:46 - error TS2345: Argument of type 'Matrix | RandomMatrix' is not assignable to parameter of type 'IMatrixJSON'.
>   Type 'Matrix' is not assignable to type 'IMatrixJSON'.
> 
> 121             compare(json.hiddenLayers[i][p], layer[p]);
>                                                  ~~~~~~~~
> 
> __tests__/recurrent_deprecated/gru.ts:124:30 - error TS2345: Argument of type 'Matrix' is not assignable to parameter of type 'IMatrixJSON'.
> 
> 124         compare(json.output, net.model.output);
>                                  ~~~~~~~~~~~~~~~~
> 
> __tests__/recurrent_deprecated/gru.ts:125:39 - error TS2345: Argument of type 'Matrix | RandomMatrix' is not assignable to parameter of type 'IMatrixJSON'.
>   Type 'Matrix' is not assignable to type 'IMatrixJSON'.
> 
> 125         compare(json.outputConnector, net.model.outputConnector);
>                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> __tests__/recurrent_deprecated/rnn-time-step.ts:57:27 - error TS2322: Type '{ type: string; options: { inputSize: number; inputRange: number; hiddenLayers: number[]; outputSize: number; decayRate: number; smoothEps: number; regc: number; clipval: number; maxPredictionLength: number; }; ... 6 more ...; outputLookupLength: number; }' is not assignable to type 'IRNNTimeStepJSON'.
>   Types of property 'hiddenLayers' are incompatible.
>     Type '{ weight: { rows: number; columns: number; weights: Float32Array; }; transition: { rows: number; columns: number; weights: Float32Array; }; bias: { rows: number; columns: number; weights: Float32Array; }; }[]' is not assignable to type '{ [index: string]: IMatrixJSON; }[]'.
>       Type '{ weight: { rows: number; columns: number; weights: Float32Array; }; transition: { rows: number; columns: number; weights: Float32Array; }; bias: { rows: number; columns: number; weights: Float32Array; }; }' is not assignable to type '{ [index: string]: IMatrixJSON; }'.
>         Property 'weight' is incompatible with index signature.
>           Type '{ rows: number; columns: number; weights: Float32Array; }' is not assignable to type 'IMatrixJSON'.
>             Types of property 'weights' are incompatible.
>               Type 'Float32Array' is not assignable to type 'number[]'.
> 
> 57         new RNNTimeStep({ json });
>                              ~~~~
> 
> src/layer/dropout.ts:63:5 - error TS2554: Expected 2 arguments, but got 1.
> 
> 63     super(inputLayer);
>        ~~~~~~~~~~~~~~~~~
> 
>   src/layer/filter.ts:60:51
>     60   constructor(settings: Partial<IFilterSettings>, inputLayer: ILayer) {
>                                                          ~~~~~~~~~~~~~~~~~~
>     An argument for 'inputLayer' was not provided.
> 
> src/layer/fully-connected.ts:177:5 - error TS2554: Expected 2 arguments, but got 1.
> 
> 177     super(inputLayer);
>         ~~~~~~~~~~~~~~~~~
> 
>   src/layer/filter.ts:60:51
>     60   constructor(settings: Partial<IFilterSettings>, inputLayer: ILayer) {
>                                                          ~~~~~~~~~~~~~~~~~~
>     An argument for 'inputLayer' was not provided.
> 
> src/recurrent/rnn.ts:506:23 - error TS2345: Argument of type 'boolean | ((status: INeuralNetworkState) => void)' is not assignable to parameter of type 'boolean | Log | undefined'.
>   Type '(status: INeuralNetworkState) => void' is not assignable to type 'boolean | Log | undefined'.
>     Type '(status: INeuralNetworkState) => void' is not assignable to type 'Log'.
>       Types of parameters 'status' and 'status' are incompatible.
>         Type 'string' is not assignable to type 'INeuralNetworkState'.
> 
> 506     this.setLogMethod(options.log ?? this.trainOpts.log);
>                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/recurrent/rnn.ts:565:7 - error TS2322: Type 'Log' is not assignable to type 'boolean | ((status: INeuralNetworkState) => void)'.
>   Type 'Log' is not assignable to type '(status: INeuralNetworkState) => void'.
>     Types of parameters 'status' and 'status' are incompatible.
>       Type 'INeuralNetworkState' is not assignable to type 'string'.
> 
> 565       this.trainOpts.log = log;
>           ~~~~~~~~~~~~~~~~~~
> 
> 
> Found 9 errors.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! brain.js@2.0.0-beta.2 build:typings: `tsc --declaration --emitDeclarationOnly --declarationMap`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the brain.js@2.0.0-beta.2 build:typings script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\searc\AppData\Roaming\npm-cache\_logs\2021-01-28T02_26_21_168Z-debug.log
> ERROR: "build:typings" exited with 1.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! brain.js@2.0.0-beta.2 build: `run-p build:**`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the brain.js@2.0.0-beta.2 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\searc\AppData\Roaming\npm-cache\_logs\2021-01-28T02_26_21_314Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! brain.js@2.0.0-beta.2 dist: `npm run build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the brain.js@2.0.0-beta.2 dist script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\searc\AppData\Roaming\npm-cache\_logs\2021-01-28T02_26_21_337Z-debug.log
> `

AND THIS ERROR OCURS HERE

recurrent_deprecated/gru.ts 117 lines

`compare(json.input, net.model.input);`

recurrent_deprecated/gru.ts 124~125 lines

> `compare(json.output, net.model.output);
>  compare(json.outputConnector, net.model.outputConnector);`

How to Fix it? I think this is compiler can not know the type of values. And the type will be Matrix :(

**Comment by mubaidr** [comment]
Typescript conversion is still in progress, we are looking for contributions: https://github.com/BrainJS/brain.js/issues/684

**Comment by robertleeplummerjr** [comment]
This is no longer and issue, tested in 2.0.0-beta.12
