### ISSUE TITLE
TypeScript error using config when initializing NeuralNetwork

### ISSUE THREAD

**Issue by DenisTimofijuk** [BrainJS/brain.js#695]
## _What_ is wrong?

Typescript unable to recognize configurations when using those from git example.

## _Where_ does it happen?

When creating a simple feed forward neural network with backpropagation

## _How_ do we replicate the issue?

Run [example ](https://github.com/BrainJS/brain.js#examples) with TypeScript

## Other Comments

```
import brain from 'brain.js';
const config = {
  binaryThresh: 0.5,
  hiddenLayers: [3], // array of ints for the sizes of the hidden layers in the network
  activation: 'sigmoid', // supported activation types: ['sigmoid', 'relu', 'leaky-relu', 'tanh'],
  leakyReluAlpha: 0.01, // supported for activation type 'leaky-relu'
};
const network = new brain.NeuralNetwork(config);

/* TypeScript error:
const config: {
    binaryThresh: number;
    hiddenLayers: number[];
    activation: string;
    leakyReluAlpha: number;
}
Argument of type '{ binaryThresh: number; hiddenLayers: number[]; activation: string; leakyReluAlpha: number; }' is not assignable to parameter of type 'INeuralNetworkOptions'.
  Types of property 'activation' are incompatible.
    Type 'string' is not assignable to type '"sigmoid" | "relu" | "leaky-relu" | "tanh" | undefined'.ts(2345)
*/
```

**Comment by mubaidr** [comment]
Typescript conversion is still in progress, we are looking for contributions: https://github.com/BrainJS/brain.js/issues/684

**Comment by vorticalbox** [comment]
@mubaidr this is actually just a TS issue.

You need to tell typescript what the config is else it will just infer the types in this case, activation gets inferred as a string

```
import brain, { INeuralNetworkOptions } from 'brain.js';

// provide optional config object (or undefined). Defaults shown.
const config: INeuralNetworkOptions = {
  binaryThresh: 0.5,
  hiddenLayers: [3], // array of ints for the sizes of the hidden layers in the network
  activation: 'sigmoid', // supported activation types: ['sigmoid', 'relu', 'leaky-relu', 'tanh'],
  leakyReluAlpha: 0.01, // supported for activation type 'leaky-relu'
};
```

doing this also nets you auto complete when you set up your config

**Comment by robertleeplummerjr** [comment]
This should no longer be an issue.  Just tried with 2.0.0-beta.12 and got no typescript error.
<img width="826" alt="Screen Shot 2022-04-13 at 10 20 05 AM" src="https://user-images.githubusercontent.com/679099/163201613-ab35e942-ff5e-40e4-9e50-b43067d25cbd.png">
