### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by clive-g-brown** [BrainJS/brain.js#701]
Hi, any idea when the LSTM/GRU networks will work on GPU ?

thanks

**Comment by monckey100** [comment]
Bump, I've seen this issue outstanding since 2019:

#379   
#667   
  
With no official response, can we get a little context on where this is going?

**Comment by robertleeplummerjr** [comment]
I've not looked at the code in a while.  I essentially all the framework completed, and it works, but the networks don't always learn correctly.  I was somewhat hoping to collaborate to find where the issue may be (more brains are better than one).  If anyone wants to volunteer to help me work through the issue, let's set a date and tackle it!  In the mean time, I may have some time to continue looking into this in a few weeks.

**Comment by robertleeplummerjr** [comment]
Looking starting today.

**Comment by robertleeplummerjr** [comment]
I found a major issue and have resolved it here: https://github.com/BrainJS/brain.js/commit/87dcbfb3c81ade049924499e9a127abe62ebd626#diff-231ba92c55221a8c23bd822e4aa12c22ade0a5b3d1dbcdbfe5e1a7d509fdf648R415

Funny enough, it was a loop causing too much backpropagation.

**Comment by robertleeplummerjr** [comment]
Fixed and published: https://www.npmjs.com/package/brain.js/v/2.0.0-beta.5
