### ISSUE TITLE
BrainJS to detect PII

### ISSUE THREAD

**Issue by Mihailoff** [BrainJS/brain.js#702]
## Summary

Working with PII (personally identifiable information) is still a pain for developers. Both Google Cloud and AWS have REST APIs to detect PII, but to me this is an oxymoron, sending text data to the cloud to get responses back doesn't seem like a good concept from a privacy standpoint.

### Basic example

Email can be matched with a regexp. It is obvious today that neural nets do a way better job for other categories like names.

For example, there are open source lists of English first names. Should be straightforward to train an LSTM net. Any considerations in terms of speed, memory, production readiness?

### Motivation

This is not a feature request, more an inquiry for the community on how realistic it is with BrainJS today.

**Comment by vorticalbox** [comment]
LSTM networks aren't GPU accelerated so you will be in for a long train time if you use brainjs until it's supported

**Comment by robertleeplummerjr** [comment]
>This is not a feature request, more an inquiry for the community on how realistic it is with BrainJS today.

This is probably not very easy in its current state.
