### ISSUE TITLE
detect emotion, value return NaN

### ISSUE THREAD

**Issue by pioupia** [BrainJS/brain.js#703]
## _What_ is wrong?

Hello, I created a code to detect the emotions behind a message. With the brain.recurrent.LSTM function, it works well, but unfortunately, we don’t get a percentage chance that it’s mean or nice. So I decided to adapt my code to the brain.NeuralNetwork, thanks to a function that transforms all data into binary. Except that ! The returned value is NaN. How can I resolve this problem? If you want my code, I can provide it to you without any problem.

## _Where_ does it happen?

Nodejs version : v12.22.1
npm version : v6.14.12
brain.js version : 2.0.0-beta.2
os : ubuntu 18.04 and ubuntu 18.04 (server) and windows 10

## _How_ do we replicate the issue?

```js
var brain = require('brain.js');
const network = new brain.NeuralNetwork({});
const tdata = require("./src/tdata.js");
const serializer = require("./src/serializer.js");

network.train(serializer.serialize(tdata), {
  errorThresh: 0.005,  
  iterations: 200,  
  log: true,
  logPeriod: 10, 
  learningRate: 0.3
});

const gOb = network.run(serializer.encode("Salut !"));
console.log(gOb);
```

function serializer : 
```js
const fixLength = (data) => {
	let maxLenInput = -1;
	for(let i = 0; i < data.length; i++){
		if(data[i].input.length > maxLenInput){
			maxLenInput = data[i].input.length;
		}
	}

	for(let i = 0; i < data.length; i++){
		while(data[i].input.length < maxLenInput){
			data[i].input.push(0);
		}
	}

	return data;
}

const encode = d => {
	const theNewarray = [];
	d.split('').map(c => {
		theNewarray.push(
				(c.charCodeAt(0)/255)
			)
	});

	return theNewarray;
}

const encodeData = data => {
	return data.map(d => {
		return(
			{
				input: encode(d.input),
				output: d.output
			}
		)
	})
}

const serialize = data => fixLength(encodeData(data));

module.exports = {
	serialize, encode, fixLength
}
```

Exemple of data train : 
```json
{ input: "bad words x)", output: [0] }
{ input: "Oh ! You are beautiful", output: [1] }
```

Return : 
```sh
Float32Array(1) [ NaN ]
```

**Comment by baradm100** [comment]
Hi @pioupia,
I was able to recreate this issue locally and to resolve it.
Once I forced the input data for the `run` function to have the same size as the training data I got a valid response.

## General Note
For string-based learning, the better option is `LSTM`.
Please read more here: https://github.com/BrainJS/brain.js#for-training-with-rnn-lstm-and-gru

## My Code

```javascript
var brain = require("brain.js");
const network = new brain.NeuralNetwork({});
const tdata = [
  { input: "bad words x)", output: [0] },
  { input: "Oh ! You are beautiful", output: [1] },
];
const serializer = require("./serializer.js");

const data = serializer.serialize(tdata);

network.train(serializer.serialize(tdata), {
  errorThresh: 0.005,
  iterations: 200,
  log: true,
  logPeriod: 10,
  learningRate: 0.3,
});

const runData = serializer.encode("Salut !");

// Add `0` to the end of the `runData` in order to fit the input size
for (
  let i = runData.length;
  network.sizes[0]; // this uses the trained network input layer size
  i++
) {
  runData.push(0);
}

const gOb = network.run(runData);
console.log(gOb);
```

## Why it works?
The neural network has a set of "inputs" and a set of "outputs", in your example you have 22 inputs (the maximum length of the example data you provided) and 1 output.

The run data that you ran on only has 7 inputs, this means that for the other missing inputs the value that will be run in the trained network will be `undefined`.

To make sure you're getting the correct value, make sure the expected number of inputs are matched to the network inputs
