### ISSUE TITLE
LSTM training not using available resources

### ISSUE THREAD

**Issue by KCGD** [BrainJS/brain.js#704]
![A GIF or MEME to give some spice of the internet](https://media.tenor.co/videos/93dd69d51af4080b18eddd17fdb08c5b/mp4)

## _What_ is wrong?

The AI training only uses about 15% of the CPU, i get that LSTM networks arent GPU accelerated yet but it could be going
so much faster if it actually used more of the CPU

## _Where_ does it happen?

It happens on nodejs 12.18.0 so far, havent tested other versions yet

## _How_ do we replicate the issue?

train an LSTM network on a really large dataset
open task manager
see how it has very low cpu usage

## Expected behavior (i.e. solution)

I expected it to use all the resources available to it but it doesn't

## _How_ important is this (1-5)?

3.5, it isn't essential for it to work (the network trains fine) but it can be so much more efficient

## Other Comments

yep thats it

**Comment by mubaidr** [comment]
CPU training is single threaded. We had plans to implement Multi-threaded training (a demo is already ready) but it is delayed because of lack of resources. 

Details: [New Feature: Multithreaded Training](https://github.com/BrainJS/brain.js/issues/417)
