### ISSUE TITLE
Probability Default Feature

### ISSUE THREAD

**Issue by RaxoCoding** [BrainJS/brain.js#711]
Have a feature where you can see the probability of the choice it chose so for example it i 90% sure or 34% sure. and add a default value if not > 75% sure

**Comment by vorticalbox** [comment]
not sure this is needed if you normalize your inputs between 0 - 7 anything that is 0.75 or higher is 75% and you can just return whatever you like.

**Comment by robertleeplummerjr** [comment]
This is an ability by default with standard classification with either a single output.  We'd need more clarification to understand what you are trying to accomplish.
