### ISSUE TITLE
deep q learning network

### ISSUE THREAD

**Issue by ashkanpower** [BrainJS/brain.js#714]
Hey guys, I was wondering if anybody found a way to create a deep q network with brain.js.

and if not can anybody suggest a way to implement something like this :

```
model = Sequntial()

model.add(Dense(24, input_dim = 4, activation='relu'))
model.add(Dense(24, activation='relu'))
model.add(Dense( 3, activation='linear'))

```

**Comment by vicary** [comment]
@ashkanpower did you find a way to incrementally mutate the network without using the train function?

**Comment by robertleeplummerjr** [comment]
>Hey guys, I was wondering if anybody found a way to create a deep q network with brain.js.

We have not.

**Comment by brandonros** [comment]
Are there plans for this repo to support Deep Q-Learning?
