### ISSUE TITLE
TrainAsync does not work

### ISSUE THREAD

**Issue by DanielHaitink** [BrainJS/brain.js#721]
## _What_ is wrong?

`trainAsync()` does not work for `NeuralNetworkGPU` and `NeuralNetwork`, using brain-browser.js

```
TypeError: Thaw$1 is not a constructor
    at new Promise (<anonymous>)
    at NeuralNetwork.trainAsync 
```

Line 29467 in `brain-browser.js`

## _Where_ does it happen?

In both NeuralNetworkGPU and NeuralNetwork when running in the browser (chrome and firefox) on windows 10.

## _How_ do we replicate the issue?

- Create Network
- run trainAsync()
- Crashes at Thaw$1 construction

## Expected behavior (i.e. solution)

Running the training async.

## _How_ important is this (1-5)?

3

**Comment by bobbjedi** [comment]
Confirm, some.

**Comment by m-ahmadi** [comment]
Same issue for me as well. 
Using `brain.js@2.0.0-beta.2/dist/brain-browser.js`:

![be](https://user-images.githubusercontent.com/16363767/128316034-1b238a15-2076-4419-8f66-11ca7b32e8c5.png)

**Comment by rentalhost** [comment]
It fails for `beta.2`, but works for `beta.1`.

**Comment by robertleeplummerjr** [comment]
This has been resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.11.  Here is a working example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-721
