### ISSUE TITLE
TrainStream: discard old data

### ISSUE THREAD

**Issue by rentalhost** [BrainJS/brain.js#722]
Hi, I would like to know if it would be possible to train in real time using `TrainStream` or similar so that it only considers the last written records.

For example, initially a training set with _60 records_ would be sent, and every minute, _1 new set_ would be write and the oldest set would be removed.

Meanwhile, training would be going on with the number of interactions `Number.MAX_SAFE_INTEGER` and the error rate close to zero, so the process never stops (this problem is already solved).

```js
// Every minute:
trainingSet = trainingSet.slice(1).concat([ newRecord ]);
```

In addition to the error rate, I made a script that checks if the input data has a high assertiveness in relation to prediction. However, only the latest records should be taken into account. In the meantime, my idea is to restart the training process every minute, but I don't think it's the best way.

**Comment by robertleeplummerjr** [comment]
TrainStream has moved: https://github.com/BrainJS/train-stream
It sounds like you just want to train up something, and then just use `.train()`, on that trained network.  Yes you can do that.
