### ISSUE TITLE
Different Outputs Each Run

### ISSUE THREAD

**Issue by DaveBben** [BrainJS/brain.js#73]
Is it normal to get different outputs each time you run this?

I have the following code that's trying to predict how long it will take me to complete a run. My input is a percentage of my distance range (0 -5 miles) and my output is a percentage of my time range (0 -60 minutes).

```
const brain = require('brain.js');

var net = new brain.NeuralNetwork();

let ops = [
    { input: [.7], output: [.5] },
    { input: [.71], output: [.5] },
    { input: [.708], output: [.5] },
    { input: [.704], output: [.53] },
    { input: [.708], output: [.53] },
    { input: [.68], output: [.55] },
    { input: [.58], output: [.46] },
    { input: [.7], output: [.55] },
]

net.train(ops, { log: true });

var output = net.run([.64]);  

console.log(output);

```
My output ranges from 0.47 - 0.54. Do I need more data?

**Comment by wagenaartje** [comment]
Weights are initialised differently everytime you create a network. So running this code will result in a different output every time.

> Do I need more data?

Yes. With only 8 training samples your network will overfit easily. So make a few runs to collect some more data and you're good to go :wink:

**Comment by DaveBben** [comment]
Ok okay! Thanks! I also found that if I lowered the error threshold and cap the iterations, it seems to be consistent.

` errorThresh: 0.0001,  iterations: 50`
