### ISSUE TITLE
Typescript compilation no longer works for beta3

### ISSUE THREAD

**Issue by petemorrisuom** [BrainJS/brain.js#730]
Hi there, as of beta3 release, tsc no longer works. Beta2 worked fine. Adding skipLibCheck doesn't seem to fix anything. I have strict mode turned on, but I wouldn't expect beta2 to work fine and beta3 to fail? Here are the errors:

node_modules/brain.js/src/layer/base-layer.ts:206:16 - error TS6133: 'isTraining' is declared but its value is never read.

206   setupKernels(isTraining?: boolean): void {}
                   ~~~~~~~~~~

node_modules/brain.js/src/layer/base-layer.ts:238:11 - error TS6133: 'inputs' is declared but its value is never read.

238   predict(inputs?: KernelOutput): void {}
              ~~~~~~

node_modules/brain.js/src/layer/base-layer.ts:240:11 - error TS6133: 'targetValues' is declared but its value is never read.

240   compare(targetValues?: KernelOutput): void {}
              ~~~~~~~~~~~~

node_modules/brain.js/src/layer/multiply.ts:61:13 - error TS6133: 'width' is declared but its value is never read.

61   set width(width: number) {
               ~~~~~

node_modules/brain.js/src/layer/multiply.ts:69:14 - error TS6133: 'height' is declared but its value is never read.

69   set height(height: number) {
                ~~~~~~

node_modules/brain.js/src/layer/multiply.ts:77:13 - error TS6133: 'depth' is declared but its value is never read.

77   set depth(depth: number) {
               ~~~~~

node_modules/brain.js/src/layer/recurrent-connection.ts:19:13 - error TS6133: 'value' is declared but its value is never read.

19   set width(value: number) {
               ~~~~~

node_modules/brain.js/src/layer/recurrent-connection.ts:28:14 - error TS6133: 'value' is declared but its value is never read.

28   set height(value: number) {
                ~~~~~

node_modules/brain.js/src/neural-network-gpu.ts:683:3 - error TS2578: Unused '@ts-expect-error' directive.

683   // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~

node_modules/brain.js/src/neural-network.ts:1186:44 - error TS6133: 'layerWeights' is declared but its value is never read.

1186     const layerWeights = this.weights.map((layerWeights, layerIndex) => {
                                                ~~~~~~~~~~~~

node_modules/brain.js/src/neural-network.ts:1191:42 - error TS6133: 'layerBiases' is declared but its value is never read.

1191     const layerBiases = this.biases.map((layerBiases, layerIndex) =>
                                              ~~~~~~~~~~~

node_modules/brain.js/src/recurrent.ts:250:12 - error TS6133: 'input' is declared but its value is never read.

250   runInput(input: KernelOutput): KernelOutput {
               ~~~~~

node_modules/brain.js/src/train-stream.ts:98:5 - error TS6133: 'enc' is declared but its value is never read.

98     enc: BufferEncoding,
       ~~~

node_modules/brain.js/src/utilities/data-formatter.ts:293:32 - error TS2339: Property 'flat' does not exist on type 'string[][]'.

293       ? (values as string[][]).flat()
                                   ~~~~

node_modules/brain.js/src/utilities/data-formatter.ts:364:17 - error TS6133: 'input' is declared but its value is never read.

364   formatDataOut(input: number[], output: number[]): string {
                    ~~~~~


Found 15 errors.

**Comment by lynellf** [comment]
Brain.js' module exports have changed between ^2.0.0-beta.2 and ^2.0.0-beta.3.

It's a breaking change for sure.

**Comment by gavin-rose** [comment]
Definitely a breaking change. I will continue to use brain.js@2.0.0-beta.2 until documentation and examples are updated.

**Comment by robertleeplummerjr** [comment]
Try Just published https://www.npmjs.com/package/brain.js/v/2.0.0-beta.4.  Ty
