### ISSUE TITLE
brain.recurrent.LSTM() is not working

### ISSUE THREAD

**Issue by anastasiiamay** [BrainJS/brain.js#733]
### Discussed in https://github.com/BrainJS/brain.js/discussions/732

<div type='discussions-op-text'>

<sup>Originally posted by **anastasiiamay** September 24, 2021</sup>
I took an example from brain.js.org, but got error when tried to use it. Error occurs because of this line:
`const lstm = new brain.recurrent.LSTM();`
Error is:
`Cannot read property 'LSTM' of undefined`
So I tried to run your example on your website. And also got error:
`Uncaught TypeError: Cannot read properties of undefined (reading 'LSTM')`
Can someone tell me please am I doing something wrong?</div>

**Comment by gavin-rose** [comment]
@anastasiiamay I am unfortunately getting the same exact error. Logging the library, you can see what is available from the package...

Gavins-MBP:forex-thread Rose$ node test.js
{
  brain: {
    activation: [Object: null prototype] {
      relu: [Object: null prototype],
      sigmoid: [Object: null prototype],
      tanh: [Object: null prototype],
      leakyRelu: [Object: null prototype]
    },
    CrossValidate: [class CrossValidate] {
      isBinaryStats: [Function (anonymous)],
      isBinaryResults: [Function (anonymous)],
      isBinaryPartitionResults: [Function (anonymous)]
    },
    likely: [Function: likely],
    layer: [Object: null prototype] {
      layerTypes: [Object],
      Add: [class Add extends Operator],
      add: [Function: add$1],
      arthurFeedForward: [Function: arthurFeedForward],
      BaseLayer: [class BaseLayer],
      baseLayerDefaultSettings: [Object],
      Convolution: [class Convolution extends Filter],
      convolution: [Function: convolution],
      Dropout: [class Dropout extends Filter],
      dropout: [Function: dropout],
      feedForward: [Function: feedForward],
      FullyConnected: [class FullyConnected extends Filter],
      fullyConnected: [Function: fullyConnected],
      gru: [Function: gru],
      Input: [class Input extends EntryPoint],
      input: [Function: input],
      LeakyRelu: [class LeakyRelu extends Activation],
      leakyRelu: [Function: leakyRelu],
      lstmCell: [Function: lstmCell],
      Multiply: [class Multiply extends Operator],
      multiply: [Function: multiply$1],
      MultiplyElement: [class MultiplyElement extends Operator],
      multiplyElement: [Function: multiplyElement$1],
      Negative: [class Negative extends Modifier],
      negative: [Function: negative],
      Ones: [class Ones extends Model],
      ones: [Function: ones],
      output: [Function: output],
      Pool: [class Pool extends Filter],
      pool: [Function: pool],
      Random: [class Random extends Model],
      random: [Function: random],
      RecurrentInput: [class RecurrentInput extends Internal],
      RecurrentZeros: [class RecurrentZeros extends Internal],
      rnnCell: [Function: rnnCell],
      Regression: [class Regression extends BaseLayer],
      regression: [Function: regression],
      Relu: [class Relu extends Activation],
      relu: [Function: relu$1],
      Sigmoid: [class Sigmoid extends Activation],
      sigmoid: [Function: sigmoid$1],
      SoftMax: [class SoftMax extends Modifier],
      softMax: [Function: softMax],
      SVM: [class SVM extends BaseLayer],
      svm: [Function: svm],
      Tanh: [class Tanh extends Activation],
      tanh: [Function: tanh$1],
      Target: [class Target extends BaseLayer],
      target: [Function: target],
      Transpose: [class Transpose extends Modifier],
      transpose: [Function: transpose],
      Zeros: [class Zeros extends Model],
      zeros: [Function: zeros]
    },
    layerTypes: {
      Activation: [class Activation extends BaseLayer],
      Internal: [class Internal],
      InternalModel: [class InternalModel],
      EntryPoint: [class EntryPoint extends BaseLayer],
      Filter: [class Filter extends BaseLayer],
      Model: [class Model extends BaseLayer],
      Modifier: [class Modifier extends BaseLayer],
      Operator: [class Operator extends BaseLayer],
      Target: [class Target extends BaseLayer]
    },
    lookup: {
      toTable: [Function: toTable],
      toTable2D: [Function: toTable2D],
      toInputTable2D: [Function: toInputTable2D],
      toOutputTable2D: [Function: toOutputTable2D],
      toHash: [Function: toHash],
      toArray: [Function: toArray],
      toArrayShort: [Function: toArrayShort],
      toArrays: [Function: toArrays],
      toObject: [Function: toObject],
      toObjectPartial: [Function: toObjectPartial],
      dataShape: [Function: dataShape],
      addKeys: [Function: addKeys]
    },
    praxis: [Object: null prototype] {
      ArthurDeviationBiases: [class ArthurDeviationBiases extends BasePraxis],
      arthurDeviationBiases: [Function: arthurDeviationBiases],
      ArthurDeviationWeights: [class ArthurDeviationWeights extends BasePraxis],
      arthurDeviationWeights: [Function: arthurDeviationWeights],
      MomentumRootMeanSquaredPropagation: [class MomentumRootMeanSquaredPropagation extends BasePraxis],
      momentumRootMeanSquaredPropagation: [Function: momentumRootMeanSquaredPropagation],
      MRmsProp: [class MomentumRootMeanSquaredPropagation extends BasePraxis],
      mRmsProp: [Function: momentumRootMeanSquaredPropagation]
    },
    FeedForward: [class FeedForward],
    NeuralNetwork: [class NeuralNetwork],
    NeuralNetworkGPU: [class NeuralNetworkGPU extends NeuralNetwork],
    Recurrent: [class Recurrent extends FeedForward],
    TrainStream: [class TrainStream extends Writable],
    recurrent: {
      RNNTimeStep: [class RNNTimeStep extends RNN],
      LSTMTimeStep: [class LSTMTimeStep extends RNNTimeStep],
      GRUTimeStep: [class GRUTimeStep extends RNNTimeStep],
      RNN: [class RNN],
      LSTM: [class LSTM extends RNN],
      GRU: [class GRU extends RNN]
    },
    utilities: {
      max: [Function: max],
      mse: [Function: mse$1],
      ones: [Function: ones$1],
      ones2D: [Function: ones2D],
      random: [Object: null prototype],
      randomWeight: [Function: randomWeight],
      randos: [Function: randos],
      range: [Function: range],
      toArray: [Function: toArray],
      DataFormatter: [class DataFormatter],
      zeros: [Function: zeros$1],
      toSVG: [Function: toSVG]
    }
  },
  default: {
    activation: [Object: null prototype] {
      relu: [Object: null prototype],
      sigmoid: [Object: null prototype],
      tanh: [Object: null prototype],
      leakyRelu: [Object: null prototype]
    },
    CrossValidate: [class CrossValidate] {
      isBinaryStats: [Function (anonymous)],
      isBinaryResults: [Function (anonymous)],
      isBinaryPartitionResults: [Function (anonymous)]
    },
    likely: [Function: likely],
    layer: [Object: null prototype] {
      layerTypes: [Object],
      Add: [class Add extends Operator],
      add: [Function: add$1],
      arthurFeedForward: [Function: arthurFeedForward],
      BaseLayer: [class BaseLayer],
      baseLayerDefaultSettings: [Object],
      Convolution: [class Convolution extends Filter],
      convolution: [Function: convolution],
      Dropout: [class Dropout extends Filter],
      dropout: [Function: dropout],
      feedForward: [Function: feedForward],
      FullyConnected: [class FullyConnected extends Filter],
      fullyConnected: [Function: fullyConnected],
      gru: [Function: gru],
      Input: [class Input extends EntryPoint],
      input: [Function: input],
      LeakyRelu: [class LeakyRelu extends Activation],
      leakyRelu: [Function: leakyRelu],
      lstmCell: [Function: lstmCell],
      Multiply: [class Multiply extends Operator],
      multiply: [Function: multiply$1],
      MultiplyElement: [class MultiplyElement extends Operator],
      multiplyElement: [Function: multiplyElement$1],
      Negative: [class Negative extends Modifier],
      negative: [Function: negative],
      Ones: [class Ones extends Model],
      ones: [Function: ones],
      output: [Function: output],
      Pool: [class Pool extends Filter],
      pool: [Function: pool],
      Random: [class Random extends Model],
      random: [Function: random],
      RecurrentInput: [class RecurrentInput extends Internal],
      RecurrentZeros: [class RecurrentZeros extends Internal],
      rnnCell: [Function: rnnCell],
      Regression: [class Regression extends BaseLayer],
      regression: [Function: regression],
      Relu: [class Relu extends Activation],
      relu: [Function: relu$1],
      Sigmoid: [class Sigmoid extends Activation],
      sigmoid: [Function: sigmoid$1],
      SoftMax: [class SoftMax extends Modifier],
      softMax: [Function: softMax],
      SVM: [class SVM extends BaseLayer],
      svm: [Function: svm],
      Tanh: [class Tanh extends Activation],
      tanh: [Function: tanh$1],
      Target: [class Target extends BaseLayer],
      target: [Function: target],
      Transpose: [class Transpose extends Modifier],
      transpose: [Function: transpose],
      Zeros: [class Zeros extends Model],
      zeros: [Function: zeros]
    },
    layerTypes: {
      Activation: [class Activation extends BaseLayer],
      Internal: [class Internal],
      InternalModel: [class InternalModel],
      EntryPoint: [class EntryPoint extends BaseLayer],
      Filter: [class Filter extends BaseLayer],
      Model: [class Model extends BaseLayer],
      Modifier: [class Modifier extends BaseLayer],
      Operator: [class Operator extends BaseLayer],
      Target: [class Target extends BaseLayer]
    },
    lookup: {
      toTable: [Function: toTable],
      toTable2D: [Function: toTable2D],
      toInputTable2D: [Function: toInputTable2D],
      toOutputTable2D: [Function: toOutputTable2D],
      toHash: [Function: toHash],
      toArray: [Function: toArray],
      toArrayShort: [Function: toArrayShort],
      toArrays: [Function: toArrays],
      toObject: [Function: toObject],
      toObjectPartial: [Function: toObjectPartial],
      dataShape: [Function: dataShape],
      addKeys: [Function: addKeys]
    },
    praxis: [Object: null prototype] {
      ArthurDeviationBiases: [class ArthurDeviationBiases extends BasePraxis],
      arthurDeviationBiases: [Function: arthurDeviationBiases],
      ArthurDeviationWeights: [class ArthurDeviationWeights extends BasePraxis],
      arthurDeviationWeights: [Function: arthurDeviationWeights],
      MomentumRootMeanSquaredPropagation: [class MomentumRootMeanSquaredPropagation extends BasePraxis],
      momentumRootMeanSquaredPropagation: [Function: momentumRootMeanSquaredPropagation],
      MRmsProp: [class MomentumRootMeanSquaredPropagation extends BasePraxis],
      mRmsProp: [Function: momentumRootMeanSquaredPropagation]
    },
    FeedForward: [class FeedForward],
    NeuralNetwork: [class NeuralNetwork],
    NeuralNetworkGPU: [class NeuralNetworkGPU extends NeuralNetwork],
    Recurrent: [class Recurrent extends FeedForward],
    TrainStream: [class TrainStream extends Writable],
    recurrent: {
      RNNTimeStep: [class RNNTimeStep extends RNN],
      LSTMTimeStep: [class LSTMTimeStep extends RNNTimeStep],
      GRUTimeStep: [class GRUTimeStep extends RNNTimeStep],
      RNN: [class RNN],
      LSTM: [class LSTM extends RNN],
      GRU: [class GRU extends RNN]
    },
    utilities: {
      max: [Function: max],
      mse: [Function: mse$1],
      ones: [Function: ones$1],
      ones2D: [Function: ones2D],
      random: [Object: null prototype],
      randomWeight: [Function: randomWeight],
      randos: [Function: randos],
      range: [Function: range],
      toArray: [Function: toArray],
      DataFormatter: [class DataFormatter],
      zeros: [Function: zeros$1],
      toSVG: [Function: toSVG]
    }
  }
}

Notice that while 'recurrent shows in the packages available classes, methods, and functions, it simplly doesn't work. The latest update to this library was a little over a week ago. 

**_I got it working by installing the second-most recent package. npm install brain.js@2.0.0-beta.2_**

**Comment by gavin-rose** [comment]
@anastasiiamay,
I got it working by installing the second-most recent package. npm install brain.js@2.0.0-beta.2

Didn't realize how much space my previous reply would take up.

**Comment by kamit-transient** [comment]
In recent versions of brain.js you can try like below.


```
const brain = require("brain.js").brain;

var net = new brain.recurrent.LSTM();

```

Note the import, first line.

**Comment by gavin-rose** [comment]
> In recent versions of brain.js you can try like below.
> 
> ```
> const brain = require("brain.js").brain;
> 
> var net = new brain.recurrent.LSTM();
> ```
> 
> Note the import, first line.

@kamit-transient, that isn't the issue here. The latest brain.js version is broken.

**Comment by ghost** [comment]
> 
> ### Discussed in #732
> 
> Originally posted by **anastasiiamay** September 24, 2021 I took an example from brain.js.org, but got error when tried to use it. Error occurs because of this line: `const lstm = new brain.recurrent.LSTM();` Error is: `Cannot read property 'LSTM' of undefined` So I tried to run your example on your website. And also got error: `Uncaught TypeError: Cannot read properties of undefined (reading 'LSTM')` Can someone tell me please am I doing something wrong?

You probably didn't import brain.js, and if you did, it's probably the fact that it is now require("brain.js").brain.recurrent.LSTM();

**Comment by robertleeplummerjr** [comment]
This has been resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.11

**Comment by retrievaaaa** [comment]
Getting this error again. Installing beta.2 works fine.

**Comment by SudhanshuBlaze** [comment]
SOLVED for React users, use the brain.js CDN by including it in index.html:

`    const net = new window.brain.recurrent.RNN();
` 

Don't forget to use the **window** keyword.

**Comment by retrievaaaa** [comment]
How is that solved? Not everyone is using React, lol

**Comment by riyanswat** [comment]
> How is that solved? Not everyone is using React, lol

true.. i dont use react.  the CDN just works fine for `NeuralNetwork()` class but not for `recurrent.LSTM()`.....  and npm just wont work. npm throws the following error, idk why:

```
PS E:\DESKTOP\soft-hard-ware> npm i brain.js
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path E:\DESKTOP\soft-hard-ware\node_modules\gl
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.8.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.13 found at "C:\Users\Eagle computers\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (E:\DESKTOP\soft-hard-ware\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at E:\DESKTOP\soft-hard-ware\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (E:\DESKTOP\soft-hard-ware\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at E:\DESKTOP\soft-hard-ware\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at E:\DESKTOP\soft-hard-ware\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at E:\DESKTOP\soft-hard-ware\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at E:\DESKTOP\soft-hard-ware\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "E:\\SOFTS_TO_INSTALL\\node.exe" "E:\\DESKTOP\\soft-hard-ware\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd E:\DESKTOP\soft-hard-ware\node_modules\gl
npm ERR! gyp ERR! node -v v18.8.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Riyan\AppData\Local\npm-cache\_logs\2022-09-03T18_56_42_104Z-debug-0.log
```

**Comment by Radulepy** [comment]
> This has been resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.11

Nope, i have the same error! `version": "2.0.0-beta.11",`

**Comment by Radulepy** [comment]
What helped me is access default brain module:

`const network = new brain.default.recurrent.RNN();`
