### ISSUE TITLE
Network.run doesn't work

### ISSUE THREAD

**Issue by OguzhanUmutlu** [BrainJS/brain.js#746]
![](https://tenor.com/view/but-why-why-scream-mad-annoyed-gif-15498922)

## _What_ is wrong?

```js
// input is Array<0 to 1> Length: 128
// output is string
network.train([{
  input, output
}], {
  iterations: 1000,
  log: true
});

// input is Array<0 to 1> Length: 128
console.log(network.run(input));
```

## _Where_ does it happen?

Network.run function returns `{0: NaN}`

## _How_ do we replicate the issue?

- Create network
- Train with an array that includes numbers from 0 to 1 and a string
- Run and log the network with an array that includes numbers from 0 to 1

## Expected behavior (i.e. solution)

It should've sent like `{0: 0.34, 1: 2.45}`, i guess?

## _How_ important is this (1-5)?

4

## Other comments

Full code: https://github.com/OguzhanUmutlu/ImageGuessAI

**Comment by robertleeplummerjr** [comment]
What does your training data look like?  When using `NeuralNetwork` they will need to be the same length.

**Comment by robertleeplummerjr** [comment]
There are many unit tests that show this to be working.  Unless more insight comes to light, we'll go ahead and close this issue.
