### ISSUE TITLE
NeuralNetworkGPU does not work when using the brain.js package through CDN

### ISSUE THREAD

**Issue by Nelias** [BrainJS/brain.js#747]
## _What_ is wrong?

NeuralNetworkGPU does not detect the gpu.js when using the brain.js package through CDN.

When this code is exectued:
```
            const network = new brain.NeuralNetworkGPU({
                activation: 'sigmoid',
                hiddenLayers: [4],
                learningRate: 0.6,
            });
```

## _How_ do we replicate the issue?

<img width="516" alt="brain-js-cdn-gpu" src="https://user-images.githubusercontent.com/23236940/144729681-482f5576-fa5d-47b5-925c-772256225546.png">

- Add ` <script src="https://unpkg.com/brain.js"></script>` to your HTML file then try to create the new NeuralNetworkGPU in next `<script>` tag.

## Expected behavior (i.e. solution)

The documentation has to be updated with the CDN gpu.js package or maybe it should somehow link that package from brain.js itself.

## _How_ important is this (1-5)?

4

**Comment by robertleeplummerjr** [comment]
This has been resolved in the latest version of brain.js https://www.npmjs.com/package/brain.js/v/2.0.0-beta.11.  Here is a working version: https://observablehq.com/@robertleeplummerjr/brain-js-issue-747
