### ISSUE TITLE
LSTM model returning empty output

### ISSUE THREAD

**Issue by UP941594** [BrainJS/brain.js#749]
![A GIF or MEME to give some spice of the internet](url)

## _What_ is wrong?
LSTM model returning empty output. 

## _Where_ does it happen?
when the model has been trained. I am trying to run `net.run(data)` but it return empty in command line. 

## _How_ do we replicate the issue?

- Step 1
- Step 2
- Step 3

## Expected behavior (i.e. solution)

I am expecting an output or at least an error if the model cannot classify the data. 
## _How_ important is this (1-5)?

 5 
## Other Comments

I am using this model for my final year project at University so its very important.

**Comment by Nelias** [comment]
Paste an example of your {input: [], output: []} object, maybe those two values have to return the same type but indeed there should be an error or some kind of response even if it was set up in a wrong way.

**Comment by UP941594** [comment]
Hi Nelias,
Thanks for helping. 
I have an array as an input and an array as an output. 
The length of input arrays varies from 129 to 235. 

`const dataset = [
 {input: [-0.04145152278764286,
            -0.04145152278764286,
            0.02931191649103404,
            0.025314243671365394,
            0.09964059565399563,
            0.13279864523813079,
             220 more items],
output: [0,0,1]},
 {input: [-0.07838869117980984,
            -0.07838869117980984,
            0.005700191047779968,
            0.16397912434852924,
            0.16847045770006555,
             190 more items],
output: [0,1,0]}]`

The size of `dataset `variable is 24. 

Below is the code for training LSTM. 
```
const net = new brain.recurrent.LSTM({
  inputSize: 235,
  inputRange: 24,
  hiddenLayers: [5]
});

net.train(dataset, {
  // Defaults values --> expected validation
  iterations: 2000, // the maximum times to iterate the training data --> number greater than 0
  errorThresh: 0.005, // the acceptable error percentage from training data --> number between 0 and 1
  log: true, // true to use console.log, when a function is supplied it is used --> Either true or a function
  logPeriod: 1, // iterations between logging out --> number greater than 0
  learningRate: 0.3, // scales with delta to effect training rate --> number between 0 and 1
  momentum: 0.1, // scales with next layer's change value --> number between 0 and 1
  callback: null, // a periodic call back that can be triggered while training --> null or function
  callbackPeriod: 10, // the number of iterations through the training data between callback calls --> number greater than 0
  timeout: Infinity, // the max number of milliseconds to train for --> number greater than 0
});
```

When I test this model with another array from testing data. The model returns empty output and I have tried different types of arrays as well.

**Comment by robertleeplummerjr** [comment]
You need to not use `brain.recurrent.LSTM`, but rather `brain.recurrent.LSTMTimeStep`.  A LSTM network deals with strings, where a LSTMTimeStep deals with numbers.
