### ISSUE TITLE
toSVG returns error: sizes not set correctly

### ISSUE THREAD

**Issue by DanielHaitink** [BrainJS/brain.js#751]
## _What_ is wrong?

`brain.utilities.toSVG(net)` gives an error: 
```
Uncaught Error: sizes not set correctly
    at checkSizes (brain-browser-new.js:9348)
    at Object.toSVG (brain-browser-new.js:9340)
    at Network.getSVG (emote.js:46)
    at Emote.showSVG (emote.js:539)
    at HTMLButtonElement.onclick (index.html?_ijt=idpod1bos59nhdb2r6if0ciohu:43)
```

## _Where_ does it happen?

In brain.utilities.toSVG()

## _How_ do we replicate the issue?

- create network `net = new brain.NeuralNetwork({hiddenLayers: [5]});`
- draw svg `return brain.utilities.toSVG(net);`

## Expected behavior (i.e. solution)

It should have returned an SVG.

## _How_ important is this (1-5)? 

3

**Comment by chapman** [comment]
Just hit this myself when I changed from one to two hidden layers. 

In my case calling brain.utilities.toSVG(net.toJSON()) worked around it.

**Comment by robertleeplummerjr** [comment]
Can you please post how your networks are defined?

**Comment by robertleeplummerjr** [comment]
In either case this has been resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.11.  Here is a working example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-751-tosvg
