### ISSUE TITLE
How do I import and use brain in a React app?

### ISSUE THREAD

**Issue by grmatthews** [BrainJS/brain.js#752]
I have been through all the doc, and searched the Internet far and wide but cannot find a simple 5 line example (or any examples at all) that show how to use brain.js in a React app (normal web app, not native).

Here's what I've tried

Install
-------
npm install brain.js, then verified it's installed via npm list

Code
------
import brain from "brain.js"

...

const handleTrainBrain = () => {
    const net = new brain.NeuralNetwork();
}

Error received when this is run
---------------------------------

Uncaught TypeError: brain_js__WEBPACK_IMPORTED_MODULE_24__.default.NeuralNetwork is not a constructor

This is received on the 'const net....' line

Expected behaviour
----------------------
There'd be some doco on importing brain.js into a React apps. I could be doing something stupid. Any advice appreciated.

**Comment by grmatthews** [comment]
Also, importing like this..

import { brain } from "brain.js"

...gives this error...

Attempted import error: 'brain' is not exported from 'brain.js'.

**Comment by iagormoraes** [comment]
> Also, importing like this..
> 
> import { brain } from "brain.js"
> 
> ...gives this error...
> 
> Attempted import error: 'brain' is not exported from 'brain.js'.

@grmatthews try to `import * as brain from 'brain.js'`

**Comment by ChocolateLoverRaj** [comment]
@grmatthews This is what worked for me:
```js
import { NeuralNetworkGPU } from 'brain.js/dist/brain-browser.mjs'
```

**Comment by klappy** [comment]
downgraded to v1.4.10 and it worked for me...

**Comment by robertleeplummerjr** [comment]
Looking at this now.

**Comment by robertleeplummerjr** [comment]
This should be resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.6.

**Comment by robertleeplummerjr** [comment]
Via: https://github.com/BrainJS/brain.js/pull/775
