### ISSUE TITLE
models example for home listings application

### ISSUE THREAD

**Issue by zourdyzou** [BrainJS/brain.js#753]
Hi there, 

I am currently building an application for home renting / listings and I just want to know what is the perfect models to do so or is it possible to implement such machine learning models with this library?

thank you...

#curious #needadvice

**Comment by robertleeplummerjr** [comment]
What data do you have available?  What are you trying to estimate?

**Comment by robertleeplummerjr** [comment]
To be clear, this is absolutely a problem a feed forward neural network could be able to handle.  The thing you'd need is a good amount of data: features of homes, location, pricing, etc.  If that doesn't answer your question let me know.  This would be a fun problem to solve with machine learning.
