### ISSUE TITLE
New example: Detecting the general color of an image

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [BrainJS/brain.js#754]
![A GIF or MEME to give some spice of the internet](https://user-images.githubusercontent.com/52586855/148579630-9a852952-b9f3-411e-90c5-4cda0207ec30.png)

## Summary
[I used brain.js to train a nueral network which can know the main color of an image](https://github.com/ChocolateLoverRaj/detect-image-color). I am wondering if it could be added to the examples.

### Motivation
Currently there are no examples which use images as inputs. The example can help people who want to make something similar, and show that it's possible to use Brain.js with images (not as advanced as #352, but still uses images with <10 min training time when I ran it).

**Comment by robertleeplummerjr** [comment]
Do you have a link to it working in a browser?

**Comment by ChocolateLoverRaj** [comment]
@robertleeplummerjr The code is meant to run in Node.js, but I could make it a webpage if needed. This is the link to the github repo with the code: https://github.com/ChocolateLoverRaj/detect-image-color.

**Comment by robertleeplummerjr** [comment]
Do you want to open a PR with the link added in the readme?  We love contributors.

**Comment by ChocolateLoverRaj** [comment]
@robertleeplummerjr I will
