### ISSUE TITLE
Training too slow, even using Train Stream

### ISSUE THREAD

**Issue by teeban10** [BrainJS/brain.js#756]
I have an array input with a size of 13, 000 as training data. And the problem is training time takes more than 30 minutes. Is there a way to improve this

**Input example**
```
[{
    "input": {
      "Luis,Arce,Bolivia,Sunday,La,Paz,Karl,Marx,Arce,Evo,Morales,Arce,Morales,Movement,Socialism,Arce,Sunday,Morales,Argentina,Evo,Friday,Arce,Bolivia,Morales,Aymara,Argentina,Peronist,President,Alberto,Fernandez,Paraguay,Mario,Abdo,Hassan,Rouhani,Spain,King,Felipe,Venezuela,Delcy,Rodríguez,Sunday,Karl,Marx,Arce,Reuters,October,Arce,Bolivia,South,America,Bolivia,America,Arce,Morales,Morales,Morales,Arce,La,Paz,Bolivia,Universidad,Mayor,Andrés,University,Warwick,England,Franklin,Pareja,La,Paz,Arce,Morales,Arce,Morales,Reuters,Morales,Reuters,Arce,World,Bank,Morales,Arce,Reuters": 1
    },
    "output": {
      "bolivia": 1
    }
  },
  {
    "input": {
      "Le,Tour,Langkawi,LTdL,Voyage,Sdn,Bhd,World,Tour,World,Tour,NTT,Cycling,LTdL,Feb,Cycling,Union,UCI,Series,ProSeries,Cycling,Federation,MNCF,Abu,Samah,Abdul,Wahab,LTdL,UCI,MNCF,Kazakhstan,Astana,Team,Australia,World,Tour,UCI,LTdL,April,UCI,February,Voyage,UCI,World,Tour,UCI,UCI,Games,Kuala,Lumpur,Voyage,M,Sdn,Bhd,Youth,Sports,Ministry,January,LTdL,LTdL,Kuching,Langkawi,Kota,Kinabalu,Criterion,Feb,Race,Langkawi,Feb,Bernama": 1
    },
    "output": {
      "ltdl": 1
    }
  }
]

```
```
const net = new brain.NeuralNetwork()
const prepInput = str => {
  const stripped = striptags(str)
  const rem = unescapeHtml(stripped)
  const doc = nlp.readDoc(rem)
  const properN = doc
    .tokens()
    .filter(
      // Exclude nouns inside an entity
      t => {
        return t.out(its.pos) === 'PROPN'
      }
    )
    .out()
  return sw.removeStopwords(properN)
}

const readInputs = (stream, data) => {
  for (let i = 0; i < data.length; i++) {
    stream.write(data[i]);
    console.count('Training Process')
  }
  // let it know we've reached the end of the inputs
  stream.endInputs()
}

const trainingStream = new brain.TrainStream({
  neuralNetwork: net,
  /**
   * Write training data to the stream. Called on each training iteration.
   */
  floodCallback: function () {
    readInputs(trainingStream, stories)
  },

  /**
   * Called when the network is done training.
   */
  doneTrainingCallback: function (obj) {
    console.log(
      `trained in ${obj.iterations} iterations with error: ${obj.error}`
    );
    const str = "Random HTML string"    const output = net.run({
      [prepInput(str)]: 1
    })

    const sortable = Object.fromEntries(
      Object.entries(output).sort(([, a], [, b]) => b - a)
    )
    const sliced = Object.fromEntries(
      Object.entries(sortable).slice(0, 20)
    )
    console.log(sliced, 'Out')
  },
})

readInputs(trainingStream, stories)
```

**Comment by killkli** [comment]
Em... Of course trainging is slow and time consuming, thats why we have toJSON() to export pre trained network, and fromJSON() to import it.
Read the document about it~~

**Comment by robertleeplummerjr** [comment]
How are you feeding in the inputs?  I think what's happening is you are creating too many nodes from `prepInput`.  If you can simplify those inputs you'll greatly increase performance.  There are a number of ways that can be done, such as associating a word with a decimal amount, or perhaps (not ideal) treating each word as an input with a value of 1 when it is defined.

**Comment by teeban10** [comment]
> 

The thing is I needed the lengthy input. Basically, the input is an article and the output is the tag associated with it. I need my program to identify tags it is closely associated with it. The `prepInput` function actually helps simply input by removing stopwords, HTML tags, and non proper nouns.

**Comment by teeban10** [comment]
> How are you feeding in the inputs? I think what's happening is you are creating too many nodes from `prepInput`. If you can simplify those inputs you'll greatly increase performance. There are a number of ways that can be done, such as associating a word with a decimal amount, or perhaps (not ideal) treating each word as an input with a value of 1 when it is defined.

The thing is I needed the lengthy input. Basically, the input is an article and the output is the tag associated with it. I need my program to identify tags it is closely associated with it. The prepInput function actually helps simply input by removing stopwords, HTML tags, and non proper nouns.

**Comment by robertleeplummerjr** [comment]
You really should be using either a `brain.recurrent.LSTM` (for use with strings), or `brain.recurrent.LSTMTimeStep` (for use with numbers) for this task.  This is also because your inputs/outputs are dynamically sized.  A standard feed forward neural network, which is what `brain.NeuralNetwork` is, is for inputs of the same size and outputs of the same size.
