### ISSUE TITLE
https://github.com/BrainJS/brain.js/issues/80 is not fixed

### ISSUE THREAD

**Issue by grmatthews** [BrainJS/brain.js#757]
![A GIF or MEME to give some spice of the internet](url)

## _What_ is wrong?
https://github.com/BrainJS/brain.js/issues/80 doesn't seem to be fixed.

Cannot do any sort of import based usage of brain.js -- must use require

## _How_ do we replicate the issue?

- Step 1
- Step 2
- Step 3

## Expected behavior (i.e. solution)

Expect to be able to do one of something like

import { brain } from 'brain.js'
or
import * as brain from 'brain.js'

Cannot do either

Must use const brain = require('brain.js')

Even if I change the npm type in package.json to 'module', then import based usage still doesn't work.

## Version information

brain.js@2.0.0-beta.4

**Comment by robertleeplummerjr** [comment]
This should be resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.6.

**Comment by robertleeplummerjr** [comment]
Via: https://github.com/BrainJS/brain.js/pull/775
