### ISSUE TITLE
Brain JS not installing via NPM on mac

### ISSUE THREAD

**Issue by Micah-6424** [BrainJS/brain.js#759]
<img width="1137" alt="Screen Shot 2022-01-28 at 5 13 49 PM" src="https://user-images.githubusercontent.com/81455112/151634311-67207803-62be-4a27-bf24-ff738273c1d7.png">

**Comment by Micah-6424** [comment]
- [ ]

**Comment by robertleeplummerjr** [comment]
Did you get it installed?

**Comment by Micah-6424** [comment]
no, I closed the issue because the CDN worked fine but I would much rather be able to use the package directly. (I will reopen the issue. And i'm  sorry, I am fairly new to GitHub)

**Comment by DJj123dj** [comment]
i have the same problem

**Comment by EduApps-CDG** [comment]
same on ubuntu

**Comment by robertleeplummerjr** [comment]
I can take a look tomorrow.

**Comment by robertleeplummerjr** [comment]
Just tested the latest release, https://www.npmjs.com/package/brain.js/v/2.0.0-beta.11, and it works fine on windows and mac.  I haven't tested ubuntu yet, but since this thread was about installing on mac, I'm going to go ahead and close.
