### ISSUE TITLE
Brain.js not installing

### ISSUE THREAD

**Issue by DGoel1602** [BrainJS/brain.js#763]
![A GIF or MEME to give some spice of the internet](url)

## _What_ is wrong?
Error while downloading (library is no longer supported)

## _Where_ does it happen?
In the terminal when I'm downloading it

## _How_ do we replicate the issue?
npm i brain.js

- Step 1
- Step 2
- Step 3

## Expected behavior (i.e. solution)
Brain.js to install

## _How_ important is this (1-5)?
4

### _****_

**Comment by DJj123dj** [comment]
i have the same problem

**Comment by DGoel1602** [comment]
I just solved it! You have to download the visual studio code _installer_, not just visual studio code and also Visual studio community with desktop development with C++
