### ISSUE TITLE
net.run() returns NaN when using NeuralNetworkGPU, still acts a bit weird when using NeuralNetwork, though doesn't return NaN

### ISSUE THREAD

**Issue by TheRedXD** [BrainJS/brain.js#765]
![A GIF or MEME to give some spice of the internet](url)

## _What_ is wrong?

For whatever reason, when I do net2.run(_input here_) it returns NaN. This has been causing me a headache for a while now and I have no idea why this is happening

## _Where_ does it happen?

It happens in my ai.js file in my Discord AI bot that I'm trying to make - it's pretty basic right now

## _How_ do we replicate the issue?

Well, no real idea lol. But here's the ai.js code:
```js
const brain = require('brain.js');
const fs = require('fs');

let net2 = new brain.NeuralNetworkGPU({hiddenLayers: [10], log: true, iterations: 300000});

function encodeText(str) {
    // ensure array length is 50
    return str.split('').map(char => char.charCodeAt(0)/1000).concat(Array(50 - str.length).fill(0));
}

async function train() {
    const _db = require("./db.js");
    let db = await _db;
    let crabCollection = db.db.collection("crab");
    let ourData = await (crabCollection.find()).toArray();
    console.log(ourData);
    let dataToMagik = ourData.map(crab => {
        return {
            input: encodeText(crab.input),
            output: [crab.output]
        }
    });
    console.log("BONK")
    console.log(dataToMagik);
    net2.train(dataToMagik);
    console.log("TRAINED")
}

async function isCrab(name) {
    console.log(typeof encodeText(name));
    console.log(await net2.run(await encodeText(name)));
    return (await net2.run(await encodeText(name))[0]) > 0.5;
}

module.exports = {
    async request(message) {
        return await isCrab(message)
    },
    train
}
```

## Expected behavior (i.e. solution)

this should've worked flawlessly and returned `true` upon feeding my bot the string `crab`

### Nodejs:
v16 something, probably is unneeded

### Browser:
not using a browser

### Brain.js:
whatever is the latest

## _How_ important is this (1-5)?

very important yesyes

no not really. it's probably at a 1 but I really really want for this to be fixed cause it has been giving me a headache

## Other Comments

funnily enough, it didnt return NaN when I tried using NeuralNetwork instead of NeuralNetworkGPU. no idea why's that the case, but it was still acting a bit weird.

**Comment by robertleeplummerjr** [comment]
Based off `encodeText`, I believe  the problem seems that you are feeding different size inputs into `NeuralNetwork`, that will not work, it is designed to feed into the same size inputs and outputs.  You are probably looking to use `brain.recurrent.LSTM`.

**Comment by roysG** [comment]
@TheRedXD, how did you solved it?

**Comment by TheRedXD** [comment]
> @TheRedXD, how did you solved it?

sorry for late reply, but in fact I haven't solved it. I have a bit too many projects so this has been out of my radar for quite some time at the moment
