### ISSUE TITLE
TypeError: brain.NeuralNetwork is not a constructor

### ISSUE THREAD

**Issue by vetterdoo** [BrainJS/brain.js#767]
I've been following the examples exactly in my app that uses Node.js and React.

1. I ran: "npm install brain.js"
2. and I see it show up in my package.json under dependencies ("brain.js": "^2.0.0-beta.4")
3. and I checked my node_modules folder and I see brain.js and even explored the index to check for the NeuralNetwork class
4. Then in my index.js, I have:
`const brain = require("brain.js");
  const net = new brain.NeuralNetwork();
  net.train(DATA); // this is my testdata set
`
BUT i keep getting the error: TypeError: brain.NeuralNetwork is not a constructor

also to note - when I require brain and just try to console log out brain, I get: /static/media/index.d565194ca5f64baedda2
what's happening?

WHAT IS HAPPENING?!

**Comment by robertleeplummerjr** [comment]
Duplicate of #752, closing in favor of that.
