### ISSUE TITLE
NeuralNetworkGPU: OffscreenCanvas is not defined

### ISSUE THREAD

**Issue by EpicPuppy613** [BrainJS/brain.js#768]
![me at 10pm](https://user-images.githubusercontent.com/61771471/153694230-2f96fd9a-ed9c-49d7-b44b-f2c7b410a0fe.jpg)

## _What_ is wrong?
When trying to train a NeuralNetworkGPU, throws error `ReferenceError: OffscreenCanvas is not defined`

## _Where_ does it happen?
Trying to train a NeuralNetworkGPU, 42 inputs, 7 outputs with config ```{
    iterations: 2000,
    learningRate: 0.3
}```

## _How_ do we replicate the issue?

- Create a new NeuralNetworkGPU
- Train the neural network using any data

## Expected behavior (i.e. solution)

The neural network trains properly

## _How_ important is this (1-5)?

4: neural network training using a gpu just does not work (although cpu training still works)

**Comment by proxnull** [comment]
**npm i gpu.js@2.11.4**

**Comment by markhicken** [comment]
@proxnull, installing the older version allowed my code to run, but in my case, using `brain.NeuralNetworkGPU` is more than 10 times slower than `brain.NeuralNetwork` in node. 🤷🏼

**Comment by robertleeplummerjr** [comment]
What size of inputs, hidden layers, and output are you dealing with?  GPU doesn't mean faster in all situations, but it does mean faster with bigger, deeper problems.

**Comment by robertleeplummerjr** [comment]
Also, I'll have this issue resolved tomorrow.

**Comment by markhicken** [comment]
@robertleeplummerjr Thanks for the info. I was working with 3000 input nodes, 1 hidden layer (only 5 nodes), about 40 outputs. I was watching activity monitor though and I could see that it was using about 50% cpu and 45% GPU. Meanwhile everything else that depends on GPU was super laggy (slack, browsers, vs code, etc). I'll play with it a bit more over the next few days and see if I can find a case where it is faster.

**Comment by robertleeplummerjr** [comment]
https://www.npmjs.com/package/brain.js/v/2.0.0-beta.10 fixes the `OffscreenCanvas` issue.
