### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by gabrielfreire** [BrainJS/brain.js#77]
This library is awesome and i would like to work on it, where do i start? Do you guys have any to do list somewhere?

**Comment by Dok11** [comment]
Maybe you want include gpu.js for super mega faster work? :)))
p.s. just joke.. maybe

**Comment by robertleeplummerjr** [comment]
That is already happening here: https://github.com/harthur-org/brain.js/tree/nn-gpu
Next big plans are to get gpu.js to run server side via opencl (already works in cpu mode) and then recurrent and convolutional neural networks.  We are going to setup tons of layers, and have base networks as a type that can be extended, so you basically will have a neural net + layer playground.

To: we loath the complexity of setting up the neural net, it must be simple first, simple enough to teach a child.  That being said, if you were to take a look at, for example, the gpu-nn and can think of simpler means of implementing, you'll be a super star.

**Comment by gabrielfreire** [comment]
Cool! i'll take a look at that. Thanks

**Comment by gabrielfreire** [comment]
This link you put here takes  me to the main repo page
