### ISSUE TITLE
Some of the BrainJS Site's Links Don't Work

### ISSUE THREAD

**Issue by JeffMII** [BrainJS/brain.js#779]
![A GIF or MEME to give some spice of the internet](https://s3.amazonaws.com/rails-camp-tutorials/blog/programming+memes/works-doesnt-work.jpg)

## _What_ is wrong?

The [website's](https://brain.js.org) got at least a couple links/buttons that don't work correctly. There could be more, but the two I'm specifically talking about are Become a Sponsor and Contribute. The Become a Sponsor button simply doesn't do anything, and the Contribute button leads to a GitHub 404 page.

## _Where_ does it happen?

[BrainJS Website](https://brain.js.org)

## _How_ do we replicate the issue?

In your browser of choice,

- Navigate to the [BrainJS Website](https://brain.js.org)
- Scroll down the homepage until you reach the Become a Sponsor and Contribute buttons
- Try clicking both buttons

## Expected behavior (i.e. solution)

I'm not sure exactly, but it's not this.

The Become a Sponsor button should probably navigate to the sponsor site in a new tab exactly as the Sponsor button in the top right of the page does.

## _How_ important is this (1-5)?

Probably a 1, but I'd like to contribute in the development, testing, or documentation of the project. I thought the Contribute button would take me to a page containing information on how to get started.

## Other Comments

I didn't know where else to post the issue. It's probably already a known issue, but just in case, here you go.

**Comment by robertleeplummerjr** [comment]
Thank you!  Merged.
