### ISSUE TITLE
How use brainjs to create chatbot?

### ISSUE THREAD

**Issue by Iazzetta** [BrainJS/brain.js#78]
I trying to use brainjs to make a simple chatbot.
```
var brain = require('brain.js');
var net = new brain.recurrent.LSTM();
var user_messages = [
  {id: 1, message: "Hello"},
  {id: 2, message: "Tudo bem?"},
  {id: 3, message: "Voce gosta da Arvore?"},
  {id: 4, message: "voce manja de machine learning?"},
  {id: 5, message: "Voce é um robo?"},
  {id: 6, message: "robo?"},
]

var bot_messages = [
  {id: 1, message: "Tranquilo?"},
  {id: 2, message: "Sim!"},
  {id: 3, message: "Eu sou O robo ;)"},
  {id: 4, message: "Tudo otimo"},
  {id: 5, message: "Manjo até demais"},
]

net.train([{input: [1], output: [1]},
           {input: [2], output: [4]},
           {input: [3], output: [2]},
           {input: [4], output: [5]},
           {input: [5], output: [3]},
          ]);

for (var i = 0; i < user_messages.length; i++) {
  usermessage = user_messages[i];
  
  //Humano fala
  console.log("Human:", usermessage.message)
  var output = net.run([usermessage.id]);
  
  console.log("output: ", output)
  //Robo responde
  for (var j = 0; j < bot_messages.length; j++) {
    if (bot_messages[j].id == output) {
      console.log("Bot:", bot_messages[j].message)
    }
  }
}
```

I know, I train to check ID's and not match words. But what I need do to train with messages or match words?

**Comment by gabrielfreire** [comment]
To train, i think you should train the messages
like
`
net.train([
  {input: "Hello", output: "Tranquilo?"},
  {input: "Tudo bem?", output: "sim!"}
]);
`
so when you're finished just pass the message as input to predict
like 
`net.run("Hello")`
output: `//Tranquilo?`

i'm not sure if i'm correct but makes more sense to me.

**Comment by Iazzetta** [comment]
Yes, but brain don't match the messages. Trying "Hello" works, but "hello" not. Maybe I need remove accents and set all words to lowercase before train and pass to predict. But how I train to words/phrases match? Like "hello, I love that music" and "wow I love this music" be the same thing..

**Comment by gabrielfreire** [comment]
I think that you will have to normalize the data first.
ie.
//input: "hello" output: "tranquilo?"
[ 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] = "hello"
[0] = "Tranquilo?"

`net.train([{input: [ 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], output: [0]}`

**Comment by SISheogorath** [comment]
The answer is simple: You need more training data.

I already worked on something similar but you need a few thousand training elements or even more to make sure the AI notices the difference. Keep in mind that your neuronal network starts with an empty mind. knowing nothing about language. Doesn't even know that characters exist.

So when you want to build up a context based on the content of a sentence you have to provide all needed data to make sure the neuronal network get's the difference and not simply uses any word or the string length, to calculate its answer.

**Comment by Iazzetta** [comment]
Thanks!
