### ISSUE TITLE
Uncaught TypeError: data[0] is undefined

### ISSUE THREAD

**Issue by kevinreu** [BrainJS/brain.js#780]
I don't know what to do about this error.

**Comment by robertleeplummerjr** [comment]
Reproduction steps would help.

**Comment by robertleeplummerjr** [comment]
The default new issue has direction for you to fill out.  Simply ignoring it waists both of our time.  Open a new issue, pay attention to the questions asked, of course answer the questions, and please don't just ignore us trying to help you.
