### ISSUE TITLE
GPU acceleration not working

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#790]
## _What_ is wrong?

The NeuralNetworkGPU will not work in node and throw an error in the browser. The example at https://github.com/BrainJS/brain.js/blob/master/examples/javascript/gpu.html is not working either. In the Browser one receives the error TypeError: Cannot read properties of undefined (reading 'GPU').

## _Where_ does it happen?

When trying to use GPU for training 

## _How_ do we replicate the issue?

- try GPU acceleration

## Expected behaviour (i.e. solution)

Use GPU, webgl in browser and gpu.js in node

## _How_ important is this (1-5)?

3

## Other Comments

Recently managed to get some basic image training working, but its very slow. I have my scripts in node.js, just tried out the browser version to see if it would work. I'd appreciate any multithreading support, or a working GPU implementation.

**Comment by sbcarp** [comment]
Seems like you didn't install `gpu.js`

**Comment by Ultr4Dev** [comment]
> Seems like you didn't install `gpu.js`

I did install GPU.JS and it still dont work.
Code:
```html
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/npm/gpu.js@latest/dist/gpu-browser.min.js"></script>
     <script src="https://unpkg.com/brain.js"></script>
      <script>
      const net = new brain.NeuralNetworkGPU();

      const xorTrainingData = [
        { input: [0, 0], output: [0] },
        { input: [0, 1], output: [1] },
        { input: [1, 0], output: [1] },
        { input: [1, 1], output: [0] },
      ];

      net.train(xorTrainingData);

      console.log(net.run([0, 0]));
      console.log(net.run([0, 1]));
      console.log(net.run([1, 0]));
      console.log(net.run([1, 1]));
    </script>
  </head>
  <body></body>
</html>
```

console:
```
Uncaught TypeError: gpu_js.GPU is not a constructor
    at new NeuralNetworkGPU (brain.js:5460:24)
    at (index):9:19
```

**Comment by ghost** [comment]
I fixed my problem by updating my GPU Drivers

**Comment by Ultr4Dev** [comment]
> I fixed my problem by updating my GPU Drivers

Did not work for me
