### ISSUE TITLE
Cant install module

### ISSUE THREAD

**Issue by bugra568** [BrainJS/brain.js#791]
i cant download module because node-gyp failing:
Could not find any visual studio installation to  use
![Ekran Alıntısı](https://user-images.githubusercontent.com/81085730/165630753-255e894a-32a9-4ea0-8c05-da57fb86985f.PNG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/81085730/165631336-a6159d02-86e5-48a3-81d4-dc7778793047.PNG)

**Comment by robertleeplummerjr** [comment]
Try installing using npm or yarn directly.  Installation using visual studio in whatever way you are trying is not supported.
