### ISSUE TITLE
Abnormal prediction results

### ISSUE THREAD

**Issue by AryaAnish121** [BrainJS/brain.js#796]
This code:
```
const data = [1, 2, 3];
const net = new brain.recurrent.LSTMTimeStep();
net.train([data]);

const output = net.forecast([1, 2, 3], 1);

console.log(output); // [3.4478390216827393]
```
gives `3.4478390216827393` as the output but I want to forcast it properly and the expected output should be `4`, how can I fix it?

**Comment by robertleeplummerjr** [comment]
Train it showing 4.  You aren't providing enough training data.

**Comment by AryaAnish121** [comment]
I mean I want to build a stock prediction app and there I can provide the current data and it will need to predict itself, how can I achieve this?
