### ISSUE TITLE
Installation warnings

### ISSUE THREAD

**Issue by vanillamasonry** [BrainJS/brain.js#811]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
## Expected behavior (i.e. solution)
no warnings

### Nodejs:
18
### Browser:
N/A
### Brain.js:
last

**Comment by hug0b** [comment]
These warnings happen because BrainJS depends on gpu.js which uses an oudated version of gl.

(gl ^4.5.2 depends on node-gyp ^6.1.0 -> request ^2.88.0 -> outdated har-validator and uuid dependencies)

This is an ongoing issue: https://github.com/gpujs/gpu.js/issues/711

**Comment by monomy001** [comment]
Has this been resolved? I'm still seeing the same error message

**Comment by robertleeplummerjr** [comment]
I just published a new version of GPU.js and brain.js that should resolve this.
