### ISSUE TITLE
Error On Installation

### ISSUE THREAD

**Issue by JacobScheff** [BrainJS/brain.js#821]
When I run` npm install brain.js`, I get an error. What should I do to fix this? Here is what it shows in the terminal:

PS C:\Users\john\Documents\VSC\AI> npm install brain.js
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\john\Documents\VSC\AI\node_modules\gl
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.5 found at "C:\Users\john\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2015
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details     
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\john\Documents\VSC\AI\node_modules\node-gyp\lib\find-visualstudio.js:121:47)      
npm ERR! gyp ERR! stack     at C:\Users\john\Documents\VSC\AI\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\john\Documents\VSC\AI\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\john\Documents\VSC\AI\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\john\Documents\VSC\AI\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\john\Documents\VSC\AI\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\john\Documents\VSC\AI\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\john\\Documents\\VSC\\AI\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\john\Documents\VSC\AI\node_modules\gl
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\john\AppData\Local\npm-cache\_logs\2022-07-24T17_28_06_675Z-debug-0.log

**Comment by hug0b** [comment]
On first glance I assume it's because of the [`gpu.js` dependency](https://github.com/BrainJS/brain.js/blob/8d74cea5a13af3a6de9d622814c5a87cee622dc5/package.json#L44) which itself depends on `gl`.

@Snowplou did you install Visual C++ build tools ? https://github.com/nodejs/node-gyp#on-windows

**Comment by JacobScheff** [comment]
> On first glance I assume it's because of the [`gpu.js` dependency](https://github.com/BrainJS/brain.js/blob/8d74cea5a13af3a6de9d622814c5a87cee622dc5/package.json#L44) which itself depends on `gl`.
> 
> @Snowplou did you install Visual C++ build tools ? https://github.com/nodejs/node-gyp#on-windows

@hug0b I have installed the C++ build tools already.

**Comment by hug0b** [comment]
I think this is again related to https://github.com/gpujs/gpu.js/issues/711

**Comment by hug0b** [comment]
Also might be a duplicate of https://github.com/BrainJS/brain.js/issues/813, https://github.com/BrainJS/brain.js/issues/792 and [#734](https://github.com/gpujs/gpu.js/issues/734)

**Comment by JacobScheff** [comment]
I fixed the bug. I had to run: `C:\Users\john\Documents\VSC\AI>npm config set msvs_path C:\Program Files (x86)\Microsoft Visual Studio\2017`. I set the version to 2017, but the path to it was never set.
