### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by alex706848548** [BrainJS/brain.js#834]
![A GIF or MEME to give some spice of the internet](https://c.tenor.com/_4YgA77ExHEAAAAd/rick-roll.gif)

## _What_ is wrong?
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\alexW\OneDrive\Desktop\space2\node_modules\gl
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.7.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "C:\Python310\python.exe"
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2017
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\alexW\OneDrive\Desktop\space2\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\alexW\OneDrive\Desktop\space2\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\alexW\OneDrive\Desktop\space2\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\OneDrive\Desktop\space2\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\OneDrive\Desktop\space2\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\OneDrive\Desktop\space2\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\OneDrive\Desktop\space2\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:418:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\OneDrive\\Desktop\\space2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\OneDrive\Desktop\space2\node_modules\gl
npm ERR! gyp ERR! node -v v18.7.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Local\npm-cache\_logs\2022-08-16T23_03_41_214Z-debug-0.log

## _Where_ does it happen?
when I'm installing brain.js

## _How_ do we replicate the issue?

- Step 1 npm v: 8.17.0
- Step 2 npm install --save brain.js
- Step 3 I don't know if this helps but use VSC 2022

It should have just been installed without errors
I think it's a bug, I have tried to reinstall brain.js.

## Version information
npm v: 8.17.0
node v: v18.7.0
VSC v: 2022

**Comment by JoelBonetR** [comment]
Can you please try to replicate the same using a stable version of Node to see if the issue persists? 
16.17.0 is the **latest stable** (at the time of writing that) whereas 18.7.0 is the **latest experimental**

**Comment by alex706848548** [comment]
I’m sorry I didn’t update it. I actually fixed it by reinstalling node and installing 2019 or 2020 (2017 also worked) Desktop development C++ I have windows 11 installed and for some reason the 2022(Desktop development c++)version won’t work with gyp. The installation note needs to be updated/fixed as npm rebuild will not fix the installation errors ( I had to do more then just installing VSC Desktop development C++)

> Can you please try to replicate the same using a stable version of Node to see if the issue persists?
> 16.17.0 is the **latest stable** (at the time of writing that) whereas 18.7.0 is the **latest experimental**
@JoelBonetR
