### ISSUE TITLE
Chatbot ?

### ISSUE THREAD

**Issue by IvanJRCH** [BrainJS/brain.js#836]
Hola cómo están 👍, alguien a usado brain.js? estoy programando un chatbot pero la manera en que lo hago no me gusta mucho, a si que quería saber si alguien que lo a ya hecho antes me puede dar un ejemplo de código con brain.js para enseña al bot a escribir y a responder al texto del usuario de una manera coherente  luego solo faltaria clasificar algunas palabras para ejecutar comandos, ví este ejemplo usando redes neuronales recurrentes:

const trainingData = [ 
'Jane saw Doug.', 
'Spot saw himself.', 
'Doug saw Jane.' ]; 
const lstm = new brain.recurrent.LSTM(); const result = lstm.train(
trainingData, { iterations: 1000 }
); 
const run1 = lstm.run('Jane'); 
const run2 = lstm.run('Spot'); 
const run3 = lstm.run('Doug'); console.log('run 1: Jane' + run1); console.log('run 2: Spot' + run2); console.log('run 3: Doug' + run3);

Se supone que esto le enseña a la red a crear fraces lo probé y le agregue mis propios datos de entrenamiento pero tengo como resultado puras cosas sin sentido, no quiero usar servicios externos, quiero crear mi propio chatbot, alguien ha usado brain.js y hecho esto? Pero de una manera que no se tenga que clasificar el texto? Quiero que la IA aprenda a escribir primero español pasándole un archivo grande lleno de texto, luego como la red ya sabe escribir quiero procesar el texto del usuario input y como salida output solo una sugerencia de como debería responder la red para que la conversación se sienta natural y he evitarme tener que clasificar a mano un montón de texto

**Comment by JoelBonetR** [comment]
Hola IvanJRCH, escribo la respuesta en inglés para mantener una cohesión lingüística en el repositorio:

I understand that you want to train your AI, please see the [training reference](https://github.com/BrainJS/brain.js#training).
You'll need to work out the training before the chatbot answers make sense at all, I suggest you to define the use-cases, make sure your intents are distinct and that each intent contains many utterances. 
Also note that your job isn’t done after your chatbot has been deployed. Continuous improvement is important for a successful result and identifying situations where your chatbot needs more training will give you important insights about it.

I don't spot any bug or problem related with Brain.js here so I'd recommend to close this issue.

**Comment by IvanJRCH** [comment]
hello, thank you very much for your answer, I have created a chatbot, but the chatbot only responds with predefined responses that are already in training, what I would like is for the AI to learn to write, and to respond to the user with consistency only by passing examples of a normal conversation that I will take from a plain txt file, but that the AI does not respond with predefined text but creates its own dialog, then I plan to use another neural network to classify the intention of the text of the AI not of the user, in order to execute commands, I saw the example of using recursive.LSTM(); but notice that it only repeats what is already in the training, how can I make the AI create its own conversations but not with predefined texts, is using LSTM the right way? Could you give me an example? I don't understand how to put that in the code. Also, I don't understand the neural network well either. Thank you very much for answering.

**Comment by JoelBonetR** [comment]
Hi IvanJRCH, I'm not an expert on ML, just reached this project as a way to learn more in my free time.
Also got this resource that may help (didn't read it yet) https://www.deeplearningbook.org/

I suggest you to interact with the community through other sites more prone to the conversation such stackoverflow, dev.to or any other forum that's specific to have conversations around the niche of ML. This way we don't convert this issue tracker into something else.

Have a great day and hope you find the way to solve your issue :)

**Comment by IvanJRCH** [comment]
Thank you very much, I'll take a look at the link.
