### ISSUE TITLE
gpu.html - failing in browser

### ISSUE THREAD

**Issue by flyingzebra** [BrainJS/brain.js#842]
## _What_ is wrong?

I tried this browser example [gpu.html](https://github.com/BrainJS/brain.js/blob/master/examples/javascript/gpu.html) from GitHub and running this in the browser (without node.js), I get the following error:

undefined is not an object (evaluating 'new gpu_js.GPU')

## _Where_ does it happen?

during instantiation:

> const net = new brain.NeuralNetworkGPU();

## _How_ do we replicate the issue?

- download https://github.com/BrainJS/brain.js/blob/master/examples/javascript/gpu.html on your desktop
- run gpu.html in any browser
- check console

## Expected behavior (i.e. solution)

The example does not specify any prerequisite to run this example successfully, but I am expecting that this example to run straight away in a browser.  If this example requires a node.js server in the first place and server is not there, this example should fallback to browser-only processing.

## _How_ important is this (1-5)?

3

**Comment by suspicious-pineapple** [comment]
someone else mentioned a workaround:

```html
<script crossorigin="anonymous" src="https://unpkg.com/gpu.js@2.9.5/dist/gpu-browser.js"></script>
    <script>
        gpu_js = GPU;
        gpu_js.GPU = GPU;
    </script>
```
This seems to make the error go away, but performance is really not great

really hope that it gets fixed soon; the provided GPU examples dont work with latest gpu.js

(why didnt more people notice this?)

**Comment by robertleeplummerjr** [comment]
Thank you guys for bringing this up again.  I'll address it tomorrow morning.

**Comment by suspicious-pineapple** [comment]
Amazing!
Looking through the history of gpu.js and brain.js, your name pops up all the time, answering questions and fixing things.
Great work.

**Comment by robertleeplummerjr** [comment]
Resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.19 with https://github.com/BrainJS/brain.js/commit/ddfa691d1ce3f6ff526e131007f292fa1d99f5b6#diff-efbb74ddd79a873bfde6a469e0eb961a4fe205a233b06fab43510c4bda06b971R16

**Comment by flyingzebra** [comment]
Great fix !
