### ISSUE TITLE
Dockerizing with `node:14-buster-slim`

### ISSUE THREAD

**Issue by TheUntraceable** [BrainJS/brain.js#848]
![A GIF or MEME to give some spice of the internet](https://c.tenor.com/HxDyev3mE2sAAAAC/kill-remove.gif)

## _What_ is wrong?
I am trying to dockerize my application which uses Brain.JS, and it persistently fails, saying that python isn't found, I have tried making `python` an alias of `python3`, tried using npm config, no luck. I have attached logs

## _Where_ does it happen?
When trying to install

## _How_ do we replicate the issue?
- Step 1
    Create a "server"/container with that egg on a Pterodactyl Panel.
- Step 2
    Upload this  [egg](https://github.com/parkervcp/eggs/blob/master/generic/nodejs/egg-node-js-generic.json)
- Step 3
    Upload your application
- Step 4
    Make sure to install brain.js
- Step 5
    Set your startup command to `npm uninstall brain.js; npm install --save brain.js; if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install --python="/usr/bin/python3"; fi; /usr/local/bin/node /home/container/${BOT_JS_FILE}` and run the app.

## Expected behavior (i.e. solution)
For BrainJS to install

### Nodejs:
v18.9.0

### Brain.js:
2.0.0-beta.16"

## _How_ important is this (1-5)?
3

## Other 
Dependencies.
```json
  "type": "module",
  "main": "./index.js",
  "dependencies": {
    "axios": "^0.27.2",
    "brain.js": "^2.0.0-beta.16",
    "discord.js": "^14.4.0",
    "gpu.js": "^2.15.2",
    "mongodb": "^4.9.0",
    "sharp": "^0.31.0"
  }
}
```
Error: [2022-09-25T10_15_07_991Z-debug-0.log](https://github.com/BrainJS/brain.js/files/9640528/2022-09-25T10_15_07_991Z-debug-0.log)

**Comment by Vectorrent** [comment]
I've been running brain.js in the official node docker images (version 16-19) without any trouble. 

First thing I'd suggest, is using python2 instead of python3. Python3 is not supported, and won't work with brain.js.

Second thing I'd suggest: don't run all that stuff in a startup command. Do it in a dockerfile, extending the official node image. Here's a basic example that's working for me:

```
FROM node:19-slim

MAINTAINER Hollowpoint Organization

RUN apt-get update && \
    apt-get install -y build-essential libgtk2.0-0 libgtk-3-0 libnotify-dev \
    libgconf-2-4 libglew-dev libglu1-mesa-dev libnss3 libxss1 libxi-dev \
    libasound2 libxtst6 pkg-config xauth xvfb libgbm-dev curl git python make

WORKDIR /app

COPY package*.json tsconfig.json ./

RUN npm install

COPY src ./src

RUN npm run build

RUN chown -R node /app && chmod -R 740 /app

USER node

ENV NODE_ENV=production

CMD ["npm", "start"]
```
You won't need all those packages, but I don't know which I can remove, at this point.

**Comment by TheUntraceable** [comment]
I've tried installing Python 2.7 as per the dependencies, but I've received an error.
```
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - executable path is "/usr/bin/python"
npm ERR! gyp ERR! find Python - version is "2.7.18"
npm ERR! gyp ERR! find Python - version is 2.7.18 - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
```
The thing is, that I'm using pterodactyl panel, and I've now used Python 3.6 with some other things, and this seems to be working now, forgot to close the issue.
