### ISSUE TITLE
Is this repo no longer maintained?

### ISSUE THREAD

**Issue by imkane** [BrainJS/brain.js#859]
I was just surprised to see the last release was 4 years ago ... :exploding_head: 

It seems so awesome! What happened?

**Comment by Nelias** [comment]
It is maintained but I think the next major release will be with fully implemented TypeScript

**Comment by imkane** [comment]
> It is maintained but I think the next major release will be with fully implemented TypeScript

Oh great, that's fantastic news. Thank you @Nelias.

**Comment by hems** [comment]
> It is maintained but I think the next major release will be with fully implemented TypeScript

very good, looking forward to it ( :

**Comment by hems** [comment]
> It is maintained but I think the next major release will be with fully implemented TypeScript

is the new code being developed in another fork of the repo? i couldn't find any other active branch with typescript code in it?

**Comment by robertleeplummerjr** [comment]
We're close to a new release, just hardening the overall implementation.
