### ISSUE TITLE
cant install brainjs on mac m1

### ISSUE THREAD

**Issue by ADx96** [BrainJS/brain.js#864]
i have an issue installing brainjs on mac m1 its using pyhton3 i installed python 2.7 but it still reads python 3 from the new xcode version

**Comment by fckffln** [comment]
i have the same issue

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/83829392/207179326-f2c1af06-4b74-4200-aff9-4d5b737bc6e2.png">

**Comment by hems** [comment]
maybe in the meanwhile you could look into some [node-gyp related threads](https://www.google.com/search?q=node-gyp+use+python+2.7&sxsrf=ALiCzsaPPtwQJaXgsO3VozqfwdKjh-bApQ%3A1672022390852&ei=dgmpY4zSM4STgQaDirrQCQ&ved=0ahUKEwiM5abloJb8AhWEScAKHQOFDpoQ4dUDCA8&uact=5&oq=node-gyp+use+python+2.7&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIGCAAQFhAeMgUIABCGAzIFCAAQhgMyBQgAEIYDMgUIABCGAzoKCAAQRxDWBBCwAzoHCCMQsAIQJzoFCAAQgAQ6BwgAEB4Q8QQ6CQgAEAgQHhDxBDoJCAAQFhAeEPEESgQIQRgASgQIRhgAUN8CWMQYYLIZaAJwAXgAgAFOiAHAA5IBATaYAQCgAQHIAQjAAQE&sclient=gws-wiz-serp)?

**Comment by cclauss** [comment]
Can this issue be closed?  Python 2 died 1,197 days ago on 1/1/2020.

**Comment by robertleeplummerjr** [comment]
Unable to reproduce on OSX 13.0.1 (22A400).
