### ISSUE TITLE
Why is unsupported Python 2 required for installation

### ISSUE THREAD

**Issue by cclauss** [BrainJS/brain.js#875]
![A GIF or MEME to give some spice of the internet](url)

## _What_ is wrong?

Python 2 died 1,132 days ago on 1/1/2020 with no security updates since then and there is no Python code in this repository.

### Why is unsupported software a requirement for installation?
* https://github.com/BrainJS/brain.js#system-dependencies
* https://devguide.python.org/versions

## _How_ do we replicate the issue?

- Step 1
- Step 2
- Step 3

**Comment by elvis-pereira** [comment]
I don't think that Python 2 is really a requirement, I'm building using Python 3, the README text is probably just outdated. Now why Python is required at all, I believe is because of `headless-gl`.

**Comment by robertleeplummerjr** [comment]
I believe this to be correct.  Python is a requirement of node.

**Comment by Hamza-b93** [comment]
> I don't think that Python 2 is really a requirement, I'm building using Python 3, the README text is probably just outdated. Now why Python is required at all, I believe is because of `headless-gl`.

Did you have to change the installation process in any way to accomodate Python 3 instead of Python 2?

**Comment by cclauss** [comment]
Fixed in #880
