### ISSUE TITLE
Reinforcement Learning Feature Request

### ISSUE THREAD

**Issue by unpaid6607** [BrainJS/brain.js#883]
Reinforcement Learning Feature Request

**Comment by Vectorrent** [comment]
This is a duplicate of #317.

**Comment by suspicious-pineapple** [comment]
i wonder if some optional feedback (like `net.run(data).feedback(0.4)`) would be possible.
...i don't know much about neural networks (*yet*, brainJS is rapidly changing that)
- would that work against the normal error function?
- what if more training iterations have passed since then?
