### ISSUE TITLE
Cannot find module '../node_modules/gpu.js/src/index.js'

### ISSUE THREAD

**Issue by ppedziwiatr** [BrainJS/brain.js#885]
![A GIF or MEME to give some spice of the internet](https://preview.redd.it/web-3-devs-turning-into-ai-devs-v0-nx0pi9c9i0aa1.png?width=640&crop=smart&auto=webp&s=2ed1bd4353eb9f9ff137eb08589c5f941d69bb8d)

## _What_ is wrong?

I cannot properly install brain.js on my machine.

## _Where_ does it happen?

Im running on M1 Pro, Node 18.
`yarn add brain.js` adds the `brain.js`, but does not add the `gpu.js` (i.e. there is no gpu.js in `node_modules`).
Adding `gpu.js` manually (i.e. `yarn add gpu.js`) does not help - the same error persists (even though the gpu.js is now in the node_modules):
```
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '../node_modules/gpu.js/src/index.js'
Require stack:
- /Users/piotrpedziwiatr/projects/example-redstone/node_modules/brain.js/dist/index.js
- /Users/piotrpedziwiatr/projects/example-redstone/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/piotrpedziwiatr/projects/example-redstone/node_modules/brain.js/dist/index.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/piotrpedziwiatr/projects/example-redstone/node_modules/brain.js/dist/index.js',
    '/Users/piotrpedziwiatr/projects/example-redstone/index.js'
  ]
}

Node.js v18.12.1
```

The only way to fix it for me is to manually change
`var index_js = require('../node_modules/gpu.js/src/index.js');`
to
`var index_js = require('../../../node_modules/gpu.js/src/index.js');`

on line 6 of the `dist/index.js` in brain.js.

## _How_ do we replicate the issue?

1. Clone https://github.com/warp-contracts/example-redstone/tree/ppe/brain-js-issue
2. `yarn`
3. `node brain-damage.js`

- should end-up with sth like:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/84311757/227789370-2ea9ceed-719b-4a80-8109-9206ff026ea9.png">

## Expected behavior (i.e. solution)

I should be able to import the library in my script without having to manually change
`var index_js = require('../node_modules/gpu.js/src/index.js');`
to
`var index_js = require('../../../node_modules/gpu.js/src/index.js');`

on line 6 of the `node_modules/brain.js/dist/index.js` :-).

### Nodejs:
18.12.1

### Browser:
nope

### Brain.js:
2.0.0-beta.20

## _How_ important is this (1-5)?

Well, the basic functionality does not work...so sth like 4? ;-)

## Other Comments

I've just noticed that gpu.js is set as a peerDependency. AFAIK yarn (at least version 1.x) does not install peerDeps by default (in contrary to npm).

I'll perform some more tests using npm

**Comment by ppedziwiatr** [comment]
Same issue after removing node_modules, yarn.lock and a fresh `npm install`. Though - as mentioned - npm did install the gpu.js peer dep - but the error stays the same:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/84311757/227790091-5bc8570e-dbbe-446b-a8b1-ac57decd7cf8.png">

**Comment by pinturic** [comment]
It is the same for me and I use npm

**Comment by madhankk** [comment]
Same issue reproduceable in Node.js v18.15.0 using NPM
Doing the change to the index.js as listed above and doing a NPM rebuild helped get things going for now.

**Comment by NvIGA** [comment]
It is the same for me

**Comment by roysG** [comment]
Same for me..

**Comment by mmxhello** [comment]
I created a zip of the previous version of brain.js, found in one of my projects. It works well. To use it, just download it and unzip into the node_modules folder as a replacement for the current brain.js folder. I hope this error will be fixed soon
[brain.js.zip](https://github.com/BrainJS/brain.js/files/11182856/brain.js.zip)

**Comment by luccas222** [comment]
me too, using npm, same manual fix... "var index_js = require('../../../node_modules/gpu.js/src/index.js');"

**Comment by intuity-hans** [comment]
> I created a zip of the previous version of brain.js, found in one of my projects. It works well. To use it, just download it and unzip into the node_modules folder as a replacement for the current brain.js folder. I hope this error will be fixed soon [brain.js.zip](https://github.com/BrainJS/brain.js/files/11182856/brain.js.zip)

You can always install just an earlier version from npm by explicitly specifying it. I would discourage from using a zip-file from the internet in my node-application even though maybe well-meant by this person
