### ISSUE TITLE
Create

### ISSUE THREAD

**Issue by Godofthemarketing** [BrainJS/brain.js#897]
![A GIF or MEME to give some spice of the internet](url)

## Summary

Brief explanation of the feature.

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by robertleeplummerjr** [comment]
Please use issue for things that are relevant.
