### ISSUE TITLE
We're moving! 🚀

### ISSUE THREAD

**Issue by IonicaBizau** [BrainJS/brain.js#91]
I am pleased to see the great work in this project! ❤️ 

It's been a while since [I was wondering](https://github.com/harthur/brain/issues/72) about the future of this project. The activity is amazing and so is the feedback! 🎉 

After talking to @robertleeplummerjr, we are transferring the repository to the @brainjs organization.
I will invite the members of @harthur-org (/cc @harthur-org/devs @harthur-org/devs) to join the organization.

Some links will have to updated (in `package.json` etc), but the old links will still work because GitHub handles those redirects. Phew. 😁

**Comment by robertleeplummerjr** [comment]
love it!

**Comment by abhisheksoni27** [comment]
:tada:

**Comment by IonicaBizau** [comment]
Welcome to @BrainJS! 🎉

**Comment by abhisheksoni27** [comment]
![](https://media.tenor.com/images/04052e9d28831ce512093906edec28f6/tenor.gif)

**Comment by kurttheviking** [comment]
nice work @IonicaBizau &ndash; thank you!

**Comment by robertleeplummerjr** [comment]
We've moved!
