### ISSUE TITLE
Rebuild Website

### ISSUE THREAD

**Issue by abhisheksoni27** [BrainJS/brain.js#92]
I'll keep posting new screenshots and/or related things to the website so that everyone can provide feedback. 

_Ideas_ are welcome! :tada:

**Comment by abhisheksoni27** [comment]
![screenshot from 2017-09-05 13-27-53](https://user-images.githubusercontent.com/4340071/30051004-16d207a6-923e-11e7-8e59-02ff8644c59c.png)

**Comment by abhisheksoni27** [comment]
![screenshot from 2017-09-05 13-34-24](https://user-images.githubusercontent.com/4340071/30051271-ff922354-923e-11e7-9155-015e11c55106.png)

**Comment by abhisheksoni27** [comment]
![screencapture-localhost-3000-1504857858348](https://user-images.githubusercontent.com/4340071/30202005-825eb826-949a-11e7-8b86-98381ba0a237.png)

**Comment by abhisheksoni27** [comment]
**1.** We need to decide that description line below Who are We?

**2.** The description of authors. Should I copy the GitHub profile description? If anyone wants, though, they can post their author-description right here.

The author name will be a link, so that's that.

**Comment by IonicaBizau** [comment]
@abhisheksoni27 I have a tool for that: https://github.com/IonicaBizau/github-org-members.js

I'm happy with my GitHub short bio as description.
I would suggest using the GitHub API (the above library) so things are a bit more dynamic.

**Comment by abhisheksoni27** [comment]
@IonicaBizau Brilliant! :tada:

I think it's great. Does the library return profile descriptions? :thinking: 

Actually, even if it doesn't as of now, it's easy, right? We just have to call the API again for each author, and grab the description text.

Maybe that was on the roadmap. :joy:

**Comment by IonicaBizau** [comment]
> Does the library return profile descriptions?

If I'm not wrong they are called `bio`.

**Comment by abhisheksoni27** [comment]
Right. There you go: https://developer.github.com/v3/users/#get-a-single-user

**Comment by IonicaBizau** [comment]
It doesn't return the bios... It could be a feature.

**Comment by abhisheksoni27** [comment]
Exactly!

Seems doable to me. What do you think?

**Comment by IonicaBizau** [comment]
@abhisheksoni27 I'm just wondering if the new API (v4) can return the `bio`s in the same call. My library already supports a `source` url. :grin:

**Comment by abhisheksoni27** [comment]
Oh! GraphQL. Great. Let's try and figure out if that's possible.

**Comment by abhisheksoni27** [comment]
It most certainly is possible.

```graphql
query{
  organization(login:"Brainjs") {
    members(first:7) {
      edges {
        node {
          name
          bio
          avatarUrl
        }
      }
    }
  }
}
```

Can you try running it? It returns an empty array for me because maybe I can't access that information since I am not the owner.

**Comment by IonicaBizau** [comment]
@abhisheksoni27 That indeed works, but fetches the public owners. GraphQL requires authentication. Maybe we can do it via v3 for now...

**Comment by abhisheksoni27** [comment]
Right. Good catch. I am getting two members now, and they are listed as Public. Cool.

Anyway, I am fine with v3.

**Comment by abhisheksoni27** [comment]
@IonicaBizau As it happens, even REST can't return private members. :thinking:

**Comment by IonicaBizau** [comment]
It can, but it needs the right scopes.

We can use the `source` option of my library which will fetch the data from a JSON file, but we will have to update that file from time to time.

**Comment by abhisheksoni27** [comment]
Right! How about we provide it with an authentication token (which has to
be generated by one of the owners)?  And then, when we query, we can see
the private members as well.

OR. Like you said, we can go ahead and use the `source` option to get data
from a pre-saved file. Whatever works.

**Comment by IonicaBizau** [comment]
> Right! How about we provide it with an authentication token 

No, we don't want to share the tokens!!!

**Comment by abhisheksoni27** [comment]
Of course. But, Firebase. But yeah, too much hassle.

**Comment by abhisheksoni27** [comment]
![screencapture-localhost-3000-1506077141718](https://user-images.githubusercontent.com/4340071/30741178-7020c196-9fb1-11e7-878c-b3e5f73aa98b.png)

**Comment by abhisheksoni27** [comment]
The form looks odd right now, but as we add more sections showcasing brain.js sorcery, it'll fall into place.

**Comment by IonicaBizau** [comment]
@abhisheksoni27 Do we really need a contact form? Maybe we can track those as issues (e.g. `brainjs/hello/issues/new`).

**Comment by abhisheksoni27** [comment]
@IonicaBizau Sure. Great idea.

But I only put the form there so that people who want to connect with us, but are not necessarily on `GitHub` (yes, yes, potential sponsors :laughing: ), can.

**Comment by robertleeplummerjr** [comment]
I'd like to brainstorm demos we could show off at some point as well.

**Comment by abhisheksoni27** [comment]
@robertleeplummerjr I think the time is now. Brainstorm! :thinking:

**Comment by arguiot** [comment]
Here are some ideas 💡:
- Black and White text (the one already existing)
- MNIST handwritten digits recognition
- Face recognition
- Flappy Bird game that works by itself
- Pathfinding in a maze
- Day or night recognition (with images)

**I'll edit this post if I find new ideas**

**Comment by lunaroyster** [comment]
Hey guys. I'm working on a MNIST demo using BrainJS. Will post it here when it's presentable.

**Comment by robertleeplummerjr** [comment]
love it!

**Comment by arguiot** [comment]
@lunaroyster If you want, there is one on GitHub made by a Russian guy that works. 😊

**Comment by mokhosh** [comment]
what a great conversation guys!

i'm really glad you're talking about the demo. because it was cool at first to find an easy to use ml library for js, and the contrast decider is cool compared to coming up with an algorithm. but compared to what we expect from ai, not so much. it doesn't really help with branding, and makes brainjs look basic and impractical to more serious users. demos with different input and output types would be nice:
- image classification (not necessarily object/face recognition, but no digit detector please 😄)
- learning to play a game with maybe a genetic algorithm
- generating music
- chatbot

thanks for the hard work. bravo

**Comment by mubaidr** [comment]
Any update on this? This is still in progress?

**Comment by robertleeplummerjr** [comment]
still in progress

**Comment by robertleeplummerjr** [comment]
I don't have the source of the above.  @abhisheksoni27, do you?

**Comment by abhisheksoni27** [comment]
Here's the source for anyone who is interested: https://github.com/abhisheksoni27/brain.js/tree/gh-pages

**Comment by abhisheksoni27** [comment]
@robertleeplummerjr Here's the source for anyone who is interested: abhisheksoni27/brain.js@gh-pages

**Comment by abhisheksoni27** [comment]
@robertleeplummerjr Here's the source for anyone who is interested: https://github.com/abhisheksoni27/brain.js/tree/gh-pages

**Comment by robertleeplummerjr** [comment]
Nice!

**Comment by robertleeplummerjr** [comment]
You wouldn't have any interest in helping finish it would you @abhisheksoni27?

**Comment by mubaidr** [comment]
Since this is abandoned, I will be working on this. Pogress will be followed in the project dashboard.
