### ISSUE TITLE
Storing trained net 

### ISSUE THREAD

**Issue by thegamecat** [BrainJS/brain.js#97]
Loving Brain.js - how do I store the trained nn and then re-use it in other scenarios?

**Comment by robertleeplummerjr** [comment]
After training, you can do: `net.toFunction()`
This gives you a zero dependency function of your trained net.  To further that thought, you can:

```js
import fs from 'fs';
fs.writeFileSync('trained-net.js', `export default ${ net.toFunction().toString() };`);
```

Which gives you a 100% es6 file you can just import and run, like so:

Then later:
```js
import trainedNet from './trained-net';
trainedNet(data);
```



>Loving Brain.js

Wait till we land gpu support in v1, and tons of layers in v2!

**Comment by robertleeplummerjr** [comment]
You can also export and import via json: https://github.com/BrainJS/brain.js#json

**Comment by thegamecat** [comment]
You are a hero!!!!

Gonna try this now. Thank you so much!

**Comment by thegamecat** [comment]
Any ideas?

import trainedNet from logpath+'/trained-net.js';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:73:16)

**Comment by robertleeplummerjr** [comment]
Just try non-es6
```js
var trainedNet = require('./trained-net');
trainedNet(data);
```

**Comment by thegamecat** [comment]
ah yes, thanks. Will the export approach in the stored nn work with node7.6?

**Comment by robertleeplummerjr** [comment]
I don't see any reason why it wouldn't work.

**Comment by thegamecat** [comment]
Thanks for your help so far Robert.

A few things I've found.

I'm on Node 7.6 and I've had to change the trained-net file to read like this:
module.exports = {

  getnn: function (input
/**/) {
return {'do':1/(1+1/Math.exp(1.424093361048118+0.693914741575579*(1/(1+1/Math.exp(0.21477080727104217-0.13510833411671558*(input['price'])+0.002514424937632802*(input['rsi'])+0.12644871083363154*(input['ema20']))))+0.666723146370773*(1/(1+1/Math.exp(0.13917289595446591+0.10253334351161274*(input['price'])+0.020849410810439374*(input['rsi'])+0.12377127023405728*(input['ema20']))))+0.7305866887169579*(1/(1+1/Math.exp(0.11302968130848308-0.015291197107745113*(input['price'])+0.23504038301431582*(input['rsi'])-0.17232474989736501*(input['ema20']))))))}
}}



Which I think looks right.

**Comment by thegamecat** [comment]
.

**Comment by thegamecat** [comment]
I ended up using the JSON method. Took some playing but the application is working, now trying to work out how to optimize to improve the training which is failing at the moment.

Thanks for your help.

**Comment by michaelonubogu** [comment]
I know I'm super late to this, but honestly, just wanted to say that brainjs is truly amazing! Thank you guys for this awesome library!

**Comment by ambroserb3** [comment]
I'm having quite a bit of trouble with this, I'm training a somewhat sizeable nn with brain.js in node, offline, and it trains perfectly fine, but I can't seem to save it at all. 
```
const json = net.toJSON()
net.fromJSON(json)
```
doesn't save the json file to my file directory?

and 
```
import fs from 'fs';
fs.writeFileSync('trained-net.js', `export default ${ net.toFunction().toString() };);

var trainedNet = require('./trained-net');
trainedNet(data);
```

doesn't work either. The file is saved to my directory, but I can't actually run the model with it.
I get TypeError: trainedNet is not a function when I use this. 

I just want to train and save this model offline, then load and use it for predictions later, online.

**Comment by mubaidr** [comment]
```js
// get json data
const json = net.toJSON()
// write to file system
fs.writeFileSync('trained-net.json', json);
```

then you can read json later: 
```js
const json= JSON.parse(fs.readFileSync('trained-net.json'))
const net = new brain.NeuralNetwork()
net.fromJSON(json)
net.run(input)
```

**Comment by ambroserb3** [comment]
I feel silly for forgetting to actually write it. This worked, I just also had to use JSON.stringify on the file when writing or it gave me [object Object].

However, when load the file with
`net.fromJSON(json)`

It gave me the error: Sizes must be set up before initializing.

**Comment by robertleeplummerjr** [comment]
That may actually be a bug.

**Comment by cameronmoodley** [comment]
Hey @robertleeplummerjr what a great library thank you for this. I seem to be running into the same issue.

If you need the stack trace please shout. I don't mind sharing.

**Comment by FDiskas** [comment]
If you trying to write json to file you need first convert it to string: :arrow_down:
```js
const json = network.toJSON();

fs.writeFileSync(__dirname + '/data/trained-net.json', JSON.stringify(json), 'utf8');
```

**Comment by aboqasem** [comment]
Is `toFunction()` not supported anymore?

**Comment by Shroototem** [comment]
That exports as this:
`export default {"type":"LSTM","options":{"inputSize":12,"inputRange":12,"hi....`

I can't seem to get a normal json file out of it.

**Comment by robertleeplummerjr** [comment]
Can you share your full example?

**Comment by polystate** [comment]
Hi all, complete noob here. Really loving the intuitive feel of brain.js, just having problems saving a trained neural network like the others. I tried the method listed above and got the same response "Sizes must be set before initializing." I have an index.js file, NN.js and a trained-net.json file in use, it loaded the data in the new JSON file but I can't seem to get it from my new NN.js file.

Is there any alternative solutions I could use? Thanks. Here's my code.


//index.js//

const fs = require('fs');

let brain = require("brain.js");
let net = new brain.recurrent.LSTM();

const trainingData = [
    'Jane saw Doug.',
    'Doug saw Jane',
 ];

net.train(trainingData, {
    iterations: 500,
    errorThresh: 0.011,
    log: (data) => console.log(data)
});

const json = net.toJSON();
fs.writeFileSync('trained-net.json', JSON.stringify(json));



-------------------


//NN.js [what I am trying to load it from] //

const fs = require('fs')
const brain = require('brain.js')
const json= JSON.parse(fs.readFileSync('trained-net.json'))
const net = new brain.NeuralNetwork()
net.fromJSON(json)
net.run("Jane")

**Comment by robertleeplummerjr** [comment]
In the above example, you are using two different neural networks.  Stick to the LSTM network for strings.

**Comment by Shroototem** [comment]
My issue was fixed. I had some small mistake and now everything's fine.

**Comment by dock-adams** [comment]
> In the above example, you are using two different neural networks. Stick to the LSTM network for strings.

Thanks! It worked.

Someday when my programming skills advance I would like to contribute to this project.

**Comment by polystate** [comment]
Thanks! It worked.

Someday when my programming skills advance I would like to contribute to this project.

Can you make a sophisticated chatbot with this? I assume you would have to use the LSTM-type NN right?

**Comment by mubaidr** [comment]
@dock-adams Please follow this thread for information regarding this topic: https://github.com/BrainJS/brain.js/issues/535
