### ISSUE TITLE
Making the Library Robust and Simple for beginners

### ISSUE THREAD

**Issue by AkashGutha** [BrainJS/brain.js#99]
User story: 
Akash is a small kid and wanted to play around with some neural networks, kids these days like to be geeky. But he finds all the libraries to be quite hard to use since they talk about math jargon all over the place and a single function is asking him to give a thousand inputs. That's not cool. 
Akash want's to get his ideas running on a Neural Network as soon as possible without the need to understand the complex math behind it.

The user story might seem a bit ridiculous, but I think will open up a number of possibilities to beginners.

My proposal is to build the library having a fine granular control.
Parallelly building a module inside the library that gives us access to preconfigured models that just work out of the box.

**Comment by robertleeplummerjr** [comment]
It is like you are in my head!: https://github.com/BrainJS/brain.js/issues/96#issuecomment-332374644

**Comment by AkashGutha** [comment]
Same thing for General neural and deep nets.

```javascript
new brain.NeuralNetowrk({
  inputLayer:
  hiddenLayers: [],
  outputLayer: 
});
```

This would be an invaluable addition to starters

**Comment by robertleeplummerjr** [comment]
This issue is really important to me, so I want to expound upon where the api is headed.  And not only do I was to make sure the library is easy, it will be GPU accelerated, and enterprise ready.  

The actual api for FeedForward nets is currently implemented as (for v2, not yet released):
```js
const net = new FeedForward({
  inputLayer: 
  hiddenLayers: [],
  outputLayer:
});
```

And the "twin" recurrent api (planned, not yet built):
```js
const net = new Recurrent({
  inputLayer: 
  hiddenLayers: [],
  outputLayer:
});
```

Note: See anything related between them?

Now, we can easily have some sort of shortcut to generate the following, but here is the verbose means of creating a deep (three layers) feed forward neural network.
```js
import { FeedForward, layer } from 'brian.js';
const net = new FeedForward({
  inputLayer: () => layer.input(settings)
  hiddenLayers: [
    input => layer.feedForward(settings, input),
    input => layer.feedForward(settings, input),
    input => layer.feedForward(settings, input)
  ],
  outputLayer: input => layer.output(settings, input)
});

net.train([
  {input: [0, 0], output: [0]},
  {input: [0, 1], output: [1]},
  {input: [1, 0], output: [1]},
  {input: [1, 1], output: [0]}
]);
net.run([0,0]); // -> outputs `[0]`
```

And the planned recurrent:
```js
import { Recurrent, layer } from 'brian.js';
const net = new Recurrent({
  inputLayer: () => layer.input(settings)
  hiddenLayers: [
    (input, recurrentInput) => layer.recurrent(settings, input, recurrentInput),
    (input, recurrentInput) => layer.gru(settings, input, recurrentInput),
    (input, recurrentInput) => layer.lstm(settings, input, recurrentInput)
  ],
  outputLayer: (input, recurrentInput) => layer.output(settings, input, recurrentInput)
});

net.train([
  {input: [0, 0], output: [0]},
  {input: [0, 1], output: [1]},
  {input: [1, 0], output: [1]},
  {input: [1, 1], output: [0]}
]);
net.predict([0,0]); // -> outputs `[0]`
```

More to come.

**Comment by freddyC** [comment]
So I have been thinking about this and I think another thing that can get new users bogged down is how many methods and variables are exposed.  For example in the REPL I instantiate a simple NeuralNetwork and her are the things I have control over:

![image](https://user-images.githubusercontent.com/2294139/34903575-7999a272-f7f1-11e7-9841-e6eb5cc76467.png)

How many of these do we actually want the user to be interacting with?  If the user trains a network, then randomly calls initialize with some given size their network is `dust in the wind`.

I propose if we take the methods that are meant to only be used internally (private methods) and declare them in the constructor (or some other scheme for having them not public).  I think that will significantly help the people new to the library.  I don't mind doing this If you guys agree it will help solve this specific problem.

**Comment by jlarmstrongiv** [comment]
I found the [scrimba course](https://scrimba.com/g/gneuralnetworks) by @robertleeplummerjr (thank you!) was extremely helpful when learning brain.js.  Updating the course and adding more examples of the new and improved features in V2 would be fantastic 🙂 

Of course, an easy-to-follow tutorial is only possible with a solid API foundation, like the one in the works 😉

**Comment by mubaidr** [comment]
Closing in favor of https://github.com/BrainJS/brain.js/issues/439
